### ISSUE TITLE
View a landing page/home page on HL before signing up or logging in

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#10]
As a person using HL,
I want to see a home page when I first visit HL
so I can access resources quickly and easily to experience the site before sign up.

## Acceptance Criteria

+ [x] Users should see a hero ‘recovery story’ at the top of the page, then ‘tip of the day’, then a couple of ‘places to go’ (upcoming events), then a couple more recovery stories
+ [x] Users should be able to access sign up & log in opportunity (in burger)

**Comment by nelsonic** [comment]
@katbow thanks for creating this story.
@MollieCourtenay please _confirm_ the requirement and add **_acceptance_ criteria**. 
and if possible, get a member of the team to upload any _initial_ wireframes/designs.
Thanks!

**Comment by MollieCourtenay** [comment]
<img width="129" alt="screen shot 2017-01-29 at 21 50 46" src="https://cloud.githubusercontent.com/assets/25012688/22408203/0df84dac-e66d-11e6-960c-10667d48bc89.png">

Non tailored info.
Can be filtered slightly proactively by the user - see other issues #7 #8 #9 .

## Acceptance Criteria

+ [ ] Users should see a hero ‘recovery story’ at the top of the page, then ‘tip of the day’, then a couple of ‘places to go’ (upcoming events)
+ [ ] Users should be able to access an About link, to take them to an About page (in footer and burger)
+ [ ] Users should be able to access sign up & log in opportunity (in burger)
____

Let's see how we get on without a welcome message....
