### ISSUE TITLE
Confirm position of HL in Azure

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1000]
Email from Adele asking:

"could you confirm that slam hl lies in azure at PIP 51.140.45.21"

Apparently the PEN testing company have asked for it to be confirmed.

**Comment by RobStallion** [comment]
The IP address we have for HL is 51.140.86.5

**Comment by katyedwards** [comment]
Thanks @RobStallion I'll pass that onto SLaM.

**Comment by katyedwards** [comment]
Hi @markwilliamfirth 

Another email from SLaM:

_Please could you check again? 
The slam it team identified this number 

"The public address within Azure for HLStaging is 51.140.45.21" 

Please it is important to have the right position._ 

I don't want to interrupt Rob & Katherine while they are working on more important things, but are you able to see what is at 51.140.45.21... 

If we can tell SLaM what is there, they might believe us that HL is where we say it is!

Thanks!

**Comment by markwilliamfirth** [comment]
@katyedwards 

When I go to 51.140.86.5 (Rob's link) it goes to https://staging.healthlocker.uk/

When I go to 51.140.45.21 (SLaM's link) I get "Error determining IP Addresses for 51.140.45.21"

When I go to:
http://get-site-ip.com/

For Healthlocker.uk it gives me the result:
62.116.130.8
Germany

When I visit 62.116.130.8 directly, it says:
Sorry, no Host found

Not sure if this answers your question, if not then @RobStallion or @katbow will need to confirm the technical details

**Comment by katyedwards** [comment]
Hi Mark, I _hope_ that'll do!  Thank you

**Comment by markwilliamfirth** [comment]
@katyedwards did SLaM confirm on their side?

**Comment by katyedwards** [comment]
@markwilliamfirth  They haven't come back to me since my last email to them this morning which I'm taking as: they have accepted the answer now.

I would expect them to come back quickly if they are unhappy and not respond if they are ok!
