### ISSUE TITLE
Architecture Documentation for SLaM

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1007]
Moving this into a new issue as it has been requested several times in previous issues, but we don't have what we need.

In time for handover to SLaM (Tues 29th) we need confirmation of the following:

- [x] SLaM will be backing up the server, but won't have a backup of the data.  Please confirm if there is a file that scripts to pick up the data when required (ie during disaster recovery) - and provide details

- [x] Please provide an updated architecture diagram (as per current build, not original plans)

- [x] Where is the database stored?

- [x] Details of SSL Certificate incl expiry date 

- [x] Details of database encryption

- [x] Deployment Documentation

- [x] Server configuration

It is part of SLaM's disaster recovery plans that they have full detailed information and instructions on what needs to be done to recover and redeploy the application.

**Comment by katyedwards** [comment]
@reddog I've put in what I know of/ have pulled out of various emails from SLaM.

Can you update the checklist above so we have points for everything we need in order to handover to SLaM... and please do add to my points to give them more clarity!

**Comment by reddog** [comment]
@katyedwards Will review your items but generally looks good.

Assigned @nelsonic, @RobStallion and @katbow for their input.

**Comment by katyedwards** [comment]
@nelsonic @iteles one quick question to get this finished off... is there a load balancer in the current build in staging?

**Comment by katyedwards** [comment]
@katbow you mentioned you'd ask about the load balancer... did you get an answer? (in case we need to update the documentation we've sent to SLaM)

**Comment by katyedwards** [comment]
Final question moved into a new issue #1065
