### ISSUE TITLE
Healthlocker domain for user testing

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#101]
As a user of the Healthlocker, I would like to see a 'real' domain rather than the existing herokuapp domain so that I can have a greater level of confidence in the application.

<hr/>

+ [x] Purchase (temporary) test healthlocker domain
+ [x] Add domain to herokuapp
+ [x] Add heroku DNS target to domain

**Comment by iteles** [comment]
Done for `http://www.healthlocker.uk` (against our production herokuapp).

Waiting for `CNAME` record update to propagate.

**Comment by iteles** [comment]
This still wasn't working so I raised tickets with our domain provider (iwantmyname) who confirmed this was on the heroku end.

Heroku has now confirmed it's the application that's redirecting incorrectly:
>It looks like your DNS and customer domain are setup correctly, but it looks like it's your application that is responding with a 301 "Moved Permanently" to "https://https://healthlocker.herokuapp.com//":

```shell
$ curl -v www.healthlocker.uk
* Rebuilt URL to: www.healthlocker.uk/
*   Trying 176.34.117.224...
* TCP_NODELAY set
* Connected to www.healthlocker.uk (176.34.117.224) port 80 (#0)
> GET / HTTP/1.1
> Host: www.healthlocker.uk
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Connection: keep-alive
< Server: Cowboy
< Date: Thu, 16 Feb 2017 11:10:52 GMT
< Content-Length: 0
< Cache-Control: max-age=0, private, must-revalidate
< Location: https://https://healthlocker.herokuapp.com//
< Via: 1.1 vegur
<
* Curl_http_done: called premature == 0
* Connection #0 to host www.healthlocker.uk left intact
```
> You'll need to the update the redirect code in your application, and redeploy.

@katbow Could you look into this please?

**Comment by katbow** [comment]
@iteles I'll check this out now!

**Comment by katbow** [comment]
It looks like it's being redirected because of [`force_ssl: [rewrite_on: [:x_forwarded_proto]],` in `config/prod.exs`](https://github.com/healthlocker/healthlocker/blob/master/config/prod.exs#L17)

From the [Phoenix endpoint docs](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html):

```
:force_ssl - ensures no data is ever sent via http, always redirecting to https. It 
expects a list of options which are forwarded to Plug.SSL. By default, it 
redirects http requests and sets the “strict-transport-security” header for https ones.
```

So I think we can just remove this for now since it is set up for http atm. Sound right @tonydaly ?

**Comment by katbow** [comment]
from @tonydaly on slack saw the redirect stuff, that'll be the forcing of ssl, which I highly recommend we keep! Therefore I suggest we add an ssl cert

**Comment by nelsonic** [comment]
https://letsencrypt.org/

**Comment by iteles** [comment]
From the lovely people at heroku:
Going back to the original issue, the redirect is happening in your application code. For Phoenix apps, this is happening in your config/prod.exs file here:
```shell
config :healthlocker, Healthlocker.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: System.get_env("HEROKU_URL") , port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE")
```
If you notice, the url tries to force a redirection to https with the value of the HEROKU_URL environment (AKA config) variable. On your app this is currently set to:

~ $ env | grep HEROKU_URL
HEROKU_URL=https://healthlocker.herokuapp.com/
If you change this config var to use your custom domain without the https in front, you should be able to fix the redirect issue. Give that a shot and let us know if you have any other questions.

**Comment by nelsonic** [comment]
SSL Certificate added. see: https://www.healthlocker.uk 👍 
(_un-assigning myself from this..._)

**Comment by nelsonic** [comment]
@MollieCourtenay to confirm this is done. (_please **comment and close** the issue. thanks!_)
