### ISSUE TITLE
Update caseload to get carers for non-hl service users

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#1012]
#762 
For non-hl users in the caseload, there are currently no queries to get carers for these users, since carers could not previously connect to a clinician if the service user wasn't on healthlocker.

This will need some consideration since the queries done here are quite slow already, and adding in another query for *each* unconnected user will slow the load time even more.

@katyedwards I'm not sure if I'm remembering this correctly, but was there any discussion about removing the unconnected users from the caseload page? I wasn't sure if that occurred when we realised how many patients there were for each clinician (sometimes 400+). Or even displaying these users on a separate page? If it were possible to display non-connected users **only** if there is a carer in hl that is connected to them, it might help with the load time on this page. This isn't a necessity, but I am conscious of the load times and that adding these additional queries for each user will have even more of an effect, so I want to know the options available to me.

**Comment by katyedwards** [comment]
@katbow the debate briefly had been from SLaM in terms of data protection and whether we can display people's details if they haven't consented, i.e. haven't signed up to HL voluntarily, but they are covering that by adding HL to their general SLaM consent.

In terms of load times etc, I would think it seems reasonable to only display non-connected users if there is a carer signed up (although might confuse clinicians if someone with no carer is connected, then opts to disconnect because they would vanish from the list rather than moving to the lower list in which case Clins might think there is an error with HL - probably an edge case)

I think that probably needs @MollieCourtenay to confirm as she's done all the previous thinking around this.

**Comment by MollieCourtenay** [comment]
@katbow could we turn the 'not signed up to Healthlocker' title into a clickable link/ button. Where a clinician would have to click to reveal them and the loading would only be done at that point?

**Comment by MollieCourtenay** [comment]
good point about disconnect. Maybe a similar behaviour to what we decide to do here could be borrowed for disconnected user when it comes to that.

**Comment by katbow** [comment]
This is taking slightly longer than anticipated since it's min 3 extra queries which would slow this down quite a lot.

Have talked with @MollieCourtenay and have decided to move section for non-connected users to a separate page (button at the bottom which clinicians can click to get to). 

The carers styling will be slightly different in that there will now be a section instead of the 'User not signed up to Healthlocker' section.

**Carers for users not signed up to Healthlocker**

```
[  Mary Johnson          >  ]
    [ friend/family/carer of Evan Burns ]
__________________________________________

[See all users not signed up to Healthlocker]
```

**Comment by katbow** [comment]
For styling: Colouring of carers (Mary Johnson section) will reflect the colours of carers as above in the Healthlocker Users section. The unconnected user they are caring for will be greyed out, as done currently in the Users not signed up to Healthlocker section.

Confirmed with @MollieCourtenay

**Comment by katbow** [comment]
Right now I have cares displaying in a different section
![image](https://user-images.githubusercontent.com/1287388/29725360-b88b2312-89c3-11e7-8c06-e8b4abae0c51.png)

Last bits to do are:
* Load in service user the carer is caring for & display underneath carer
* Finish loading in non-hl users on new `unconnected` page, as it is currently blank
