### ISSUE TITLE
Burger - bold current page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#1017]
+ [x] Current page on the burger menu should be bolder text than the others, so that the user is reminded what page they are on.

**Comment by katyedwards** [comment]
Bug!  Care team and Tips are both bold! @RobStallion

**Comment by RobStallion** [comment]
@katyedwards Good spot

**Comment by katyedwards** [comment]
Haha - indeed it was... person who actually spotted it!
