### ISSUE TITLE
Add links to youtube videos in about

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#1018]
Add links to youtube videos in about.
+  [x] SU paragraph
+ [x] Staff paragraph

If you are a service user at the South London and Maudsley NHS Foundation Trust, you can choose to connect your Healthlocker account with your health record and care team. This will enable you to send and receive messages with your care team, share tracking, goals and coping strategies with them. [Watch a YouTube video](url) that shows you how to use each feature.

If you are staff at the trust, you can access Healthlocker via the icon in the top panel in ePJS. You can send and receive messages with service users and their carers and view updates that your caseload has chosen to share with you. As staff, if you need help or support using Healthlocker, please contact the trust service desk. [Watch a YouTube video](url) that shows you how to use each feature.

- [x] Add SU Video to home page - welcome to HL section

**Comment by katyedwards** [comment]
Done!
