### ISSUE TITLE
Users can like a tip or recovery story

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#102]
This provides a level of interaction to track which stories and tips are popular. It gives users a reason to sign up so that they can like stories (which non-logged in users will not be able to do at this point).

Liked stories and tips for the user can be viewed on a single page when logged in. 

#7 #8

**Comment by LauraNevo** [comment]
Just a quick note for reference, last week we decided to call it "bookmark" because it makes more sense since a logged in user will be able to save resources in their Toolkit. I'll be posting some wireframes on #41 on Friday after checking with Mollie.

**Comment by katbow** [comment]
Some info on this...

#### Schema/tables
Likes are kept in a `posts_likes` table which includes `post_id` and `user_id`.  The table is created in a migration with references to post & user id:

```
defmodule Healthlocker.Repo.Migrations.AddPostsLikesJoinTable do
  use Ecto.Migration

  def change do
    create table(:posts_likes, primary_key: false) do
      add :post_id, references(:posts)
      add :user_id, references(:users)
    end
  end
end
```

A `many_to_many` association is added to each of the posts and users tables: `many_to_many :likes, Healthlocker.User, join_through: "posts_likes" ` in the posts table. 

#### Queries

Can create likes with create-like action for likes 

```
post |> Healthlocker.Repo.preload(:likes) |> Ecto.Changeset.change() |> Ecto.Changeset.put_assoc(:likes, [user]) |> Healthlocker.Repo.update!
```

where post is the post in question being liked, and the user is the current user.

For now we can access the number of likes/post with:

```
post = Healthlocker.Repo.get(Healthlocker.Post, id)
post = post |> Healthlocker.Repo.preload(:likes)
length(post.likes)
```

**Comment by MollieCourtenay** [comment]
@katbow **internal server error** when click like on things in Home:
'Talking about anxiety took the weight off my shoulders'  - story 
and
'Keep active. Regular exercise can boost your...' - tip

**See more stories:**
Error again for:
'Talking about anxiety took the weight off my shoulders'.

Worked for: 'Why can’t men talk about mental health in the pub?' and 'One conversation can save a life'.



**See more tips:**

errors for: 'Keep active. Regular exercise can boost your... '
'Keep in touch. There’s nothing....'
'Ask for help. None of us....'

worked for:
'Care for others. Caring for others....'
and all the other ones i made that are the same - with fiddled styling.

**Comment by MollieCourtenay** [comment]
@katbow 
 Also assume this will link eventually to #41  Favouriting resources. 
In which case 'Like' should be replaced with 'Favourite'

Is that a criteria to add to this story?

**Comment by katbow** [comment]
@MollieCourtenay can you check this again when you get a chance? That the internal server error is no longer showing?

Yes this will link eventually to 41. I called it "like" for now since it was only capturing if people interacted with content but they're not accessible in a list yet of the user's liked/favourited content yet. I thought favourites might indicate to the user that functionality.

Having said that, the name can be changed any time! If you want it named to something else for the beta release it's a quick fix.

**Comment by MollieCourtenay** [comment]
@katbow still experiencing the same combinations as above and getting internal server error. before trying i logged out, I deleted my cookies, hard refresh, log in, try to like  -  same error.

**Comment by MollieCourtenay** [comment]
Best to call it favourite when we have the favourite functionality then?
