### ISSUE TITLE
Page titles should be pink

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#1024]
Colour is: #EC4067 (as per style guide)

- [x] 'My Goals' on https://www.healthlocker.uk/goal
- [x] @RobStallion can you also change the text to "My **g**oals" so the capitalisation is consistent with the other pages, thanks!
- [x] 'Coping strategies' on https://www.healthlocker.uk/coping-strategy
- [x] 'Sleep tracker' on https://www.healthlocker.uk/sleep-tracker/new
- [x] 'Problem tracker: Problem name' on https://www.healthlocker.uk/symptom-tracker/new
- [x] 'Diary' on https://www.healthlocker.uk/diary/new
- [x] 'Tracking overview' on https://www.healthlocker.uk/tracking-overview
- [x] 'Tips' on https://www.healthlocker.uk/tips
- [x] 'Stories' on https://www.healthlocker.uk/posts
- [x] 'Get support' on https://www.healthlocker.uk/support
- [x] 'About' on https://www.healthlocker.uk/pages/about
- [x] 'Terms of Service' on https://www.healthlocker.uk/pages/terms
- [x] @RobStallion can you also change the text to "Terms of **s**ervice" so the capitalisation is consistent with the other pages, thanks!
- [x] 'Privacy Statement' on https://www.healthlocker.uk/pages/privacy
- [x] @RobStallion can you also change the text to "Privacy **s**tatement" so the capitalisation is consistent with the other pages, thanks!
- [x] 'Account' on https://www.healthlocker.uk/account
- [x] 'Care Plan Summary' on https://www.healthlocker.uk/care-plan
- [x] @RobStallion can you also change the text to "Care **p**lan **s**ummary" so the capitalisation is consistent with the other pages, thanks!
- [x] 'Care team' on https://www.healthlocker.uk/care-team/contacts

I think that's all - I hope you don't have to do them individually!

**Comment by RobStallion** [comment]
@MollieCourtenay @katyedwards Do you have a shade of pink that we should use?

**Comment by katyedwards** [comment]
@RobStallion 

#EC4067 (as per style guide)
