### ISSUE TITLE
Deployed site is behind current master

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#1027]
The deployed site is not up to date with current master.

When we want to deploy the application to production with the following command...
` mix edeliver deploy release to production`
we get the following message...
![image](https://user-images.githubusercontent.com/15571853/29711252-d7e283dc-898b-11e7-9fb7-2f134b5dece7.png)

If version 1.0.2 is deployed then the site works as expected but it is an older version of the HL site.
If version 1.0.3 is deployed then when we run the command 
`mix edeliver start production` 
we get the following error...
![image](https://user-images.githubusercontent.com/15571853/29711422-9e0fc786-898c-11e7-81aa-99642f353bd1.png)

from the error message, `response: 2017-08-25 11:30:47 Invalid node name!
Please check your configuration`, it looks like the issue is with the `.deliver/config` file so starting there for possible causes

**Comment by RobStallion** [comment]
after doing a little bit of looking into this issue I have seen that both the `version number` of healthlocker and the `.deliver/config` were updated in this PR. 

I'm not sure if this is what caused the error as this PR actually fixed an issue with messaging but looking into it.

**Comment by RobStallion** [comment]
I have tried `ssh`ing into the server and moving the healthlocker folder found in `/home/hladmin/healthlocker` to a different location, then exiting out of the VM and rebuilding the site from scratch with `mix edeliver build release`.

Once this had build I ran `mix edeliver deploy release to production` but got the same message as above asking to select the release. 

I tried with both and had the same results as above. 

Next step:

Going to fork the repo and try building a new `rel.config.exs` file with the `mix release.init` command. Will then try deploying the forked version and will see if it is up to date.

**Comment by reddog** [comment]
@RobStallion Thanks for your work on this.

There was recently a redeploy to effect the fix for #986. Were there any issues with the regular deploy process at that point? Was anything done differently there to how you've actioned the deploy today?

**Comment by RobStallion** [comment]
@reddog There have been no changes in the way that the deployment has been handled. 

I think that it may not have been noticed right away as there were no obvious content changes. Also when we redeployed to fix issue #934 it appears to have worked.

**Comment by katyedwards** [comment]
Thanks @RobStallion just to say, please focus all time on this right now - we **have** to handover HL on Tuesday so have to get these things sorted.  We'll have to delay Oxleas slightly.

**Comment by RobStallion** [comment]
I have just managed to get the forked repository to update all the content by following the steps I put [here](https://github.com/healthlocker/healthlocker/issues/1027#issuecomment-324947883).

Next step is to repeat the steps I just took but on the real repo

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/29722566-4a11ff8c-89b9-11e7-9b93-e116083386ea.png)

master has been merged in, deployed and appears to be working as expected.
