### ISSUE TITLE
Account, make un-editable fields look different

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#1031]
- [x] As a service user I can see clearly what fields I can edit in my account: no text box on non-editable fields

Mock up:
But ignore the wonky font on the email address!

![screenshot 2018-03-13 16 40 09](https://user-images.githubusercontent.com/24604903/37356926-ffa0a7b4-26de-11e8-8036-776e37b0f6c0.png)

Fields listed below...

**Comment by RobStallion** [comment]
@MollieCourtenay @katyedwards Do you have a list of the fields?

**Comment by katyedwards** [comment]
@RobStallion 

**User not connected to epr:**
- Email Address Only

**User connected to epr:** 
- First Name
- Last Name
- Email Address
