### ISSUE TITLE
ERROR - Tracker Overview

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1048]
Argument Error page when trying to access Tracker overview:

1. Logged in as SU
2. Access tracker overview with no problem
3. Enter sleep tracking
4. Try to access tracker overview again and get error screen:

![screenshot 2017-08-29 13 15 58](https://user-images.githubusercontent.com/24604903/29820572-d94359d4-8cbc-11e7-8e0a-31d581b7382a.png)

1. Logged in as Clinician
2. Access SU tracker page with no problem
3. SU tracks sleep
4. Clinician tries to access tracker overview and get error screen:

![screenshot 2017-08-29 13 23 20](https://user-images.githubusercontent.com/24604903/29820696-4285b90a-8cbd-11e7-8353-996de7c0adec.png)

**Comment by katyedwards** [comment]
1. Logged in as Carer
2. Tracking overview fine
3. Go to toolkit, did hard refresh
4. Tracked sleep
5. Went to tracking overview and got argument error as above

**Comment by MollieCourtenay** [comment]
ArgumentError at GET /tracking-overview
argument error
web/views/tracker_view.ex
15  defp last_week(end_date) do
16    Timex.shift(end_date, days: -6)
17  end
18
19  def get_week_average(data) do
20    total_slept = Enum.map(data, fn struct -> String.to_float(struct.hours_slept) end)
21      |> Enum.sum
22    if Kernel.length(data) == 0 do
23      0
24    else
25      format_average_sleep(total_slept / Kernel.length(data))
healthlocker anonymous fn/1 in Healthlocker.TrackerView.get_week_average/1
 Show all frames
 web/views/tracker_view.ex:20 anonymous fn/1 in Healthlocker.TrackerView.get_week_average/1
 web/views/tracker_view.ex:20 Healthlocker.TrackerView.get_week_average/1
 web/templates/tracker/tracking_data.html.eex:5 anonymous fn/1 in Healthlocker.TrackerView.tracking_data.html/1
 web/templates/tracker/index.html.eex:18 anonymous fn/1 in Healthlocker.TrackerView.index.html/1
Request info
Headers
Session

**Comment by katyedwards** [comment]
Both slam connected and non-connected users

**Comment by katyedwards** [comment]
Thanks @katbow seems to be working great now
