### ISSUE TITLE
ERROR: cannot convert to nil param

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1049]
Description:
Error - cannot convert to nil param
 
Steps:
ePJS user 'gmor...@....uk' (obfuscated) has three patient records extracted to his health locker caseload from ePJS.  When clicking Healthlocker caseload button within ePJS, immediately his by 'cannot convert to nil param' error.
 
URL from ePJS:  (see Slack for URL)
 
Error: 

![image001](https://user-images.githubusercontent.com/24604903/29869730-1acf0208-8d7c-11e7-8482-5204dde358ec.jpg)

FYI, this occurs on Garry's account.  He is able to continue testing using another dummy account (vtestward) which operates correctly.  Please note the URL enclosed to generate the error is only valid for today.

Garry has also tested on an external connection (off the SLaM Network) and the same error is repeated.

**Comment by reddog** [comment]
Tested locally and gives the same error.

**Comment by katbow** [comment]
This was fixed alongside the deploy. Checked & it is accessible now

**Comment by katyedwards** [comment]
Thanks @katbow is that everything deployed now?  What was it that caused the error?

**Comment by katbow** [comment]
It seems that account was used for testing carer functionality, then was switched to a clinician account, so it was removing the carer room that they were in previously. Care Team was showing in the menu with no room for the account as a carer (room was the nil part). Seems like something to keep in mind, but probably also an edge case during testing phase.

**Comment by katyedwards** [comment]
Ah ok thanks.  I'm just waiting for them to confirm they can access ok and then I'll close the issue.

**Comment by katyedwards** [comment]
SLaM have confirmed access is working again, thanks!

**Comment by katyedwards** [comment]
@katbow   This has occured again for James who is testing while Garry is off...

Assuming it's the same problem - it definitely seems like an edge case during testing so we don't wanna to spend too long on fixing it to the detriment of other bugs, but if possible we want to avoid this happening again with another test user and it looking like we're just not fixing it properly.

I'm not meant to be working today, so tagging in @MollieCourtenay and @reddog to think about the best way to approach this.

@MollieCourtenay do you think it would be acceptable to just explain what is causing the error, why it is an edge case in testing and ask them just not to do it again?!

**Comment by katyedwards** [comment]
Description:
Error - cannot convert to nil param
 
Steps:
ePJS user 'jroberts2@slam.nhs.uk' has a patient records extracted to his health locker caseload from ePJS.  When clicking Healthlocker caseload button within ePJS, immediately his by 'cannot convert to nil param' error.
 
URL from ePJS:  on slack

![image008](https://user-images.githubusercontent.com/24604903/29961107-3f65ed22-8ef6-11e7-8d14-8cbf7213ba44.jpg)

**Comment by MollieCourtenay** [comment]
@katbow how was this one fixed? Did you fix something in the DB for the user that was having problems or fix in a different way.
Would you expect to the the error reoccurring like this for a different user.
It does appear to be the same as I can see this user has Care Team in his menu where he shouldn't have as a clinician.

**Comment by katbow** [comment]
Yeah it's a DB fix. In Garry's case it's because he previous connected as a carer in testing, then as a clinician. For James it was connected as a service user, then later as a clinician (which I'm about to fix).

I'll ensure the links are removed for clinicians, but it would still be a problem if they did either of those things first (signed up as service user or carer) with their nhs email. To avoid this during testing they shouldn't sign up for carer/service user for email addresses they intend to use for a clinician. It wasn't accounted for that clinicians would at some time be either of those, at least not for the same email.

**Comment by MollieCourtenay** [comment]
@katbow that makes sense to me thanks, i'll pass that on so they know were on it.

**Comment by katbow** [comment]
it's updated now, so please test label applies again!

**Comment by MollieCourtenay** [comment]
@katbow James can enter thanks. will close this again.

**Comment by MollieCourtenay** [comment]
@katbow James has experienced this again this afternoon I think.
but his screenshot is so blurry...
**Email:**
Not sure if things are being developed but getting the same error message again:
 
ArgumentError at GET /caseload
 
cannot convert nil to param

![image011](https://user-images.githubusercontent.com/25012688/29977408-235ebcc8-8f35-11e7-813f-63a868577e1f.jpg)

**Comment by katbow** [comment]
it's because he has connected as a carer again on the same account. Clinicians can't connect as carers or service users as their role gets reset.

**Comment by katbow** [comment]
reset it back to clinician again.

**Comment by katyedwards** [comment]
@katbow Have spoken to James and he said that he hasn't used his email address for anything other than clinician testing and has been creating other hotmail etc. accounts for SU/Carer testing.

Can you give more details on which accounts have needed resetting so he can look into it further on his side.

**Comment by katbow** [comment]
It was just his and Garry's. After I fixed James' the first time, his role was set to clinician. When I looked after the error occurred again, it was set to carer, and he had been added to a newly created carer room, and to the carers table. I went through all the carers previously when Garry was connected that way to ensure the users didn't have dual roles, and James definitely wasn't connected as a carer at that time.

**Comment by katyedwards** [comment]
Thanks @katbow how could James' account have become set to carer?  would he have had to sign up for an HL account using his email address and then connected as a carer?  He said he definitely didn't do this, although depending how many windows he had open during testing I guess it's possible he thought logged into the wrong place.

Can you see/ remember which user he was set up as a carer for?  And was it using his James.Roberts@****.nhs.uk  email address?

**Comment by katbow** [comment]
@katyedwards yeah that's the one. I can't remember who he was set up to care for, and can't see that anymore. 

The only way all those things would happen is if he was logged in to that account & went through the flow to connect as a carer. I'm not sure how he would get to that link besides actually typing in the url since the link is removed now for clinicians. 

It's possible that he was logged in on one window (with a different email), then he clicked the button on ePJS to go to his clinician account which opened in a different window and overwrote his session. Then if he carried on afterwards in the other window he may have been logged in as the clinician.

**Comment by katyedwards** [comment]
@katbow Great thanks, I'll pass on so he can look into it/ have a think about it.

**Comment by katyedwards** [comment]
Closing this one again - continued discussion on this can go into #1060
