### ISSUE TITLE
Redirecting to previous page

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#105]
After a user likes a post #102, they should stay on the same page. However, I have only been able to redirect users to a specific path.

I need a way to get the path the user was on before liking, go to the endpoint to post the like, then go back to the previous page.

The only solutions I have found so far either [use a library](http://stackoverflow.com/questions/40006176/how-to-redirect-back-to-previous-page-after-invalid-input) ([docs here](https://github.com/tuvistavie/plug-navigation-history)), or [use hidden inputs on forms](http://stackoverflow.com/questions/37627725/elixir-phoenix-redirect-to-the-current-page), which I'm not certain is a viable option since this isn't from form input.

**Comment by tonydaly** [comment]
@katbow you should be able to get the `referrer` from [`Plug.Conn`](https://hexdocs.pm/plug/Plug.Conn.html#module-request-fields)

Check this out: http://ricostacruz.com/cheatsheets/phoenix-conn.html
