### ISSUE TITLE
Error: Care Plan Summary - function Healthlocker.EPJSRecoveryCarePlan.fetch/2

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1050]
Description:
Error - Care Plan Summary: function Healthlocker.EPJSRecoveryCarePlan.fetch/2
 
Steps:
Ensure the ePJS patient record holds an R&S plan and is present on the MHL extract
 
=> Go to https:staging.healtlocker.uk/login
 
=> Login as
Tkestedt3Tkest@outlook.com
 
=> Navigate to 'Goals and Tracking'
 
=> Navigate to 'Care Plan Summary'

![image001 1](https://user-images.githubusercontent.com/24604903/29884639-fbc66cfe-8dab-11e7-93d1-8ea84164a9c3.jpg)

**Comment by katbow** [comment]
I think this *should* be a fairly quick fix. My initial thought is that the field is being accessed with `recoveryCarePlan[:Field_Name]` syntax, which should be fixable by changing to `recoveryCarePlan."Field_Name"` syntax. 

Adding 2 hours however, in case that is not it & to include investigation time in that case.

**Comment by katyedwards** [comment]
Thanks @katbow fingers crossed!!

**Comment by katyedwards** [comment]
@katbow I don't know if you saw my slack message - is there any chance this can be reviewed and deployed tonight so there is something for SLaM to test first thing - as they will be starting work earlier than you tomorrow and it'll keep them busy!

**Comment by katbow** [comment]
yep, I replied there but didn't @ you. Just been merged now so about to deploy

**Comment by katyedwards** [comment]
Lovely, thank you @katbow

**Comment by katbow** [comment]
Redeployed and ready to test. They will need to make sure they test this particular part on a user with only one of each child relationship or they will run into error on #1051.

**Comment by katyedwards** [comment]
Noted, thanks @katbow

**Comment by MollieCourtenay** [comment]
So SLaM can access this now - so I think this is ok to close? 
Them being able to access  - is that evidence of this being fixed?  @katbow

**Comment by katbow** [comment]
@MollieCourtenay yes that's right. They wouldn't be able to go to the care plan page if this wasn't fixed!
