### ISSUE TITLE
ERROR: Care Plan Summary - expected at most one result but got 3 in query

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1051]
Description:
Care Plan Summary - expected at most one result but got 3 in query:
 
The primary R&S plan table ‘mhlSLAMRecoveryCarePlan’ can have a 1 to many relationship with ‘mhlSLAMRecoveryFocusedCarePlanDailyActivity’ (and other related child tables).
 
Steps:
Ensure the ePJS patient record holds an R&S plan and is present on the MHL extract
 
=> Go to https:staging.healtlocker.uk/login
 
=> Login as
tkestredatkest@outlook.com
 
=> Navigate to 'Goals and Tracking'
 
=> Navigate to 'Care Plan Summary'
   
![image003](https://user-images.githubusercontent.com/24604903/29884908-cea5881c-8dac-11e7-94a8-fc2d86e0c134.png)

**Comment by katbow** [comment]
@katyedwards if possible, could you confirm how all these table relate to one another?

Right now we have assumed that we can access `mhlSummaryOfNeed` and `mhlSLAMRecoveryCarePlan` using the `Patient_ID`, then use the `SLAM_Recovery_Focused_Care_Plan_ID` from the `mhlSLAMRecoveryCarePlan` table to access all the other relevant tables. List of tables we're accessing using this includes `mhlSLAMRecoveryFocusedCarePlanLifeEventsTriggers`, `mhlSLAMRecoveryFocusedCarePlanGettingHelpFromOthersGeneral`, `mhlSLAMRecoveryFocusedCarePlanGoalsAndAsp`, `mhlSLAMRecoveryFocusedCarePlanDailyActivity`, `mhlSLAMRecoveryCarePlanContingency`. 

Can you also confirm **all** of these tables are a one to many relationship to the `mhlSLAMRecoveryCarePlan` table, and if not, what is the relationship? Should all of the results from one table be displayed on the screen then? Eg. if `mhlSLAMRecoveryFocusedCarePlanDailyActivity` has 3 results, are all the results listed under the heading for that section?

**Comment by katyedwards** [comment]
@katbow  Sorry - I just don't know enough about the care plan - have sent @MollieCourtenay  a message to ask if she can jump in here though asap

Or would it be better to see if there is someone from the ePJS team you can talk to?

**Comment by katbow** [comment]
yes, if there's someone who knows the table structure that would be best. I don't need a call or an answer urgently, as this comment

> The primary R&S plan table ‘mhlSLAMRecoveryCarePlan’ can have a 1 to many relationship with ‘mhlSLAMRecoveryFocusedCarePlanDailyActivity’ (and other related child tables).

would indicate that what I outlined above is correct. I was looking for the confirmation to avoid back & forth with fixing/testing if that's not the case for *some* of the tables. I can start work now on this. 

This part you or @MollieCourtenay can answer though, as it's about the display.

>Should all of the results from one table be displayed on the screen then? Eg. if `mhlSLAMRecoveryFocusedCarePlanDailyActivity` has 3 results, are all the results listed under the heading for that section?

**Comment by katbow** [comment]
Oh one more thing with that sorry. What is the relationship between a patient and the `mhlSummaryOfNeed` and `mhlSLAMRecoveryCarePlan` tables? Can a patient only have one of each of these (one to one) or multiple of these (one to many)?

**Comment by katyedwards** [comment]
Thanks @katbow I've asked if/when someone there will be available to confirm the tables.

I'm not sure if @MollieCourtenay is available this afternoon as she's at her other job, so I will risk making an executive decision:

Yes, if there are 3 entries in one table it should list them all - ideally with a linespace between them and the same date/person stamp.

**Comment by katyedwards** [comment]
Re: your question on the Summary of need & mhlslamrecoverycareplan tables - I don't know.  If you need to know this more urgently to get working, I'll see who at SLaM can help.

**Comment by katyedwards** [comment]
@katbow would it work for you to start on the quicker one so there is hopefully something we can tell SLaM is fixed fairly early tomorrow morning which'll buy us a bit of goodwill for fixing the other by the end of day (hopefully!)

**Comment by katbow** [comment]
Good thinking! I checked it out and it is being accessed in the way I thought, so I will change it around and see if that fixes the problem 👍

**Comment by katyedwards** [comment]
Thanks!

**Comment by MollieCourtenay** [comment]
@katbow do you still have questions for me? 
- Should all of the results from one table be displayed on the screen then? - yes.
- What is the relationship between a patient and the mhlSummaryOfNeed and mhlSLAMRecoveryCarePlan tables? Can a patient only have one of each of these (one to one) or multiple of these (one to many)? - I assume they will have only one of each. Are you seeing more than one?

**Comment by katbow** [comment]
@MollieCourtenay there appears to be only one in this case (it wouldn't have gotten to the part where the error occurred if there was more than one). However I wasn't sure if that was the case for all users, or just for the user they were testing. I am keeping it for now as a one to one (as that does make the most sense to me), but still need that confirmation. If a one to many relationship is possible, then there will be a similar error for patients with more than one mhlSummaryOfNeed and mhlSLAMRecoveryCarePlan.

**Comment by MollieCourtenay** [comment]
@katbow it makes sense to me too, so as long this is fixed and doesn't throw an error, we can ask Garry when he is back, just to be certain, if he thinks there could be a different case than one to one. As he was the one to pull these tables together for the subset.

**Comment by katyedwards** [comment]
@MollieCourtenay @katbow  If it helps I can ask James,  but he has gone for the day now and will be back first thing tomorrow.

**Comment by katbow** [comment]
Yeah @katyedwards that would be good to ask him! Tomorrow morning is fine.

**Comment by katyedwards** [comment]
I'll email now and we may have an answer by the time we start work tomorrow...

**Comment by katyedwards** [comment]
@katbow Feedback from SLaM: 
A patient can have multiple of each document (one to many), but only one of each document (the most recent)is active.

Does that answer your question sufficiently?

**Comment by katbow** [comment]
> but only one of each document (the most recent)is active.

I'm not really sure what this means in terms of what I need to do. Are multiple items stored on the database we are using, or only the most recent? If it's the latter, does this mean I am safe to keep it as looking for *one* result for a care plan for each user? If it's multiple, how do I know which is the most recent to display? There is no timestamp for when it was updated (except the `mhlSummaryOfNeed` table which contains an `Assessed_Date`).

@MollieCourtenay could I have more clarification from SLaM regarding this?

**Comment by MollieCourtenay** [comment]
I have asked for confirmation RE: one to many / one to one within the subset. FYI @katbow

**Comment by MollieCourtenay** [comment]
@katbow from James at SLaM -  Recovery and Support Plan subset – You are correct, the subset only has the most recent / active data so it would be a one to one relationship.

**Comment by katbow** [comment]
Excellent 😄! Will deploy now.

**Comment by katbow** [comment]
@MollieCourtenay the updated version has been deployed now.

**Comment by MollieCourtenay** [comment]
Thanks @katbow I'm happy to close this as there has been nothing coming back from SLaM on this since deploying.
