### ISSUE TITLE
Connected Carer has no button to disconnect from the SLaM account

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1058]
From SLaM's testing

Carer should have a 'disconnect from slam account of person I care for' button/ link the same as an SU does 

![image008 1](https://user-images.githubusercontent.com/24604903/29973656-38b5673c-8f28-11e7-8312-8769123b711a.jpg)

**Comment by MollieCourtenay** [comment]
#970  There is already an issue for this here.
its not a bug.
ill close this - and @katyedwards is going to let James know.
