### ISSUE TITLE
Change Error pages

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#1064]
1. They look scary - need prettier ones

2. PEN Testing highlighted that they give a lot of information away about the site.

More detail to be added.

**Comment by katbow** [comment]
Added a quick fix so that error should display similar to this in production

![image](https://user-images.githubusercontent.com/1287388/30708536-2888ca64-9ef7-11e7-8bd1-51c0ef198ecb.png)

It's not pretty yet, but definitely better than the debug pages, and they don't give away site info.

**Comment by katyedwards** [comment]
Yep - now getting page not found screen.

Will open new issue for @MollieCourtenay to think about making them prettier.
