### ISSUE TITLE
Does HL have a Load Balancer?

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1065]
Ref: #1007 

One remaining question that wasn't answered.  

It was in the original diagrams, @katbow wasn't sure if this was implemented.

**Comment by katbow** [comment]
The load balancer was *not* added to the live server. There will be a check for the staging server.

**Comment by reddog** [comment]
@katyedwards Do you need any further information on this?

**Comment by katyedwards** [comment]
@reddog We were waiting for someone to check on staging I think, but happy for you to close if you don't feel the information is necessary.
