### ISSUE TITLE
"Unhandled exit" / "time out" when logging in to staging site from ePJS link

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#1070]
Adele has emailed with the following error.  Both her and Garry have the same error when trying to log in from an ePJS link:

```
Unhandled exit at GET /caseload
```

```
unhandled exit at GET /care-plan
exited in: :gen_server.call(#PID<0.4570.15>, {:checkout,
#Reference <0.612779251.3868721153.87389>, true, 15000}, 5000) ** (EXIT) time out
```

![image](https://user-images.githubusercontent.com/151362/30542909-04c6534c-9c79-11e7-91a7-82be388182af.png)

**Comment by reddog** [comment]
This *might* be an issue with the test ePJS extract database (since the error is a database read timeout).  I have raised it with Stuart at SLaM IT and asked if there are any issues with the test ePJS extract database server or any firewall changes that would impact us.

**Comment by reddog** [comment]
@katbow Just to check - were any changes (inadvertently or otherwise) made to the **staging** HealthLocker environment last week?

**Comment by reddog** [comment]
Still awaiting further support from SLaM IT.

In the meantime, what would happen if the MS SQL Server ePJS extract database were to *go away* for some reason (it was restarted, temporarily blocked and access reinstated, etc)?  Would HealthLocker auto-reconnect on such occasions or is it possible that it would have a stale database handler?

**Comment by reddog** [comment]
Looks like the test ePJS extract database is fine, so it's not that.  Emails from Garry:

> In regards to test ePJS extract database.  I can confirm that it is locally accessible to me using MHL2_Reader login provided for staging to use.

>Retested the ePJS => Healthlocker caseload link multiple times and error repeated.  Refreshed the test ePJS database extract and error repeated.

**Comment by katyedwards** [comment]
FYI - seem to be getting a similar error when trying to view a care plan summary...

**Comment by MollieCourtenay** [comment]
<img width="1163" alt="screen shot 2017-09-18 at 11 28 54" src="https://user-images.githubusercontent.com/25012688/30538169-9e7b2022-9c64-11e7-9c79-60fb87ec2dee.png">

Logged in as SU: Tkestedt3tkest@outlook.com
clicked on care plan summary - given this error

**Comment by MollieCourtenay** [comment]
My feeling is this is an ePJS thing...

**Comment by reddog** [comment]
Garry is able to access the test ePJS database from his machine.

I have asked for support from Stuart.  Adele had separate internal SLaM firewall-like issues on Friday - I've asked if there have been any firewall type changes that could have caused this.  Awaiting a reply.

**Comment by iteles** [comment]
@reddog This has been assigned to @katbow and I but it looks like you're still checking things with SLaM. Shall I assign this to you until there is a response?

**Comment by reddog** [comment]
@iteles We've had some replies from SLaM (see above), but nothing on the firewall setup.

A response on any changes to the staging site would certainly be useful and should be a quick no, or possibly some detail?

Similarly with regard to a *possible* stale database handle.

Can you please restart the HealthLocker app?  This is not something we can do.  I think at that point we will have exhausted our immediate options.  Please do suggest anything you might think it to be.

**Comment by reddog** [comment]
@iteles @katbow Stuart has reported that there is SQL Server traffic from **staging** HealthLocker to the **live** ePJS extract database.

Has staging HealthLocker been restarted?  Is it possible that it was updated on Friday (or today?) with the connection details for the live ePJS extract database?

**Comment by reddog** [comment]
@RobStallion Are you about and able to restart the **staging** HealthLocker app?  We also need confirmation that the correct ePJS details are in use - it must be the **test** ePJS database.

**Comment by reddog** [comment]
Looks like **staging** HealthLocker is set to connect to **live** ePJS:

![image](https://user-images.githubusercontent.com/151362/30543150-e3ed38e2-9c79-11e7-9b0d-4bff63765a45.png)

**Comment by iteles** [comment]
@reddog I've just come out of my morning meetings - will get in touch with Rob and Katherine on this.

**Comment by reddog** [comment]
@iteles In case you don't have them immediately to hand, I have posted the *test* ePJS connection details in Slack.

**Comment by katyedwards** [comment]
@iteles  SLaM are trying to do a demo this afternoon, so can this be updated ASAP:

I don’t know when this was changed, but staging should be connecting to:

ePJS database server IP:  10.16.31.171
database name:  MHL2
database username:  MHL2_Reader
database password:  <it's not in the email - looks like it was sent over in April some time>

**Comment by katbow** [comment]
@katyedwards @reddog I double checked out the staging server settings - it is set to connect to ePJS using those details. There wasn't anything changed on the staging server last week.

**Comment by reddog** [comment]
Update:  still double checking firewall setup with SLaM IT team.

**Comment by katbow** [comment]
care plan for Tkestedt3tkest@outlook.com
![image](https://user-images.githubusercontent.com/1287388/30597588-51ff6f64-9d4f-11e7-944c-7275baf1b129.png)

**Comment by katbow** [comment]
It looks like it was a problem with sourcing the profile. I am not certain *why* this happened. I don't believe the server was rebooted as live was. The profile was never changed anyway, so even if it was rebooted & then started again, it should've still been accessing the same variables.

**Comment by katbow** [comment]
To add to my previous comment for clarity, we identified some reasons why this might occur. We just aren't certain of the exact reason this happened in this particular case. It can happen because of:
* Rebooting the server then starting the app with only step 4 below (without running through steps 1-3)
* Changing the environment variables, then not running through steps 1-3 below. The profile is sourced when the release is built, so it's not as simple as running step 1 & step 4 again.

**IF** this were to happen again in the future, then the steps to resolve were to rerun all commands to build, deploy, and start release.

1. Stop the server with `mix edeliver stop production`
1. Build the release with `mix edeliver build release`
1. Deploy release with `mix edeliver deploy release to production`
1. Start application with `mix edeliver start production`

**Comment by reddog** [comment]
@katbow I think we made some **very** useful learnings earlier.

Can your notes be added to a document so that we don't loose them / have to go hunting for them.  Maybe in a *troubleshooting* section in the current deployment document?

**Comment by katbow** [comment]
@reddog the troubleshooting section has been added now (to the oxleas document since it is a general troubleshooting thing). Can you review & close if it's good to go?
