### ISSUE TITLE
Incorrect timestamp on diary entries

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1071]
The wrong timestamp is displaying on diary entries (it is an hour out).

- [ ] When I submit a diary entry the tracker overview displays the correct timestamp (and updates when the clocks go back or foward)

![picture1](https://user-images.githubusercontent.com/24604903/30545545-d55330ea-9c81-11e7-8d83-6dbc4e080bcf.png)
* The diary entry was posted at 12.23

**Comment by katbow** [comment]
@katyedwards removing is very quick - 5 mins.
For displaying the correct time, it probably has something to do with if it is BST or not at the time the diary is saved. I would need to look into what it saves as by default in the database, and best options for how to change it. T1h.

**Comment by katyedwards** [comment]
@katbow if it's likely just a T1h to do properly, that would be better.  I'll update the issue above.

**Comment by katbow** [comment]
@katyedwards I was thinking about it last night and was going to update this morning to T2h. Reason for update is to ensure there is enough time to look at best options for this so it changes on the right date automatically each year. Ecto (what we use for interacting with the database) may have something built in to help with this which I will need to look into. 

Is that still alright?

**Comment by katyedwards** [comment]
Yep, fine - thank you!  

Once you start going through, if it seems like it is going to be more complicated than you anticipated we can always go back to just removing it and worry about correcting in the future.

**Comment by katbow** [comment]
Alright, I will keep you updated on it!

**Comment by katbow** [comment]
Where I am right now with this is:

By default, the timestamps are set to Elixir's `NaiveDateTime`. This date type does not contain any time zone information. The `DateTime` struct does, however it expects it to be set to UTC anyway so I don't think changing that would make much difference. 

We use a date time library already called `Timex`. I am looking at if it has any functionality to take BST into account.

**Comment by katbow** [comment]
![image](https://user-images.githubusercontent.com/1287388/30707398-4a24e6e8-9ef3-11e7-8750-321d658e848e.png)

**Comment by katyedwards** [comment]
Looking good thanks!
