### ISSUE TITLE
HealthLocker needs restarting on *live* server

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#1072]
Live HealthLocker at https://www.healthlocker.uk/ was unreachable earlier (from two separate physical locations) and SSH was also unavailable.

During their testing of firewall rules, SLaM IT have restarted the server.  The server now shows the nginx `502 Bad Gateway` error which frequently suggests that the Phoenix app needs starting.

Can the HealthLocker app please be restarted.

At the same time, can the ePJS database details please be **double** checked that they are the live settings.  The live ePJS database is at 10.16.31.11.

![image](https://user-images.githubusercontent.com/151362/30550507-8c337aa6-9c8f-11e7-9f12-c95990c73f01.png)

**Comment by MollieCourtenay** [comment]
I still can't access live Healthlocker.
<img width="734" alt="screen shot 2017-09-19 at 10 12 22" src="https://user-images.githubusercontent.com/25012688/30584890-1383fdbc-9d23-11e7-975b-cdd79ac74597.png">

**Comment by katbow** [comment]
does this need to be restarted right now in lieu of the plan on slack? Pasting here.
![image](https://user-images.githubusercontent.com/1287388/30585045-7c4b4ca6-9d23-11e7-833e-77601fa4bb9d.png)

I double checked the epjs database details, and they are correct on the live server for the live epjs database.

**Comment by reddog** [comment]
Live is back up and running.  Thanks @katbow.

We should have some written notes on how to start the HealthLocker app, both from a developer's machine and from the server.

**Comment by katbow** [comment]
@reddog it would be part of the instructions as per the documentation I added to on Thursday/Friday. I added a note on #1070 for what was going on in this particular case with the environment variables. 

If you mean also turning it on like how I did temporarily by ssh into the server, then going to the folder where healthlocker is stored & running `mix phoenix.server`, then we won't want to be doing this. It's reliant on that developer remaining connected to the server & their computer being on.

**Comment by reddog** [comment]
@katbow Thanks for updating the docs with a reboot restart where it was required.

I understand that running the server when directly connected is not a useful permanent anything, but maybe it's a useful troubleshooting technique?

We had the situation where the app wasn't reflecting the environment variable changes that had been made. Running the app whilst locally connected help us see where the problem was.

**Comment by reddog** [comment]
Live HealthLocker has become unreachable again.

I was in mid-test, trying to login in from an ePJS clinician link (the test link with a long-dated token expiry).

Error shown is

```
Internal server error
```

![image](https://user-images.githubusercontent.com/151362/30748782-33002732-9fa9-11e7-8c7c-1d171c85674a.png)

**Comment by katbow** [comment]
I cannot access the server at all right now

![image](https://user-images.githubusercontent.com/1287388/30748840-68973732-9fa9-11e7-9981-6eb9e8194b56.png)


And I am getting this page displaying when I try to go to the site
![image](https://user-images.githubusercontent.com/1287388/30748828-5eeca726-9fa9-11e7-98a6-29dcc5dd3752.png)

This is the same behaviour we saw when the server was stopped by SLaM

**Comment by reddog** [comment]
Email sent to Stuart at SLaM IT Operational Services to see if they have any further information.

If not, it will be their team who are required to restart the server.

**Comment by katbow** [comment]
yeah, it was brought down last week before this issue was made. I can't remember where that was updated.

I recall it as
* server was brought down
  * at this time I could not access the live server, and the site was displaying as my [screenshot here](https://github.com/healthlocker/healthlocker/issues/1072#issuecomment-331460429)
* Server was restarted and we had the 502 page from nginx.
* After I rebuilt, deployed and started the app it was accessible again. I could only do this after I was able to ssh into the live server

**Comment by reddog** [comment]
@katbow I think that's my recollection as well.  This issue was created as a result of the server being unreachable and then restarted - that's what I thought it was?  SLaM haven't previously said that they have stopped the server without telling us - have they?

**Comment by katbow** [comment]
I remember discovering I could not ssh into it, then later being told SLaM had turned it off. Entirely possible I misunderstood and the server stopped for some other reason.

**Comment by reddog** [comment]
@katbow Yes, I think you're right in that you and I couldn't connect to it, but I think SLaM then restarted it, hence we could then re-connect.

**Comment by katbow** [comment]
yeah they did restart it. The part I was misremembering was thinking they had stopped it which is why we couldn't connect. I found the conversation on Slack though and I was remembering that part wrong.

**Comment by reddog** [comment]
Access to https://www.healthlocker.uk/ is now beginning to work but is *very* slow and is still timing out.

Access to the test site at https://staging.healthlocker.uk/ is working fine.

**Comment by katbow** [comment]
@reddog what do you mean by starting to work? I am getting the exact same page as above and still cannot access the server. Are you able to get pages to load?

**Comment by reddog** [comment]
@katbow I managed to get the homepage, once.  It probably sat there for 10 mins to get to it.

**Comment by reddog** [comment]
Looks like it could the sign of an ongoing, as yet not understood issue, see #1096.  Server has been restarted from being down on this occasion.
