### ISSUE TITLE
Change forgot password flash message if email address is not in system

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1073]
From PEN testing:

If you enter your email address to get a reset password link, you currently get a different flash message depending on whether your email address exists in the DB or not.  We need them to be the same.

**If I enter my email address to get a reset password link and my email address is NOT in the HL DB, or I am a clinician:**
- [ ] redirect to login with yellow flash message that says "If your email address exists in our database, you will receive a password reset link at your email address in a few minutes."

So there is only one behaviour regardless of who takes the action.

![screenshot 2017-09-20 09 34 37](https://user-images.githubusercontent.com/24604903/30634424-f32543cc-9de6-11e7-9cf6-a9d6a1427e3a.png)

**Comment by katbow** [comment]
@katyedwards what message do they want to see?

The current behaviour is...
* user doesn't exist or user is a clinician:
  * Re-render password reset form with message that says "Could not send reset email. Please try again later"
* user exists & is not a clinician
  * redirect to login with message that says "If your email address exists in our database, you will receive a password reset link at your email address in a few minutes."

Should the user be redirected to login with the "If your email address..." message regardless?

**Comment by reddog** [comment]
@katyedwards Strictly speaking should you not be able to make the change in a git pull request? Since it's a content change (change of message) seems like that's something that's best decided by you, and you can even go ahead and implement the change ;-)

If you wanted to change the colour of the message box however, that's a different matter!

**Comment by katyedwards** [comment]
@katbow have updated the issue above - yep, it should be identical behaviour regardless of who enters an email address.

@reddog the colour will need changing, i'm afraid!

**Comment by katyedwards** [comment]
Looks good, thanks
