### ISSUE TITLE
nginx failed to restart after Let's Encrypt SSL renewal on staging

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#1076]
The staging server was restarted (as part of a process looking in to firewall rules) and the HealthLocker app was started.  Some time shortly thereafter the site stopped working.  This was because nginx had stopped.

nginx stopped because the SSL certificates had been renewed but there was a problem with them.

We need to investigate what the problem was so that it doesn't reoccur.

**Comment by katbow** [comment]
When the ssl certificate renewed, it created a new certificate/priv key. The new file was named `priv_key2.pem`, however nginx was pointing to the old certificate, `priv_key1.pem`.

**Comment by reddog** [comment]
@katbow Thanks for spotting that (probably didn't help with me renaming suggestions!)

We should re-run the Let's Encrypt renewal process and ensure it works as expected.

**Comment by katbow** [comment]
Yeah the renewal process will need to be checked so that ideally the file names remain the same and the nginx configuration will not need to be updated.

**Comment by RobStallion** [comment]
relates to #1063 and appears to have been resolved
