### ISSUE TITLE
Error on date when connecting as carer

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1089]
**On both staging and live**

I tried to connect as a carer (using wrong details as I don't have correct ones!) and after I hit submit it:

1. reversed the order of the DOB

2. added an odd entry to the DOB field

FYI, I typed in 12/03/1983

![screenshot 2017-09-20 15 34 51](https://user-images.githubusercontent.com/24604903/30649919-74c7c06c-9e19-11e7-8e35-5f2749287e7c.png)

**Comment by katbow** [comment]
This should now show up as the date that was input (once it's merged in 😉)
![image](https://user-images.githubusercontent.com/1287388/30709753-34a65ede-9efb-11e7-876b-7b2e509a0a89.png)

**Comment by katyedwards** [comment]
Great, seems to be working well now
