### ISSUE TITLE
Is AppSignal connected to live site

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1091]
Since no paid account has been provided was this ever included in the live deployment?

If not I need to update the handover documentation we have provided to the trust.

**Comment by katbow** [comment]
@katyedwards AppSignal is  still included in the application, but it's not hooked up to receive reports. The app would need to be added to appsignal, and the  `APPSIGNAL_PUSH_API_KEY` would need to be added as an environment variable, and then of course would need the paid account for it to actually do anything.

**Comment by katyedwards** [comment]
Thanks @katbow 
I'll leave it on the documentation for now then.
