### ISSUE TITLE
Alter ePJS connection details - increase keep-alive ping period

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#1095]
As an interim fix to #1090, we have spoken with Garry in SLaM's ePJS team and they are happy to consider if server performance isn't too adversely affected by increasing the *keep alive* ping duration.

What's required:

- alter the MS SQL Server ePJS extract database connection routine to perform the *keep alive* ping (`SELECT 1`) queries once every 10 seconds per connection (currently once every second).  https://github.com/findmypast-oss/mssqlex/issues/1#issuecomment-331089023 might contain useful information on the setting required.
- after re-configuring, deploying and making HealthLocker live again, Garry's team will monitor server load
- if database server load remains too high, we will be requested to increase the ping duration further.

**Comment by reddog** [comment]
@katbow Can you please let me know once this has been implemented and then we can ask SLaM to monitor server load.

**Comment by reddog** [comment]
@katbow Thanks for taking a look at this.

Would it be much work to move the ping duration to an environment variable setting (as per the database access details immediately preceding it)?  That way maybe we wouldn't need a repeat code merge if we have to alter the ping duration again (which will depend on results of server monitoring).

**Comment by reddog** [comment]
@katbow I have tested with an old clinician login link and the login is taking about 40 seconds to action.  This was previously completing in a few seconds.

It could be that this is an ePJS database issue and we can check with them.  However it might be good to rule out issues at our end.  How long would it take to revert the site back to the previous version so we could re-time the clinician login before updating the site again and passing to SLaM to test?

If the clinician login is *a lot* quicker with the previous settings then maybe something is wrong with the new change.

**Comment by katbow** [comment]
@reddog I tried this as well with an old one, and it was instant for me. Can you try one more time and of if it's still the same for you I can wind it down to 1000 ms again and redeploy.

**Comment by reddog** [comment]
@katbow Was that a link with an expired token or a non-expiring token?

**Comment by katbow** [comment]
it was with an already expired token.

**Comment by reddog** [comment]
I got a reply straight back with an expired token.  Could you re-deploy the previous version so that we can re-test?

**Comment by reddog** [comment]
@katbow Has deployed to live (and also to staging) and tests (with non-expiring ePJS token) have gone well.

This is now with Garry in the ePJS team at SLaM.  They are monitoring over the next hour and will report back.

**Comment by reddog** [comment]
Reply from Garry in SLaM's ePJS team:

> We have reviewed stats captured for pings upon SQL Database Server and can confirm that this has been reduced which will have beneficial reduction upon the overall server load.
