### ISSUE TITLE
Take live HealthLocker app down at the end of today (22/9/17)

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#1096]
Whilst we are still in the stages of live-testing HealthLocker, SLaM have requested that we take down the live HealthLocker app at the end of today, 22/9/17, and bring it back up again on Monday morning.  This is due to SLaM having no staff available at the weekend to monitor database server impact.

**Comment by katbow** [comment]
@reddog what time is their end of day?

**Comment by reddog** [comment]
@katbow I'll check.  Previously we've been asked to take it down at 4pm.

**Comment by reddog** [comment]
We're currently unable to reach the live server, see https://github.com/healthlocker/healthlocker/issues/1072.

I have sent an email to Stuart's team asking for the live server to be restarted as an effective method of stopping the HealthLocker app.  Garry's team has been copied in order to make him aware of the situation.

**Comment by reddog** [comment]
Garry has temporarily disabled the live ePJS extract database user as a workaround to stopping the live HealthLocker app.

**Comment by katbow** [comment]
Can confirm this is down now

![image](https://user-images.githubusercontent.com/1287388/30754610-47deebb8-9fbb-11e7-932d-983afb7990bc.png)

**Comment by reddog** [comment]
Looks like maybe the live site was restarted by SLaM?  @katbow you weren't able to connect and stopped the HealthLocker app did you?
