### ISSUE TITLE
Link easy-to-read content about what to do in a crisis

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#11]
As a person using HL,
I can link to information about what to do in a crisis
so that others can view it and use it to help themselves when they are facing a crisis.

## Acceptance Criteria

+ [x] Get support button to be visible and easily accessed when a user lands on HL. (a contrasting colour / easy navigation)

+ [x] if a user clicks the get support button, the Get support info appears (new screen / reveal / pop up?) This includes this one #6 SLaM crisis line (top) and #11 What to do in a crisis (underneath crisis line) Content below, these are NOT like wellness tips.

+ [x] on mobile phones -  the 999 phone number to becomes a click to call link (not sure what the technical term for that is)

+ [x] the find local A&E link - opens in a new tab
+ [x] best service for you... Only 1 full stop.

## **Copy / content:**

**What to do in a crisis:**

- follow your care plan, if you have one or call your co-ordinator
- if you think there is an immediate risk, call 999 or find your nearest A&E department, open 24/7
- if you can wait for an appointment, your GP can help find the best service for you.

**Comment by nelsonic** [comment]
@MollieCourtenay please confirm/clarify this requirement with **_acceptance_ criteria** 
and _prioritise_ it for us so we can estimate and start work. thanks! 👍

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria

+ [ ] Get support button to be visible and easily accessed when a user lands on HL. (a contrasting colour / easy navigation)

+ [ ] if a user clicks the get support button, the Get support info appears (new screen / reveal / pop up?) This includes this one #6 SLaM crisis line (top) and #11 What to do in a crisis (underneath crisis line)

+ [ ] on mobile phones -  the 999 phone number to becomes a click to call link (not sure what the technical term for that is)

**Comment by MollieCourtenay** [comment]
## **Copy / content:**

**What to do in a crisis:**

- follow your care plan, if you have one or call your co-ordinator
- if you think there is an immediate risk, call 999 or find your nearest A&E department, open 24/7
- if you can wait for an appointment, your GP can help find the best service for you.

**Comment by LauraNevo** [comment]
@MollieCourtenay I added the IT support we talked about with @nelsonic but I'm not sure if it's supposed to be in another user story?

![get support](https://cloud.githubusercontent.com/assets/3858131/22431269/dfaffc96-e708-11e6-87f5-e226c6a3ac2c.png)

**Comment by katbow** [comment]
This was done in conjunction with #6

**Comment by MollieCourtenay** [comment]
@katbow I think those two changes above have been made.

One more please, then happy to close this one.

+ [ ] Move 'What to do in a crisis' to replace 'support'

**Comment by MollieCourtenay** [comment]
Change in my comment above has not been made so reassigning @katbow
