### ISSUE TITLE
Restrict Repeat access to new problem tracker page

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1109]
2 test users experiencing an Internal server error when viewing the tracking overview.  

@reddog looked at the appsignal monitoring and it seems to be where the database thinks someone has more than one problem tracker (which shouldn't be possible!).

I have managed to replicate it today with the following steps:
- Login in
- Click on problem tracker
- Set up new problem tracker
- enter tracking data
- Tracking overview works

But if you then

- either click the back button to get back to the 'set up new problem tracker' page or paste in the address 'healthlocker.uk/symptom/new'
- label another problem tracker, edit the name or leave don't change anything
- click save
- enter tracking data
- click on tracking overview now gives an internal server error.

Can we set it up so:

- [ ] adding a unique index for the user_id in the symptoms table, which will allow only one problem type per person.

- [ ] Returning to this page and trying to save a second problem tracker would generate an error flash message saying 
"You can only set up your problem tracker once.  Track your problem now"
NB. 'Track your problem now' links to https://www.healthlocker.uk/symptom-tracker/new

**Comment by katyedwards** [comment]
Update from @katbow by email:

The simplest way is adding a unique index for the user_id in the symptoms table, which will allow only one problem type per person. If they were to paste in the url/go back and try to save again, they would have an error like how you mentioned.

We can also have a redirect on the symptom/new page, so that if someone pastes in the URL, they are redirected somewhere else with a message that they have already done that. This isn't necessary for preventing the data being saved as the above will do that, but it would follow the same flow as the sleep tracker/symptom tracker pages if you wanted to stay with that.

**Comment by katyedwards** [comment]
@katbow one thing I forgot... for those 2 users affected (just slacked to you), can you delete one of the trackers from the database so their accounts will work again?

If this is complicated or time consuming or inadvisable for some other reason, let me know - but I think the client would feel better if these 2 users were 'fixed' rather than just being told that it won't happen again for anyone else.

Thanks!

**Comment by katbow** [comment]
@katyedwards what do you want as the flash error message? For now I put "You've already added a problem. Track it in the problem tracker."

Let me know if that's alright or if you would like something different!

**Comment by katbow** [comment]
oh & also, do you want both steps completed for this? As in, I am currently adding the unique_index & error message for if someone tries to add a problem when they already added one. Do you also want to redirect before they can even input info if they have already done this?

I.e.
User adds problem
-> hits back/pastes in the url at a later time
-> user is redirected to `/symptom-tracker/new` with error that they have already done that

vs.

User adds problem
-> hits back/pastes in the url at a later time
-> user tries to input a problem, and gets an error they have already done that, & stays on `/symptom/new`

**Comment by katyedwards** [comment]
If it is to match the functionality on the sleep tracker and adding problem tracking data it would be the the first option where they can't access the page at all:

I.e.
User adds problem
-> hits back/pastes in the url at a later time
-> user is redirected to /symptom-tracker/new with error that they have already done that

But if that is more time consuming in any way then either option will have the required effect.

Again to match the other error messages, can it read:

"You can only set up your problem tracker once. Track your problem now"

Thanks @katbow

**Comment by katbow** [comment]
@katyedwards I added in that if someone types in the url, it redirects them `/symptom-tracker/new` if they already have a problem tracker. They won't get an opportunity to try entering a new symptom.

If they press back after entering it, it will still go to `/symptom/new` as it's not making a new request, but when they attempt to enter data they will get an error.

**Comment by katyedwards** [comment]
@katbow that seems to be working great on staging.

Can I make a change to one of the flash message... 

On the second option:
If they press back after entering it, it will still go to /symptom/new as it's not making a new request, but when they attempt to enter data they will get an error.

Can the second part of the flash message 'Track your problem now' be a link to enter tracking data (</symptom-tracker/new>) otherwise it feels a bit like they are stranded on that page.

The other one is ok as it redirects them to (</symptom-tracker/new>) so they can easily carry on.

**Comment by katbow** [comment]
@katyedwards I actually changed that completely in the next PR to be more generic - "Something went wrong. Try again later." This is because an error can happen for other reasons when inserting data (e.g. momentary lost connection/timeout from slow internet), so it would actually be confusing to have that error if someone is entering it for the first time, but a different error is happening. And further if this happened & they went to the link from the message, they would get another error because they have no problem to track.

Because the user_id isn't entered by the user, there's not a specific field the error can be tied to for this specific case. 

Let me know what you think.

**Comment by katyedwards** [comment]
@katbow I see what you mean - I don't know which is going to be more confusing... will people keep trying if they want to edit the title of their problem tracker?

Hopefully not as they'll struggle to find the page again later.

I think for now that works - it can be user tested.  If they want to change the flash message later then that can be added to the list for one of the support days.

Let me know when it's merged in and I'll test and close.

**Comment by katbow** [comment]
the new message is merged in now so that part can be tested as well. 

> Hopefully not as they'll struggle to find the page again later.

That was my thinking as well. If it's because of this specific problem, then the likelihood is they will stop trying for a time, and when they come back to it it would be a new request to the page so they would be redirected in that case. We can see how it works with testing!

**Comment by katyedwards** [comment]
Yep sorry - just saw that, I tried the other option and the error message looked the same!

**Comment by katyedwards** [comment]
Yep - works great!
