### ISSUE TITLE
Copy change to Feedback Page

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1115]
Feedback page currently asks for "Subject" and "Your feedback and suggestions"

- [x] Change last sentence of guidance text to: 
If you would like us to follow up to discuss, please leave your name and contact details including **email address**.  We appreciate your valuable feedback and will respond within 72 hours.”

To be changed on Staging and Live

**Comment by katbow** [comment]
t25m is assuming it's only copy change at this point. Will tack on an additional 25m if the field is separated as well.

**Comment by katyedwards** [comment]
@katbow 

Time allowing, can we please have an additional box for email address, as per this ugly mock up (sorry am designer-less!)

![screenshot 2017-11-28 15 28 19](https://user-images.githubusercontent.com/24604903/33370457-7c605dcc-d4ef-11e7-8fbe-4702dd9515d3.png)

Note: The email address box is optional so they can submit the feedback without filling it in,

**Deployed to staging only**

**Comment by katbow** [comment]
should the text still say email address above as a reminder to include it if a response is desired?

**Comment by katyedwards** [comment]
Yes, text stays as in the top comment.  Thank you!

**Comment by katbow** [comment]
@katyedwards I have a couple of questions for this! 

What do you want done with the email address that is input? I imagine the idea would be that it cane be replied to. However, in order to come through as the "from" email, it needs to be previously verified through the email sending service, which is not possible for any random user giving feedback. 

One thing I can do is make it part of the message body. Something like:

```
Message from: user_email@example.com

Feedback message goes here
```

Let me know your thoughts.

**Comment by katyedwards** [comment]
Yep that works - it doesn't need to look as though it is coming 'from' that person, it can just go in the body text of the feedback email.

If someone submits feedback and doesn't fill in the email box, that bit can just be left blank.

Thanks!

**Comment by katbow** [comment]
please test is just for the text for now @katyedwards. Working on the other part at the moment!

**Comment by katyedwards** [comment]
Copy change looks good, thanks @katbow!

**Comment by katbow** [comment]
Update for this - it's done but I can't push the local change I made up because of the poor internet.

**Comment by katyedwards** [comment]
All done!  Thank you!
