### ISSUE TITLE
Redirect users who have no goals straight to 'new goal' page

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#112]
As a user with no goals, rather than having to go through the additional click to create a new goal, I would like to be taken straight to where I can create a new goal without having to go through a 'You have no goals' screen which can demotivate me.

## Acceptance Criteria
+ [x] As a user with no goals, when I click on goals, I am taken to 'add a new goal' page 

#91

@MollieCourtenay Are you able to validate this requirement?

**Comment by MollieCourtenay** [comment]
@iteles absolutely.
