### ISSUE TITLE
Change Sleep Tracker Graph Date

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1124]
When you track your sleep it appears on the graph dated the day the data was entered.

e.g. Enter tracking data on Tues 5th December and the graph shows sleep for 5th December.

This is confusing as you are entering your data for the night before, so the graph is always a day out.

When you enter sleep tracking data it should display:

- On the graph - the day before e.g. 4th Dec

- The detail should be listed under the day before e.g. 4th Dec under the graph.

The problem tracker and diary should still both display as the day the data was entered

e.g. track problem or fill in diary on Tues 5th December and it shows on the graph as 5th Dec.

To deploy to staging only

**Comment by RobStallion** [comment]
closed in error

**Comment by katyedwards** [comment]
@RobStallion That's working great on the graph itself, but the detail is still being listed as the current day but not the day before.

![screenshot 2017-12-06 16 31 34](https://user-images.githubusercontent.com/24604903/33672849-2e3a689a-daa3-11e7-9864-ac2426cacd8a.png)

**Comment by katyedwards** [comment]
@RobStallion I'm getting an internal server error when I try to view the graph now...

Login in
Click on Sleep Tracker
Fill in data and click save
Click to view tracking overview
Internal server error

I've tested this on 2 users.  Can you let me know when you'll be able to look at this?

**Comment by RobStallion** [comment]
@katyedwards I just had a quick look at this and I believe that this happening when there are days that a user has not entered any 'notes' (for sleep or problem tracker) as the function that is being used to format the notes output never accounted for cases when there was no text.

It is a fairly quick fix but I'm not sure on availability for someone to review the code and merge it in. I'll check this on my end and update you when I have some more information

**Comment by katyedwards** [comment]
Thanks Rob - hopefully someone will be available to do a quick review and merge today!  Look forward to the update!

**Comment by katyedwards** [comment]
@RobStallion any update yet?

**Comment by katyedwards** [comment]
@RobStallion Can you confirm if someone will be able to review this - thanks!

**Comment by RobStallion** [comment]
@katyedwards Sorry for the delay in getting back to you on this. Working on it at the moment and @SimonLab will be reviewing it at the end of the day

**Comment by katyedwards** [comment]
Thanks @RobStallion and @SimonLab all looks good so have handed over to the client and will close this!
