### ISSUE TITLE
SSL cert for healthlocker.uk

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#113]
#101 need to have ssl cert for https

healthlocker.uk is automatically redirecting to https, but there is currently no ssl certificate so the connection is refused

see: https://letsencrypt.org/

**Comment by nelsonic** [comment]
@katbow see: https://blog.heroku.com/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

**Comment by nelsonic** [comment]
This will help: https://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku it's rails but we can use the `certbot` part.

**Comment by nelsonic** [comment]
@katbow can I assign this to myself while you work on the Account page? 
(_I will include step-by-step "reperformable" instructions in my PR..._)

**Comment by katbow** [comment]
sure, no problem 👍 . That would be great because I'd quite like to know what the solution is!

**Comment by nelsonic** [comment]
![heroku-cert-wrong-domain](https://cloud.githubusercontent.com/assets/194400/23306602/267571be-fa9c-11e6-85e2-122c3cc2dd87.png)
So close ... trying one more thing... 😉

**Comment by tonydaly** [comment]
Don't letsencrypt certificates expire after 90 days? Will we have anything to automate the renewal process?

**Comment by nelsonic** [comment]
@tonydaly yeah, they expire but it's one command to renew them `certbot renew` 
we can always consider a "_paid_" Cert provider if it gets tedious.
but I wanted to try this out and write up a tutorial for how to get ***Free*** SSL. 🚀

**Comment by nelsonic** [comment]
![boom-ssl-enabled](https://cloud.githubusercontent.com/assets/194400/23307463/8ffdb602-fa9f-11e6-92c5-806e3393386e.png)

**Comment by tonydaly** [comment]
It's the same issue with paid providers, happens to everyone that they forget to renew. Just happens more frequently with letsencrypt that you're almost forced to automate it (this is quite intentional on their part).

**Comment by nelsonic** [comment]
Yeah, there are few people on Hackernews who complain about the short lifetime of certificates...
When it's time to renew I will write a script and add it to our tutorial. 👍

**Comment by nelsonic** [comment]
@katbow @tonydaly @iteles @MollieCourtenay @katyedwards @emilytulloh @LauraNevo @luxyUX 
you'll be pleased to know that ***SSL Enabled***.  🎉 
The "Beta" App is deployed to: https://www.healthlocker.uk 
(_thanks to Kat & Tony mostly, I just did a bit of configuration..._)

![healthlocker-app-deployed](https://cloud.githubusercontent.com/assets/194400/23308014/91adecae-faa1-11e6-97c2-8b05216d9510.png)

**Comment by nelsonic** [comment]
@katbow please confirm this is working as _expected_ and close the issue. thanks. 👍

**Comment by katbow** [comment]
👌
