### ISSUE TITLE
Order of displayed steps on Goals (014b)

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1135]
When steps are displayed on the goals page, the steps should appear in the same order in which they were input, regardless of whether they have been ticked as complete or not.

Currently they are appearing with non-ticked steps first as below:

![screenshot 2017-12-13 16 31 42](https://user-images.githubusercontent.com/24604903/33950022-28e4d580-e023-11e7-9cbb-97b0ced670ec.png)
![screenshot 2017-12-13 16 31 50](https://user-images.githubusercontent.com/24604903/33950023-2a366e58-e023-11e7-82aa-5661ea38faf4.png)

### Acceptence Criteria:
- [ ] On https://staging.healthlocker.uk/goal steps are displayed in the same order they have been input.

**Comment by katyedwards** [comment]
Sorry @RobStallion client would like the steps to appear with the ticked steps below the un-ticked ones.

But before anything you did here, that didn't seem to be the case for all steps - I think new ones were ordering in this way but existing ones weren't?

Can you set it up so on the main view goals page, all goals (existing or new) display the steps with any ticked steps moved to the bottom of the list

So the list will be ordered such:

1. Un-ticked goals in the order in which they were entered on the new/ edit goal page
2. Ticked goals in the order in which they were ticked (most recently ticked steps at the bottom of the list)

Thanks!

**Comment by RobStallion** [comment]
I am currently having an issues testing the goal functionality. 

Tests have started failing locally that were not previously, and do no fail on travis. As this seems to be an issue that is just on my local machine at the moment I do not want to put much more time into this at the moment.

I will make a separate technical issue for this.

**Comment by katyedwards** [comment]
@RobStallion would it be worth deploying to staging so I can test?

**Comment by katyedwards** [comment]
LGTM!  Have handed over to client to test and will raise another issue to deploy to live once they have approved it.
