### ISSUE TITLE
Formatting of free text boxes (011 cont'd)

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1138]
Continuation of #1116 and #1123 

If you type something on one line, put in a single line break and then type something on the next line, it doesn't recognise the break and displays it all on one line:

**Entered:**
![screenshot 2017-12-18 14 34 14](https://user-images.githubusercontent.com/24604903/34111129-c301f34c-e400-11e7-9be0-0e8b150cfa27.png)

**Displays as:**
![screenshot 2017-12-18 14 34 19](https://user-images.githubusercontent.com/24604903/34111131-c4941122-e400-11e7-9edd-a3f7ea7fb739.png)

This should display as it has been typed in - on two lines

Please apply to:

- [x] Coping Strategies
- [x] Goals 'content' box
- [x] Sleep tracker notes
- [x] Problem tracker notes
- [x] Diary text entry box

See also #1139

**Comment by RobStallion** [comment]
Hey @katyedwards. I have started on this issue and this is what it currently looks like...

![image](https://user-images.githubusercontent.com/15571853/34522310-e9840f60-f089-11e7-8f1a-5e69d8fec414.png)

If you press return only once, the text does go to a new line but it doesn't have a space. If you press return twice or more then you get the space. 

Is this ok/what you had in mind?

**Comment by katyedwards** [comment]
Yep perfect!  Before the single return wasn't pushing text down onto the next line.

**Comment by katyedwards** [comment]
Perfect!  And this has solved #1139 as well as the line break means it will display as a bullet in effect.
