### ISSUE TITLE
DEPLOY TO LIVE Missing Diary Entries on tracking overview (016)

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1146]
There are some missing historical diary entries if you compare SU and clinician tracking overviews:

## Example 1:
**Service User Account:**
![image](https://user-images.githubusercontent.com/24604903/34722245-efbd325e-f53d-11e7-949a-c7928b4a27c8.png)

**Clinician view of above SU:**
![image](https://user-images.githubusercontent.com/24604903/34722267-1139a034-f53e-11e7-8809-5cc6eabe496d.png)

## Example 2:
**2nd Service User Account:**
![image](https://user-images.githubusercontent.com/24604903/34722275-177c9118-f53e-11e7-8698-b4f8092eb525.png)

**Clinician view of 2nd SU:**
![image](https://user-images.githubusercontent.com/24604903/34722297-2cce2112-f53e-11e7-9bbf-3940f813b8e5.png)

Katy has specific user account details
  
## Update

I queried the screenshot showing Dec 20th as it showed no data.
The client checked it and it now shows no data for them, but according to mixpanel there is a record of a diary entry having been created??!?!?

**Comment by RobStallion** [comment]
Update: 
While looking into this issue I have entered two weeks worth of data (into my local db) starting from todays date and going backwards for each of the following trackers, symptom/problem, diary and sleep.
The sleep and symptom trackers both display as expected but the diary only displays information for the current week but will not show for previous weeks. 

Next step: 
The data is put together ready to be sent to the front end by a function called merge_tracking_data in the *tracker_controller.ex*. Will look into this function to see if there is anything wrong with the way the diary data is being collected/processed

**Comment by RobStallion** [comment]
Have spotted the error with the **diary data** not being displayed. The arguments for the dates that were being passed in were incorrect. I have updated it locally and tested it and it appears to be working as expected now. 

However whilst looking into this I have come across another bug, which I will open a separate issue for, where no data is being displayed for the first day of the week.

**Comment by katyedwards** [comment]
Great, thanks @RobStallion

**Comment by katyedwards** [comment]
Issue was initially seen in the live environment so client would like this deployed to live for them to be able to test.

**Comment by katyedwards** [comment]
Client has now confirmed this is ok!
