### ISSUE TITLE
Mixpanel - how to track ePJS users

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1149]
There is a problem tracking users who come via ePJS (i.e. clinicians), in Mixpanel.

At the moment there is no way to distinguish between users so you can't tell which are the IT team accessing with test users and which are actual clinicians looking at the site.

Mixpanel seems to show a lot of 'undefined' data which we believe are the ePJS users.

![image](https://user-images.githubusercontent.com/24604903/36473155-a5760ac0-16eb-11e8-8a6c-5f4fc26d18cb.png)

![image](https://user-images.githubusercontent.com/24604903/36473576-cccfbe9e-16ec-11e8-9f2d-4cf8e9b9e6d3.png)

There are an awful lot of null there which we assume are users via ePJS.

Will slack you Mixpanel login details... 

## Acceptance Criteria
- [ ] As a Healthlocker project lead at SLaM I can see which users are being authenticated via ePJS
- [ ] As a Healthlocker project lead at SLaM I can identify individual ePJS users and track their activity.

**Comment by katyedwards** [comment]
Let me know if you need more info from me on this @RobStallion

**Comment by RobStallion** [comment]
@katyedwards How do you know that the issue is with tracking clinicians coming via ePJS? The only reason I ask is because there seems to be plenty of data tracked on mixpanel with the with emails ending in `slam.nhs.uk` which would make me think that they are clinician email addresses.

**Comment by katyedwards** [comment]
@RobStallion I think there is an amount of assumption involved, but it may also be that some of the IT team (with slam.nhs.uk email addresses may have set themselves up as SUs for testing purposes.

I'll ask...

**Comment by katyedwards** [comment]
@RobStallion if you're already logged in and have it to hand, can you slack me a few of the exact email addresses.  Thanks!

**Comment by katyedwards** [comment]
All info handed over to client and they have apparently been able to set it up to their satisfaction.
