### ISSUE TITLE
DEPLOY TO LIVE - Tracker view missing first day of the week

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#1150]
When in the tracker view no data is being displayed for the first day of the week. 

![image](https://user-images.githubusercontent.com/15571853/34771845-e6e69f74-f5fd-11e7-9abb-287b03d05353.png)

In the image above the data is being rendered as expected for the dates 5/1 to 10/1. However nothing is being rendered for the 4/1 and there is data in the database for this date. 

I have entered data for the previous week as well to make sure that it is not a problem with the data entered for the 4/1. 

![image](https://user-images.githubusercontent.com/15571853/34772197-241a9b6a-f5ff-11e7-8051-585a77dbd6bd.png)

As the image shows the 28/12 is not displaying any information despite me making an entry into my local db with a symptom and sleep trackers for that day.

**Comment by katyedwards** [comment]
Ahhhh that explains why 20th disappeared!  It was the first day of the week yesterday but isn't today.  Well spotted @RobStallion!

**Comment by katyedwards** [comment]
Issue was initially seen in the live environment so client would like this deployed to live for them to be able to test.

**Comment by katyedwards** [comment]
Client has confirmed this is now ok!
