### ISSUE TITLE
Both staging and live site are down

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#1152]
Look into why the staging and live sites are not working

**Comment by RobStallion** [comment]
I am unable to `ssh` into either server which leads me to believe that SLaM may have done something to the servers. 

@katyedwards Could you please ask your contacts at SLaM to see if they have done anything with the servers that could have caused this issue?

**Comment by RobStallion** [comment]
Getting the following error when trying to `ssh` into either server...

```ssh: connect to host xxxxxxxxxIP_address port 22: Operation timed out```

**Comment by katyedwards** [comment]
Have already asked!  Just waiting for reply - will give them a call if I haven't heard anything soon.

**Comment by RobStallion** [comment]
Just received a call from Matt at SLaM.

He has been able to access the server at SLaM and wanted to know how to start the application. Have given him instructions on how to start it and they said that the site is working internally for them but I am still unable to access the server or view the website.

This seems like it could be a firewall issue. Matt is going to look into that and get back to me

**Comment by RobStallion** [comment]
Have attempted to `ssh` into both healthlocker servers again but have been unable to gain access.

**Comment by RobStallion** [comment]
Have been able to ssh into the live server but it is quite inconsistent at the moment. Works about half the time and the other half the operation times out. 

Have emailed Matt and @katyedwards to update them. 

Have not been able to gain any access to the staging server at any point

**Comment by RobStallion** [comment]
Have just finished speaking with Matt at SLaM and we were unable to connect to the server consistently. It was failing to connect far more than it was connecting and because of this we were unable to start the application. 

We also tested logging into the server from multiple wifi spots but they all had the same issues.

**Comment by RobStallion** [comment]
Speaking with Matt at SLaM again. He said that the initial problem that was stopping us from being able to access the site and server was to do with the load balancer. He said that this issue has now been resolved but I am still having issues when trying to access the server. 

Trying to find what the source of the problem could be. Managed to start the application using the command `mix edeliver start production` but get the following error when trying to view the site...

![image](https://user-images.githubusercontent.com/15571853/35515218-7eb4d5b2-0500-11e8-837d-0fe4065b1338.png)

![image](https://user-images.githubusercontent.com/15571853/35515239-87fced44-0500-11e8-985e-0fd8b60c3cbd.png)

This seems like it could be to do with the certificate. Looking into this now

**Comment by RobStallion** [comment]
I cannot see any problems with the certificate on the live server. 

I have looked in the nginx config and that appears to be configured as expected. I have also tried to renew the certificate, using the command `cerbot renew`, just to be on the safe side but `certbot` is saying that the certificate is not due for renewal yet.

**Comment by RobStallion** [comment]
I completely removed the nginx config to and replaced it with the following...
```
server {
  listen       80;
  server_name  localhost;
  location / {
    proxy_pass          http://localhost:4000;
    proxy_set_header    Host             $host;
    proxy_set_header    X-Real-IP        $remote_addr;
    proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header    X-Client-Verify  SUCCESS;
    proxy_read_timeout 1800;
    proxy_connect_timeout 1800;
  }
}
```

With this config we are able to access the site...

![image](https://user-images.githubusercontent.com/15571853/35520405-d93f9dd8-050e-11e8-8d78-c9aa5fee275e.png)

Which leads me to think again that the issue is with the certificate. Going to put the nginx config back to what it should be and will look into the certificate again.

**Comment by katyedwards** [comment]
Any chance this has anything to do with changing the email address t'other day? @RobStallion

**Comment by RobStallion** [comment]
Attempted to renew the certificate by force with `certbot renew --force-renewal` to see if that would work but it had an error. 

Shortly after this I got an error saying `port 22: Broken pipe` and I was kicked off of the server. I can no longer ssh to the site or get any response when (even the error about the certificate) when I put the ip address into chrome.

Seems like the server may be down again. Tried calling Matt from SLaM but no answer at the moment

**Comment by RobStallion** [comment]
@katyedwards That should not have effected anything but thanks for the suggestion

**Comment by RobStallion** [comment]
Site appears to be working as expected now 
![image](https://user-images.githubusercontent.com/15571853/35525206-c1027c88-051b-11e8-82d8-80455d8cc55b.png)

I did not update the ssl certificate as it was not due for renewal. I will try to get hold of Matt to see if he has changed anything on that end

**Comment by RobStallion** [comment]
No answer from Matt. Have send them an email with the current status

**Comment by RobStallion** [comment]
Staging site is still down

**Comment by katyedwards** [comment]
@RobStallion Can you add a summary here as to what the problem was and how it was resolved so we have it noted for the future (and add the time you spend onto the HL time from yesterday).  Thanks!

**Comment by RobStallion** [comment]
Matt at SLaM has confirmed that the load balancer is what had caused the initial error. Matt at SLaM started working on this which allowed the server to be accessed and lead to the SSL error we were getting for most of yesterday. As @reddog has suggested above, it looks like this error was also linked to the load balancer.

**Comment by katyedwards** [comment]
FYI - I have spoken to Matt today and he is sure the high CPU load doesn't have anything to do with the load balancer issue.
