### ISSUE TITLE
Account screen

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#116]
As a user I can access my account to view and update my details.

## Acceptance Criteria 

+ [x] As a user I can access my account to view and update my details.

<img width="522" alt="screen shot 2017-02-21 at 18 12 12" src="https://cloud.githubusercontent.com/assets/25012688/23178209/7e6b3a3a-f861-11e6-8fe2-5ac00810bf45.png">

Linked to #28

**Comment by katbow** [comment]
@MollieCourtenay what should happen if a user clicks the cancel button?

**Comment by katbow** [comment]
also @MollieCourtenay @LauraNevo one other question, how is the account page accessed? Is this also in the drawer menu?

**Comment by LauraNevo** [comment]
@katbow 

First,I guess it there's no updated field, there's no need to cancel. Second, if someone doesn't want to update, they can press their phone's back button or go somewhere else through the menu. It would be weird to go to another page is Cancel was tapped. That sounds like we don't need the Cancel button at all.

It is in the drawer menu:

![drawer menu](https://cloud.githubusercontent.com/assets/3858131/23256531/c9343e84-f9b7-11e6-84f7-4ac57e71ba2c.png)

**Comment by katbow** [comment]
@LauraNevo great, thanks for that!
