### ISSUE TITLE
When is Care Plan pulled in?

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1161]
When the care plan is pulled in, is it/...

- Stored in the HL Database
- Just displayed and pulled through each time someone clicks to view

**Comment by katyedwards** [comment]
Thanks @RobStallion so the HL database doesn't save any of that info?

**Comment by RobStallion** [comment]
@katyedwards No, it's just queries the EPJS database

**Comment by katyedwards** [comment]
Great thanks 👍
