### ISSUE TITLE
Deployment to staging2 issue

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#1164]
@katyedwards and I spoke with Matt from SLaM last week and he provided us with a new IP_address for the staging server. This server is called `Hlockerstaging2` and is actually a different server to the one that we had been deploying to in the past. See [here](https://github.com/healthlocker/healthlocker/issues/1159#issuecomment-367616337) for more info

I have been able to start and stop the application running on `Hlockerstaging2` using the commands 
```
mix edeliver stop production
mix edeliver start production
```

But I am having an issue when trying to deploy to the server. When I run the command
```
mix edeliver build release
```
it logs the following error
```
-----> Pushing new commits with git to: root@'ip_address'
ssh: connect to host 'ip_address' port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FAILED 128:
git push --tags -f root@'ip_address' master
```

**Comment by RobStallion** [comment]
It appears as though the server does not have access to the git repository.

I have `ssh`ed into the server and run the command 
```
git remote add origin https://github.com/healthlocker/healthlocker.git
```
but I still get the same error when running `mix edeliver build release`. 

I do not think that the `.git/config` file on the server is what is causing the issue here as I think that edeliver will build a new version of this a put it on the server every deployment. 

Next step 

I am going to look at my local `.git/config` file and see if there is anything that could be causing this issue

**Comment by RobStallion** [comment]
When the `mix edeliver build release` command is run it updates the `.git/config` file on my local machine with the following
```
[remote "root@'ip_address'"]
	url = root@'ip_address':/home/hladmin/healthlocker/builds   
	fetch = +refs/heads/*:refs/remotes/root@'ip_address'/*
```

It appears this is what it is using to try and access the HL repo but it is not working for some reason. It does not look any different to the settings for any of the other remotes so not sure why this is not working currently. Will continue to look into this

**Comment by RobStallion** [comment]
Have tried running `mix edeliver build release --verbose` to see if I could get any more info but it is still the same error

**Comment by RobStallion** [comment]
@nelsonic did you have any issues similar to this when initially setting up any of the azure servers?

I have looked through #841 and the [production-deployment readme](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md) and didn't see anything like this but just wanted to check.

**Comment by nelsonic** [comment]
@RobStallion I do not _recall_ having Git issues when setting up the previous/existing Azure servers.
are you _able_ to `git pull` when you `ssh` into the server?

**Comment by RobStallion** [comment]
@nelsonic Neither do I (when I was testing deploying umbrella apps to azure). 

I was able to `pull` once I ran the command from [this earlier comment](https://github.com/healthlocker/healthlocker/issues/1164#issuecomment-369204631) but it didn't help with the edeliver commands

**Comment by RobStallion** [comment]
Have tried to deploy a test application (can be found [here](https://github.com/RobStallion/azure_deployment_test)) to the server to see if that would be possible but I am getting the same error. 

This leads me to believe that the issue may actually be with the server setup, the firewall or the load balancer. @katyedwards Could you please ask Matt at SLaM if this could be the issue?

**Comment by nelsonic** [comment]
Ok, this _could_ be a "firewall" issue. but really 
we should be trying to run the `edeliver` command/script on Travis-CI 
and then auto-deploying it to `staging` which just uses SSH.

**Comment by reddog** [comment]
@RobStallion It seems like at least one aspect of this issue is/was to do with incorrect IP address details/or those being changed?

There were at least two points previously where the staging server changed IP address.

Would it be *safer* to use FQDNs instead?  Referring to the server as `staging.healthlocker.uk` (or the equivalent for the production site) should mean that *if there are* any IP address changes, they'll be as transparent as possible.

In terms of specifying the build/deployment machine, there are a number of references by (old, incorrect) IP address:

https://github.com/healthlocker/healthlocker/blob/master/.deliver/config#L3-L13
https://github.com/healthlocker/healthlocker/blob/master/.travis.yml#L31

Interestingly, `travis.yml` refers to the build machine by both IP address (old, incorrect), and FQDN, see https://github.com/healthlocker/healthlocker/blob/master/.travis.yml#L31

**Comment by katyedwards** [comment]
@RobStallion I can certainly ask the question, but replies recently haven't been very prompt so if @reddog's suggestion above is any help it would be worth trying while we're waiting.

**Comment by ghost** [comment]
'Solved' via jump box access and longer term plans to provision a new server
