### ISSUE TITLE
Public IP for Matt

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1176]

**Comment by RobStallion** [comment]
Cannot connect to this one at all (staging)
![image](https://user-images.githubusercontent.com/15571853/38298508-6ffe32ee-37ef-11e8-8ce7-ca05be0e01c8.png)

Can connect to this one 50% of the time (production)
![image](https://user-images.githubusercontent.com/15571853/38298597-bb7f4f82-37ef-11e8-8fb1-0052397c27b8.png)

**Comment by katyedwards** [comment]
@RobStallion am going to close this one as we have a number of others relating to deployment/ server access issues!
