### ISSUE TITLE
Pink page titles Part 2

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1178]
### Extension of #1024 because I missed some :o(

- [x] 'Wellbeing Tips' and 'Stories' headings on homepage -  https://staging.healthlocker.uk/
- [x] @RobStallion can you also change the text to "Wellbeing **t**ips" so the capitalisation is consistent with the other pages, thanks!

- [x] 'Tips' on tip category pages (if not already done)
- https://staging.healthlocker.uk/tips?tag=Connect
- https://staging.healthlocker.uk/tips?tag=BeActive
- https://staging.healthlocker.uk/tips?tag=KeepLearning
- https://staging.healthlocker.uk/tips?tag=TakeNotice
- https://staging.healthlocker.uk/tips?tag=GiveToOthers

- [x] 'Sign up' on:
- https://staging.healthlocker.uk/users/new
- https://staging.healthlocker.uk/users/101/signup2
- https://staging.healthlocker.uk/users/101/signup3

- [x] Log in on https://staging.healthlocker.uk/login
- [x] 'Password reset' on https://staging.healthlocker.uk/password/new
- [x] 'Goals and tracking' on https://staging.healthlocker.uk/toolkit

- [x] 'Account' on https://staging.healthlocker.uk/account/slam
- [x] @RobStallion can you also change the text to "Connect" so it is consistent with the other connect to health record page, thanks!
- [x] 'Connect' on https://staging.healthlocker.uk/slam/new

**Comment by RobStallion** [comment]
@katyedwards I am sure I am being a little dense but could you please clarify what you wanted to be updated when you said...

> @RobStallion can you also change the text to "Connect" so it is consistent with the other connect to health record page, thanks!

Thanks 👍

**Comment by RobStallion** [comment]
@katyedwards Oh do you mean change the title from **Account** to **Connect**?

**Comment by katyedwards** [comment]
Yep So on 
https://staging.healthlocker.uk/account/slam
The heading is Account

On https://staging.healthlocker.uk/slam/new
The heading is Connect

I think connect makes most sense for both and as it stands now, you'll only be using one or the other
