### ISSUE TITLE
Deployment Issues - Check Port Configuration

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1179]
From Matt:
Question on git repos, doesn't port 9418 need to be open? What port has been configured for TCP_IN?

**Comment by nelsonic** [comment]
@katyedwards in our experience, TCP Port 9418 (typically for Git access) has not been required 
for deployment as Travis CI is configured to deploy the app via Edeliver:
https://github.com/healthlocker/healthlocker/blob/a57d2741ae703b45ac8eb8465305a6e327baa152/.travis.yml#L33
If the Edeliver is disabled and people are _manually_ deploying to the server via `git push`
and then building the app _manually_ on the server, then TCP Port 9418 _may_ be required.

Could you please _confirm_ with Matt how the app is being deployed to the server?
Thanks.

**Comment by katyedwards** [comment]
No news yet - will give him a call shortly if I haven't heard anything.

**Comment by katyedwards** [comment]
Linked to #1164

**Comment by ghost** [comment]
'resolved' via jump box access and long term plan to provision new server
