### ISSUE TITLE
Account: Profile: update my details 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#119]
As a user I can view and / update my details within my profile, to keep my profile up to date.

## Acceptance Criteria 

+ [x] As a user the details I entered during or since sign-up are displayed (definitely email, if Non-SLaM, may also show a name and phone number, if a SLaM connected user then first and last name, NHS number, DOB, email and maybe phone number and address) 
+ [x] I can add / update my name (not if a SLaM service user)
+ [x] I can add / update my phone number, address and email address. Links to #57
**Not sure about what the knock on effect that is with user’s HL account - do we validate somehow with a link?** @katbow @nelsonic 

<img width="735" alt="screen shot 2017-02-21 at 19 03 31" src="https://cloud.githubusercontent.com/assets/25012688/23180551/b21f804a-f869-11e6-8026-43735b771d7b.png">

Linked to: https://github.com/healthlocker/healthlocker/issues/28

**Comment by MollieCourtenay** [comment]
@katbow 

 _name_ and _phone number_ edit and update fine.

_Email_  I edit and update and get **'Internal server error'**

Did you discuss the question above at all? What is the impact of updating an email address which has been used to create the user account?

**Comment by katbow** [comment]
Can you raise an issue and mark that as a bug? I posted this on #134 but posting here as a guideline:

> if there is something that is a **bug**, then the story should *not* be closed, and a new issue can be raised and linked with the bug label. When reporting a bug, you should include as much detail about:
> * What was done to produce the bug. This should be detailed enough that it can be replicated by the developer.
> * Browser info
> * Description of the bug (e.g. internal server error, something doesn't update as expected, etc).

**Comment by MollieCourtenay** [comment]
@katbow  / @nelsonic 
Posting this question again... 
What is the effect of allowing a user to update their email address? As this is that they used to create their account. Would we need to do some verification?

**Comment by nelsonic** [comment]
@MollieCourtenay yes, we would need to send them an email with a link to _verify_ their new email address (_when they update it_) else we could lose contact with the user.

**Comment by MollieCourtenay** [comment]
Still need to work on email address: 
Either making it uneditable or adding a validation flow. - both as issues in backlog.
