### ISSUE TITLE
Account: Consent: anonymous data

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#121]
As a user, I can view and update my anonymous data choice, so that I can stay in control of whether researchers and HL team can access my anonymous usage data.

## Acceptance Criteria 

CONSENT
+ [x] As a user my current choice on whether I agree to share anonymous data is displayed in a tick box.
 + [x] As a user I an tick or untick and ‘update’ my decision.

Linked to account epic #28

**Comment by katbow** [comment]
@MollieCourtenay when the page renders again it reflects how things are saved in the database in that moment. 

However, there appears to be a bug with this. Please post as a bug and I'll fix it up!

**Comment by katbow** [comment]
@MollieCourtenay I am having trouble reproducing this. It's been working fine for me. Can you try again and let me know if you are still running into this issue? If you are, please write it up in another issue with full details of what you did to lead up to this and what happens after.

**Comment by MollieCourtenay** [comment]
It seems to be working fine now

**Comment by MollieCourtenay** [comment]
In which case I can accept? Or could you see something buggy?

**Comment by katbow** [comment]
I couldn't find anything & had someone else sign up & try and there were no issues with them either, so you can close if you are happy with it!
