### ISSUE TITLE
Access EPJS data (snapshot) in HealthLocker

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#122]
As a SLaM Service User 
I would like to view my NHS data in HealthLocker 
so that I can keep track of my health/wellbeing goals.

A snapshot of the data was extracted by EPJS team, zipped (_and encrypted_) and shared via DropBox:
![image](https://cloud.githubusercontent.com/assets/194400/23199746/44afb2be-f8c8-11e6-8de2-24e7fc475492.png)

In order to make this user-story possible,
We need to create an "ETL Pipeline" to import the data into HealthLocker database. 
We can _either_ split this data into a _separate_ database or keep it in the main one.
For _simplicity_ I'm happy to keep the data in the same DB for now.
But once we deploy to SLaM's Azure infrastructure we can _easily_ split out the main application data from the EPJS data. 

@MollieCourtenay please confirm this requirement and prioritise for inclusion in sprint 4 as discussed. thanks!

**Comment by tonydaly** [comment]
The `DB_DUMP.zip` contains a `.bak` file, which is a database backups for MS SQL Server...

**Comment by tonydaly** [comment]
Ok, so I used these guides: 
- https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-get-started-tutorial
- https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-migrate-restore-database

You can then get a local docker container running MSSQL using this [`Dockerfile`](https://gist.github.com/tonydaly/e6d4330e12879a1b692c6bde426d67c6). This will copy the backup into the container. Then:
  - `docker build -t healthlocker-mssql .`
  - `docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 -d healthlocker-mssql` 

You should now have an MSSQL server running on port 1433, you can connect to it using [`sql-cli`](https://www.npmjs.com/package/sql-cli) with the following:
`mssql -s localhost -u SA -p '<YourStrong!Passw0rd>'`

You _should_ then be able to import to backup using: 
`RESTORE DATABASE CareNotesTRNG FROM DISK = '/var/opt/mssql/backup/CareNotesTRNG2016_20161021.BAK' WITH MOVE 'CareNotesTRNG2016' TO '/var/opt/mssql/data/CareNotesTRNG2016.mdf', MOVE 'CareNotesTRNG2016PMI' TO '/var/opt/mssql/data/CareNotesTRNG2016PMI.ndf', MOVE 'CareNotesTRNG2016Activity' TO '/var/opt/mssql/data/CareNotesTRNG2016Activity.ndf', MOVE 'CareNotesTRNG2016Reference' TO '/var/opt/mssql/data/CareNotesTRNG2016Reference.ndf', MOVE 'CareNotesTRNG2016AUDIT' TO '/var/opt/mssql/data/CareNotesTRNG2016AUDIT.ndf', MOVE 'CareNotesTRNG2016Clinical' TO '/var/opt/mssql/data/CareNotesTRNG2016Clinical.ndf', MOVE 'CareNotesTRNG2016MHA' TO '/var/opt/mssql/data/CareNotesTRNG2016MHA.ndf', MOVE 'CareNotesTRNG2016_log' TO '/var/opt/mssql/data/CareNotesTRNG2016_log.ldf';`

NOTE: all on one line...

However, afterward it said "an error occurred". But if you try:

`USE CareNotesTRNG`
`SELECT * FROM information_schema.tables`

A bunch of relevant looking tables show up...but not the main ones we need 🤔

**Comment by nelsonic** [comment]
@tonydaly that's a _great_ start! thanks for updating! 🍦 🚀

**Comment by nelsonic** [comment]
@MollieCourtenay we have _extracted_ the data from the `DB_DUMP.zip` shared via DropBox
![carenotes-unzipped](https://cloud.githubusercontent.com/assets/194400/23403491/45f74ff8-fda8-11e6-8af5-a95b0f9936e6.png)

The data "dump" is in a `.BAK` file which we are going to have to do some work to "_convert_" into a useable format so we can import it. 

Would it be possible to ask the team @EPJS to extract the data in a different format?
Specifically: can we ask them to export it as `.CSV`?

**Note**: The "_added benefit_" of doing this is that the data will be more recent.
(_the current snapshot we've been given is from **21 October 2016**_)
For User-testing purposes it's a _good idea_ to have recent (_i.e. relevant_) data to show people,
so they engage with the app better.

**Comment by nelsonic** [comment]
My original estimate of **T1d** (_one day_) was based on the expectation that it would be _possible_ to import the "Data Dump"  in the "_proprietary_" `.BAK` (_Microsoft SQL Server Backup_) format ... i.e non-standard.
I was _initially hopeful_ that I would be able to run a Windows "Virtual Machine" (VM), install Microsoft Server and import the backup, which _appeared_ to be _possible_ according to:
http://dba.stackexchange.com/questions/20078/can-i-restore-a-sql-server-bak-files-without-sql-server
Sadly Microsoft have changed SQL Server since 2012 when the stackexchange answer was posted.

3.5 days of hitting my head against walls installing VMs, Attempting to run SQL Server on two separate windows PCs and being greeted with:
![00-download-sql](https://cloud.githubusercontent.com/assets/827662/23606151/66df9da4-0214-11e7-8222-cec3efe4d8dd.PNG)
![00-express-edition-also-doesnt-install](https://cloud.githubusercontent.com/assets/827662/23606149/66ded52c-0214-11e7-849d-fea7334f95cb.PNG)
![00-sql-wont-work-on-this-machine](https://cloud.githubusercontent.com/assets/827662/23606150/66df4764-0214-11e7-94c5-a23397d42bf9.PNG)

I've decided to take a different approach: Load the Data to "Real" Windows Server!
So... today I'm going to use Windows Azure ("Cloud") to import the data.
I expect to spend the next 4 hours of my life on this, and will document my findings. 👍

**Comment by katyedwards** [comment]
@nelsonic I'll be honest, I don't understand most of this!  But did you see the follow up email from the ePJS team last week:
"It occurs to me that rather than the full CareNotes SQL database of 5000+ tables, your interest would be in only handful of these.  If my assumption is correct and you can identify to me the table/s (if not, then the ePJS form).  I will be able to assist with the export of the identified table/s to a .csv format."

Would this help you in anyway with this?

**Comment by nelsonic** [comment]
@katyedwards I saw the email reply and felt it was a little "_computer says no_"... 😞 
The _first_ result on Google explains how to do what I requested:
http://stackoverflow.com/questions/3169220/export-query-result-to-csv-file-in-sql-server-2008

From _our_ side it's a bit "Chicken and Egg":
+ We cannot _view_ the "Schema" (_data/tables_) without importing the backup. 
+ And we _cannot_ determine the list of the _tables_ we need for HL without knowing the "Schema" of the ePJS database ...

> It's like the waiter at a restaurant saying: "order your food" (_without providing the menu_)
> _How_ are we meant to know what we _can_ order...?

I took a look at the list of queries in DropBox:
![image](https://cloud.githubusercontent.com/assets/194400/23607138/9ba22e52-025b-11e7-9052-d8a25c7e0afc.png)

Example:
![image](https://cloud.githubusercontent.com/assets/194400/23607166/b7b17472-025b-11e7-8e7e-0efc64ca20e4.png)

We can _infer_ what the tables from the queries, but I don't have the "complete picture".

> It's like being in the restaurant, seeing what someone `else` has ordered and and saying to the waiter: "That looks good, I'll have what she's having..."
I still have no way of knowing what `else` is _available_ that I _can_ order.

It would be _way_ easier for the _creator_ of the queries (_who has much better knowledge of the Database/Schema_) to provide the _exact_ data we require.

I have _replied_ to the email with  **_possible_ next course of action**:

![email-to-garry-part1](https://cloud.githubusercontent.com/assets/194400/23608917/79170f26-0263-11e7-9403-a1022b13cda7.png)

![email-to-garry-part2](https://cloud.githubusercontent.com/assets/194400/23608940/99e82776-0263-11e7-9ef2-17eafbc7ae1c.png)

**Comment by katyedwards** [comment]
Thanks @nelsonic Not something I can help with either (knowledge wise), but if you need me to do a bit of legwork with them let me know

**Comment by katyedwards** [comment]
From Garry:

Hi Nelson,
 
For the medium to long-term, I would see it as important that Option C) is pursued successfully. 
 
Option A) - Towards the end of the week I will produce the .csv dump files from our CarenotesTRNG2016 database for the following:
 
PATIENT REGISTRATION (tblPatient)
(tblCNDocument)
(tblCNDocumentHierarchy)
ADDRESS (tblAddress)
GP (tblGPDetail)
RECOVERY AND SUPPORT PLAN (tblSLAMRecoveryFocussedCarePlan & 16 dependent tables)
 
Before producing this I will need to build up patient records examples so that the .csv’s hold data useful to mhl2.0 development.
 
Thanks,

Garry
 
Garry Moriarty
Clinical Systems Manager

**Comment by pm5k** [comment]
### Is this the droid you're looking for?

![epjs_01](https://cloud.githubusercontent.com/assets/9250112/23666561/45207bd0-0353-11e7-952d-40f4cee79f85.PNG)

**Comment by nelsonic** [comment]
@pm5k this is _useful_ are you running this SQL viewer on your Mac or on a PC?
Please let me know when you'll be at the MWV office and if I can sit with you to understand the data. thanks! 👍

**Comment by pm5k** [comment]
I wont be there until.. maybe next week? I basically downloaded MSSQL 2014 server on my gaming rig (win8.1), installed, then did the following:

- Ran SSMS
- Right-clicked databases tree node and selected restore
- Navigated to the bak file
- It restored it as "CareNotesTRNG2016"
- Then went and right clicked that node and chose "properties"
- In the left-hand pane chose "Files" and changed owner to my windows user.
- Applied the operation and voila.

You don't need anything special, just get a copy of MSSQL2014 and thats it.
I can perhaps investigate if i can just do CSV exports, but I think that might be slightly useless since it offers no insight into relationships.

Tell you what, have a try to replicate my results and if it definitely does not work, I will find some time to see if I can chuck it on a VM and bring it in? But I will need to test first.

**Comment by nelsonic** [comment]
@pm5k that's _really_ helpful, thanks! 🥇 
Can you do me a _huge_ favour and put the `.exe` for `MSSQL 2014 server` you used on the HL2.0 Drop Box so I can grab it and try and use it on our Windows box to replicate your steps. 🤞 
Thank you! 👍

**Comment by nelsonic** [comment]
Catch up with Garry went _really_ well. 

On the data front we agreed that the _simplest_ short-to-medium term solution was to create a table within EPJS' SQL Database with the healthlocker-specific data which we can then query to display the data within HL. The main advantage being that we don't _store_ any of the data within HL so there's no data protection/retention to think about. 
(_so I'm updating the title of this issue/story to reflect that simplification_)

We were able to _simulate_ the HL icon within EPJS and even show an "***unread count***" 
(_which isn’t currently in our backlog but **Jane** mentioned it would “**reduce anxiety**” for clinicians because they wouldn’t have to “keep checking” HL multiple times a day to see if there is new messages/content from people…_)
Garry is going to write a 3 SQL queries which will result in read-only data for us.
I’m speaking Stuart tomorrow for how to get _access_ to this data directly in EPJS MS SQL, so we can avoid waiting for the API (_which isn't ready and won't have all the data we need in any case!_)

So overall v. positive. visiting Garry & Jane @ Bethlem Royal Hospital was a _great_ time investment. 👍

**Comment by katyedwards** [comment]
Hi @nelsonic Can you update following your meeting with Stuart yesterday...  hopefully it's all on its way now!

**Comment by nelsonic** [comment]
@katyedwards the meeting with Stuart & Jason was to get the application deployed to SLaM's Microsoft Azure Infrastructure. It went well; we managed to deploy the app. see: https://github.com/healthlocker/healthlocker/issues/340

Stuart will get our Azure application access to the data that Garry is going make available in EPJS but the _current_ bottleneck is Garry's work.

**Comment by iteles** [comment]
@katyedwards Garry has estimated that his piece will take around 2 week so we're not counting on it until the next sprint.

**Comment by katyedwards** [comment]
Thanks @nelsonic @iteles Assuming Garry manages to get it done in 2 weeks, would you expect that will that give you enough time to then do what you need to so it's all connected and working ready for the soft launch date after Easter?

**Comment by nelsonic** [comment]
![basic overview of tech](https://cloud.githubusercontent.com/assets/194400/24954957/630d0ae0-1f79-11e7-8d69-9f7cc22092ae.png)

**Comment by nelsonic** [comment]
ePJS data has been available in Healthlocker for a `while` now. 
The ePJS-related (_micro_) "Service" is now in: https://github.com/healthlocker/epjs_app
Closing issue as we consider it to be complete per the original story description. 👍
