### ISSUE TITLE
Clean up tests with exunit tags

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#124]
There is a lot of repetition in the tests, such as in the the `coping_strategy_controller_test`, or any other tests that require a current_user.

Can use [tags](https://hexdocs.pm/ex_unit/ExUnit.Case.html#module-tags) to avoid repetition.

See also: http://blog.simonstrom.xyz/elixir-testing-tag-tests-in-exunit/

**Comment by tonydaly** [comment]
Maybe I haven't totally understood the use of `tags`. But I think we can solve the repitition in those tests by using [`describe`](https://hexdocs.pm/ex_unit/ExUnit.Case.html#describe/2) and setup blocks. e.g.

```elixir
describe("#index") do
  describe("when logged in") do
    setup [:log_user_in]

    test "blah" do
      ...
    end
  end

  describe("when logged out") do
    ...
  end
end
```

**Comment by katbow** [comment]
I ended up using [describe in the end](http://blog.simonstrom.xyz/grouping-tests-with-exunit-elixir/) 😄
