### ISSUE TITLE
Account - Update security details

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#127]
As I user I want to be able to update my security details so that I keep my account secure.

## Wireframe
 
![image](https://cloud.githubusercontent.com/assets/1287388/23256407/354ddfea-f9b7-11e6-92de-ab7adb1e1aaf.png)

## Acceptance Criteria 

SECURITY

+ [x] as a user if I click on update my password, I am taken to a new page, asked to enter my current password and a new one, and my new one a second time.
+ [x] When I have updated my password, I am assured it’s been updated, then am asked to log in with my new password.

+ [x] as a user if I click on update my security question, I am taken to a new page, asked to enter the answer to my current question. Then pick a new question, and enter a new answer. Then click update.
+ [x] When I have updated my password, I am assured it’s been updated.

+ [x] Replace 'Please confirm your password and enter a new one' with  'Update password'

+ [x] Replace 'Confirm password' with 'Confirm new password'

+ [x] 'Current security question' (remove : ) and make bold.

+ [x] Replace 'Please confirm your security details and enter new ones.'  With 'Update security question'

Linked to #28 epic

**Comment by katbow** [comment]
@LauraNevo @MollieCourtenay for the password update section, should this be using a confirm password field instead of having the display button? So instead of 2 fields, should there be 3 fields for current password, new password, and repeat new password?

@MollieCourtenay can you confirm the priority when you have a chance? 😃

**Comment by MollieCourtenay** [comment]
@katbow Yes there should be 3 fields for current password, new password, and repeat new password.

agree with priority 3.

**Comment by katbow** [comment]
>  When I have updated my password, I am assured it’s been updated, then am asked to log in with my new password.

@MollieCourtenay @LauraNevo does this mean the user should be automatically logged out after a successful update and redirected to the log in page?

**Comment by MollieCourtenay** [comment]
@katbow @LauraNevo 
yes, that was my original thinking - reinforcing their new password but reading it back - does it seem like a bit of a fuss?

**Comment by katbow** [comment]
@MollieCourtenay I think it's not 100% necessary at this point. If you do want to hold off on it, we can make another issue for it so it's still recorded to implement at a later time.

**Comment by MollieCourtenay** [comment]
@katbow I was able to update my password to what it already was.

Is that the convention? Or should we force the new one to be different?

**Comment by katbow** [comment]
@MollieCourtenay it's not the convention, but I wouldn't say it's necessarily a blocker for beta release. 

I think at some point it *is* necessary to force users to use a different password, but it is up to you when you want this done. If you want it done before beta release let me know 👍

**Comment by MollieCourtenay** [comment]
@katbow

 I'll create a new issue for forcing users to create a different password.

I cant see that those two text changes have been made, so I've unticked the acceptance criteria.

**Comment by katbow** [comment]
@MollieCourtenay I made these changes now. Please check it out 😎

**Comment by MollieCourtenay** [comment]
https://www.healthlocker.uk/account/security/edit 
Im getting internal server error @katbow

**Comment by MollieCourtenay** [comment]
@katbow 

+ [ ] can you please make the 'Update security question' match the size and central alignment as per update password page.

<img width="757" alt="screen shot 2017-03-28 at 13 50 51" src="https://cloud.githubusercontent.com/assets/25012688/24405668/93f8a79e-13bd-11e7-8fc4-8713a04a0ce3.png">
