### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#13]
We're going be deploying the application to Heroku, so there's some setup work required.

- [x] Setup Heroku account
- [x] [Make application Heroku ready](http://www.phoenixframework.org/docs/heroku)
- [x] Deploy
- [x] Setup Heroku Pipelines and Review Apps

**Comment by nelsonic** [comment]
Confirmed technical tasks. 
Initial deployment during "Alpha User Testing" phase will be to Heroku for simplicity.
We will liaise with the SLAM team on deployment to Azure after sprint 3 
so that we can streamline the **_Continuous_ Deployment** pipeline
which will be managed by Steve's team when project is "BAU". 👍

**Comment by tonydaly** [comment]
Who's able to setup the account and add a credit card?

**Comment by nelsonic** [comment]
@tonydaly good question. let's ask @iteles to set this up on the DWYL Company account today.
We can _grant access_ to any MWV people who want to deploy the app. 👍

**Comment by tonydaly** [comment]
@iteles any update on the account. I'm planning on starting to hook this up this weekend?

**Comment by iteles** [comment]
@tonydaly I've set up:
+ A test healthlocker gmail that any of us can log into
+ Two heroku apps:
  + http://healthlocker.herokuapp.com/
  + http://healthlocker-staging.herokuapp.com/ (we won't need this one for the first 3 sprints I suspect)

The details for logging into both gmail and heroku accounts are in our shared Google Drive.

@tonydaly @katbow I wasn't sure which email addresses you use to corral your heroku apps, so I haven't added you guys as collabs yet - please either add yourselves or let me know and I'll add you :blush:

**Comment by tonydaly** [comment]
@katbow @nelsonic what are you heroku emails? I'll add em.

**Comment by tonydaly** [comment]
@iteles could we add a credit card to the account?
