### ISSUE TITLE
Connect to SLaM - profile page

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#134]
Users need to be able to check that that are a SLaM SU and have access to a link which takes them to a form to fill out SLaM account info.

TODO:
- [x] Add field to check or uncheck if it's a SLaM SU
- [x] Update schema to reflect if a user is a SLaM user
- [x] Update slam_user in db when user checks box
- [x] Reveal link to connect with SLaM if box is checked
- [x] Send information to account profile depending on if the user is connected to slam or not.
+ [x] South London and Maudsley (please capitalise SL M)

#118

**Comment by MollieCourtenay** [comment]
@katbow is it a java script reason that the link to Connect link can only be revealed if the user has clicked to update?

**Comment by katbow** [comment]
No, in this case it was because the data base is updated and the page renders again. The link displays based on whether it's *true* or *false* that the user identifies as a SLaM SU. 

The JS in the other case was because it would've been a click event in the browser (rather than any changes to the data structure).

**Comment by MollieCourtenay** [comment]
Ok thanks.
I think once we have the styling in and the Update button becomes active if an update is made like the tick box, then the UX will be improved, and it should be clearer that the user should click Update.

How should I note styling things like this in Github?

**Comment by katbow** [comment]
You can make a new issue for it and link to this one. If you are happy that the original criteria was met, you can still close this and add something like that in as a separate issue with an **enhancement** label. 

If there is something that is a **bug**, then the story should *not* be closed, and a new issue can be raised and linked with the bug label. When reporting a bug, you should include as much detail about:
* What was done to produce the bug. This should be detailed enough that it can be replicated by the developer.
* Browser info
* Description of the bug (e.g. internal server error, something doesn't update as expected, etc).

For example, the extra bit added in to the description here applies to another story (#136) that hasn't been merged in yet, so it may be better for review in that story when it is marked as please-test as well.

**Comment by MollieCourtenay** [comment]
i'll close once letters are capitalised - sorry didn't notice Wednesday!
