### ISSUE TITLE
Connect to SLaM form

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#135]
SLaM users need a place to input their information so they can connect with SLaM.

- [x] Create form template to display labels & fields
- [x] Make action to render form
- [x] Make action to be done after clicking connect

**Comment by MollieCourtenay** [comment]
@katbow for the reveal where to find NHS number info, may be best to copy over mechanism from profile page, why and how to connect to care team info #136

**Comment by katbow** [comment]
Status for this... The form & connecting is 'complete' but with assumptions about ePJS. Waiting to merge into master until call/meeting with Moriarty on Mon/Tues.

Current action updates users table with a slam id when data matches, which is used to display data/forms differently based on if the user is connected.
