### ISSUE TITLE
Connect to SLaM - display how & why the user can do this

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#136]
SLaM service users may wish to know how and why they should connect with SLaM

- [x] Need to display information about how to connect, benefits of connecting, and reassurance about sharing info.
- [x] Need to know how this is displayed - modals may not be the right answer as there are various extensions, etc which can prevent them from displaying @MollieCourtenay @LauraNevo 
- [x] Action to render

**Comment by MollieCourtenay** [comment]
@katbow in which case - could the (?) push content below down and reveal the info underneath like this:

![image uploaded from ios](https://cloud.githubusercontent.com/assets/25012688/23368716/a25730c6-fd06-11e6-89d4-9702d3207025.jpg)

WORDING FOR THIS SECTION:
[  ]  I am a South London and Maudsley service user *

Connect with my SLaM care team and health record (?) 

(?) To connect you will need to enter your NHS number, First name, Last name and Date of Birth, these details will be matched against your SLaM record - they must match perfectly.
Once your account has been connected you will be able to see the contact details of the SLaM staff you see, view your current care plan, interact with your goals and coping strategies from your care plan, receive recommendations and resources from your care team and more. What you share with your care team, is up to you.

**Comment by katbow** [comment]
@MollieCourtenay @LauraNevo are you in tomorrow? It would be good to have a conversation about if we can 😃

**Comment by katbow** [comment]
@MollieCourtenay since we didn't get a chance to catch up today I'll discuss here.

Revealing the info when the (?) is clicked requires front end JavaScript, which can be a [problem](https://answers.microsoft.com/en-us/ie/forum/ie8-windows_xp/unable-to-enable-javascript-in-ie8/0aba6b02-5783-49ca-a27b-6636e43ed1dc) when working with older browsers such as [IE8](http://stackoverflow.com/questions/1794189/ie8-javascript-not-running-or-loading) (and up to IE10). 

I talked with @LauraNevo about other options including:
* taking the user to a separate page to view the text if they click
* displaying the information directly on the same page. It's possible to display it only if the user has checked & updated that they are a SLaM SU, without using JavaScript. 

Let me know what is the best course of action and I can get started on this and #137

**Comment by MollieCourtenay** [comment]
Thanks. So it sounds like new page is the safest option. 

Will the user only see the help info, and be given a close button to go back to the form / page?

**Comment by katbow** [comment]
I can make it display just the help info then add a Back/Close button to go back to the profile 👍  (or form in the case of NHS number).
