### ISSUE TITLE
Connect to SLaM - Display information about how to find NHS number

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#137]
Information on finding NHS number can be displayed to the user so that they can have it in order to connect their account.

- [x] Need to display info on finding NHS number
- [x] like the info on connecting with care team, need to know best way to display
- [x] Action to render

**Comment by MollieCourtenay** [comment]
@katbow for the reveal where to find NHS number info, may be best to copy over mechanism from profile page, why and how to connect to care team info #136

**Comment by katbow** [comment]
@MollieCourtenay is there a text copy for this?

**Comment by MollieCourtenay** [comment]
## Content
Your NHS number will be on any letter, prescription, test result, appointment letter or medical card from the NHS. NHS numbers are made up of 10 digits shown in a 3-3-4 format. If you can’t find any documents, ask your GP practice for help, they will be able to provide it as long as you are registered there.

**Comment by katbow** [comment]
Okay thanks, sorry internet is a bit slow here so I didn't see that yet when I posted my comment.
