### ISSUE TITLE
Connect to SLaM: Check information input by user with NHS record

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#138]
The information input by users will need to be checked against ePJS record to ensure it matches before the accounts can be connected.

- [x] Create schema for slam_users
- [x] Add slam_id to users table when data matches
- [x] Redirect user to profile with new info if profile is correct
- [x] If information is incorrect, display error message to the user.

**Comment by katbow** [comment]
This currently is checking information from a table within Healthlocker. However, there may be changes to the data/it may be accessed from another database. Waiting to merge until call/meeting with Moriarty.

Some possible implications of changes: 
* need to change how to display data (may not be able to edit directly/may need some displayed from healthlocker users table/may need to add more fields to users.
* need to change how data is checked - check from another table or database.

**Comment by MollieCourtenay** [comment]
@katbow 
Is there any more test data to try this with?
I'm familiar with Evan and Lisa. Does Robert have someone else in his caseload i can try to connect as?

**Comment by katbow** [comment]
yup there's one more.
**Sign in details:** angela@email.com, password
**NHS details:**
First name:  Angela
Last name: Hernandez
Date of birth: 24/05/1988
NHS number: 8132051535

**Comment by MollieCourtenay** [comment]
@katbow 
First time I tried I got this:
<img width="752" alt="screen shot 2017-05-26 at 16 27 13" src="https://cloud.githubusercontent.com/assets/25012688/26501056/4355d400-4230-11e7-8d38-bd3a7b8e33b6.png">

I tried again and got this:
<img width="525" alt="screen shot 2017-05-26 at 16 27 06" src="https://cloud.githubusercontent.com/assets/25012688/26501063/49a08864-4230-11e7-9774-83378df6a36a.png">

**Comment by katbow** [comment]
Right, thanks for letting me know! I believe this is because I had connected Angela at some point & disconnected her before I had the new disconnect set up (so the room for her is still there & not allowing the connection). 

I'll check the database & delete any rooms with Angela or her care team & see if that fixes it.

**Comment by MollieCourtenay** [comment]
Yeah assumed it could be something like that  - let me know how it goes :)

**Comment by katbow** [comment]
removed all of the rooms with Angela and tried it out myself. Worked now for me 🙂
