### ISSUE TITLE
Variable "timestamps" needs renaming to "timestamps()"

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#150]
The following warning message is issued when setting up the project:

<img width="868" alt="timestamp variable warning" src="https://cloud.githubusercontent.com/assets/16775804/23407431/ce82cf38-fdbb-11e6-8145-cadf619551fd.png">

It does not prevent the app from running but it would be good to amend the variable name to stop it from occurring.

**Comment by katbow** [comment]
Closing as I went through previously and fixed all these warnings
