### ISSUE TITLE
Menu rule breaking onto 2 lines on iPhone SE

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#152]
See the dashed line underneath 'Log in'. The screenshot is from iPhone SE on Simulator but screens up to and including iPhone 7 have the same issue. 

![menu top](https://cloud.githubusercontent.com/assets/16775804/23408324/89f4403c-fdbf-11e6-90ab-215ef64d2d9e.png)

**Comment by katbow** [comment]
@Cleop this should be fixed on healthlocker.uk after #154 is merged in. Please check and verify after it's merged 🙂

**Comment by Cleop** [comment]
Thanks @katbow! It's now contained on one line so I'm happy to close this 👍
