### ISSUE TITLE
Create Privacy Statement page/link on sign up

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#158]
**As a person** using HL,
**I want to** be able to read the full privacy statement
**so that** I have the information I need in order to decide whether I agree to it or not.

Issue #12 currently discusses alongside other things the format for signing up and agreeing to the privacy statement. 

However I think for clarity it's useful to have a specific issue reminding us to create the page containing the content for the privacy statement as regardless of the format of the checkbox this content will be required.

This is the current display without any link or details of what the terms are:
<img width="200" alt="screen shot 2017-02-28 at 16 31 04" src="https://cloud.githubusercontent.com/assets/16775804/23414297/57333d60-fdd3-11e6-8fc9-adeaab715439.png">

**Comment by katbow** [comment]
linked to #115

**Comment by katbow** [comment]
@Cleop can you check this out now? Links should be functional now 👍

**Comment by Cleop** [comment]
Thanks @katbow, all working well. Happy to close.
