### ISSUE TITLE
Accessibility: 'Read this story' font size too small?

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#159]
Maybe already being covered in #29...

**As a** long sighted person using HL,
**I want to** be able to read all text
**so that** I can use HL effectively.

The font size on 'Read this story' is very small. This screenshot comes from viewing on an iPhone 5C.

<kbd>
<img src="https://cloud.githubusercontent.com/assets/16775804/23416172/bbafe24c-fdd9-11e6-95de-49865f0214a9.PNG" width="250" />
</kbd>

**Comment by katbow** [comment]
@Cleop The fonts have been standardised now to be the same for read this story and the content. Can you take a look?

**Comment by Cleop** [comment]
Thanks @katbow, I've taken a look on my phone (5C) and it's much easier to read now 🎊
