### ISSUE TITLE
Extra margin needed on iPhone 5C

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#160]
This maybe be being covered already in issue #29 on general styling.

These screenshots come from an iPhone 5C. The markdown border around them from github adds a tiny bit of padding which you may be able to see when you look carefully but this isn't the case on the phone.

However you can definitely see that the edge of the security question option is cut off.
<kbd>
<img src="https://cloud.githubusercontent.com/assets/16775804/23416184/c89d67ea-fdd9-11e6-98a6-14026e0cec48.PNG" width="250" />
</kbd>

You can see that there could be some extra margin underneath 'Get support'. This screenshot is a view at the lowest possible point on the page.
<kbd>
<img src="https://cloud.githubusercontent.com/assets/16775804/23416175/bf9ec7f6-fdd9-11e6-90f3-ee1060e79761.PNG" width="250" />
</kbd>

**Comment by katbow** [comment]
@Cleop can you check out if this is fixed with the new styling?

**Comment by Cleop** [comment]
Get support now has sufficient margin ✅  
Styling on security question / password page has enough space ✅  
Both tested on iPhone 5C.
