### ISSUE TITLE
Suggested schema for epjs data

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#161]
#148 

This does not include all the information available in the data dump. Other information not included below are:
* Clinician name
* GP details (address, end_date, telephone, practice_name)
* patient gender
* mobile & landline @MollieCourtenay which of these should be used when connecting to SLaM?
* local authority
* C4C (done via IDs, data_asked (most recent matters only)
* care team (staff_name, role via ID)
* Support plan (completed_by_staff_id from staff table)
* CAG (no extra details - not sure what this is)

For sprint 4, the tables I would need in order to complete the stories are:

```
schema "slam_users" do
  has_one :user, Healthlocker.User
  field :first_name, :string
  field :last_name, :string
  field :email, :string
  field :nhs_number, :string
  field :phone_number, :string
  has_many :goals, Healthlocker.SUGoal
  has_many :coping_strategies, Healthlocker.SUCopingStrategy
  has_one :address, Healthlocker.Address
end

schema "addresses" do
  field :flat_number, :integer
  field :building_name, :string
  field :street_name, :string
  field :post_code, :string
  field :city, :string
  belongs_to :slam_user, Healthlocker.SlamUser
end

schema "goals" do
  belongs_to :slam_user, Healthlocker.SlamUser
  field :goal_detail, :string
  field :action_detail, :string
  field :supported_by, :string
end

schema "coping_strategies" do
  belongs_to :slam_user, Healthlocker.SlamUser
  field :content, :string
end
```

If I can have verification that these schemas will work alright, then I can make these up using some mock data until the imports are complete, then I can crack on with the other stories. The main thing I am not sure about is if the `slam_users` table should belong to `users` or the other way around... I think it would make more sense if the `users` table `belongs_to` the `slam_users` table, and each slam user has one user.

**Comment by tonydaly** [comment]
@katbow looks good. One thing I'm not sure of is having a separate table for `addresses`, each user can only have one address, so it feels like we're having to perform an extra join, but without any other benefits?

**Comment by katbow** [comment]
I guess that is another point I was unsure of. In the profile form #140 it display address with multiple fields for flat number, street name city etc. That was driving the suggestion to put it in a separate table so we could have fields for each section of the address (and for each input in the form via nested inputs). 

If that can be done without nested inputs, or with a single field to input all the address info, then I don't see the need for a separate addresses table.

**Comment by MollieCourtenay** [comment]
@katbow not sure what you mean by your question above sorry.

**Comment by katbow** [comment]
@MollieCourtenay ahh nevermind. I was thinking it was one of the fields to check against when connecting to SLaM account, but I double checked the wireframes and it's not.
