### ISSUE TITLE
Recognise capitalised tip/story hashtags

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#162]
At the moment the screenshot shows a tip where the #Connect tag has not been recognised because it's capitalised. The function should be amended to allow for capitalised tags.

<img src="https://cloud.githubusercontent.com/assets/16775804/23459395/08144a3a-fe78-11e6-8fef-e52853be28ff.png" width="250" />

**Comment by Cleop** [comment]
On further investigation it appears that despite capitalised tags not being listed under the 'See more X tips' link, they are appearing in the results for the tags that they have been given and therefore their capitalised tag is being noted. It is only the 'See more X tips' display that is failing to recognise them.

Therefore, providing issue #84 goes ahead and the 'See more X' line is replaced by the tags themselves being links, capitalised tags will be being noted in all the relevant places and this issue will no longer exist.

**Comment by katbow** [comment]
@Cleop By your last comment, do you mean that it is working fine for any capitalisation when looking at tips in general (i.e. #tip capitalisation does not matter), but for individual 'category' tags, that's when capitalisation currently matters (i.e. #connect is not the same as #Connect)?

Thanks!

**Comment by tonydaly** [comment]
I believe on twitter hashtags are case insensitive.

**Comment by katbow** [comment]
The problem was with how the tags were being set in the templates. It was only looking for lowercase. However, when getting the tags from the database, the search was case insensitive, so when you went to `tag=connect`, it would show all the tags containing connect, regardless of case (even though it may have been displayed as "no tag found").
