### ISSUE TITLE
Agree on consistent styling for tips / tip titles

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#163]
Need to agree on a consistent styling for the tips section.

- Should there be `<h1>` titles or just a bold `<p>` for a tip title?
- Should there be any text in italics?
- Where should there be new lines?
- Remove the 'See more X tips' link and replace with hashtags as links, as explained in issue #84

The tip titled 'Care for others' uses a bold `<p>` for its title:
<img width="200" alt="tips 3" src="https://cloud.githubusercontent.com/assets/16775804/23458600/c61027d8-fe74-11e6-8e27-354323a6c9b2.png">

## Other tip titles

Example with `<h1>` titles:
<img width="200" alt="tips 2" src="https://cloud.githubusercontent.com/assets/16775804/23458648/054af4a0-fe75-11e6-9b18-b547eff77bfc.png">

Example with italics but no bold or `<h1>` title:
<img width="200" alt="tips 3" src="https://cloud.githubusercontent.com/assets/16775804/23459813/fd977940-fe79-11e6-8948-7f8b6c64edf9.png">

This issue may be being addressed in #29 already...

**Comment by katbow** [comment]
Just a note: these are added in via markdown which is then converted to HTML. So these 3 need to be agreed upon for those entering the tips (and stories):

> Should there be `# Title` or `**Title**` for a tip title?
Should there be any text in italics?
Where should there be new lines?

@MollieCourtenay I wasn't sure if it was just you entering the tips & stories, or who else was involved. Can you look into this so we can remove those tips and stories which don't fit the decided convention, and anyone inputting new tips & stories can use the same convention going forward?

**Comment by MollieCourtenay** [comment]
I would like it to be:
First sentence in bold.
(new line) Second sentence regular.

e.g.

**This week, how about making time to catch up with someone you care about.**
Feeling close to, and valued by, other people contributes to functioning well in the world.

#Tip #Connect

**Comment by MollieCourtenay** [comment]
@katbow sorry cant locate where this was discussed.
Should hashtags have capitals or not?

#Tip / #Story

#Connect
#BeActive
#KeepLearning
#TakeNotice
#GiveToOthers

**Comment by katyedwards** [comment]
For good record keeping, we're going with Capitals as @MollieCourtenay has typed above.

**Comment by katyedwards** [comment]
@katbow @Cleop I have now added all the tips we had. Noticed the formatting isn't working still - the first sentences seem to have come out italicised not bold.

**Comment by katbow** [comment]
@katyedwards #216 covers why the bold wasn't showing up. Short story is there needed to be another font loaded in to show the bolded text (otherwise the font did not respond to bolding). I believe this has been picked up by @nogainbar and is waiting to be merged in.

However, is this with the `**text**` (**text**) still and not `*text*` (*text*)? The latter will be italics.

**Comment by katyedwards** [comment]
Oh Balls.  I had noted down *text* not the double.  @katbow Assuming there isn't an easy way for me to edit them, can you clear the database again and I'll re-add them all with the correct **text**

**Comment by katbow** [comment]
yeah not an easy way to edit right now unfortunately 🙁 . Sure, should I just clear the tips?

**Comment by katyedwards** [comment]
Hi @katbow Sorry wasn't working yesterday.  Yes - please clear the tips and I'll re-add today with the correct formatting.  Thanks!

**Comment by katbow** [comment]
@katyedwards done!

**Comment by katbow** [comment]
@Cleop can you verify these are consistent now & close please?

**Comment by Cleop** [comment]
@katbow all of the tips are now consistent and looking good 😄 Happy to close
