### ISSUE TITLE
View list of existing posts

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#17]
As a person using the app
I want to view a list of existing posts (_content_)
so that I can see what is new.

## Acceptance Criteria

+ [x] The list of posts will appear as "cards" which can be scrolled through.

Sample design (_low-fi sketch_)
![image](https://cloud.githubusercontent.com/assets/194400/22249838/8c1c8c6e-e23c-11e6-828a-c918f72e05e1.png)

**Comment by katbow** [comment]
For now I am going to focus on integrating one type of content (e.g. stories #8) instead of all of the events (#9) , tips (#7) , etc. which will be integrated at a later date. Need to know how to differentiate between the different types of posts when users are posting content.

**Comment by katbow** [comment]
Those last 2 commits are supposed to reference #7!
