### ISSUE TITLE
NHS Choices syndicated content

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#170]
Discuss how to make use of this in HL, who to register, etc.

http://www.nhs.uk/aboutNHSChoices/professionals/syndication/Pages/Webservices.aspx

**Comment by MollieCourtenay** [comment]
@katyedwards think this repeats the new issue you made last week - can you close one and keep another one going?

**Comment by katyedwards** [comment]
Will close this one as Nelson has acknowledged the other.
