### ISSUE TITLE
Forgotten password link

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#176]
**As a** HL user
**I want to** be able to get a password reminder 
**so that** I can access my account even if I have forgotten my password.

At the moment there is an error message but no option about how to solve this and gain access to your account.

Previously mentioned briefly in #12: 
> We know some people had trouble with the current online version of MyHealthlocker (not created by us) and clinicians sometimes have to help with people forgetting their password, reset, etc...

But this comment was amongst many others and no solution was proposed for the new HL.

### Acceptance Criteria
+ [x] Link expires after 24 hours

**Comment by MollieCourtenay** [comment]
<img width="816" alt="screen shot 2017-04-04 at 10 04 40" src="https://cloud.githubusercontent.com/assets/25012688/24649207/33962dac-191e-11e7-925c-260cc7eb8fa5.png">

**Comment by MollieCourtenay** [comment]
Above is one option:
Enter security q and answer correctly = prompt a reset PW link to email address, follow link , reset password, log in. 


Simpler option being: 
Enter security answer correctly = sent to reset password screen, reset password = logged in.

**Comment by iteles** [comment]
Discussed flow with @katyedwards and agreed the flow would be have no security question on the 2nd screen.

**Comment by katyedwards** [comment]
@MollieCourtenay Jump in if there is a particular reason for needing the security question to generate a reset password link to email but this seemed sensible for a first iteration.

**Comment by MollieCourtenay** [comment]
@katyedwards @iteles  what was the agreed flow then?

In one of my older comments above, I had a thought about not needing to send an email link at all.
But by entering the correct security question - the user could reset their password... how did that feel - is it simpler to implement?

**Comment by iteles** [comment]
@MollieCourtenay It's simpler to implement but in our experience, the probability of people remembering their security question is much lower than people remembering their password, so we agreed that it was worth investing the time at this stage to get the email link-through in if we can before the end of Friday.

**Comment by MollieCourtenay** [comment]
@iteles  oh interesting. Does that make the security question redundant then?

**Comment by iteles** [comment]
@MollieCourtenay Sorry, I missed this! Yes, in my experience, security questions aren't very useful for things like forgotten passwords (more of a hinderance in fact).

Their only (debatable) use is in creating a greater perception of security for things like banking logins.

**Comment by katbow** [comment]
@iteles @nelsonic I got the reply today that we've been moved out of the sandbox & had our daily/hourly limit increased 🙌

**Comment by nelsonic** [comment]
@katbow sweet! 🍭 
(_hope you're having a good weekend!_) 😉

**Comment by katbow** [comment]
@MollieCourtenay when testing please ensure it's with a real email address - if we test with a lot of fake email addresses it can raise warnings with the account.

**Comment by MollieCourtenay** [comment]
@katbow internal server error when I tried this with my email just now.

**Comment by katbow** [comment]
@MollieCourtenay what part of the process did this happen on? I just tried going through with my email & had it working.

**Comment by MollieCourtenay** [comment]
@katbow  It was when I typed in my email address and pressed 'Send reset link'

**Comment by MollieCourtenay** [comment]
it just did it again just now

**Comment by iteles** [comment]
@MollieCourtenay We couldn't replicate this 😕 
Could you try again and see whether it's still the case?

**Comment by MollieCourtenay** [comment]
@iteles still happening... ill set up a new account with my mindwave email account then try it.

**Comment by katbow** [comment]
@MollieCourtenay 
The problem here is with Amazon SES which is the service we are using to send emails. The sandbox account we started with allowed us to send emails only to verified emails (so your mindwave account, my gmail account, and the healthlocker test gmail account). 

I sent an email to get out of this as I mentioned above, and received a reply that we can now send emails to unverified emails, however it doesn't appear to be working. I am looking if there is anything I need to do that I missed for this, & if not then I am going to contact them today and see what's happening.

**Comment by katbow** [comment]
@MollieCourtenay all set up now! You can try again with an unverified email address.

**Comment by MollieCourtenay** [comment]
yay it worked!
