### ISSUE TITLE
Implement Analytics for HL Web App

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#193]
> As a SLaM Stakeholder
I would like to know what parts of the HL app are most popular
so that I know what features we need to prioritise

@tonydaly given your experience implementing MixPanel, Segment, etc.
Can you please indicate what would be the best option for the HL app?
Thanks.

**Comment by tonydaly** [comment]
Ok...so I've signed us up for:

- segment.com
- mixpanel.com
- analytics.google.com

They've all been done through my tony@dwyl.io email, segment. Who else shall I invite to these?

I've started this in #215 but there's still some work to add server-side tracking, once that's done we'll be able to create some proper funnels in Mixpanel to show conversion.

**Comment by tonydaly** [comment]
I also investigated using https://amplitude.com/ which was recently recommended to me, it looks pretty promising, but the pricing model goes from free to $2000/month...

**Comment by iteles** [comment]
@tonydaly healthlocker.test@gmail.com and the rest of the team please 👍

**Comment by tonydaly** [comment]
@iteles @nelsonic @katbow this is all merged in and working now. The login details for segment.com and mixpanel are in the Google Drive. As I won't be around until next week, maybe someone else can set up some funnels and show @MollieCourtenay and @katyedwards how it works?

That would also be good to then generate a list of other events to track.

**Comment by nelsonic** [comment]
@tonydaly 🎉
