### ISSUE TITLE
Create tests for automated browser interaction

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#201]
Automated User Acceptance Tests allow us to _automatically_ run "scenarios" against the app to confirm that it's (_still_) working as expected.

> As an HL stakeholder 
I want to know that all features of the application are working as expected
So I can be sure that users can use the app effectively

We _propose_ using daydream and nightmare to create automated browser tests.

**Comment by Cleop** [comment]
@tonydaly I recommend checking out: https://github.com/dwyl/learn-daydream-and-nightmare

Thanks for sharing the resources on hound and wallaby.

@nelsonic suggested daydream. The cool thing about it is that using the chrome extension it enables you to navigate through your browser whilst 'recording' a given user journey and when you end the recording it lists the corresponding code for the journey you just made. So I think this element of it should hopefully help save some time.

**Comment by tonydaly** [comment]
Two immediate things that I can see that might make that difficult:

1. How does it fit in the TDD loop? If we need the view to exist before we can write a test for it. I'm a big fan of outside-in development, where you write your integration tests before anything else and can see this being a blocker for that.
2. How do we run these alongside our other tests locally and on CI. Can we still run `mix test` and run _all_ our tests?

I'm not sold on the benefits of writing integration specs in JS, when everything else is in Elixir, but open to being persuaded otherwise @Cleop @nelsonic.

**Comment by nelsonic** [comment]
@tonydaly I _completely **agree**_ that it would be _way_ better for _us_ (_the technically proficient people_) to write our tests in Elixir to keep everything in the same language.

The idea behind using Daydream (_the chrome extension_) is that it allows ***non-technical people*** "_record_" their browsing activity and then create an automated test _from_ that "_recording_".
I don't know of another way to let _non-technical_ people get involved with automating tests ...

I've not used Wallaby, is this it: https://wallabyjs.com or https://github.com/keathley/wallaby ?

**Comment by tonydaly** [comment]
@nelsonic what's the workflow you imagine from starting with an issue, developing the feature, to a "non-technical" person writing these integration tests? Are they part of the feature? Can things be merged in without integration tests?

What's the benefit of having "non-technical" people writing automated tests? Is this something they want to do? I've never seen this work out correctly in the past, and you end up having two tests suites that do similar things.

I'm not sold on the speed issue, whatever system you decide to use will get "progressively" slower over time as you add more and more tests.

**Comment by nelsonic** [comment]
@tonydaly while I _agree_ that I have not seen _non-technical_ users write tests in the past,
I still think it's a _good_ idea that `should` be pursued. 

Our development workflow will remain unchanged:
+ feature/story specified in GitHub issue
+ developer estimates time required to build
+ product owner prioritises based on time estimates and other criteria
+ product owner includes story in sprint (milestone)
+ developer builds feature with functional/integration tests and documentation.
+ developer submits Pull Request
+ QA reviews & merges the PR.

What I would _like_ to see as an improvement to this workflow is:
+ product owner (_or any other non-technical stakeholder_) creates a "click-through" test for the newly released feature. 
+ this "click-through" test is referred to in the release notes for the feature
+ users can click on the release notes and "_watch_" the click-through in action on staging environment to see the workflow of the new feature.

The idea is that we get the non-technical people to write "living acceptance tests".
If these tests need to be updated in the future, the developer should sit with the PO to understand exactly what is required to be updated so everyone is clear that we are changing _existing_ functionality.

Thoughts?

**Comment by katbow** [comment]
@Cleop can this be closed now? wallaby is now used for integration testing
