### ISSUE TITLE
Homescreen Icon

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#207]
Need to have a Healthlocker favicon so that when users add Healthlocker to their homescreen, the icon is visible (instead of a blank square).

https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by indiamindwave24** [comment]
@katbow I have provided in .png (192x192px) as well as .svg - is this correct?
[HL_FAVICON.zip](https://github.com/healthlocker/healthlocker/files/826812/HL_FAVICON.zip)

**Comment by katbow** [comment]
@nogainbar can you take a quick look at this?

**Comment by MollieCourtenay** [comment]
@katbow i get tips as my home screen icon. Not the icon as above.

**Comment by katbow** [comment]
Can you take a screenshot please? I can't visualise what you mean.

**Comment by nogainbar** [comment]
@MollieCourtenay I am working on it now :) #257

**Comment by MollieCourtenay** [comment]
<img width="85" alt="screen shot 2017-03-10 at 11 03 15" src="https://cloud.githubusercontent.com/assets/25012688/23792988/2fd5d1c8-0581-11e7-906f-bbc166f94895.png">
