### ISSUE TITLE
Coping strategies: copy changes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#209]
## Acceptance Criteria
+ [x]  Add line breaks as per below for the prompting text. well. // behaviour. //
+ [x]  Make '**Note down an action you can take to stay well.**' bold 
+ [x]  When I add a new coping strategy or edit a coping strategy, the button should be 'Save' not 'Submit'

Link to #88

**Comment by katbow** [comment]
@MollieCourtenay I'm not sure I understand the first criteria. Do you mean you want a line break between the text **Note down an action you can take to stay well** and what is below it?

**Comment by MollieCourtenay** [comment]
@katbow yes, as per #88 
Line breaks like this:

**Note down an action you can take to stay well.**
Something can you do, or avoid doing when you notice a change in your feelings, thoughts or behaviour.
For example, practice relaxation techniques, leave the room if things are too tense, take a break or tell someone you trust.

**Comment by katbow** [comment]
Ahh okay got it. Thanks!

**Comment by MollieCourtenay** [comment]
great! thanks.
