### ISSUE TITLE
Rendering a 404 page

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#21]
This test is failing

```
  test "renders page not found when id is nonexistent", %{conn: conn} do
    assert_error_sent 404, fn ->
      get conn, user_path(conn, :show, -1)
    end
  end
```

It is returning a 500 error instead of 404, and it is breaking on [this line](https://github.com/healthlocker/healthlocker/blob/sign-up/web/templates/user/show.html.eex#L7) with `nil.name is undefined or private function`. 

The `user` is determined in [this function](https://github.com/healthlocker/healthlocker/blob/sign-up/web/controllers/user_controller.ex#L29), and sets the user to `nil` when the id doesn't exist in the `users` table.

I need to be able to render the 404 page when the user is set to nil, and the `show.html` in all other cases. I tried this with a case expression, and I was able to render some other random html from the `templates/user` in the case that user is nil, but I am not sure how to get the 404 page specifically.

**Comment by katbow** [comment]
@tonydaly (or anyone else who was curious!) it was because I was missing some parentheses 😑 .

Specifically [right here](https://github.com/healthlocker/healthlocker/pull/20/commits/7d286f6bdb9d95e78ee23c6e0a97fda9cfbd6e40).

I am still interested to know how to do this, or if there would ever be a reason to force a certain error page to show.

**Comment by pm5k** [comment]
I was actually about to write here regarding this. So the parentheses were one thing, but manually directing someone to a 404 template (rather than throwing a 404 response) could be done like this:

```
    def show(conn, %{"id" => id}) do
        post = Repo.get(Post, id)

        case post do
            nil -> render conn, "404.html"
            post -> render conn, "show.html", post: post
        end

    end
```

Considering this still belongs in controller logic, and unless you have a specific reason to just return a 404 response (perhaps JSON?) - you could just return a 404.html template with some apologetic text. 

Or you could just return:

```
... render( ErrorView, "404.html", error: "FUBAR")
```

**Comment by katbow** [comment]
@pm5k I tried this out before, but didn't have any success with it. However, I am thinking it is a non-issue and not something that would need to be done for an error page in particular.

I did also realise that the `!` was the problem more than the missing parentheses, as that was what gave an error when the action to get a non-existent user failed 👍

**Comment by tonydaly** [comment]
I believe this is the right way to do this. It'll only actually return a 404 in production, in dev/test you'll see the proper error.

There's a plug which handles this for you: https://hexdocs.pm/plug/Plug.Exception.html

There's a write up with some more details here: http://joshwlewis.com/essays/elixir-error-handling-with-plug/

**Comment by katbow** [comment]
Cool, thanks @tonydaly! I did some fiddling around with the dev config when I was first figuring it out and found that if I wanted to see what would be in production I could change the `debug_errors: true,` to `false`.
