### ISSUE TITLE
Goals: confirmation of deletion when deleting goals

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#213]
+ [x] As a user, if i click delete goal, I am prompted with 'Are you sure you want to delete this goal?' I can click Delete goal or cancel.

**Comment by katyedwards** [comment]
@RobStallion do you need any kind of design for this, or can you base it on something else we already have in HL?

**Comment by RobStallion** [comment]
@katyedwards I think a basic design would be helpful if you could, just so I have a better idea. I can't think of anything in the site that I could base this off of.

**Comment by katyedwards** [comment]
Will try to get someone to mock something up in the next hour or so.

**Comment by katyedwards** [comment]
![iphone 2](https://user-images.githubusercontent.com/24604903/35626944-3758fc58-068f-11e8-88a0-bb109c3171f1.png)

@RobStallion and same for coping strategies with the slightly different text

**Comment by RobStallion** [comment]
@katyedwards. This is what it currently looks like. Are you happy with this?

![image](https://user-images.githubusercontent.com/15571853/35635524-6a5476f2-06a6-11e8-900b-a08f2656a3c4.png)

**Comment by katyedwards** [comment]
That looks good!  On mobile view - will the pop up, pop up lower down so the user doesn't have to scan up to click it?

**Comment by RobStallion** [comment]
Yeah that will happen 👍
