### ISSUE TITLE
Goals: mark as important 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#214]
+ [x]  As a user I can mark goals as important (without clicking on edit first), 
- [x] goals that are marked important most recently are listed first on the goals list.

**Comment by katbow** [comment]
@MollieCourtenay would you want this to follow the flow discussed in #211 ? Where it is a button instead? 

It can still be a checkbox, but the user would need to click a 'Save' button to save it to the db.

**Comment by MollieCourtenay** [comment]
Yes please.

So when viewing a goal, 
I can click on 'Mark as important'.
I am then taken to the edit screen, I review the change has been made - that my Goal is Marked as important,
I click 'Save'.

**Comment by katbow** [comment]
> goals that are marked important most recently are listed first on Toolkit landing page.


Is this supposed to be on the goals page where all goals are listed? Since the toolkit change to icons you can click to view goals or coping strategies.

**Comment by MollieCourtenay** [comment]
@katbow yes sorry didn't review this AC after the Toolkit nav was changed.

**Comment by MollieCourtenay** [comment]
@katbow 

Mark as important are listed above those not marked as important = great.

However, the most recently marked as important are not always listed at the top.
I entered goals in this order: 1 important, 2 , 3 important, 4 , 5 , 6 important, 7 important , 8 , 9 important.

In my mind, the list should be ordered: 9,7,6,3,1,8,5,4,2.

See screenshot of my testing.  
<img width="302" alt="screen shot 2017-03-14 at 10 22 00" src="https://cloud.githubusercontent.com/assets/25012688/23896350/00143182-08a1-11e7-85cd-9a0032b9121e.png">
