### ISSUE TITLE
Investigate earmark not bolding content

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#216]
The markdown parser earmark does not seem to be bolding content that is added as a tip. 

When content is added as `**here is some text**` it shows up normally in just a `<p>` tag.

**Comment by katbow** [comment]
earmark generates a `<strong>` tag when text is placed in **. [The font is the problem here](http://stackoverflow.com/questions/16105292/strong-tag-not-showing-up-in-chrome-but-does-show-up-in-all-other-browsers). 

I tried adding to the css `strong {font-weight: bold;}`, however that did not fix the issue. When I changed the font to Arial temporarily, the bold did work again.

So the options are: use a different font that responds better to bold, or to use a different format for inputting tips (something other than bold). @MollieCourtenay @indiamindwave24

**Comment by nogainbar** [comment]
@katbow I think it might be that I didnt add a Bold weight to the google font, but can try it now and see if that solves the problem.

The font I am using is just temporary until we put in the original font (Century gothic) with @font-face.

**Comment by nogainbar** [comment]
@indiamindwave24 I think that also we have to consider that the font you are suggesting is not a webfont which means that we have to use [@font-face] (https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp) in order to use it. 
This would also mean no support for IE8 and so on IE8 the fallback font will used instead.
[Question about Century gothic](http://stackoverflow.com/questions/2186714/century-gothic-font-usablility-question)

The other option is to use a webfont that is maybe similar to Century gothic such as the one that we are using now, a google font - Didact Gothic

Let us know what you think?

**Comment by nogainbar** [comment]
This is how it look for example with [Muli font](https://fonts.google.com/specimen/Muli?selection.family=Muli:400,700) 

<img width="367" alt="screen shot 2017-03-08 at 11 52 17" src="https://cloud.githubusercontent.com/assets/12494147/23703039/d6fefade-03f5-11e7-91b2-ee45dc1d8946.png">

**Comment by nogainbar** [comment]
'btw' this copy was randomly generated ;)

**Comment by indiamindwave24** [comment]
It is very important that we use an accessible font - one that is good for dyslexia etc. It would be good to know if the issue @nogainbar raised earlier about not adding the bold weight has resolved this @katbow? If this is not resolved, I will search for an alternative. The issue with changing the font at this stage is that the branding has already been signed off and the UI designed around it.... 

With regards to the IE8 etc, can we use Verdana as a fall back?

**Comment by nogainbar** [comment]
@indiamindwave24 yes sure, so if you are happy with that, lets go with the @font-face option with fallback of verdana for IE8.

The issue of the bold was solved when switching to the other google font and adding the bold to it..

I have added the google font just temporarily until we add the font-face font, which is going to be soon! :)

Thanx!!

**Comment by indiamindwave24** [comment]
great! thanks @nogainbar

**Comment by katbow** [comment]
closing as content now bolds when formatted as `**text**`
