### ISSUE TITLE
Stories and Tips always display #tip

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#217]
By the looks of the code in _post.html.eex this section has been hard coded this way. It seems that to give stories a story tag this would have to be dynamic.

https://github.com/healthlocker/healthlocker/blob/master/web/templates/post/_post.html.eex#L18

**Comment by MollieCourtenay** [comment]
<img width="555" alt="screen shot 2017-03-10 at 12 12 27" src="https://cloud.githubusercontent.com/assets/25012688/23794941/e02921f2-058a-11e7-8085-54e04d11533b.png">

Is this what you mean?

**Comment by katbow** [comment]
That's it, that whole section is hardcoded right now. I think that best solution is to just remove it for now. Thoughts @MollieCourtenay ?

**Comment by MollieCourtenay** [comment]
Agreed.

**Comment by MollieCourtenay** [comment]
thanks!
