### ISSUE TITLE
About HL page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#23]
As a user I can read about Healthlocker.

## Acceptance Criteria
+ [x] About page can be accessed via the in the footer.
+ [x] About page content below (titles bolded)
+ [x] Email addresses carry mailto links
+ [x] SLaM link directs to their website in a new window (update: New browser tab - comments below)
+ [x] sign up to Healthlocker links to the sign up screen

(no need for SLaM logo at this stage)

## Content

**What is Healthlocker?**
Healthlocker is a secure platform powered by the South London and Maudsley Trust (http://www.slam.nhs.uk/) that promotes supported self-management and opportunities to improve communication between service users, carers and clinicians.

**It is currently in development and this is the Beta version. More features and improvements will be added in the coming months.**

**Who is Healthlocker for?**
Anyone can sign up to Healthlocker to explore wellbeing tips and recovery stories and create goals and coping strategies.
 
If you are a South London and Maudsley (SLaM) service user, you can choose to connect your Healthlocker account with your SLaM health record and care team. Soon you will be able to communicate with your care team and access your care plan, to interact with your goals and coping strategies.

If you are a close family member, friend or carer of someone at SLaM, soon you will be able to sign up and connect with their care team so that you can let them know how the person you support is doing.

If you are staff at SLaM, you can access Healthlocker via the icon in the top panel in ePJS. Soon you will be able to share information, resources and messages with service users and their carers and view updates that your caseload has chosen to share with you. 

Healthlocker is powered by South London and Maudsley NHS Foundation Trust (SLaM), if you are interested in using Healthlocker in your Trust or organisation, contact: DigitalServices@slam.nhs.uk

**Why Healthlocker?**
Healthlocker aims to demonstrate how personalised health records (PHRs) could enhance NHS service delivery and support people to stay well.

**How does it work / what next?**
Healthlocker is built using agile development processes which enables iteration through user-centred build, test and learn cycles. 

Healthlocker integrates with SLaMs clinical record system (ePJS), meaning that service users are able to access and interact with their care plan. 

The platform will be built open source and in a modular way that allows for future integrations. Healthlocker will continue to grow and develop.

If you are interested in using Healthlocker in your Trust or organisation or have ideas for how to add to the platform, contact: DigitalServices@slam.nhs.uk

**Comment by katbow** [comment]
@MollieCourtenay do you want the SLaM link to open in a new window or a new tab?

**Comment by MollieCourtenay** [comment]
@katbow 
New browser tab. Yes, sorry. Not sure how a new window would open in mobile?

**Comment by katbow** [comment]
Great I'll do that then. I think it would probably default to new tab on mobile anyway since there's not really an option for a new window.

**Comment by MollieCourtenay** [comment]
@katbow the link to About in the footer seems to just take me to the top of the page i'm on.
