### ISSUE TITLE
Goals: copy/formatting changes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#237]
+ [x] Formatting change **What do you want to achieve?**
 (line break) (regular) Describe a personal goal.

+ [x] When I add a new goal or edit a goal, the button should be 'Save' not 'Submit'

**Comment by MollieCourtenay** [comment]
Getting internal server error when clicking on goals from toolkit

**Comment by katbow** [comment]
@MollieCourtenay fixed now 😃

**Comment by MollieCourtenay** [comment]
Great thanks
