### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by nogainbar** [healthlocker/healthlocker#239]
Looking into implementing @font-face to have Century Gothic font in the application (which is not a web font) as well as making sure Verdana is ok for fallback for IE8

**Solution**
The designer wanted to implement a specific font which is not a web font. 
This means that the font (in .ttf format) had to be added to the assets folder and served by the server. 
This can be easily done by using the CSS3 @font-face rule, which allows you to download a particular font from your server to render a webpage if the user hasn't got that font installed. 

However, @font-face is not supported in IE8 so as suggested by the designer, I have used Verdana as a fallback font, which is a 'web-safe' font.

**Comment by iteles** [comment]
@nogainbar Could you please add to your story above to explain why this decision was made?

**Comment by iteles** [comment]
@nogainbar Reopened just to make sure we capture the above please!

**Comment by nogainbar** [comment]
Hi Ines!

I have added the solution to it, hope that is what you meant? happy to say more if needed :)

**Comment by nogainbar** [comment]
merged :)
