### ISSUE TITLE
Locate sign up / log in option, when not logged in P1

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#24]
## Acceptance Criteria

+ [x] users must be able to access opportunity to sign up / log in in burger menu when on Splash page / any pages and not logged in.

+ [ ] engaged users can be prompted to sign up once they have looked at some content (clicked on see more tips, read a recovery story, liked a place to be.) See screenshot - but would want to simplify.

<img width="235" alt="screen shot 2017-01-29 at 22 20 30" src="https://cloud.githubusercontent.com/assets/25012688/22408465/3eb8d3cc-e671-11e6-94b4-a10059ab521e.png">

**Comment by LauraNevo** [comment]
Maybe we could have similar to an onboarding feature? Something a user could swipe on to know about more features if they wanted to learn about it.

![01](https://cloud.githubusercontent.com/assets/3858131/22461954/55332ffc-e7a3-11e6-8e0f-a743af115cc1.jpg)
![02](https://cloud.githubusercontent.com/assets/3858131/22461955/5540ca18-e7a3-11e6-9b89-de1e0f96127d.jpg)
![03](https://cloud.githubusercontent.com/assets/3858131/22461956/554a8328-e7a3-11e6-8552-31e9ebff8836.jpg)

**Comment by MollieCourtenay** [comment]
Hi @LauraNevo 
I like this kind of interaction, but in order to keep MVP, let's keep it simple. We can return to this concept at a later date.

I imagine the content being something closer to:

_Sign-up to Healthlocker_ to save your favourite resources, create goals and coping strategies and XYZ. If you are a service user at SLaM you can also connect to your health record and care team. Something about carers...
