### ISSUE TITLE
Styling toolkit page

### ISSUE THREAD

**Issue by nogainbar** [healthlocker/healthlocker#242]
Applying simple styles to toolkit page:
- Adding temporary icons (for user testing purposes) 
- Changing links to buttons

**Comment by nogainbar** [comment]
taken a bit longer as decided to sketch the icons to make it look nicer :)

**Comment by MollieCourtenay** [comment]
@nogainbar @indiamindwave24  has made this icon for goals.


[HL_goals_icon-01.svg.zip](https://github.com/healthlocker/healthlocker/files/833732/HL_goals_icon-01.svg.zip)

**Comment by nogainbar** [comment]
@MollieCourtenay thank you very much, we didnt use that because I didnt know it existed! These were intended just as temporary until we start applying all the specific designs.. 

Is there also an icon for strategies, to keep consistency? If you can send me that I will add them now :)

thanx!!!

**Comment by MollieCourtenay** [comment]
It didn't exist till this morning :) 
I don't think @indiamindwave24 has had time to make a strategies one. it may come next week :)

**Comment by nogainbar** [comment]
ah ok...! :) so if its ok with you, I will leave these ones now just so we have consistency and until we get all the assets from you. 🥇 🌟 🍉
