### ISSUE TITLE
Converting to date without time

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#245]
I need to convert an ecto date, which looks like `2017-03-09 13:48:09.875620` to just the year, month day `2017-03-09`. 

Locally, this works fine with either `Date.to_string(@date_goes_here)`(first test below) or `Date.to_iso8601(@date_goes_here)`(second test below). However on travis this fails with similar errors:
![image](https://cloud.githubusercontent.com/assets/1287388/23755343/f3f0b0b4-04d7-11e7-87de-4960c324e52c.png)

There is something that's different about my local environment from travis - checking it out now.

Couple of things I noticed right away - travis.yml had 1.3.4 and I am running 1.4.0
mix.exs has `elixir: "~1.2"`

**Comment by katbow** [comment]
Changing version in travis.yml fixed the issue.

**Comment by nelsonic** [comment]
@katbow thanks for fixing the Elixir version and confirming it sorted the Date issue. 👍
