### ISSUE TITLE
Updates to goal schema

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#247]
Goals are currently in the 'posts' schema, however more detail is needed for additional info required for goals.
In addition to the general content of the goal (the goal itself) it needs to have:

- [x] `detail` (bullet point list with steps to take) : string, displayed with markdown
- [ ] `supporters` tbc. possibly list. possibly combined with detail
- [x] `completed` :boolean, display differently in all goals.
- [x] `notes` :string
- [x] `important` :boolean. displays at top if important.

**Comment by MollieCourtenay** [comment]
@katbow should this be in backlog? only one left in sprint 5 - wasn't sure what you wanted to do with it.

**Comment by katbow** [comment]
@MollieCourtenay I can close this now actually, thanks for reminder.
