### ISSUE TITLE
Navigating in toolkit

### ISSUE THREAD

**Issue by nogainbar** [healthlocker/healthlocker#251]
Currently there is not way to go to other pages in the toolkit besides from hitting the browsers 'back' button, I.e if you are on 

toolkit homepage > goals > view single goal > delete that goal > redirected to 'goals'

If we hit back we will hit an 'error' that the 'view single goal' doesnt exist. what would you like us to do to prevent this? such as:

- a link that goes back to 'toolkit'?
- a button that goes back?

**Comment by LauraNevo** [comment]
Oops, that's definitely my mistake for not thinking about it in the wireframes. Sounds like a toolkit button would help the user better to know where they are. And they can also use the back button of the browser. Does that sound okay?

**Comment by MollieCourtenay** [comment]
In the wireframes, where you have the Healthlocker logo currently @nogainbar , @LauraNevo had designed it to say 'Toolkit'.
I had imagined this being a clickable button to take the user back to Toolkit homepage.
However if we do this - we loose the link to 'Home' that the logo holds. Although users can access Home via burger menu...

The flow you are talking about, I think for now a button / link to go back to Toolkit would be good.

**Comment by katbow** [comment]
Closing - implemented link back to toolkit
