### ISSUE TITLE
Home page: intro paragraph

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#261]
As someone landing on Healthlocker.uk, I can read something which helps me understand what the website is for.

## Acceptance criteria

+ [x] As a not logged in user landing on healthlocker.uk, I can read an intro statement to find out what Healthlocker is. (positioned above the first story)
+ [x] I can click on links to sign up / log in / about, and am navigated to a new page within the same browser tab.

## Content

**Welcome to Healthlocker**

Healthlocker is a secure platform powered by South London and Maudsley Trust that promotes supported self-management and opportunities to improve communication between service users, carers and clinicians. 

It is currently in development and this is the Beta version. Lots more features will be added in the coming months.

[Sign up](https://www.healthlocker.uk/users/new), [Log in](https://www.healthlocker.uk/login) or [read more here.](https://www.healthlocker.uk/pages/about)

**Comment by MollieCourtenay** [comment]
Cool! There does seem to be quite a big gap between the header logo bit and the welcome to Healthlocker text. Could this be reduced slightly?

**Comment by katbow** [comment]
@MollieCourtenay yup. There's less space now. Please test again 🙂

**Comment by MollieCourtenay** [comment]
thanks
