### ISSUE TITLE
Sign up with exisiting email address. behaviour an flow. 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#264]
As a user I do not want to see this message as it is a data leak. 
"You already have an account. Please log in."

## Acceptance Criteria

+ [x] As a user who is trying to sign up to Healthlocker, and the email address I use in the sign up form is already used by a Healthlocker account, I am given a message that says (I am not redirected to the log in screen):
'Sorry you cannot create an account at this time, try again later or with different details, or [click here](log in) if you meant to log in.'

@nelsonic @katbow does this align with your memory of our conversation on Tuesday night?

**Comment by katbow** [comment]
That sounds about right - we were discussing the best wording which was not really decided yet.

If you are happy that is vague enough I can put that in instead!

**Comment by katbow** [comment]
@MollieCourtenay do you think it would be better to not have the log in suggestion in the message? and have a general "existing user? Login (link)". Similar this on the log in page:

![image](https://cloud.githubusercontent.com/assets/1287388/23800870/e3a28772-05a5-11e7-89e9-8fee89ba8bea.png)

Then there's no hint of being able to log in with that error message, it fits the same kind of formatting, and there is still a prompt on the page for logging in.

**Comment by katbow** [comment]
Like this:

![image](https://cloud.githubusercontent.com/assets/1287388/23801675/e6292a20-05a8-11e7-8df7-a27bc058d7dd.png)

**Comment by MollieCourtenay** [comment]
that looks good & sounds sensible.

**Comment by MollieCourtenay** [comment]
lovely.
