### ISSUE TITLE
Reset end user password

### ISSUE THREAD

**Issue by LauraNevo** [healthlocker/healthlocker#27]
As an end user,
I can recover my password if I lost it
so that I can access again to my account again.

![recovery](https://cloud.githubusercontent.com/assets/3858131/22781719/acfd03c4-eebb-11e6-9a98-cf451510e488.png)

I used the term "end user" here because clinicians will probably have their own way to recover password.

**Comment by katyedwards** [comment]
Clinicians will access directly via a HL button in ePJS so they won't have any kind of HL username/ password.

**Comment by LauraNevo** [comment]
Quick update to the wireframes above to include confirm password fields following #28

**Comment by MollieCourtenay** [comment]
closing as this is duplicated here: #176
