### ISSUE TITLE
Disconnect account from SLaM flow

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#271]
As a user, I may want to disconnect my HL account from my SLaM record and care team. 

## Acceptance Criteria
+ [x] As a user I can choose to disconnect, before my account is updated, I have to confirm that I do want to take this action. 

![delete account](https://cloud.githubusercontent.com/assets/3858131/24292393/105ac088-1085-11e7-9688-dd6c80895162.png)

**Comment by katyedwards** [comment]
Hi @katbow could you do us a rough time estimate for this one so we can see if it's worth prioritising - it could be helpful for demoing if we can disconnect and re-connect users and aside from this is an option that users wanted.

**Comment by katbow** [comment]
@katyedwards there you go 🙂

**Comment by katyedwards** [comment]
Thanks @katbow 
@MollieCourtenay half a day - where do you want to put this in the priorities?

**Comment by katbow** [comment]
@MollieCourtenay I was going with the same pattern we've been using of a different page instead of modal...is this okay, & how do you feel about styling of that page? This is what I have right now:

![image](https://cloud.githubusercontent.com/assets/1287388/25803489/0456cdd0-33ef-11e7-9d5e-8cc4395aec0c.png)

I wasn't sure if you wanted more text here to say about what happens if you disconnect your account.

**Comment by MollieCourtenay** [comment]
@katbow thanks for checking in with this. I like it, please can we just have this text in to be more explicit?

**Are you sure you want to disconnect your Healthlocker account?**
If you disconnect, you will no longer be able to send / receive messages with your SLaM Care team or see Care Plan updates in Healthlocker. Your Care team will no longer be able to view your tracking graphs or any new Goals and Coping Strategies you create.

You can connect again in the future if you wish.

Yes, disconnect
No, take me back

**Comment by MollieCourtenay** [comment]
@katbow  I have internal server error when trying to connect as Evan Burns on my account. 

ill log in as Evan and see if I can disconnect.

**Comment by MollieCourtenay** [comment]
I wonder if there is a better way to word the Disconnect opportunity. 

e.g.   Disconnect from SLaM

But happy to leave for now and see how people interpret it.

@katbow  Once the issue above is figured out - happy to close this one.

**Comment by iteles** [comment]
@MollieCourtenay This issue should now be fixed.
