### ISSUE TITLE
Add icons to Toolkit page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#272]
@nogainbar   I've created a new story as #244 was closed.

Attached are 2 icons: goals and coping strategies. Be great if you could add these. so we can get feedback on the HL style icons. 

[Archive.zip](https://github.com/healthlocker/healthlocker/files/838194/Archive.zip)

**Comment by nogainbar** [comment]
Hey @MollieCourtenay! Thanx, thats great! I will add these now :) 👍
