### ISSUE TITLE
Care team: Care team page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#275]
As a user, who has either ticked to identify themselves as a SLaM SU or Carer OR connected to a SLaM care team - I have a new item in my Burger menu  'Care team'.

## Acceptance criteria

+ [x] As a user, I can see Care team as an item in the burger menu.
+ [x] As a user, when I click on Care team I am taken to a new page. #275

<img width="215" alt="care team menu" src="https://cloud.githubusercontent.com/assets/25012688/23863057/9f893898-0806-11e7-817b-b77ffda3f198.png">

**Comment by iteles** [comment]
The carers now see their carers and and who their care team is. Need to implement the second half of this in sprint 11 around adding this view to the SU pages.

**Comment by MollieCourtenay** [comment]
@katbow I logged in as me, then account, Connect with the SLaM care team of someone I care for, entered Evan's details, connected, and now I have Care team menu item.

Is there anything else I am meant to try?

**Comment by katbow** [comment]
Ahh so before this, we only had the care team showing in the burger menu for carers. Second half was showing this for SLaM SUs as well, and adding the message item in the menu on the care team page.

So if you log in as Evan (who is a SLaM SU), care team will be in the menu for him as well.

**Comment by katbow** [comment]
Also welcome back 🙂  🙌  🎉

**Comment by MollieCourtenay** [comment]
Thank you @katbow .  :) 
What's Evans email address? Katy told me on the phone earlier but i've forgotten sorry.

**Comment by katbow** [comment]
evan@email.com 🙂

**Comment by MollieCourtenay** [comment]
thanks - yep that works. @katbow 

It looks like half of https://github.com/healthlocker/healthlocker/issues/277 is done.
Do you know whether it is still in sprint 10 as its nearly complete? or has it been left behind? 
It is just ideally we would display the role and the name of the clinician as a minimum?

**Comment by katbow** [comment]
@MollieCourtenay There is a bit more detail we would need to add to the mock data. I will write it up on that issue with time estimates for what is left & we can go from there on what to action on.

**Comment by MollieCourtenay** [comment]
@katbow ok ill close this one now  :)
