### ISSUE TITLE
Care team: Contacts

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#277]
As a user I can access the contact details of the care team I am connected to, so that I can keep up to date with who is providing me or the person I care for support, and I know how to get in touch with them if I need to.

## Acceptance Criteria
+  [x] As a user who has clicked on Contacts, I see a list of the SLaM care team that I am connected to, I can click to reveal their contact details.

<img width="299" alt="care team contacts" src="https://cloud.githubusercontent.com/assets/25012688/23863134/d8b08676-0806-11e7-9185-752ca88f1d66.png">

**Comment by iteles** [comment]
@MollieCourtenay @katyedwards Does this information (on who the care team is) also come from ePJS?

**Comment by MollieCourtenay** [comment]
Yes. Or an associated DB - I remember Garry referring to is as a staff table.

**Comment by MollieCourtenay** [comment]
nelsons email is said team members.

**Comment by MollieCourtenay** [comment]
@iteles

**Comment by tonydaly** [comment]
@MollieCourtenay so if a Carer signs up and then successfully connects with a SU would they appear here as part of "SLaM care team"? I thought this was coming from ePJS?

**Comment by MollieCourtenay** [comment]
@tonydaly sorry I previously misread your comment in #278 as that issue is about a carer connecting to a care team - that is what I thought you were asking about.

We are not connecting SU's and Carer's HL accounts at the moment, in the interest of getting where we NEED to be this is where we are starting:

a carer can connect with a slam care team.

a SU can connect with a slam care team.

**Comment by katbow** [comment]
There is more data we will need to add to the mock ePJS tables for this.

The missing information currently is:
* Clinician role/job title
* email
* Tel_no

If we want the minimum of name + role displaying **only** on the page with the full care team list, then time estimate is T2h. With the second page of a single clinician view with more detail, it will be another 1-2 hours, so total it's around the original estimate of T4h.

**Comment by katyedwards** [comment]
@MollieCourtenay How high would you prioritise this for the T2h version or T4h?

**Comment by MollieCourtenay** [comment]
2 hour please, just name and role.

This is because clinicians should be given the choice as to whether their email is displayed - which will require more thought and time.

**Comment by iteles** [comment]
@MollieCourtenay Can we add this final requirement in the comments as a separate issue please?

**Comment by MollieCourtenay** [comment]
Have added two:

one for email : #659
one for contact details: #660

**Comment by MollieCourtenay** [comment]
@iteles it feels a bit odd to close this issue and test it working with such limited test data. I have previously seen Evan has two care team members.

When I logged in as Lisa and Evan just now, I got internal server error when clicking to view contacts.

**Comment by MollieCourtenay** [comment]
I'd like to check this out- alongside trying a new connected SLaM user Angela in #138
