### ISSUE TITLE
Carer connect with SLaM SUs care team

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#278]
similar to #135 

Users need to be able to tick that that are family, friend or carer of a SLaM SU and have access to a link which takes them to a form to fill out in order to connect with a SLaM team.

Acceptance criteria:
- [x] As a user I can check or uncheck if I am a SLaM Carer "I am a family, friend or carer of a South London and Maudsley service user"
+ [x] Update schema to reflect if a user is a SLaM Carer
+ [x] Update slam_carer in db when user checks box - ASSUMED @katbow can you fiddle as appropriate
+ [x] If I have ticked that I am a family, friend or carer, (just now or some other time in the past, a link to "Connect with a service user’s SLaM care team (?)" is revealed below.
+ [x] Make the (?) a clickable Tooltip.
+ [x] when tooltip clicked, take to new page and show this copy. "

(?) To connect you will need to enter your full name and relationship to the person, as well as their First name, Last name, Date of Birth and NHS number, these details will be matched against their SLaM record - they must match perfectly. 
Once you have connected to the SLaM care team, you will be able to see their contact details and be able to send and receive messages with them online."
+ [x] Send information to account profile depending on if the user is connected to slam or not.
+ [x] South London and Maudsley (please capitalise SL M)

**Comment by LauraNevo** [comment]
In profile:
![carer connect](https://cloud.githubusercontent.com/assets/3858131/24293007/a057da3e-1087-11e7-935f-7a6b69b7ed5a.png)

An additional feature (lower priority) would be to prompt the user to do it at first use of the app or when they go to the Care Team page but haven't connected to a SU already:
![carer connect prompt](https://cloud.githubusercontent.com/assets/3858131/24293490/eaaed662-1089-11e7-81d8-e373f9753526.png)

**Comment by tonydaly** [comment]
A few questions:

- What's the purpose of the "I am a family, friend or carer of a South London and Maudsley service user" checkbox? Won't the fact that they have a connection to SU give us this same information? Why not just have the link "Connect with a service user’s SLaM care team (?)" permanently there. Seems like it adds a lot of technical complexity and additional steps for the user.
- The first wireframe is a bit confusing. After you've correctly entered the details correctly and they've matched who's details are you seeing on the profile screen? Won't they be waiting for their request to be approved?
- "Once the care team has reviewed and accepted your request" how does this approval process work?

**Comment by MollieCourtenay** [comment]
@tonydaly  

1.   How will we know that someone is connected to a SU? 
 "Won't the fact that they have a connection to SU give us this same information?"
I see the purpose of the checkbox being the thing that defines which connecting form the user can access. (connect to my care team OR connect with the team of the person that I care for.) Happy if you can suggest a simpler way?


2 / 3 .  there is no approval or reviewing at this stage. (I've edited the tooltip content above this was out of date sorry). This is because, all we are opening up to connected carers is the opportunity to send and receive messages to the care team. They are not seeing anything the service user is doing/ has in their record.


2. Profile is always the users own details. populating the home address etc from ePJS is a lower priority than making the connection with the care team & record.

**Comment by tonydaly** [comment]
Are "connecting to _my_ care team" and "connecting with the team of the person that I care for" mutually exclusive? Could we have both links?

**Comment by tonydaly** [comment]
That makes more sense _without_ the approval process.

**Comment by tonydaly** [comment]
Can you be the carer for more than one SU?

**Comment by MollieCourtenay** [comment]
So we could have these two options available to all HL users, unless they have already connected to a team?

Connect with my SLaM care team and health record (?)
Connect with the SLaM care team of the person I care for (?)

I've asked around and being a carer for more than one person is rare - but does happen.
I would be happy for MVP to run with allowing just one connection either as a SU or Carer and only to one team.

And use that to understand whether people would want to do more than this...

**Comment by tonydaly** [comment]
@MollieCourtenay exactly.

Ok let's go with just one for the moment.

**Comment by tonydaly** [comment]
@MollieCourtenay after a carer has connected with an SU, where either of them see this relationship?

**Comment by MollieCourtenay** [comment]
@tonydaly  

#275   #276    #277

**Comment by MollieCourtenay** [comment]
@tonydaly the connecting as a carer to the care team form at the moment is missing the fields where the carer enters their own details:

First name, Last name, Relationship to the SU.

Just wanted to check in on your thinking/ plans around this?  As without this detail entered, how in messaging would the carers name display to the clinicians?
(I also mentioned to @iteles on the call just now, it would be great to display name and relationship in Clinician caseload view for each of the carers. )

**Comment by tonydaly** [comment]
@MollieCourtenay we're currently using the carer's name that they used when they created their Healthlocker account.

You're correct that the relationship field is missing, could you add a separate issue for that (should be small).

**Comment by iteles** [comment]
@MollieCourtenay The relationship is now captured in a separate issue. The only one I'm not sure about it what you mean by your last checkbox in the very first comment above?
Everything else is ready to test.
