### ISSUE TITLE
The save button has been lost for editing coping strategies.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#280]

**Comment by katbow** [comment]
@MollieCourtenay I still see the save button:

![image](https://cloud.githubusercontent.com/assets/1287388/23897566/91d01862-08a5-11e7-82ad-30936f88da22.png)

Can you take a screen shot of what you're seeing and post here please?

**Comment by MollieCourtenay** [comment]
sorry was working on my iphone 5s safari
![img_2119](https://cloud.githubusercontent.com/assets/25012688/23897692/0bc777aa-08a6-11e7-9ec3-b7ba67f1e6cd.PNG)
