### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by tonydaly** [healthlocker/healthlocker#29]
Implementing some basic components from here: https://www.dropbox.com/sh/oxvwi0eh6xlkj03/AABdIQSYCz4AiMNKABpWPH-4a?dl=0

**Comment by tonydaly** [comment]
Style guide examples:

- https://marvelapp.com/styleguide/overview/introduction
- http://www.martinwright.uk/2017/01/12/designing-inspired-style-guides/
- https://www.designernews.co/stories/72224-style-guide-examples

Feel free to add any more.

**Comment by Cleop** [comment]
Landing page, click on 'See more stories', to list of all stories page with view of stories page at the top and lower down.

![landing to see more stories](https://cloud.githubusercontent.com/assets/16775804/23413919/20bf8a1e-fdd2-11e6-8fee-052fb6dc5e85.png)

**Comment by Cleop** [comment]
Landing page, click on menu icon, to menu, click on 'get support', support page with a view at the top and bottom of the page.

![landing to get more support](https://cloud.githubusercontent.com/assets/16775804/23458412/1c008b02-fe74-11e6-9954-bbdceb20759b.png)

**Comment by Cleop** [comment]
Landing page, click on 'See more tips', scroll tips page to see different tips.
![landing to tips](https://cloud.githubusercontent.com/assets/16775804/23463845/eb10d3a0-fe8a-11e6-8ba1-d98e02e483f3.png)

**Comment by Cleop** [comment]
Landing page, click on 'See more "beactive" tips', all beactive tips page.

<img width="460" alt="tips 3" src="https://cloud.githubusercontent.com/assets/16775804/23464480/0aa092b2-fe8d-11e6-9794-ff054417e599.png">

**Comment by Cleop** [comment]
Landing page, click on 'Sign up', click 'back' on sign up page, click 'new post' on welcome page, log in page with error message.
<img width="700" alt="post notsigned in" src="https://cloud.githubusercontent.com/assets/16775804/23465499/584e6cc0-fe90-11e6-8b4a-5369c4e67277.png">

**Comment by Cleop** [comment]
Sign up process using a new user and new email. 
Landing page, click on 'Sign up', fill in details, click 'submit', fill in details, click 'submit', accept terms, click 'submit', arrive with success message and view of dashboard.

![landing sign up stages 1 2 3 complete](https://cloud.githubusercontent.com/assets/16775804/23557894/974d9ea6-0029-11e7-9f94-fb05faf31ceb.png)

**Comment by katbow** [comment]
![image](https://cloud.githubusercontent.com/assets/1287388/23667395/990b0826-0355-11e7-8790-16f69d52b34e.png)

**Comment by MollieCourtenay** [comment]
still work to be done, but closing now as work is continuing.
