### ISSUE TITLE
Spike for messaging feature

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#291]
* Are web sockets appropriate for this?
* Using [phoenix channels](http://www.phoenixframework.org/docs/channels)
* Ways to build without sockets/channels/JS (if it is not instant messages)

**Comment by iteles** [comment]
What messaging feature @katbow ? Is this linked to a user story?

**Comment by katbow** [comment]
Yes, sorry. #49 #283 #284

**Comment by katbow** [comment]
From the time I've spent on this so far, the most useful docs will the phoenix channels linked above, and ch10 of phoenix. 

[Here's a resource](https://github.com/dwyl/learn-phoenix-framework/tree/cb3a345ce35faec64c6644819663af15c7b7592a/rumbl/web/channels) with example code to check out!

**Comment by nelsonic** [comment]
@katbow its _really_ worth following the examples in the book all the way as the authors are the "original source" for learning Phoenix and you will acquire a _lot_ of useful/practical knowledge in a systematic way.

**Comment by nelsonic** [comment]
@katbow quick PR with a chat (_messaging_) spike just to demo the "OTP Channels": https://github.com/dwyl/chat/pull/30
(_in case we don't get a chance to catch up this morning..._)

**Comment by katbow** [comment]
Got this sorted now so closing.
