### ISSUE TITLE
Failed to load resource: /css/fonts.css 404 (Not Found)

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#294]
@katbow can you please check the `404` we are getting for font on the home page:
![image](https://cloud.githubusercontent.com/assets/194400/23997955/5cc2a598-0a4b-11e7-929a-38b2864a2939.png)

It's being included in the main layout template:
https://github.com/healthlocker/healthlocker/blob/74f980307e5cdbcafe1811942c5a74385d189e48/web/templates/layout/app.html.eex#L15

Steps to reproduce:
+ Visit: https://www.healthlocker.uk 
+ Open developer console.
+ Notice that  https://www.healthlocker.uk/css/fonts.css fails to load 😞 

Thanks for investigating. 👍

**Comment by MollieCourtenay** [comment]
Not sure what / how to test this @katbow

**Comment by katbow** [comment]
No worries @MollieCourtenay - I put it for @nelsonic to check out. I'll remove the please test label to avoid confusion.

**Comment by nelsonic** [comment]
@katbow I can _confirm_ that I'm no longer seeing the `404` error for the `.css` file.
(_thanks for fixing it!_) 🎉 

I am _however_ seeing a WebSocket connection issue:
![image](https://cloud.githubusercontent.com/assets/194400/24688318/239292c6-19b7-11e7-9057-384da0e23480.png)

But that is a _separate_ issue which needs to be looked at: https://github.com/healthlocker/healthlocker/issues/387
So, closing this one. 👍
