### ISSUE TITLE
Account: edit to say SLaM health record

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#304]
Account> Profile: 
Connect with my SLaM care team and SLaM health record (?)

Account> Profile> Connect:
Please use the correct information as it appears in your SLaM health record.

**Comment by katbow** [comment]
@MollieCourtenay @katyedwards this is another one that was updated to no longer say slam. Is this okay to close?

**Comment by katyedwards** [comment]
Yep, I think this has been superseded.
