### ISSUE TITLE
Make tooltips easier to find and use

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#308]
+ [x] replace the '?' with an icon (NHS number)
+ [x] replace the '?' with an icon (Connect to SLaM)

**Comment by Cleop** [comment]
Does this one need assigning to @indiamindwave24, @MollieCourtenay? Who will be determining the approach for this?

**Comment by tonydaly** [comment]
Generally, tooltips don't work as well on mobile as you can't hover and their small size can make them difficult to touch. For something important like this, a link that opens in a new page should be suitable?

**Comment by MollieCourtenay** [comment]
@Cleop @tonydaly 

Yes idea is the content would still open in a new page. @indiamindwave24 is just going to design a simple icon to replace the '?' we have now.

**Comment by Cleop** [comment]
@MollieCourtenay @indiamindwave24 do you have an ETA of when we're likely to get this icon?

**Comment by indiamindwave24** [comment]
@Cleop 
[tooltip-20.svg.zip](https://github.com/healthlocker/healthlocker/files/951885/tooltip-20.svg.zip)

**Comment by MollieCourtenay** [comment]
@katbow they are where they need to be but they aren't standing out enough for me - ive asked India if she has a mo to make new icons.

**Comment by MollieCourtenay** [comment]
@katbow just noticed we're missing the one for when a carer connects.

**Comment by indiamindwave24** [comment]
Updated tooltip icon: @katbow 

[Tooltip.zip](https://github.com/healthlocker/healthlocker/files/975809/Tooltip.zip)

**Comment by MollieCourtenay** [comment]
Looking better thanks.

We need to add the tooltip and content for when a carer connects:

Connect with the SLaM care team of someone I care for (?)

To connect you will need to enter your full name and relationship to the person, as well as their First name, Last name, Date of Birth and NHS number, these details will be matched against their SLaM record - they must match perfectly. 
Once the care team has reviewed and accepted your request, you will be able to see the contact details of their SLaM care team and be able to share notes with the care team online.

**Comment by katbow** [comment]
Ok, I'll add that in. I changed the time estimate to reflect this because I'll need to add the new page for this.

**Comment by MollieCourtenay** [comment]
@katbow Yikes sorry gave you old version of tooltip content. 

Please replace second paragraph with this: 

Once you have successfully connected, you will be able to see the details of the SLaM care team and send / receive messages with the care team online.

**Comment by MollieCourtenay** [comment]
@katbow the second paragraph for the connect with carers tooltip still says this:
Once the care team has reviewed and accepted your request, you will be able to see the contact details of their SLaM care team and be able to share notes with the care team online.

**I want it to be replaced with this please:**

Once you have successfully connected, you will be able to see the details of their SLaM care team and send / receive messages with the care team online.

**Comment by MollieCourtenay** [comment]
@iteles looks like this has been stuck waiting review / not moved to please test.
