### ISSUE TITLE
Case sensitivity of email on sign up

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#313]
**As a** user **I want to be able to** sign up and sign in with my email regardless of using lower or uppercase **so that** I don't have to worry about my mobile automatically using uppercase for the the first letter and removing this on another instance.

Relates #311

**Comment by katbow** [comment]
@Cleop this should be fixed now! It won't work on past email addresses unfortunately, but if you try to sign up with an email that is uppercase, then log in with it written lowercase, you'll be able to log in.

The emails are now saved to the database all lowercase, so `MyName@dwyl.io` will be the same as signing up with `myname@dwyl.io`

**Comment by Cleop** [comment]
@katbow I just tested this and it works 👌  Thanks for fixing
