### ISSUE TITLE
edit crisis support info

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#314]
## Acceptance Criteria

+ [x] As a Healthlocker user, when I click on Get Support, I see the content below. The phone support section is in its own grey box - with a phone icon.

**Comment by MollieCourtenay** [comment]
awaiting approval from Nicola on this.

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria

+ [ ] As a Healthlocker user, when I click on Get Support, in the grey box, I see:

## What to do in a crisis 

*If you need urgent help you have lots of options:* 

- If you can wait to see your GP they can help you find the best service for you
- If you are under a mental health team remember to follow your care plan if you have one, and call your care co-ordinator (or speak to a duty worker from their team) during office hours
- If you are in an emergency call 999 or find your nearest A&E.

## Free 24-hour phone support
**SLaM mental health support line:** 0800 731 2864 for anyone in Southwark, Lambeth, Lewisham or Croydon

**The Samaritans:** 116 123 is a national service (and you don't have to be suicidal to call for support) 

**NHS 111:** 111 for urgent, but non-emergency, medical advice

**Comment by MollieCourtenay** [comment]
@indiamindwave24 please add the phone icon in here when you have it.

**Comment by katbow** [comment]
Couple of styling questions for this one @MollieCourtenay @indiamindwave24

* Can the positioning of the phone icon be confirmed? Does it go left/right of the section title, within the grey box, text wrapped around, vertically centred etc?
* Is the entire section below `Free 24-hour phone support` in the grey box? 
* Is the title for phone support itself also in the box or above it?

**Comment by MollieCourtenay** [comment]
![img_2219](https://cloud.githubusercontent.com/assets/25012688/24668308/5875672e-195e-11e7-975e-65a7cfde2a4a.JPG)

Icon, in grey box - centered under 24 hour phone support header.
24 hour support, icon, phone lines = all in grey box.

**Comment by indiamindwave24** [comment]
@katbow 
[Crisis_line_Strategies copy 9.svg.zip](https://github.com/healthlocker/healthlocker/files/900013/Crisis_line_Strategies.copy.9.svg.zip)

**Comment by MollieCourtenay** [comment]
@katbower 
+ [ ] need the A&E link to work, link to a new browser window
+ [ ] all phone numbers should link to call on mobile devices
+ [ ] on iPhone 5s, safari, the bullet pointed statements are held in very narrow columns. Can the columns be as wide as the grey box?
+ [ ] can the bullet points be left aligned? so in line with the 'If you need'.
