### ISSUE TITLE
Toolkit: Sleep tracker button

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#318]
## Acceptance criteria

+ [x] As a user on Toolkit, I can click on a button called 'Sleep tracker'.

@indiamindwave24 can you supply an icon for sleep tracker please?

**Comment by LauraNevo** [comment]
Here is the wireframe. We're considering the Toolkit to become a dashboard / home page when the user is logged in. Please have a chat with Mollie. :)

As I understand, the sleep tracker will be the only one developed at the moment as opposed to all the other trackers.
![tracking_dashboard](https://cloud.githubusercontent.com/assets/3858131/24292085/a2bb96ca-1083-11e7-9bce-316fc6d2db44.png)

**Comment by katbow** [comment]
Thanks for that @LauraNevo ! Yup, just starting with sleep then going from there 🙂

**Comment by indiamindwave24** [comment]
Will be creating icon for this on Monday

**Comment by indiamindwave24** [comment]
[Sleep_tracker_icon.zip](https://github.com/healthlocker/healthlocker/files/879090/Sleep_tracker_icon.zip) @katbow

**Comment by katbow** [comment]
@indiamindwave24 that icon is so cute 😍 . I love it!

**Comment by MollieCourtenay** [comment]
Lovely

**Comment by indiamindwave24** [comment]
@katbow 
[Sleep_tracker_.svg.zip](https://github.com/healthlocker/healthlocker/files/900006/Sleep_tracker_.svg.zip)

**Comment by katbow** [comment]
@MollieCourtenay the new icon is in there now 🙂

**Comment by indiamindwave24** [comment]
[Sleep_tracker.svg.zip](https://github.com/healthlocker/healthlocker/files/952099/Sleep_tracker.svg.zip) @katbow can this be updated, please?

**Comment by katbow** [comment]
@indiamindwave24 Same question as in #323 - what is the priority for this in relation to [Sprint 9](https://github.com/healthlocker/healthlocker/milestone/10)?
