### ISSUE TITLE
Toolkit shrink icons

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#321]
it would be nice to see both goals and strategies icons when i load the screen on all screen sizes. 

Do we do it side by side?

Have sleep tracker underneath - when you get to that??

**Comment by MollieCourtenay** [comment]
@katbow Footer is hogging again - Safari macpro. 
<img width="1251" alt="screen shot 2017-03-27 at 12 50 32" src="https://cloud.githubusercontent.com/assets/25012688/24354980/0d029064-12ec-11e7-9fae-6eb0b3f69cd1.png">

**Comment by katbow** [comment]
can you give me your screen size & safari version please (from safari -> about safari)?

This doesn't happen on my mac pro in safari so I need a bit more detail.

**Comment by MollieCourtenay** [comment]
oh really sorry i mean Chrome and 13 inch macpro

**Comment by katbow** [comment]
Alright, can you give me version number still? I have the same size and I am still not seeing this happening. You can get it from going to the three dots -> help -> about chrome.

Also, is this happening even when the chrome window is full screen, or only when it's resized to be smaller?

**Comment by MollieCourtenay** [comment]
Version 56.0.2924.87 (64-bit)

when ive make the screen slightly smaller than full screen.  is ok on full screen.

<img width="1280" alt="screen shot 2017-03-27 at 15 40 46" src="https://cloud.githubusercontent.com/assets/25012688/24362146/c73c9bca-1303-11e7-850b-eb4bd73ffe71.png">

**Comment by katbow** [comment]
ok great, thank you!
