### ISSUE TITLE
Toolkit - Tracking overview button

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#323]
## Acceptance criteria

+ [x] As a user on Toolkit, I can click on a button called 'Tracking overview'.

@indiamindwave24 can you supply an icon for Tracking overview please?

**Comment by katbow** [comment]
@MollieCourtenay where does this button go? is it the page to show what you've tracked over time?

**Comment by LauraNevo** [comment]
![tracking_dashboard](https://cloud.githubusercontent.com/assets/3858131/24292164/0e452a78-1084-11e7-94d8-84d7436b6e38.png)

**Comment by indiamindwave24** [comment]
will be creating this on Monday :)

**Comment by katbow** [comment]
Great 🙂 . I put in a temp icon for now (not merged in yet), but it will be a quick switch then.

**Comment by MollieCourtenay** [comment]
@katbow for now it will be an icon on Toolkit, just as goals / strategies / sleep tracker / tracking overview.

(PS: I'm thinking Tracking may become its own menu item in the future - not in toolkit)

**Comment by katbow** [comment]
@indiamindwave24 do you have the icon for this one as well?

**Comment by indiamindwave24** [comment]
[Tracking_overview.svg.zip](https://github.com/healthlocker/healthlocker/files/890843/Tracking_overview.svg.zip)

**Comment by indiamindwave24** [comment]
Can this be updated? @katbow 
[Tracking_overview.svg.zip](https://github.com/healthlocker/healthlocker/files/952136/Tracking_overview.svg.zip)

**Comment by katbow** [comment]
@indiamindwave24 what is the priority for this in relation to [Sprint 9](https://github.com/healthlocker/healthlocker/milestone/10)?
