### ISSUE TITLE
Care team: Carer send message to SLaM care team.

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#328]
As a carer of someone at SLaM, I can choose to send messages, (thoughts, observations, reflections) to the care team of the person I support.

## Acceptance Criteria

+ [x] As a user, who has clicked on Care team in the burger menu, I can write and send a message to that care team. 
+ [x] As a user, who has just sent a message, I see it displayed at the **bottom** of my message feed.

<img width="107" alt="write message" src="https://cloud.githubusercontent.com/assets/25012688/23862665/87f9f74a-0805-11e7-9095-9829da0d00ea.png">

## Content
**Write a message to [service users first name]’s care team.**
Share your thoughts, observations and reflections.
[TEXT BOX]
Messages should not be used in emergency situations. If you need urgent help or advice, go to [Get support](https://www.healthlocker.uk/support). Your message will be sent to the care team. Do not expect an immediate response. 

Send

**Comment by katbow** [comment]
@MollieCourtenay can you add a priority label & move to the correct place in sprint 7 when you get a chance?

**Comment by MollieCourtenay** [comment]
@katbow RE sending messaged - all good.

Not sure about this: TBC Connecting Carer with SU care team. Connection can probably be done through SU i.e. if the SU has identified someone as a carer, then that person will have access to the care team.

There is an issue here about Carers connecting to SLaM here #278

**Comment by katbow** [comment]
@MollieCourtenay yup that's what I was looking for! Thanks
