### ISSUE TITLE
Message display

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#329]
I wanted to confirm my understanding from the discussion during yesterday's demo/sprint planning regarding the layout of the messages screen.

The original wireframes had the input box at the top of the screen with the messages displaying in a box below with most recent messages at the top. However, if we take from other messaging apps that users are likely to have experience with, then we should flip this around so the input field is at the bottom of the screen and messages display above with the newest message at the bottom.

Can you confirm this change @MollieCourtenay? For #49, #283, #284, #328.

**Comment by MollieCourtenay** [comment]
Yes, happy to run with that.
