### ISSUE TITLE
Sorting list of numbers for select

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#333]
We've been able to load in security questions from a file #144. However, what I did not notice at first was that when converting from a `list` to a `map` [here](https://github.com/healthlocker/healthlocker/blob/master/web/views/component_view.ex#L6-L23), the order rearranges. This is fine for security questions, but I was attempting to do the same for the [sleep tracker](#320), and these are numbers so the order matters. 

I thought of sorting, however in maps, [the keys do not follow any order](http://elixir-lang.org/getting-started/keywords-and-maps.html#maps), so I don't think I can do this.

I tried instead the trick shown [here for age](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#select/4-examples), however it only works with whole numbers. For `hours_slept` we are going up by 0.5, and the `wake_count` ends with 10+(instead of just 10).

Any thoughts on how to achieve this without having the list of options directly in the `form.html.eex` file?

Edit: this is for #320

**Comment by tonydaly** [comment]
Instead of loading the questions from a `.txt. file, could we instead use YAML? Then we could have an ordered collection of questions?

**Comment by katbow** [comment]
Won't we run into the same issue when it's converted to a map?

**Comment by tonydaly** [comment]
Maybe I missed it before, but why do we need to convert it to a map?

**Comment by katbow** [comment]
I think it was because of how [select takes options](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#select/4). We tried it as a list before, but we kept getting errors. 

I think it can still be a regular list like `["a", "b", "c", "etc"], but then there's no value for that option.

**Comment by tonydaly** [comment]
I believe if you just provide a List, then the "element will be used both as key and value for the generated select".

e.g. `select(form, :question, questions)`

**Comment by tonydaly** [comment]
That said what we should really do is have the value as the string, and the key as the array index.

**Comment by katbow** [comment]
I just checked and it does work & preserves the order.

The reason why I went for both the key and value as the string is so the full question saves to the db which was useful in cases where I need to display the question, like in account for updating the question. When I had numbers as the key, then it was saving & displaying that instead of the actual question.

**Comment by katbow** [comment]
We can use the yaml file or txt...I think the reason we went with txt is because it would just be a more familiar format/file type for anyone non-technical updating the list. 

I'm not certain I understand the benefit for using yaml? This seems to keep the order still (now).

**Comment by tonydaly** [comment]
YAML is a more standard format for configuration data and you can use it to store different types of data. So we could define them as an Array, or as a key/value pair (if we wanted). The libraries available make it much easier to read the data into native datatypes, without the need for splitting on newlines, deleting empty strings etc.

Also will the `security_questions()` read the file each time the view is rendered? Feels like we'd want to move that processing into the application config, so that it's only performed once on boot. Can then fetch it with `Application.get_env`! 😃

**Comment by katbow** [comment]
Ahh I see. I wonder then if it's better to keep the familiarity for the person changing the file or go for yaml so it's easier to read the data... thoughts @nelsonic?

Yeah, that's a good point. I'll add that in a separate issue as a todo, because at the moment it would read the file each time.

**Comment by tonydaly** [comment]
In my opinion, if someone needs to change the questions (is this a requirement?), then there should be an interface for it, and then the questions should probably be kept in the DB.

**Comment by katbow** [comment]
fixed the ordering
