### ISSUE TITLE
Input field height obscures text in signup form ?

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#335]
visiting https://www.healthlocker.uk/users/new I see:

![image](https://cloud.githubusercontent.com/assets/194400/24256171/50d271a2-0fdf-11e7-98a2-9396770ea3c1.png)

But when I increase the input field height above `44px` I see the input text:
![image](https://cloud.githubusercontent.com/assets/194400/24256219/76c79220-0fdf-11e7-9b51-d579e30e7cfe.png)

@Cleop can you please confirm you see this on your side? thanks.

**Comment by Cleop** [comment]
How odd @nelsonic... I am not getting the same display as you. Both dev tools (various dimensions) and my iPhone 5C do not seem to be encountering this issue.

I'm using the healthlocker.uk version. 

Let me know if there's any set up that I'm missing out that led you to get this bug.

**Comment by nelsonic** [comment]
@Cleop thanks for investigating. I was running the app on my localhost off `master`. 
Will re-visit it on Monday. 👍

**Comment by katbow** [comment]
I believe this issue was fixed a while again when @RobStallion was making some fixes for IE11. I have not encountered it in a while, and if others can confirm this, then this issue should be good for closing 👍

**Comment by katyedwards** [comment]
@RobStallion see Katherine's message - can this be closed?

**Comment by RobStallion** [comment]
@katyedwards @katbow is correct. This was fixed a while ago. I'll close the issue now
