### ISSUE TITLE
Error page when trying to sign up using existing user details

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#336]
As a user I should get an error message in TTRR if I have already signed up and try to sign up again using the same details.

At present you get a horrible error page:
https://www.dropbox.com/s/jiz9ywoo80m4avz/Screenshot%202017-03-24%2010.32.13.png?dl=0

**Comment by katbow** [comment]
@katyedwards I think this is meant to be posted [here](https://github.com/research-resource/research_resource/issues).

**Comment by katyedwards** [comment]
Dammit I was looking for that - I assumed it hadn't posted!  Thanks @katbow

**Comment by katbow** [comment]
No problem! I did post a reference to this issue there, but would be good to still have it posted by you as a user story
