### ISSUE TITLE
prevent injection of html in chat

### ISSUE THREAD

**Issue by andrewMacmurray** [healthlocker/healthlocker#338]
sorry I was a troll in the phoenix talk lol

in the chat a user can put html in the chat which could potentially fill the screen with an annoying red div

<img width="616" alt="screen shot 2017-03-24 at 16 15 56" src="https://cloud.githubusercontent.com/assets/14013616/24303240/34fa50a2-10ad-11e7-8478-64219188ee26.png">

**Comment by nelsonic** [comment]
@andrewMacmurray thank you _very_ for reporting that. :

**Comment by katyedwards** [comment]
@RobStallion Has this been solved by restricting the cross-site scripting or have I misunderstood?  Can this be closed?

**Comment by RobStallion** [comment]
resolved with #1074
