### ISSUE TITLE
Internal server error for editing security details

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#344]
Noticed in #127 

When checking the heroku logs, there was this issue:

![image](https://cloud.githubusercontent.com/assets/1287388/24354340/4d447046-12e9-11e7-9eae-debb80df6b07.png)

The `security_questions.txt` file is not found in the build of healthlocker. Need to update brunch so that the text files are included in the build.

**Comment by iteles** [comment]
Expected implementation plan needed to be refined.
