### ISSUE TITLE
Clinician: skeleton interface

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#354]
As discussed a little earlier.

Ahead of having ePJS going next week  (hopefully)  would it be useful to create some skeleton interfaces?

**Comment by iteles** [comment]
@molliecourtenay We have this from Laura: https://github.com/healthlocker/healthlocker/issues/38#issuecomment-278615874

Are you thinking that those wireframes need to be revisited?

For simplicity, what we propose is to have a list of the people that we get from epjs as part of the clinician's caseload, with those at the top being those who also have healthlocker accounts (this might be more valuable than the 'recent activity' split and we wouldn't implement the 'unread count' just yet).

**Comment by MollieCourtenay** [comment]
Yes, lets go with what we have in GH already in terms of the Caseload. 
But the Clinician interface will need to hold more than the caseload shortly, when messaging comes etc.

So by skeleton I mean is there work we need to to / issues to create about:
creating a basic interface with a home, back to ePJS button and some basic nav, before we build the caseload feature?

**Comment by iteles** [comment]
@MollieCourtenay We just need to split this out into the acceptance criteria - at this stage, with it being a simple wireframe, the detail we need is around:
+ Will the split in the caseload be around Healthlocker vs non-healthlocker users?
+ What is the treatment of the non-healthlocker users?
+ A new issue on what the service user summary page will look like when we click into it.

**Comment by MollieCourtenay** [comment]
<img width="426" alt="screen shot 2017-04-10 at 17 10 35" src="https://cloud.githubusercontent.com/assets/25012688/24906708/c504961a-1eb0-11e7-8dc7-7daac6ae4f91.png">
Clinician case load skeleton

**Comment by MollieCourtenay** [comment]
Example of one a clinician has clicked on a user 

<img width="424" alt="screen shot 2017-04-11 at 12 17 54" src="https://cloud.githubusercontent.com/assets/25012688/24906897/ac388e42-1eb1-11e7-83be-2a421be3f22a.png">

**Comment by indiamindwave24** [comment]
![clinician_caseload_style_guide](https://cloud.githubusercontent.com/assets/25007700/25128231/e6dee4fe-2430-11e7-8bae-eaa0c64a68b7.png)

**Comment by iteles** [comment]
For 28th:
+ [ ] Change kerning on Caseload word
+ [ ] Add pink arrow

**Comment by Cleop** [comment]
@indiamindwave24 - do we have a copy of the new yellow arrow yet? I want to do the issue but I don't know where the new arrow is.

**Comment by indiamindwave24** [comment]
yes this is okay

**Comment by katyedwards** [comment]
Closing this issue as primary requirements for now have been achieved - how to display carer's on the clinician caseload will be opened as a separate issue
