### ISSUE TITLE
Prevent users from entering sleep data more than once per day

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#357]
relates to #320. Users shouldn't be able to enter info more than once.

**Comment by iteles** [comment]
Also good to clarify here that this is a starting assumption. We're looking to build this simply and fully understand that people may want to track naps or irregular sleep cycles, but we would like this request to come from the user testing to ensure that we are building the most valuable features first.

@katbow We need to have some nice user feedback to go with the input to say 'you have already entered your sleep data for today' if they try to enter more than once.
