### ISSUE TITLE
Active button styling.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#363]
Grey buttons look dull and inactive.

@katbow how best to note this issue, list each button, or is there a simple way you can change the colour of all the call to action buttons?

**user feedback**

**Comment by katbow** [comment]
@MollieCourtenay @indiamindwave24 in the original style guide, the buttons are in the HL pink, and aqua on hover. Is this still the case?

I know @indiamindwave24 is updating the style guide, but I wanted to include this here to double check and as a reminder to myself

**Comment by indiamindwave24** [comment]
<img width="366" alt="hl_updated_style_guide" src="https://cloud.githubusercontent.com/assets/25007700/24720714/f1c77f70-1a35-11e7-808c-b1f1596ea0ae.png">

**Comment by iteles** [comment]
@katbow Can we add this mini style guide pic to the documentation too please?

**Comment by MollieCourtenay** [comment]
@indiamindwave24 please can you add your comment about hover state?

**Comment by indiamindwave24** [comment]
@katbow the current hover state on the site appears to be adding transparency, not as outlined in the styleguide.

If there is an issue with the stye guide hover state, do let me know and I will design an alternative.
<img width="319" alt="screen shot 2017-04-13 at 09 58 21" src="https://cloud.githubusercontent.com/assets/25007700/24997850/1187f592-2030-11e7-9363-b6db202ab398.png">

**Comment by katbow** [comment]
@MollieCourtenay this should be done for all buttons that are currently on the site. We'll be able to add the default styling to any new buttons we add.

**Comment by MollieCourtenay** [comment]
@indiamindwave24 can you please test this and close if you're happy?
