### ISSUE TITLE
Flash messages - styling

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#364]
These are being missed by users - if they are noticed it takes a few seconds.

Can they be coloured / centred? / exist in a banner?

@indiamindwave24 can you come up with some ideas/ a solution?

e.g. 
welcome to healthlocker!
Goal added!
Coping strategy added!

**Comment by katbow** [comment]
Another note for myself to refer to update style guides when they become available @indiamindwave24

**Comment by indiamindwave24** [comment]
<img width="366" alt="hl_updated_style_guide" src="https://cloud.githubusercontent.com/assets/25007700/24720707/ea857a28-1a35-11e7-9225-e2526f93a132.png">

**Comment by MollieCourtenay** [comment]
<img width="744" alt="screen shot 2017-04-10 at 11 31 25" src="https://cloud.githubusercontent.com/assets/25012688/24857739/44e5953a-1de1-11e7-9316-a2efd8bb3b84.png">
<img width="755" alt="screen shot 2017-04-10 at 11 31 10" src="https://cloud.githubusercontent.com/assets/25012688/24857746/478932ba-1de1-11e7-8da4-c65ed69b4831.png">

**Comment by indiamindwave24** [comment]
The padding above this flash message seems to have been removed @Cleop <img width="884" alt="screen shot 2017-04-27 at 11 46 05 am" src="https://cloud.githubusercontent.com/assets/25007700/25480098/3961abf2-2b3f-11e7-9f9a-0a2ddbde4816.png">

**Comment by indiamindwave24** [comment]
👍
