### ISSUE TITLE
Burger menu - reorder & redirect

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#365]
In order to enable users to pick up Healthlocker and use it straight away - make the menu more literal. 

Goals and tracking           (renamed from Toolkit)
Care team       
Tips    (https://www.healthlocker.uk/tips)
Stories    (https://www.healthlocker.uk/posts)
Get support
Account 
Log out

About in footer (remove from burger)

**Comment by katbow** [comment]
@MollieCourtenay this looks like logged in view? How is this for logged out?

My assumption would be:
Tips
Stories
Get Support
Sign up
Log in

**Comment by katbow** [comment]
Also, is there a still dividing line with Account & Log out in smaller, dimmer text?

**Comment by katbow** [comment]
One last question lol. Is get support still displayed in the same way as a pink button?

**Comment by katbow** [comment]
Logged out:

![image](https://cloud.githubusercontent.com/assets/1287388/26399278/4ad74280-4074-11e7-88b2-0c2ba6691fbf.png)

Logged in with care team:
![image](https://cloud.githubusercontent.com/assets/1287388/26399336/7b0e9b38-4074-11e7-87a8-4dfd7ac2483c.png)

& logged in without care team:

![image](https://cloud.githubusercontent.com/assets/1287388/26399363/9204d776-4074-11e7-80fc-e70a2c2a1156.png)

**Comment by iteles** [comment]
@katbow Yes, the intention was always to make Get Support stand out and be obvious :+1:

**Comment by MollieCourtenay** [comment]
@katbow  

get support pink  - yes please.
loose the dotted line - yes please.

Make all the same size, so account and log out being same colour and size as others please. 

For logged out:
Please keep Home and About.

Sorry I didn't think of logged out user!
