### ISSUE TITLE
Goals: mark as important - add icon

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#367]
As a user I can tell visually which of my goals I have marked as important.

## Acceptance criteria 

+ [x] As a user, I can mark a goal as important, then see it listed with an overlaid icon in the goal list. 

Icons - to come from @indiamindwave24 

<img width="195" alt="screen shot 2017-04-03 at 17 49 24" src="https://cloud.githubusercontent.com/assets/25012688/24620521/faeb91be-1895-11e7-911d-9ae9c2df4a55.png">

**Comment by katbow** [comment]
> I see an empty state icon 
> I see an positive state icon

I'm not sure what this means. Is it an empty icon vs a coloured in icon?

**Comment by MollieCourtenay** [comment]
yes, e.g. 
<img width="48" alt="screen shot 2017-04-18 at 15 02 32" src="https://cloud.githubusercontent.com/assets/25012688/25134658/15797d08-2448-11e7-9a3e-18e6d7313dbb.png">
<img width="55" alt="screen shot 2017-04-18 at 15 02 29" src="https://cloud.githubusercontent.com/assets/25012688/25134659/157d5aa4-2448-11e7-9dc8-e5fe8e378b75.png">

**Comment by katbow** [comment]
One other question for @indiamindwave24, how does this look when viewing a single goal?

![image](https://cloud.githubusercontent.com/assets/1287388/25172562/59796eea-24e9-11e7-91f9-310fc44d3a5a.png)

**Comment by indiamindwave24** [comment]
![edit_goal](https://cloud.githubusercontent.com/assets/25007700/25180130/b8ff3adc-2504-11e7-897b-199d60cc8fb6.png)
![goals_overview](https://cloud.githubusercontent.com/assets/25007700/25180131/b9002460-2504-11e7-83d0-daae76937320.png)
![view_goal](https://cloud.githubusercontent.com/assets/25007700/25180132/b907f712-2504-11e7-97a9-10a689ee3910.png)

Please see changes to 'goals': Edit now houses the delete as well as mark as important. There is no longer a 'back to toolkit' link as we discussed a few weeks ago that the header should house the menu title and clicking this should navigate back to 'toolkit', for example.

**Comment by indiamindwave24** [comment]
Also, here are the stars (selected and unselected) and the tick for the check boxes.
[Stars.zip](https://github.com/healthlocker/healthlocker/files/934391/Stars.zip)
[tick.svg.zip](https://github.com/healthlocker/healthlocker/files/934393/tick.svg.zip)

**Comment by katbow** [comment]
@indiamindwave24 I'm moving the last 2 criteria to #491 so I can estimate this easier.

**Comment by indiamindwave24** [comment]
Would it me useful for me to create the stars as PNGs (also checkboxes) - there is a relatively long loading time @katbow

**Comment by katbow** [comment]
yes please - they can all go into the #539.

If you're happy with the styling of this overall besides that then it can be closed 🙂
