### ISSUE TITLE
links - styling throughout

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#370]
can we agree a convention?

**Comment by indiamindwave24** [comment]
<img width="366" alt="hl_updated_style_guide" src="https://cloud.githubusercontent.com/assets/25007700/24720642/ba34e39a-1a35-11e7-8759-a6d0573aef14.png">

**Comment by MollieCourtenay** [comment]
+ [ ] links on log in page don't look like links.
<img width="697" alt="screen shot 2017-04-19 at 16 41 11" src="https://cloud.githubusercontent.com/assets/25012688/25188760/100343e0-251f-11e7-9183-1e47f80f0f5c.png">

+ [ ] Not consistent colours (light blue vs dark blue). E.g. on landing page:  all links are dark blue on my Chrome, but mixed colours on India's chrome. Mixed on my phone on safari. 

![screencapture-healthlocker-uk-posts-1492616744778](https://cloud.githubusercontent.com/assets/25012688/25188972/b8077b9c-251f-11e7-8dae-0ace602365fc.png)
![screencapture-healthlocker-uk-1492616795476](https://cloud.githubusercontent.com/assets/25012688/25188996/c9e54222-251f-11e7-8a78-f9125e000758.png)

**Comment by katbow** [comment]
@MollieCourtenay for that last one, is that not just for non-visited vs visited links? For me it's only links I've visited in the past that are coloured dark blue, links which I've never been to are light blue.

**Comment by MollieCourtenay** [comment]
@indiamindwave24 seeing it like this - I would prefer to have links always light blue, no matter if I have visited or not..

**Comment by katbow** [comment]
all fixed with the links all as light blue now
