### ISSUE TITLE
Create mixpanel analytics funnels

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#374]
- Start with client-side funnels
- Move on to server-side

- Start with sign up flow funnel

**Comment by Cleop** [comment]
I've successfully created a basic flow for sign up which measures loaded page URLs. 

I'm now seeking to enhance that by creating custom events for basic functions. I succeeded in creating a custom event for loading the homepage but am now getting this error when trying to create a second custom event:

![image](https://cloud.githubusercontent.com/assets/16775804/24611799/2d4b4a2a-187b-11e7-951b-ab00f272d85d.png)

@tonydaly any advice?

**Comment by Cleop** [comment]
Fortunately @tonydaly has some suggestions up his sleeve using segment that I am now going to pursue to overcome the problem above.

**Comment by Cleop** [comment]
Relates to #35

**Comment by Cleop** [comment]
My current 'Coping Strategy' tracking is not appearing in the Phoenix logs (neither confirmation nor success) and I think this may be down to with the 'Posts' identifier.

**Comment by tonydaly** [comment]
@Cleop the `analytics is not defined` error you're seeing might be because the Segment JS snippet isn't being included on the page, [this](https://github.com/healthlocker/healthlocker/blob/master/web/views/layout_view.ex#L4) is the function that renders it.

**Comment by Cleop** [comment]
Thanks @tonydaly bizarrely @katbow managed to help me fix this by merge in master. Not quite sure what was causing it.

**Comment by Cleop** [comment]
The Coping strategy event has now been created and can be used in funnels on Mixpanel. The page load is yet to appear and I will now work on this (it had to be merged before it was possible to test). 

I have also just discovered that Mixpanel does not allow you to create more than 5 funnels using its free version. So @katyedwards and @MollieCourtenay this underlines even more that the client should consider budgeting for a paid version of Mixpanel. The free version also only tracks data dating back 60 days. Given that currently we can only create 5 funnels (user journeys to get analytics on) it would be great if you could give me some refined priority for what 5 journeys you'd like these to be ahead of the upcoming user testing. Please let me know precisely which pages you'd like the journeys to cover.

**Comment by katyedwards** [comment]
@Cleop I think this'll be an @MollieCourtenay ollie call, but as @iteles mentioned, go with what was discussed on Tuesday - I'll set a reminder to ask Mollie about this on Monday but she is out most of the day with external meetings so she may not have much chance to look until later in the afternoon.  I can delay sending the link out to our testers until late Mon or early Tues though if necessary.

**Comment by Cleop** [comment]
I'm going to close this issue for now as we have currently set up the maximum number of funnels possible (5) without paying for mixpanel. We can open a new issue should this change and we have new opportunities.
