### ISSUE TITLE
Tick boxes. Make them pretty. 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#378]

**Comment by indiamindwave24** [comment]
<img width="134" alt="screen shot 2017-04-20 at 15 38 50" src="https://cloud.githubusercontent.com/assets/25007700/25236316/7a20b0ee-25df-11e7-8748-d195c3d74e33.png">

**Comment by MollieCourtenay** [comment]
closing as this is a repeat
