### ISSUE TITLE
Clinician: list ePJS caseload of Healthlocker users

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#38]
As a clinician I can view a caseload list of all my service users, so that I can access their individual HL dashboards / summary screens.

## Acceptance Criteria

+ [ ] As a clinician, when I click on the HL logo within ePJS, a new window opens in my browser (a requirement for Garry?)
+ [x] As a clinician, I can see a list of service users (first name and last name displayed) from my ePJS caseload.

Links to #131  #132

**Comment by MollieCourtenay** [comment]
The Clinician will click a button something like this in epjs, to load the same caseload in Healthlocker.
<img width="642" alt="hl access on epjs" src="https://cloud.githubusercontent.com/assets/25012688/22511373/66c1227a-e88d-11e6-88ed-44296f6d4280.png">

EMAIL FROM GARRY:
> Hi Mollie,
 
The prototype for the placement of the clinician HL portal link on the ePJS caseload/search results page has been done.  Further dev work would continue when HL becomes available to us to link to i.e. transmission of the logged in username to HL. Do you know when this will be?

Kind regards,
Garry
Garry Moriarty
Clinical Systems Manager
Digital Services | South London and Maudsley NHS Foundation Trust
Clinical Systems Team | Denis Hill Unit | Bethlem Royal Hospital

**Comment by LauraNevo** [comment]
![clinician - dashboard](https://cloud.githubusercontent.com/assets/3858131/22781356/0d3dbb4a-eeba-11e6-9011-e704f2e7d4d9.png)

**Comment by katbow** [comment]
linked to #122

**Comment by MollieCourtenay** [comment]
<img width="428" alt="screen shot 2017-04-12 at 17 45 59" src="https://cloud.githubusercontent.com/assets/25012688/24969296/353a2f1a-1fa8-11e7-9124-0df32be7637b.png">

**Comment by iteles** [comment]
Removing from milestones until we have access to ePJS and can complete the second portion of this.

**Comment by MollieCourtenay** [comment]
@iteles / @katbow  Not sure how I can test this - as I cant see the DB vs the user input info...

**Comment by MollieCourtenay** [comment]
Ive closed this and created a new issue for backlog: #670
