### ISSUE TITLE
Clear analytics data history of dev/skewed data or remove certain user from results

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#380]
- In order for the data analytics to be presented cleanly it would be best if the data created during development was not included.

- As real users start using the app there are certain team members who will still be using the healthlocker site a lot. We do not want their activity to skew the results of the user testing data that will begin to come through. Is it possible to remove/block their activity from being tracked?

Relates #35

**Comment by iteles** [comment]
For now, we can just limit the date range to post-launch 👍
