### ISSUE TITLE
Tracking sleep overview: View previous/next time period

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#382]
- [x] As a user, I can choose the navigate with previous and next buttons, this will alter the graph and average data to show the previous or next selected time scale. #324 

<img width="276" alt="screen shot 2017-03-21 at 19 13 56" src="https://cloud.githubusercontent.com/assets/25012688/24166247/903f0844-0e6a-11e7-9945-091889ff8b27.png">

@MollieCourtenay can you verify priority including position in sprint?

**Comment by MollieCourtenay** [comment]
@katbow after our conversation yesterday, I've moved down the extended time scales issue, and kept the priority up on this issue.

The user will need to know what week / dates they are looking at - the wireframes have the dates displayed under each day - yesterday morning in our demo, it seemed like this was a complicated / timely requirement?

Could we have the first and last date displayed on the graph /below the graph? - This was something discussed I think when we were considering the 30 day timescale.

This may help the highlighting today - if today was displayed as todays date, then I would argue it doesn't need to be highlighted?

**Comment by katbow** [comment]
I'm going to take 1 hour to see how to go about adding date under the graph. I think it is the most clear that way so I think it's worth checking out for timing. 

If not, then I can add the start and end dates under the graph 👍

**Comment by katbow** [comment]
@MollieCourtenay update for this: dates are now displayed under each day 👍 . The only difference from the wireframe here is I wasn't able to have it on a new line underneath the day of the week, which seems to be a default of the graphing library. 

Instead the view switches depending on the screen size.

Mobile: 
![image](https://cloud.githubusercontent.com/assets/1287388/24713500/c6481fde-1a1d-11e7-96b9-594f5514acb2.png)

Desktop:
![image](https://cloud.githubusercontent.com/assets/1287388/24713554/f5cefd9a-1a1d-11e7-9acb-cc143e116271.png)
