### ISSUE TITLE
Rounding average hours slept

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#388]
This morning I input more sleep data & I got an average with 3 decimal places:

![image](https://cloud.githubusercontent.com/assets/1287388/24699361/a22d61c2-19eb-11e7-96e0-6947a5e2d411.png)

What would you like the standard to be? Rounded to 1 to match how sleep is input? E.g. above should be 7.4

**Comment by katyedwards** [comment]
@katbow yes I would think so... 1 decimal place seems like it would be enough detail.  I think sensible to start with that and then get feedback.  You'd want to know 7.5 hours, but probably 7.52 doesn't add any real value.

**Comment by markwilliamfirth** [comment]
@katyedwards I saw this and had an idea/feedback! Decimal points for hours can be quite difficult to understand - for example 7.4 (rounded from 7.375) hours is 7h and 23 minutes, but a user may see this and mistake it for 7h40m if they don't think about it and calculate it in their head

To me as a user 7h23m is more valuable than 7.4h

If this is too much detail, the minutes could be rounded to the nearest 5/10/15 etc

**Comment by katyedwards** [comment]
Thanks @markwilliamfirth  If that's as easy to implement then that would be great yes

**Comment by katbow** [comment]
fixed now 👍

**Comment by MollieCourtenay** [comment]
@katbow

Like the decision to display the averages as you have done. Just aware that that is not how we have displayed the hours and minutes in the scroller in the input page. 
We currently have 
7
7.5
8
8.5

I think to be consistent, then perhaps the scrolls should display this too? 
7h
7h 30m
8h
8h 30m

**Comment by katbow** [comment]
@MollieCourtenay how do you feel about trying out your first pull request on this?!

I have a [guide in the readme](https://github.com/healthlocker/healthlocker#updating-select-input-options-eg-security-questions) for this. It might be a good opportunity to test it out & let me know if anything is confusing in the instructions so I can update it.

What do you think?

**Comment by MollieCourtenay** [comment]
yep I can give it a go next week @katbow

**Comment by katbow** [comment]
great! We can walk through it together if you like, then I can update the instructions as we go for anything that I missed or didn't explain well 👍
