### ISSUE TITLE
Linter?

### ISSUE THREAD

**Issue by shouston3** [healthlocker/healthlocker#396]
What are your thoughts on setting up a linter?
[dogma](https://github.com/lpil/dogma) seems good (took about 2 mins to get set up) (may take longer to fix the linting errors).
I ran it in the project and there are a couple of long lines and inconsistencies (pretty good though)

**Comment by tonydaly** [comment]
[credo](https://github.com/rrrene/credo) is already added, but we aren't using in CI or anything (I have my editor configured to warn me).

**Comment by tonydaly** [comment]
@shouston3 I set it up ages ago to use [hound](https://houndci.com/), but it never worked and it looks like their configuration has changed since: https://houndci.com/configuration#elixir (it was in beta).

Would be great to properly hook that up.

**Comment by shouston3** [comment]
Great, I'll have a look at hooking up credo
