### ISSUE TITLE
Unique index in sleep trackers prevents data entry

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#398]
The for_date should be unique on a per user basis. Instead, I made it unique on its own which prevents more than one user from entering data for a day. 

Need to remove the unique index and check if data exists already for the user trying to enter data more than once.

**Comment by katbow** [comment]
@Cleop Want to check out that this works now?

**Comment by Cleop** [comment]
Thanks @katbow It now works, I'm going to close this issue.
