### ISSUE TITLE
Error Screen on Login after Timeout

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#413]
One of our User Testers has reported:

The system generated a crash when I tried to login due to a time out.
![crash](https://cloud.githubusercontent.com/assets/24604903/24946673/8f6e42de-1f5b-11e7-802e-05c758a983e7.jpg)

FYI, Mollie had the same problem yesterday as well although this didn't occur again after she refreshed.

**Comment by tonydaly** [comment]
This looks like the same issue in #425
