### ISSUE TITLE
Error from analytics after tracking sleep

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#414]
This happened running locally from master branch

When I input data into `/sleep-tracker/new`, and click `Save` I get an error screen for no function clause matching in Healthlocker.Analytics.EventNameBuilder.event_name/2:

![image](https://cloud.githubusercontent.com/assets/1287388/24950808/2843dcf4-1f6a-11e7-849c-f61d01ab9566.png)

The information is saved, because when I go to `/sleep-tracker` then the data is displayed.

**Comment by tonydaly** [comment]
Fixed by #424.
