### ISSUE TITLE
Sleep tracker, hit save with no data entered - internal server error

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#418]
<img width="485" alt="screen shot 2017-04-12 at 16 06 36" src="https://cloud.githubusercontent.com/assets/25012688/24964746/055938b2-1f9a-11e7-8013-2500a44a702a.png">

Chrome.

**Comment by tonydaly** [comment]
This should be fixed by #424.

**Comment by MollieCourtenay** [comment]
@tonydaly  I got it again today.... after entering sleep data, hitting save, internal server error, hit back in my browser, landed on toolkit, and i had the error flash saying i cant enter data more than once in a day.

**Comment by tonydaly** [comment]
@MollieCourtenay sorry I was a bit eager in closing this, the fix in #424 hasn't been merged yet.

**Comment by MollieCourtenay** [comment]
<img width="740" alt="screen shot 2017-08-09 at 08 29 21" src="https://user-images.githubusercontent.com/25012688/29109978-f54ee520-7cdc-11e7-9a43-27e220fc4f44.png">

<img width="811" alt="screen shot 2017-08-09 at 08 31 28" src="https://user-images.githubusercontent.com/25012688/29110032-2e4dc92c-7cdd-11e7-883f-6c97ae1ec2ad.png">

the error message shows if there is no data in the sleep tracker / diary  and the user clicks save
