### ISSUE TITLE
Make 'See more stories' a button

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#420]
- [x] Make 'See more stories' a button

**Comment by Cleop** [comment]
I'm imagining that whatever the answer for #421 is then this will be the same but....

@MollieCourtenay @indiamindwave24 which style of button would you like for this?

![image](https://cloud.githubusercontent.com/assets/16775804/25227231/cae7a2be-25bf-11e7-9374-dc8996d9aa04.png)

**Comment by indiamindwave24** [comment]
secondary @Cleop

**Comment by indiamindwave24** [comment]
increase spacing between like button & Read this story (as above) @Cleop

**Comment by indiamindwave24** [comment]
Looks great! 💯
