### ISSUE TITLE
Make 'See more tips' a button

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#421]

**Comment by Cleop** [comment]
@MollieCourtenay @indiamindwave24 which style of button would you like for this?

![image](https://cloud.githubusercontent.com/assets/16775804/25227231/cae7a2be-25bf-11e7-9374-dc8996d9aa04.png)

**Comment by indiamindwave24** [comment]
secondary @Cleop

**Comment by indiamindwave24** [comment]
This has been removed now, correct? @Cleop

**Comment by Cleop** [comment]
Yes it has. If you could close the issue for that reason instead @indiamindwave24, thanks!
