### ISSUE TITLE
Toolkit, page seems to take quite long time to load icons

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#429]
+ [ ] make the page quicker to load

@tonydaly do you need @indiamindwave24 to do anything or can you edit the SVGs you have?

**Comment by tonydaly** [comment]
@MollieCourtenay we'll be converting them to a PNG, so I'll need to know is what size they should be?

**Comment by MollieCourtenay** [comment]
@indiamindwave24 ?

**Comment by indiamindwave24** [comment]
@tonydaly @Cleop (not sure if Tony is working on this today) Apologies, I had not seen this notification. 

I have provided all in svg format so that they can be made responsive? Is PNG the best way to provide - will this affect the responsiveness?

**Comment by indiamindwave24** [comment]
@tonydaly What sizes should I provide if PNG is necessary to speed up loading time?

**Comment by tonydaly** [comment]
@indiamindwave24 we can start with whatever the largest version we need. If we need different versions for different resolutions we can generate those later. The PNG will be significantly smaller in file size even if it's slightly bigger (pixels) than we need everywhere.

**Comment by indiamindwave24** [comment]
@tonydaly I have put all the icons for the site in a zip file
[PNG_Icons.zip](https://github.com/healthlocker/healthlocker/files/958040/PNG_Icons.zip)

**Comment by katyedwards** [comment]
Have been testing and this definitely seems better.  @katbow you removed the please-test label, does this mean you're still tinkering with it?  If not, I think it's ok to close!

**Comment by katbow** [comment]
@katyedwards I realised there was one icon that still needed to be changed to png 🙂 . It will be in the next pull request, so if you'd like you can wait until I have that in, or close now if it's already looking better. It will be going in for certain either way!

**Comment by katyedwards** [comment]
Sure, no problem!  I'll close it now because I don't get to do that very often!
