### ISSUE TITLE
Tips: add intro to the 5 ways to wellbeing

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#441]
As a user on the landing page, I am given some information about each of the 5 ways to wellbeing - so that I can understand why these tips might be useful to me. 

+ [x]  Add title 'Tips: 5 ways to wellbeing' (bold, centerd, dark blue, same size as welcome to HL and Stories)
+ [x]  Add copy 
+ [x]  Add link to document
+ [x] Add light grey dividing line before and after each 5 ways section (but not after the last one)

Each of the 5 ways to wellbeing is introduced with: (see google doc for content)
+ [x] a Title which has #link (e.g. #Connect is a link to a page that lists all the Connect tips as per current interaction on live site)
+ [x] a short paragraph
+ [x] Add icons for each category

+ [x] This tips section is at the top, the random story is now displayed underneath the intro to the 5 ways.

Other issues will cover:
an example tip under each section: #473
the pages that list tips from each category: #483
all tips page: #482

https://docs.google.com/document/d/1wHQVJp6p3W2_6debDxn8BtbbHwVPQI717csrodYgSnM/edit

**Comment by indiamindwave24** [comment]
#447

**Comment by indiamindwave24** [comment]
![tips_filtered_by_hashtag](https://cloud.githubusercontent.com/assets/25007700/25192199/32cd2318-252a-11e7-86ed-4f595f003cdb.png)

**Comment by Cleop** [comment]
@indiamindwave24 - is the header now different and won't include the 'healthlocker' logo? but the title of the page instead? 

This will be more difficult to implement because it would mean changing the master template for the header/footer which is applied to every page? Would it just be like this on the tips page or every page?

**Comment by Cleop** [comment]
Also @indiamindwave24 - is the interconnected circles the correct logo for 'Connect', that's what you've got on the homepage design but here it seems to be a set of scales?

**Comment by Cleop** [comment]
@indiamindwave24 @MollieCourtenay Should the general 'Tips' page include all 5 intros to tip types in the same way that the landing page does?

**Comment by MollieCourtenay** [comment]
@Cleop regarding the Title in the header instead of logo. This has aways been on the wireframes and has been discussed at a couple of demos but just hasn't happened yet.
We see this as a really useful navigation tool too, if it was clickable.
I think we need to make a separate issue for this.

All icons in those designs above are placeholder at the moment.

Only the intro paragraphs to be on landing page and individual tip category pages. not on the page that just lists the tips.

**Comment by MollieCourtenay** [comment]
@Cleop I realise this issue is overloaded and needs rewriting. i need to pop out for a bit can i do it when i get back.

**Comment by Cleop** [comment]
These are the only points specifically for the tips pages which I haven't already included in #465:

TIPS- CATEGORIES
- Add 'Explore more tips:' link at the bottom of each category of tip page.
- Add 'Create a goal for yourself' copy at the bottom of each tip page.
- Add category introduction and image to each category page

**Comment by Cleop** [comment]
Awaiting images from @indiamindwave24

**Comment by indiamindwave24** [comment]
Here is the screen updated with correct icons: 
![home_01](https://cloud.githubusercontent.com/assets/25007700/25335029/0219e0f4-28e9-11e7-9c4a-bd3814a60b72.png)

And this is the spacing information:
<img width="517" alt="screen shot 2017-04-24 at 12 23 50" src="https://cloud.githubusercontent.com/assets/25007700/25335043/11d2432e-28e9-11e7-8ccd-e622e2a3a594.png">

Icons:

**Comment by Cleop** [comment]
Thanks for the update @indiamindwave24, I think the icons may have failed to download properly at the end of your message there?

**Comment by indiamindwave24** [comment]
@Cleop have updated

**Comment by indiamindwave24** [comment]
@Cleop I have not given specific dimensions for the SVG files. As long as they all use the same vertical spacing and are top and left aligned with the text. No less than 20px padding on the right margin of the icon
<img width="776" alt="screen shot 2017-04-24 at 12 35 15" src="https://cloud.githubusercontent.com/assets/25007700/25335351/8d6fce74-28ea-11e7-94f3-6ea3ffecf399.png">
Hope this screenshot helps explain

**Comment by indiamindwave24** [comment]
@Cleop On Mobile, icons are not aligned to the top of text.

Padding is not consistent on mobile. 

Perhaps we can stack the icons above the '5 ways of wellbeing' descriptions? - makes everything less squished and, if centered, avoids the alignment issues.
![iphone_home](https://cloud.githubusercontent.com/assets/25007700/25386864/b033691c-29c0-11e7-88f1-eb0a6f700bb7.png)

**Comment by indiamindwave24** [comment]
@katbow Should I open the mobile stacking as a new issues?

**Comment by katbow** [comment]
yes please, that'd be great 🙂
