### ISSUE TITLE
About page: add SLAM logo

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#442]
@indiamindwave24 please supply the logo and mock up the placement of the SLAM logo

**Comment by Cleop** [comment]
@MollieCourtenay @indiamindwave24 do you have an ETA of when we're likely to get this?

**Comment by indiamindwave24** [comment]
@Cleop 

I seem to have misplaced the illustrator file with the illustrations in SVG format. I will upload when I find
![about_01](https://cloud.githubusercontent.com/assets/25007700/25339786/b86a6556-28fb-11e7-8481-30c08fd40ebc.png)
 them.
[About_page.zip](https://github.com/healthlocker/healthlocker/files/951851/About_page.zip)

**Comment by indiamindwave24** [comment]
I have recreated the illustrations as SVGs. Please use these :)

[About_illustrations.zip](https://github.com/healthlocker/healthlocker/files/953040/About_illustrations.zip)

**Comment by katbow** [comment]
see png_icons for SLaM logo
