### ISSUE TITLE
Menu: shrink width on desktop screen sizes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#448]
+ [x] As a user using Healthlocker on a desktop screen - when I click the menu it does not fit the full width of the screen.

+ [x] The menu has a white outline - as the footer and the menu are soon to be the same dark blue.

**Comment by indiamindwave24** [comment]
![menu_desktop](https://cloud.githubusercontent.com/assets/25007700/25178536/0d694fce-24fe-11e7-9b73-33c054dd3c97.png)

**Comment by indiamindwave24** [comment]
looks lovely :)
