### ISSUE TITLE
Clinician can see SUs interactions with Goals & Coping strategies

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#45]
As a clinician I can get a sense very quickly of how a service user is or isn't interacting with their goals or coping strategies in HL.

**Comment by LauraNevo** [comment]
![clinician - goals and strategies](https://cloud.githubusercontent.com/assets/3858131/22780989/915114ba-eeb8-11e6-99fb-8dd965f6d792.png)

**Comment by MollieCourtenay** [comment]
<img width="424" alt="screen shot 2017-04-11 at 12 17 54" src="https://cloud.githubusercontent.com/assets/25012688/24968831/83001126-1fa6-11e7-9c05-bad910a22843.png">
