### ISSUE TITLE
Move login link to navbar and change it to a button 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#468]
+ [x] Remove login link from welcome message 
+ [x] Add log in button to navbar

<img width="547" alt="screen shot 2017-04-21 at 13 27 51" src="https://cloud.githubusercontent.com/assets/25012688/25277553/1c02095a-2697-11e7-8289-8fa15bd0cf18.png">

**Comment by indiamindwave24** [comment]
@Cleop Kerning is different on this button to the rest of the site.
<img width="144" alt="screen shot 2017-04-25 at 1 41 31 pm" src="https://cloud.githubusercontent.com/assets/25007700/25386496/79b687c6-29bf-11e7-9eb2-0422a96604a4.png">

**Comment by indiamindwave24** [comment]
@katbow The hover for log inout does not appear as on the rest of the site, the opacity seems to be altered. 
<img width="128" alt="screen shot 2017-04-26 at 10 06 31" src="https://cloud.githubusercontent.com/assets/25007700/25426805/38a46178-2a68-11e7-896d-c5c02fa4fd7f.png">

**Comment by katbow** [comment]
@indiamindwave24 I have this changed in another branch (along with the kerning) - will let you know when it's merged in & ready to check

**Comment by indiamindwave24** [comment]
👍
