### ISSUE TITLE
Log out button in nav bag when logged in

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#469]
+ [x] Ensure when using a desktop screen size, the Log in button says and works as a 'Log out' button in nav bar when a user is logged in

<img width="547" alt="screen shot 2017-04-21 at 13 27 51" src="https://cloud.githubusercontent.com/assets/25012688/25277532/04e21f30-2697-11e7-93c7-306123b7a833.png">

#468

**Comment by indiamindwave24** [comment]
@Cleop Kerning is different on this button to the rest of the site.
<img width="144" alt="screen shot 2017-04-25 at 1 41 31 pm" src="https://cloud.githubusercontent.com/assets/25007700/25386496/79b687c6-29bf-11e7-9eb2-0422a96604a4.png">
