### ISSUE TITLE
Change 'Welcome to Healthlocker' text

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#471]
+ [x] Welcome to Healthlocker - keep bold please
+ [x] Welcome to Healthlocker - make bigger, the same size as titles for Stories and Tips:5 ways will be
+ [x] Welcome to Healthlocker - aqua blue

![home](https://cloud.githubusercontent.com/assets/25007700/25191964/49b1d12e-2529-11e7-80d0-700c7f0800a9.png)

**Comment by indiamindwave24** [comment]
👍
