### ISSUE TITLE
Right align sign up link and change to a button

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#472]
+ [x] Right align sign up link 
+ [x] Make Sign up a primary button

![home](https://cloud.githubusercontent.com/assets/25007700/25191964/49b1d12e-2529-11e7-80d0-700c7f0800a9.png)

**Comment by indiamindwave24** [comment]
The padding below the sign up button should be the same size as the padding between the dark blue divider and the title below: 24px -- is it at the moment?

**Comment by indiamindwave24** [comment]
👍
