### ISSUE TITLE
Example tip under each 5 ways to wellbeing intro paragraph

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#473]
+ [x] As a user, I can see an example tip underneath each of the 5 ways to wellbeing introduction paragraphs. 

use the tips in the google doc please: https://docs.google.com/document/d/1wHQVJp6p3W2_6debDxn8BtbbHwVPQI717csrodYgSnM/edit

EXTENSION + [ ] the example tips should be random, so that the user doesn't see the same examples each time they access this page.
(be good to have an estimate on this too?)

+ [x] As a user I can click on the #Tip and be taken to https://www.healthlocker.uk/tips?tag=Tip 
(changes to this page covered in this issue: )

+ [x] As a user I can click on the tip category(#Connect / #BeActive / #TakeNotice / #GiveToOthers / #KeepLearning)  and be taken to e.g. https://www.healthlocker.uk/tips?tag=TakeNotice
(changes to these pages covered in this issue: )

![home](https://cloud.githubusercontent.com/assets/25007700/25191964/49b1d12e-2529-11e7-80d0-700c7f0800a9.png)

**Comment by indiamindwave24** [comment]
great 👍
