### ISSUE TITLE
Homepage: add 2 dark blue dividers

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#476]
As a user I see the page is broken up by dividers to help me understand when one section starts and ends.

+ [x] as a user I can see a dark blue divider at the end of Welcome to Healthlocker and before Tips:5 ways to wellbeing
+ [x] as a user I can see a dark blue divider after Tips:5 ways to wellbeing and before Stories

**Comment by indiamindwave24** [comment]
Great 👍
