### ISSUE TITLE
Home page: centre and resize Stories title

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#477]
- [x] Centre 'Stories' title
- [x] Make Stories title bigger and the same size as Welcome to Healthlocker and Tips: 5 ways to wellbeing titles will be.

<img width="213" alt="screen shot 2017-04-21 at 14 22 22" src="https://cloud.githubusercontent.com/assets/25012688/25279323/f4c3fffe-269d-11e7-86aa-d6cd5ac03de5.png">

**Comment by indiamindwave24** [comment]
@Cleop yes, great. 

However, I cannot find the issue where I wrote this, but the stories title text should be the same size as the tip titles. (Styled as in above image)

**Comment by Cleop** [comment]
Would you be able to close this one and find/ open a new issue where appropriate for the individual story styling @indiamindwave24? Thanks
