### ISSUE TITLE
Stories: Resize individual story titles

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#478]
- [ ] Resize individual story title

@indiamindwave24  Was your intention for the stories titles and the tips statements to be of the same size and weight?

<img width="213" alt="screen shot 2017-04-21 at 14 22 22" src="https://cloud.githubusercontent.com/assets/25012688/25279392/33f0a376-269e-11e7-810f-062dd15cd158.png">

**Comment by indiamindwave24** [comment]
Main title: ie. 'stories' - **20px centered**
Title: ie. 'tip title'; 'story title' - **16px bold left aligned**
Body text: **16px regular left aligned**

Same for both tips and stories

**Comment by iteles** [comment]
It was agreed with @katyedwards that this would be done manually via markdown 👍

**Comment by katyedwards** [comment]
@indiamindwave24 @MollieCourtenay are you happy with the stories and tips as they are now - or do you want me to do more editing?

**Comment by indiamindwave24** [comment]
I am happy - @MollieCourtenay ?
