### ISSUE TITLE
Reduce top padding of each tip

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#481]
+ [x] Reduce top padding of each tip

<img width="591" alt="screen shot 2017-04-21 at 14 27 28" src="https://cloud.githubusercontent.com/assets/25012688/25279543/abf1b798-269e-11e7-8b79-6434fbe51b35.png">

@indiamindwave24 please add any specifics?

**Comment by indiamindwave24** [comment]
**24px** top and bottom padding

**Comment by Cleop** [comment]
@MollieCourtenay do you want me to remove the 'like'? This is what I'm doing at the moment without it:

![image](https://cloud.githubusercontent.com/assets/16775804/25283625/4d908856-26ac-11e7-9200-884f1864e676.png)

**Comment by MollieCourtenay** [comment]
@Cleop 
The like will be replaced by the bookmark  #41  - but perhaps till we get round to that we can remove it - so it looks good.

**Comment by indiamindwave24** [comment]
<img width="517" alt="screen shot 2017-04-24 at 12 23 50" src="https://cloud.githubusercontent.com/assets/25007700/25335510/400e9e48-28eb-11e7-86db-87540c7a327f.png">

**Comment by indiamindwave24** [comment]
Looks great!

**Comment by MollieCourtenay** [comment]
The padding feels quite tight on smaller screens especially where the pink bits are - @indiamindwave24 what do you think?

![img_2339](https://cloud.githubusercontent.com/assets/25012688/25698849/8a1bd788-30b8-11e7-9bf4-865c761bcb37.PNG)

**Comment by indiamindwave24** [comment]
Agreed: I have mocked up new mobile view of this - what do you think @MollieCourtenay does this solves it as the icons help break up the page? https://github.com/healthlocker/healthlocker/issues/541

Although, happy to increase padding as it is quite tight

**Comment by MollieCourtenay** [comment]
Ah yes. More padding would be good I think. I've added a new comment on that other issue when we get to it. It wasn't in sprint 11 though so no rush.

**Comment by iteles** [comment]
@MollieCourtenay Can we threfore close this issue in favour of #541?
