### ISSUE TITLE
Tip page: add category links at the bottom and button to goals

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#482]
As a user at the bottom of the Tips page https://www.healthlocker.uk/tips?tag=Tip, I am given more options, so that I stay engaged.

+ [x]  Add 'Explore more tips:' and links to 5 #categories

+  [x] add a good amount of space between the two offers

+ [x] Add a link [Create a goal](https://www.healthlocker.uk/goal/new) for yourself based on one of the 5 ways to wellbeing. (if the user is not logged in, take them to log in page)

![img_2297](https://cloud.githubusercontent.com/assets/25012688/25280291/5897299a-26a1-11e7-9962-5547042c61d9.JPG)

**Comment by indiamindwave24** [comment]
👍
