### ISSUE TITLE
Tips: category pages

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#483]
As a user who has clicked on a #category link, I am taken to a new page, that introduces the category, and lists all the tips for that category underneath.

+ [x]  Add a link Create a goal for yourself based on one of the 5 ways to wellbeing. (if the user is not logged in, take them to log in page) (T1h)

+ [x] the same category title, intro paragraph and icon from the homepage are displayed at the top of the page. (T1h)

![tips_filtered_by_hashtag](https://cloud.githubusercontent.com/assets/25007700/25192199/32cd2318-252a-11e7-86ed-4f595f003cdb.png)

![img_2297](https://cloud.githubusercontent.com/assets/25012688/25280291/5897299a-26a1-11e7-9962-5547042c61d9.JPG)

**Comment by indiamindwave24** [comment]
@Cleop 
- [ ] Hashtags on these pages should be all blue
- [ ] The category icon should appear on the top left of tip box, as in the homepage
- [ ] Tip box should be the same as on homepage tip boxes

**Comment by MollieCourtenay** [comment]
lovely
