### ISSUE TITLE
Stories: display the first 50 words

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#486]
+ [x] As a user, I can see the story title and first paragraph, then the Read this story link.

**Comment by MollieCourtenay** [comment]
@iteles hello - why has this been assigned - i'm pretty sure it has not  been worked on.

https://www.healthlocker.uk/posts

When you see here - the stories show different amount of words in each listing.

**Comment by iteles** [comment]
Ah, you're right! My apologies, I went off the title and missed the detail here.

**Comment by MollieCourtenay** [comment]
@RobStallion  some seems to be 42 or 43 words and only a couple closer to 50. (including the title)
It is better as words aren't cut off - but they still do look fairly uneven?

https://www.healthlocker.uk/posts

**Comment by RobStallion** [comment]
Hey @MollieCourtenay. Could you please update the acceptance criteria to say that you wanted the header and the first paragraph?

**Comment by MollieCourtenay** [comment]
@RobStallion  @iteles  
At the moment this is only showing the title and no paragraph at all.
