### ISSUE TITLE
Styling of: Add new coping strategy page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#488]
+ [x] mimic the styling of the add new goals page.
![edit_goal](https://cloud.githubusercontent.com/assets/25007700/25180130/b8ff3adc-2504-11e7-897b-199d60cc8fb6.png)

**Comment by iteles** [comment]
+ [ ] Change title
+ [ ] Left align text

**Comment by katbow** [comment]
from @indiamindwave24 in #551:

As a user, I should see the coping strategies formatted similar to the rest of the site.

- [ ] Title 'Edit coping strategy' should be dark blue, not grey
- [ ] Text in text boxes should be correct font
- [ ] Subtitles (eg. Note down an action you can take to stay well.) should be left aligned
- [ ] All description text should be left aligned
- [ ] Padding should be consistent with rest of site (eg. width of text box)

**Comment by MollieCourtenay** [comment]
looks good.

@katbow on mobile the content box is quite small. only shows 2 lines and the tops of the letters of the third line.
Can you please increase the default depth of the content box, as when adding new and viewing it feels too cramped.

**Comment by MollieCourtenay** [comment]
thanks!
