### ISSUE TITLE
Styling of: view coping strategy page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#489]
+ [x] mimic styling of new view goal page 

![view_goal](https://cloud.githubusercontent.com/assets/25007700/25180132/b907f712-2504-11e7-97a9-10a689ee3910.png)

**Comment by indiamindwave24** [comment]
@katbow If the goal/coping strategy has been marked as important, this should also show on this page (below the check boxes)

[left aligned]
marked as important *(star icon)

**Comment by katbow** [comment]
@indiamindwave24 coping strategies don't have this functionality - it was only requested for goals.

**Comment by indiamindwave24** [comment]
Apologies - yes this is complete :)
