### ISSUE TITLE
Care team: SU send message to SLaM care team.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#49]
As a SLaM service user, I can choose to send messages, (thoughts, observations, reflections) to my care team.

## Acceptance Criteria

+ [x] As a user, who has clicked on Care team in the burger menu, I can write and send a message to that care team. Max characters 550.
+ [x] As a user, who has just sent a message, I see it displayed at the **bottom** of my message feed.

<img width="107" alt="write message" src="https://cloud.githubusercontent.com/assets/25012688/23862665/87f9f74a-0805-11e7-9095-9829da0d00ea.png">

## Content

**Write a message to your care team.**
[TEXT BOX]
Messages should not be used in emergency situations. If you need urgent help or advice, go to [Get support](https://www.healthlocker.uk/support). Your message will be sent to your care team. Do not expect an immediate response. 

Send

Covered in other issues: + [ ] As a user, if I click on the Get support link within the disclaimer text, I am taken to Get support page within same browser tab.
  + [ ] As a user I am offered reassurance about when and who will read my message.
#587

**Comment by MollieCourtenay** [comment]
MURAT:
Can a disclaimer be added to free text boxes (when the message is sent) to ensure that the user is aware that HL should not be used for emergency purposes and point the user to Get support page.

**Comment by katbow** [comment]
@MollieCourtenay I'm going to split this into 2 issues - one for the carer being able to send a message to the care team of the person they support & one for the service user to send a message to their care team.
