### ISSUE TITLE
Goals: view goal styling

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#490]
+ [x] style as per visual below 
+ [x] remove button to delete ( user can only delete from within edit goal)
+ [x]  'created on' now sits below the goal card
+ [x] if a goal is not marked as important - dont show option to makr as important in view goal ( user can only mark as important from within edit goal)

+ [x] best to keep Back to toolkit link until #466 is complete.

![view_goal](https://cloud.githubusercontent.com/assets/25007700/25180132/b907f712-2504-11e7-97a9-10a689ee3910.png)

**Comment by katbow** [comment]
@indiamindwave24 I just realised this new styling has no option to delete the goal. Where should this go?

**Comment by indiamindwave24** [comment]
@katbow deleting a goal should sit within the edit area as an 
- underlined link
- right aligned
- in line (if possible, if not above 'what do you want to achieve)

**Comment by katyedwards** [comment]
Closing this issue as the original requirements have been completed aside from the 'delete' button which has been added as a new issue.
