### ISSUE TITLE
Goals: edit goal styling

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#491]
+ [x] style as per rep
+ [x] When editing a goal that is **not** marked important, I see an empty state (outlined) icon and 'Mark as important' statement.
+ [x] When editing a goal that is marked important, I see a positive state icon (colour filled)  and 'Unmark as important' statement.
![edit_goal](https://cloud.githubusercontent.com/assets/25007700/25180130/b8ff3adc-2504-11e7-897b-199d60cc8fb6.png)

**Comment by Cleop** [comment]
(I've not finished the positioning yet)

@indiamindwave24 - the unselected star icon doesn't seem to be as thick as the version Mollie showed, is this what you had envisaged?

<img src="https://cloud.githubusercontent.com/assets/16775804/25433133/43344f74-2a7f-11e7-8452-87018e2cb564.png" width="200px" />

Whereas Mollie showed this: 
<img src="https://cloud.githubusercontent.com/assets/16775804/25433153/59e5f646-2a7f-11e7-89f5-3eeb1392421f.png" width="60px" />

Do you think this will be visible enough?

**Comment by indiamindwave24** [comment]
[stars.zip](https://github.com/healthlocker/healthlocker/files/958801/stars.zip)
Is this any better? If not, do feel free to go into the SVG file and edit the line thickness

**Comment by Cleop** [comment]
- At the moment 'mark as important' does not change to 'unmark as important' when star is filled.

**Comment by indiamindwave24** [comment]
@Cleop As discussed yesterday, the outline on the star is too thin - Shall I remake the SVG or can this be done at your end? Or is the one I see on the site not the most up-to-date?
<img width="657" alt="screen shot 2017-04-27 at 11 50 18 am" src="https://cloud.githubusercontent.com/assets/25007700/25480216/c207310c-2b3f-11e7-8048-b1bf134bf419.png">

**Comment by Cleop** [comment]
@indiamindwave24 the version you can see is the revised svg you sent across. It would be great if you could send us a thicker version!

**Comment by katyedwards** [comment]
@cleop Yes, please go ahead as you suggest with 'Star as Important'

**Comment by indiamindwave24** [comment]
[star_unselected_01-42.svg.zip](https://github.com/healthlocker/healthlocker/files/961726/star_unselected_01-42.svg.zip)
@Cleop

**Comment by Cleop** [comment]
New version: <img src="https://cloud.githubusercontent.com/assets/16775804/25490299/55b6d1fe-2b64-11e7-94fa-4effbce0b266.png" width="200px"/>

**Comment by katyedwards** [comment]
Done - thanks!
