### ISSUE TITLE
goals: view list styling

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#492]
+ [x] please style as per rep

![goals_overview](https://cloud.githubusercontent.com/assets/25007700/25180131/b9002460-2504-11e7-83d0-daae76937320.png)

**Comment by katbow** [comment]
@indiamindwave24 the estimate here is just for the styling of the goals themselves & removing the back to toolkit link.

Changing the header title is a wider site issue so would be done separately (and would take more time).

**Comment by indiamindwave24** [comment]
Yay! :1st_place_medal:
