### ISSUE TITLE
Story styling on homepage

### ISSUE THREAD

**Issue by indiamindwave24** [healthlocker/healthlocker#506]
Stories should be styled as in this image:
<img width="365" alt="screen shot 2017-04-26 at 11 07 52" src="https://cloud.githubusercontent.com/assets/25007700/25429360/a15f650c-2a70-11e7-983a-dbf93242d955.png">

- [x] Title: Centred, 20px
- [x] Bookmark icon left aligned and bottom aligned to image in circle
- [x] Image in circle, centred
- [x] Story title: 16px Bold
- [x] Body text: 16px regular
- [x] Read story link
- [x] See more stories button: Right aligned

**Comment by katbow** [comment]
technical tasks: 
- [ ] Add edit functionality to posts T1h
- [ ] Only admins can access edit functionality T2h
    - [ ] Use admin role, add manually to chosen users on site
- [ ] Bookmark icon & functionality T1h

**Comment by katbow** [comment]
@indiamindwave24 can you upload that image again when you have a moment?

**Comment by indiamindwave24** [comment]
done 👍

**Comment by katbow** [comment]
@indiamindwave24 for the bookmark icon:

I have added it in now, however it is currently positioned at the top left of the story. (this isn't on the main site yet).
This is because the solutions to lower it in line with the image were quite hacky & would not work in situations without an image - > in those cases the bookmark was overlaying the story text.

If there will **always** be an image, it can be added in line with the image. 

I can still play around with it, but it will take up a lot of time to get right for different cases. 

Let me know where you want me to go with this...

**Comment by indiamindwave24** [comment]
Are you able to provide a screenshot? @katbow

**Comment by katbow** [comment]
![image](https://cloud.githubusercontent.com/assets/1287388/25444035/ad5b32ce-2aa1-11e7-8f43-30417cf5a01f.png)

**Comment by katbow** [comment]
here's the problem I described if I move it down (in the one without the image)
![image](https://cloud.githubusercontent.com/assets/1287388/25444145/09e1f866-2aa2-11e7-8756-9695b544bc30.png)

**Comment by indiamindwave24** [comment]
Yes it is okay at the top left 

--- it would be IDEAL if at the top it could align with the image or the padding reduced slightly as it seems to be really floating there but overall much better :)

(like the circular images!)

**Comment by katbow** [comment]
@katyedwards @indiamindwave24 when testing this, if you could please verify that you have the ability to edit posts to look as required, that'd be great!

**Comment by katyedwards** [comment]
Hi @katbow all working great so far, but I was wondering about centering the story titles too and wasn't sure how to do that - @indiamindwave24 what do you think?

**Comment by katbow** [comment]
@katyedwards if you wanted it centred, bold, same size as rest of text you would do:

`<p class="b tc">Title here</p>`

**Comment by katyedwards** [comment]
Will that still be h2 size?

**Comment by katbow** [comment]
That's the same size as the rest of the text, but bold which looks like the requirement for @indiamindwave24's styleguide?

If you would like the h2 size & centred it's similar. It would be:

`<h2 class="tc">Title here</h2>`

**Comment by katyedwards** [comment]
Ahhh ok - when I did the original styling I did ## styling

**Comment by katyedwards** [comment]
I'm happy then - @indiamindwave24 do you want to check and close this one as it's styling...

**Comment by indiamindwave24** [comment]
It doesn't seem to be the same size as title '5 ways to wellbeing' @katyedwards ? but it can be left aligned :D

**Comment by katyedwards** [comment]
All good - will edit styling etc if/as needed
