### ISSUE TITLE
Explore more tips section

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#508]
+ [ ]  Add 'Explore more tips:' and links to 5 #categories

+ [ ]  add a good amount of space between the two offers at the bottom of the page (explore and goal)

**Comment by katbow** [comment]
@indiamindwave24 can you verify priority label & position in sprint for these ones?

**Comment by Cleop** [comment]
Almost a replica of #482?

**Comment by katbow** [comment]
Yeah my bad. We can close this as duplicate & move that into the sprint in place
