### ISSUE TITLE
Phone number - do we want to bring in phone number from ePJS?

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#513]
Phone number is currently option in Healthlocker so we have a couple open questions on this:
+ Do we want to bring in phone number data from ePJS?
  + If so and it is different from the phone number data in HL, which one takes precedence and is seen as the correct one?

**Comment by katyedwards** [comment]
Can we pull phone number through from ePJS, but if they don't match then give the one they have entered into HL precedence in case they have updated their phone number and not told their care team yet.

This gives Clinicians the option to view both (1 in ePJS and 1 in HL) and discuss with the SU which to use.

Also won't piss off the SU if they have got a new number which they enter into HL, then connect with ePJS which overrides it with their old number!

**Comment by MollieCourtenay** [comment]
@iteles if / when the mini API that advanced have build for epjs is implemented at SLaM we could have an opportunity to update a users phone number / address / email from HL into epjs.
As this is still unlikely to happen anytime soon - lets, as Katy said, stick with he number the user enters themselves and leave at that.
There is an issue about highlighting IF the number is different from HL to EPJs - which could prompt the Care team to update ePJS.  https://github.com/healthlocker/healthlocker/issues/57

**Comment by katbow** [comment]
@iteles is this good to close now?

**Comment by iteles** [comment]
Thanks for the answers @MollieCourtenay @katyedwards
