### ISSUE TITLE
Clinician SU view | Details & Contacts

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#514]
As a clinician, I want to see the contact details for the service users in my caseload so that I can contact them if I wish.

_**NB.** For now, this will include the details below until the issue has been fleshed out - I suggest this is done in a separate, add-on issue linked to the epic #385._

+  [x] Forename + Surname (from fake ePJS, name optional in HL)
+  [x] DOB (from fake ePJS)
+  [x] NHS number (from fake ePJS)
+  [x] Email (HL)
+  [x] Address ( from fake ePJS)
+  [x] Phone number (fake ePJS, optional in HL) see #513

**Comment by katyedwards** [comment]
All working thanks!
