### ISSUE TITLE
Clinician SU view | Trackers

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#517]
As a clinician, I want to see the tracker information input by the service users in my caseload within HL so I can see how they have been doing and contact them if necessary.

Format of this view TBD.

NB. At the time of this issue creation, only the sleep tracker exists.

**Comment by katbow** [comment]
@iteles this is done. Should @MollieCourtenay be assigned to test or is it yours to close?

**Comment by iteles** [comment]
Looks good to be! There are also other issues tracking this and it mimics the SU view so covered there 👍
