### ISSUE TITLE
Seed sleep data for live HL

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#526]
@katbow As discussed, could you please add seed sleep data to the production site for our Evan user?

3 weeks of data (at least one week with some no-data days) would be perfect 👍

**Comment by iteles** [comment]
@katbow Doesn't look like this is showing in live for me yet!

**Comment by katbow** [comment]
I realised I hadn't run the seed yet for it 😬 . should be good now for Evan.

**Comment by katyedwards** [comment]
Yes- all displaying nicely thanks!
