### ISSUE TITLE
Carers | NHS number tooltip redirects to the wrong place

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#532]
Currently the [tooltip against the NHS number](https://www.healthlocker.uk/pages/nhs_help) in the ['Carer Connect' screen](https://www.healthlocker.uk/slam/new) screen redirects to the 'Connect my SLaM account screen' when closed instead of back to the Connect screen.

Placing a high priority on this as it's extremely misleading and very likely to happen!

**Comment by katbow** [comment]
This should be good now @iteles. Can you check it out?
