### ISSUE TITLE
Change images to pngs to decrease loading time

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#539]
links to #474 

png icons here 
[PNG_Icons.zip](https://github.com/healthlocker/healthlocker/files/964622/PNG_Icons.1.zip)

see #503

**Comment by indiamindwave24** [comment]
![bookmark_selected](https://cloud.githubusercontent.com/assets/25007700/25614556/5d3e2f5c-2f2a-11e7-8d00-f2f09eb907b1.png)
![bookmark_unselected](https://cloud.githubusercontent.com/assets/25007700/25614557/5d417932-2f2a-11e7-8bd2-4bcd001997ee.png)
![star_selected](https://cloud.githubusercontent.com/assets/25007700/25614558/5d43947e-2f2a-11e7-9d60-5e7e8bbbfce1.png)
![star_unselected](https://cloud.githubusercontent.com/assets/25007700/25614559/5d495fd0-2f2a-11e7-8fd9-1659e761904e.png)

**Comment by katbow** [comment]
@MollieCourtenay for this one it should all look the same, but the images should hopefully be loading faster now 🎉

**Comment by indiamindwave24** [comment]
I'm on a fast internet connection today but everything is loading super quick for me! :)

**Comment by MollieCourtenay** [comment]
nice
