### ISSUE TITLE
Inputting users

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#54]
@tonydaly wanted to check how we should input users for the end of this sprint. Since we weren't planning on having a sign up page, would we just add them via command line or is there a different way? 

It wouldn't be too many people for me to add - only those at MWV who will be adding content - so I thought maybe that would be the quickest way to hit the ground running.

**Comment by tonydaly** [comment]
Seeds would probably be the best approach: http://www.phoenixframework.org/docs/seeding-data

Thanks,

Tony

**Comment by katbow** [comment]
Sweet, thanks!

**Comment by tonydaly** [comment]
@katbow actually...maybe this isn't the right approach as then those usernames and passwords will then be shown in the repo.

**Comment by tonydaly** [comment]
TBH it's probably easiest just to add them in the console.
