### ISSUE TITLE
Toolkit Button Styling

### ISSUE THREAD

**Issue by indiamindwave24** [healthlocker/healthlocker#543]
As a user I would like the buttons on the toolkit page to have the same styling as the rest of the site

**Comment by MollieCourtenay** [comment]
Hey @katbow any chance you can 
+ [ ] align the top of the buttons?
<img width="370" alt="screen shot 2017-05-26 at 15 30 34" src="https://cloud.githubusercontent.com/assets/25012688/26498857/65cff9fa-4228-11e7-923e-57c8d63fa5d4.png">
<img width="381" alt="screen shot 2017-05-26 at 15 30 30" src="https://cloud.githubusercontent.com/assets/25012688/26498858/65d64a12-4228-11e7-96d0-87ee2e40b07e.png">

**Comment by MollieCourtenay** [comment]
I've moved this in to sprint 12 as it has been being worked on without being in a milestone - I don't want it to get lost...
