### ISSUE TITLE
Text Box Font - Sleep, Problem & Diary

### ISSUE THREAD

**Issue by indiamindwave24** [healthlocker/healthlocker#544]
As a user, I would like the font in the text input box to be the Century Gothic, as on the rest of the site. 
<img width="851" alt="screen shot 2017-05-02 at 12 30 51 pm" src="https://cloud.githubusercontent.com/assets/25007700/25616184/34cc36d2-2f33-11e7-932e-a03787da4b59.png">

**This needs to be applied for:**

- [x] Sleep Tracker - Notes Box
- [x] Problem Tracker - Notes Box
- [x] Diary Entry Box

**Comment by katyedwards** [comment]
Looks good - thanks!
