### ISSUE TITLE
Reformat NHS number

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#545]
NHS number is all digits in the form XXX XXX XXXX.

Need to remove spaces when input/have it input in particular format.

**Comment by MollieCourtenay** [comment]
@katbow how can I test this?
Have you reassigned Evans NHS no?

**Comment by katbow** [comment]
yup, if you log in as robert_macmurray@nhs.co.uk -> go to caseload -> click on a connected user, then their NHS number should be all digits as above.

**Comment by MollieCourtenay** [comment]
Ah ok, yes i see: 
NHS Number:
824 338 6647

Has this also been added to the user interface for when a SU / Carer connects and has to enter NHS number?

**Comment by MollieCourtenay** [comment]
I connected with Evans care team using his new NHS number, and the same for Lisa on a different account and it worked.

**Comment by katbow** [comment]
Great! I thought I had replied to this hours ago but I had just left it open without commenting, sorry for that. Thanks!
