### ISSUE TITLE
Delete goals

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#547]
from @indiamindwave24 in #490 

deleting a goal should sit within the edit area as an 
- underlined link
- right aligned
- Above 'what do you want to achieve'

@katbow have edited this to say above 'what....' so it works on all screen sizes.
and created a new issue for delete coping strategy.

How should this look for coping strategies? #554

**Comment by katbow** [comment]
time estimate is for goals only right now since that part is lacking information - probably best to have coping strategies in different issue.

**Comment by katbow** [comment]
@indiamindwave24 I've added this in as per the design in #211

**Comment by MollieCourtenay** [comment]
@katbow  Can there be a bit more space between Save and Delete - it is a bit close for thumbs on mobile.

**Comment by MollieCourtenay** [comment]
@katbow getting internal server error for goals on my iPhone 5s. Safari. 

Worked fine just 20 mins ago on a SLaM computer.  I.E.

**Comment by katbow** [comment]
@MollieCourtenay I fixed it now - it was because of goals that were previously marked as achieved without an achieved_at date. It probably worked at first because it was a different user logged in without any achieved goals. I reset the completion for goals that did not have an achieved_at date 👍

**Comment by MollieCourtenay** [comment]
sweet
