### ISSUE TITLE
Review current analytics

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#550]
Review with Mollie & Katy to go over what we already have, anything that is missing and we may need. (for Tuesday)

**Comment by iteles** [comment]
@MollieCourtenay One to pick up again in sprint 12 :)

**Comment by iteles** [comment]
After catching up with @MollieCourtenay and @katyedwards on 23rd May, it appears that contrary to what we had originally been told, SLaM cannot yet provide us with access to the paid for version of Mixpanel this week. Closing this issue for now, to be reopened when this is feasible.
