### ISSUE TITLE
Delete link within Edit coping strategy

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#554]
'Delete' link should sit within the edit coping strategy page as an 
- underlined link
- right aligned
- above 'Note down an action you can take to stay well.'

**Comment by katbow** [comment]
@MollieCourtenay should this now look like how it was outlined for goals?
On the edit screen, underneath Save, with the same margins?

**Comment by MollieCourtenay** [comment]
Yes please.
