### ISSUE TITLE
As a user I am invited to sign up for C4C as part of the sign up journey

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#566]
### Acceptance criteria
+ [x] As a user, within the connect to SLaM form (for a service user only not a carer), I am invited to join C4C. 

+ [x] I can decide whether to tick the join C4C box. Then Click save. 

+ [x] When a user ticks this new C4C box, it does not actually do / influence anything, but save the answer (yes or blank) the database.

## Content 
Are you interested in being contacted if you are eligible to take part in research that contributes to better health for people with mental health related problems? If so you can sign up to a register called [Consent for Contact (C4C)](http://www.slam.nhs.uk/research/patient-involvement/current-opportunities/consent-for-contact). All researchers work for or are approved by South London and Maudsley NHS Foundation Trust.

[  ]  I agree to join the [C4C register](http://www.slam.nhs.uk/research/patient-involvement/current-opportunities/consent-for-contact)

## Extension
+ [x] As a SLaM connected user, in consent page within Account. IF i have ticked to join C4C I see that displayed. [ x ]  I agree to join the [C4C register](http://www.slam.nhs.uk/research/patient-involvement/current-opportunities/consent-for-contact)
+ [x] IF, I have not ticked the box, I am given the option to, tick the box and update. Same content as with form: 
Are you interested in being contacted if you are eligible to take part in research that contributes to better health for people with mental health related problems? If so you can sign up to a register called [Consent for Contact (C4C)](http://www.slam.nhs.uk/research/patient-involvement/current-opportunities/consent-for-contact). All researchers work for or are approved by South London and Maudsley NHS Foundation Trust.

[  ]  I agree to join the [C4C register](http://www.slam.nhs.uk/research/patient-involvement/current-opportunities/consent-for-contact)

**Please note: **
The idea is not to build a C4C feature but to hint at the possibilities.

So that, when EPJS is ready to accept info via an API, _OR_ SLaM can agree another way of getting the C4C choice where it needs to be, we already have he consent from all those users that have already signed up to HL. 

Ref: #120 #129

**Comment by katbow** [comment]
@katyedwards is this option **only** available in the connect to slam form? If a user connects to slam, should they be allowed to update this in the profile? 

Timing this one out..

**Comment by katyedwards** [comment]
If it can be in both, that would be ideal (esp as we already have the consent tab in account), but if time doesn't allow - 1 is better than nothing!

**Comment by MollieCourtenay** [comment]
@katbow, I'm imagining people will ignore if the only way to do this is in consent in account.
So having it in the form is more likely to be demo'd and for people to actually do.

**Comment by MollieCourtenay** [comment]
Is that as its quicker to do it in Consent?

In terms of demo-ing and people doing it - i'd prefer in the form.

But as time is super tight - then which ever is quicker..? :)

**Comment by katbow** [comment]
@MollieCourtenay it's in both places now - when connecting to slam, and if someone is connected to slam then it shows up in consent part of the account.

**Comment by MollieCourtenay** [comment]
<img width="797" alt="screen shot 2017-05-30 at 10 07 50" src="https://cloud.githubusercontent.com/assets/25012688/26576211/eff8c95a-451f-11e7-815d-b0e589e0460e.png">
