### ISSUE TITLE
Get support: copy changes and additions

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#572]
https://docs.google.com/document/d/1qsvWbpy-9q9pUmu94cDpWSLvQKotiTTmXhzonpWTHis/edit

+ [x] Edit page title to 'Get support'
+ [x] remove word 'urgent' - to read 'If you need help you have lots of options:'
+ [x] remove word 'phone'  and add 'services'- to read 'Free 24-hour support services'
+ [x] add Local support subtitle
+ [x] edit **South London and Maudsley NHS Foundation Trust mental health support line** 
+ [x] add **Solidarity in a crisis**
+ [x] add National support subtitle
+ [x] add: **Childline** 
+ [x] add: **FRANK** 
+ [x] edit NHS 111 line
+ [x] remove colons
_________

+ [x] add grey box for: **For family, friends and carers:**
+ [x] add centred bold title
+ [x] add icon (hand and flower)
+ [x] add Local support subtitle
+ [x] add National support subtitle
+ [x] add services detail: name in bold and linked to URL where there is a link in the doc, phone numbers as call to links, emails as mail to: links. 
_________

+ [x] add grey box for: **More information and advice:**
+ [x] add centred bold title
+ [x] add icon (shield)
+ [x] add Clinical information and advice: subtitle
+ [x] add National mental health charities: subtitle
+ [x] add Specialist: subtitle
+ [x] add services detail: name in bold and linked to URL where there is a link in the doc, phone numbers as call to links, emails as mail to: links. 
_________

+ [x] At the bottom add, [Suggest an addition or amendment to this page](https://healthlocker.uk/feedback).

**Comment by indiamindwave24** [comment]
![hand_plant](https://cloud.githubusercontent.com/assets/25007700/26005852/43dc8256-3732-11e7-8947-bc88c1496ce7.png)

**Comment by indiamindwave24** [comment]
Other places to find quality health information and advice icon
![quality-27](https://cloud.githubusercontent.com/assets/25007700/26209382/8cfda7ba-3be4-11e7-8534-bdf7c8749f6d.png)

**Comment by Cleop** [comment]
@MollieCourtenay - where you've said subtitle, I'm doing them smaller than the 'Free 24-hour support services' title to look like this:
![image](https://cloud.githubusercontent.com/assets/16775804/26489960/60e93798-4201-11e7-98ac-5c5995e77743.png)
Please let me know if by subtitle you wanted them the same size as the 'Free 24hour' title

**Comment by Cleop** [comment]
@MollieCourtenay - would you like the title centred? None of the other subtitles are centred e.g. Free 24-hour support services isn't. Are they both meant to be centred or neither of them?
![image](https://cloud.githubusercontent.com/assets/16775804/26491569/11e3b1da-4208-11e7-8511-cb656d529289.png)

**Comment by MollieCourtenay** [comment]
@Cleop yep, I want Free 24 hour support centred as well please so that
Free 24-hour support services
For family, friends and carers
More information and advice

Are all centred and bold. (note no colons, meant to remove those in the ACs)

The subtitles e.g. Local services are to be smaller like your example you sent earlier.

**Comment by MollieCourtenay** [comment]
A couple of things that are different to the Google doc - sorry if not totally clear in the ACs!

+ [ ] top subtitle should read: If you need help or advice you have lots of options: 
+ [ ] add a last point at the top of the page ' there are various local and national support services you can contact (see below).'
+ [ ] remove the fullstops from the end of each of the sections in grey boxes.

+  [ ] add a bit of extra space between the end of the subsection and the next subtitle.

+ [ ]  Suggest an addition or amendment to this page. - this shouldn't be bold.
+ [ ] Also remove the extra 'e' from amendment.

**Comment by katbow** [comment]
>make the mobile number here link of the right colour

For this one, we kept it the same colour as the rest of the text since it isn't a link like the other numbers. There's not a way to make a `text_to` link in the same way you would do for calling/emailing.

We thought changing the colour when it's not a link might be confusing. Thoughts?

**Comment by MollieCourtenay** [comment]
@katbow on mobile it makes it a link automatically. so it goes dark blue and therefore makes it self a tel link anyway.
If you make it a call to link - on my iphone it gives me the option to message or call.

**Comment by katbow** [comment]
> Make these blue please: Advice from a pharmacist. / Self referral drug and alcohol services / National mental health charities

I didn't change the last one because it's a subtitle - it should be more obvious now with the extra spacing (once it's merged in I mean 🙂 )
