### ISSUE TITLE
Stack images in About for Mobile

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#576]
+ [x ] larger images in the same place on mobile#439

**Comment by katbow** [comment]
Here's an example of larger images in the same place on mobile. Wanted to post it for you so you could compare 🙂 

![image](https://cloud.githubusercontent.com/assets/1287388/25855651/b73255fa-34cb-11e7-8278-5f5d6606fe01.png)

**Comment by MollieCourtenay** [comment]
@katbow I'd be happy to run with them that size for mobile if you can push that would be lovely.

**Comment by MollieCourtenay** [comment]
@iteles this awaiting review has been on for a while too. Where are we with this?

**Comment by RobStallion** [comment]
This was not styled based off of what is in the AC. It is styled based on the image @katbow put above. 

@MollieCourtenay Would you like to update the AC to this so that we can close the issue?
