### ISSUE TITLE
Update name to first & last name in sign up

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#583]
for #569 
We need to match the model we will be using from ePJS so that we can update the HL info, with info entered when connecting to SLaM.

Question about this for @MollieCourtenay:

Because we need to update to first name & last name split up and would be getting rid of the single name field, what do we need to do with the name data that is already on HL?

Since it is optional and mainly test users right now (?), the quickest option is to simply remove it & the data that is there with it. Users would be able to update their name in account still (as first & last name), and we can have it update when a user connects to slam as SU or carer which is the most important case for having the full name.

- [x]  Change sign up form to accept first & last name
- [x]  Update name anywhere it's displayed/used to first name + last name (outlined in #582)
- [x]  Delete name field from db

**Comment by MollieCourtenay** [comment]
@katbow that makes sense to me. i'm not too worried about loosing existing names entered.

**Comment by katbow** [comment]
complete, refer to user story in #582
