### ISSUE TITLE
Access SLaM's crisis line

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#6]
As a person using HL
I want to be able to get immediate support from SLaM's crisis line
so that I can get help quickly & easily when I need it urgently.

This should be a section that is linked on every page of the application. The section should be linked in a place on the page that is prominent and easy to find for me.

**Comment by nelsonic** [comment]
@katbow thank you for creating this issue/story from the original HL feature priority list. 👍 
@MollieCourtenay we need this to be fleshed out with additional detail specifically:
+ any UI/UX or Wireframes/Designs that have been worked on and are considered "MVP-able"
+ **_acceptance_ criteria**
+ details of the SLAM crisis line (_phone number_?)

**Comment by iteles** [comment]
This is what we have from the very first wireframes on this:
![slam-crisis-line-wireframes](https://cloud.githubusercontent.com/assets/4185328/22332662/edf03d94-e3c9-11e6-9077-860a1a45a1d3.jpg)

**Comment by LauraNevo** [comment]
Below is the latest and most minimal version of the Get Support page. We added tech support (suggested by Dwyl) in case there's a problem with the beta or the site. Not sure where this will go though.

![get support mvp](https://cloud.githubusercontent.com/assets/3858131/22342197/6c8ed144-e3eb-11e6-831c-62fcbc077937.png)



And the way to access it in the drawer menu (and not in the navbar anymore - might need this space in the future for account or even later notifications):

![get support mvp menu](https://cloud.githubusercontent.com/assets/3858131/22342305/d4deed10-e3eb-11e6-89f6-3d635995c6ed.png)

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria

+ [ ] Get support button to be visible and easily accessed when a user lands on HL. (a contrasting colour / easy navigation)

+ [ ] if a user clicks the get support button, the Get support info appears (new screen / reveal / pop up?) This includes this one #6 SLaM crisis line (top) and #11 What to do in a crisis (underneath crisis line)

+ [ ] on mobile phones -  the slam crisis phone number to becomes a click to call link (not sure what the technical term for that is)

**Comment by MollieCourtenay** [comment]
If you need urgent help or advice:
SLaM crisis support
Mental health support line
0800 731 2864

**Comment by katbow** [comment]
> call 999

@LauraNevo @MollieCourtenay in the wireframes this looks like a link - is this supposed to be clickable to dial 999 in the same way as the crisis line?

**Comment by LauraNevo** [comment]
@katbow I should've only underlined 999. Yes it would work in the same way as the crisis line, on mobile phone, it would trigger the phone to ring the number.

Unless we have any reason not to do this? @MollieCourtenay

**Comment by katbow** [comment]
Great, thanks @LauraNevo. I will add it in for now and I can easily remove it if that's not a necessity. I was wondering if it was desirable to have it as a link in case of accidental clicks.

**Comment by MollieCourtenay** [comment]
@katbow yes please clickable 999.
