### ISSUE TITLE
AppSignal Billing

### ISSUE THREAD

**Issue by tonydaly** [healthlocker/healthlocker#601]
We use AppSignal for error notifications and performance monitoring. We're coming to the end of our trial and need to signup to a paid plan: https://appsignal.com/healthlocker/admin/billing. Based on our current usage the recommended plan costs €15 / $19 a month.

**Comment by katyedwards** [comment]
Thanks, will pass info onto Adele to get approval.

**Comment by tonydaly** [comment]
🎵  dramatic music 🎵

![](https://d2ppvlu71ri8gs.cloudfront.net/items/1O2y3v2b411K0t0P0M05/Screen%20Shot%202017-05-12%20at%2016.47.45.png?v=3a85840b)

**Comment by katyedwards** [comment]
Yikes!  It'll take several days at least to get approved by SLaM.  I'm assuming it's a problem to let it lapse for a week?  If so - are you able to pay for 1 month only and invoice us?  Then we'll switch over to the SLaM account as soon as we have it.  Thanks!

**Comment by iteles** [comment]
This is done for one month 👍
