### ISSUE TITLE
No visible Login Button on Chrome iPhone 5s

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#605]
When I go to healthlocker on my Phone, I have the welcome to HL message and sign up button, but no login button visible on the screen.

I've found this annoying for demos so I'm sure other signed up users would - I've been having to go to the menu to get the login button

*if* the issue for rethinking the home page gets prioritised then I guess this'll be dealt with, but putting this here in case we don't get to a full re-think in which case this might be worth a look!

@MollieCourtenay

**Comment by katbow** [comment]
@katyedwards I think the login button is displaying correctly on all devices now. The issue was applying `float:right` to the button, which does some weird things to the height so it was disappearing underneath the footer. That was removed & it was moved to the right in a different manner.

**Comment by katyedwards** [comment]
It still isn't showing up as a button on iPhone, but there also isn't really room for it on the screen so I'll just leave this here in case of a future rethink.

**Comment by MollieCourtenay** [comment]
It's visible when you turn your phone landscape @katyedwards

**Comment by katyedwards** [comment]
Ah ok cool thanks - I'll close this then and we can revisit _if_ there is any other user feedback.
