### ISSUE TITLE
IE testing

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#608]
Test messaging on windows machine

@MollieCourtenay @katyedwards any word on which version of IE is used at SLaM?

**Comment by katyedwards** [comment]
We're waiting for Adele to confirm.

**Comment by katyedwards** [comment]
Adele is checking on this, but in the meantime, I have found a doc from the days of previous devs and we'd said that SLaM use IE11, Edge, Chrome and Firefox, depending which team you're in. 

I can't remember who would have given us this info now, but is that any help or should we wait for Adele?

**Comment by katyedwards** [comment]
@katbow Adele has confirmed - IE11

**Comment by katbow** [comment]
@katyedwards great, thanks! We checked it out on IE11 & all of the messaging ran as expected (yay!)  👍 .
