### ISSUE TITLE
Clinician view: sleep graph

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#612]
+ [x] when I click Tracking, I can see the latest sleep tracking data for the service user #622 menu

**Comment by MollieCourtenay** [comment]
@RobStallion 
Can you ensure the previous next buttons are also pulled over to clinician view. What I saw yesterday they weren't there.

**Comment by RobStallion** [comment]
Hey @MollieCourtenay. They are in the current version now 👍

**Comment by iteles** [comment]
@molliecourtenay The feature wasn't quite finished when you took a look which is why we hadn't moved it to please-test yet :blush:
