### ISSUE TITLE
sign up: screen 3 copy change

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#618]
+ [x] remove top line about being voluntary
+ [x] edit last point, 'I will respect other users, including NHS stuff, at all times.
+ [x] full stop on last point

<img width="765" alt="screen shot 2017-05-12 at 10 28 01" src="https://cloud.githubusercontent.com/assets/25012688/25993135/f359831e-3700-11e7-9bfb-15b43999fdb4.png">

**Comment by katyedwards** [comment]
@Cleop some more copy tweaks to be made... will confirm Thursday once Comms have had their input!

**Comment by iteles** [comment]
@katyedwards Can we please add the new copy changes as a separate issue (as this is new scope) and determine whether the original issue can be closed?

**Comment by katyedwards** [comment]
Yep, sorry will do  @MollieCourtenay back to you to test this one then!
