### ISSUE TITLE
SLaM logo placement

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#619]
+ [x] As a user on the landing page for a logged out user, I see the SLaM logo at the top of the page, left aligned.

We're just waiting now on the right logo.

<img width="797" alt="hl and logo mock up" src="https://cloud.githubusercontent.com/assets/25012688/26458020/0b8fcd80-416a-11e7-8de0-8ec47df7c16e.png">

**Comment by katyedwards** [comment]
Those were the main two - or possibly sitting smaller and just above the footer in the centre?

**Comment by katyedwards** [comment]
Depending what India has given her to do - this could be an easy thing for Caroline to have a look at.

**Comment by katyedwards** [comment]
The other thing suggested was a white footer not blue - just remembered!  Although this wasn't our preferred option.

**Comment by Cleop** [comment]
@MollieCourtenay @katyedwards 

Which of these would you like me to implement? or is @indiamindwave24 going to show designs to them to get their approval before you want me to make any changes?

**Comment by katyedwards** [comment]
Hi @Cleop The SLaM Comms team have got involved and we may not have much of a choice!  We have a meeting with them on Thursday and will be able to update you after that - sorry for the delay!

**Comment by Cleop** [comment]
Thanks for the update @katyedwards

**Comment by indiamindwave24** [comment]
@Cleop 

https://www.england.nhs.uk/nhsidentity/identity-guidelines/organisational-logos/

<img width="797" alt="hl and logo mock up" src="https://cloud.githubusercontent.com/assets/25007700/26486783/88379522-41f4-11e7-965a-cc6867a12c12.png">

![slam_logo_01-01-01](https://cloud.githubusercontent.com/assets/25007700/26486789/8d1cefa6-41f4-11e7-9010-de94e9e083b2.png)

**Comment by MollieCourtenay** [comment]
https://www.england.nhs.uk/nhsidentity/identity-examples-categories/websites/

**Comment by MollieCourtenay** [comment]
![slam_logo_with_padding](https://cloud.githubusercontent.com/assets/25012688/26491325/1ae89256-4207-11e7-9640-743a18d47efb.png)

@Cleop @iteles

**Comment by katbow** [comment]
@MollieCourtenay thoughts on the beta banner above the nhs logo?

![image](https://cloud.githubusercontent.com/assets/1287388/26492591/d4026ea6-420c-11e7-97b8-6d620453f8d9.png)

**Comment by MollieCourtenay** [comment]
@katbow are you able to show me what it looks like on mobile?

**Comment by katbow** [comment]
![image](https://cloud.githubusercontent.com/assets/1287388/26492840/2e502d34-420e-11e7-9aa8-bf280e54cf39.png)

I wasn't sure as well if you'd like the logo bigger on mobile. The bottom text is much smaller than the rest so it's more difficult to read 😕

**Comment by MollieCourtenay** [comment]
guidance on sizing: @katbow 
<img width="696" alt="screen shot 2017-05-26 at 12 27 56" src="https://cloud.githubusercontent.com/assets/25012688/26492953/d1d5a0c4-420e-11e7-8f8a-47721eddc5ea.png">

**Comment by katbow** [comment]
okay thanks for that. besides that part, what should we do with the banner then?

**Comment by MollieCourtenay** [comment]
I've asked opinions (can we get away with this)
Are you able to pause on this till I get some feedback?

**Comment by katbow** [comment]
Yup no problem. It will be a quick change to switch from one spot to the other. I have it working now for the different screen sizes & only showing on the home page for logged out users 👍

**Comment by MollieCourtenay** [comment]
So @katbow it would be easy to place above the banner - if we have to?

**Comment by katbow** [comment]
yeah it's just moving one html block above another.

So with the nhs logo at the top it is:

```elixir
    <%= if !@current_user && @conn.request_path == "/" do %>
      <div class="pa1 w-100 w-70-m w-70-l">
        <%= img_tag("/images/nhs-logo.png", class: "w-60 w-40-m w-25-l") %>
      </div>
    <% end %>
    
    <div class="hl-bg-pink pa1">
      <div class="pa1">
        <p class="di b white">Healthlocker is in progress -</p>
        <small>
          <%= link "share feedback and suggestions",
          to: feedback_path(@conn, :index), class: "white" %>
        </small>
      </div>
    </div>
```

and with the beta banner at the top it is:

```elixir
    <div class="hl-bg-pink pa1">
      <div class="pa1">
        <p class="di b white">Healthlocker is in progress -</p>
        <small>
          <%= link "share feedback and suggestions",
          to: feedback_path(@conn, :index), class: "white" %>
        </small>
      </div>
    </div>

    <%= if !@current_user && @conn.request_path == "/" do %>
      <div class="pa1 w-100 w-70-m w-70-l">
        <%= img_tag("/images/nhs-logo.png", class: "w-60 w-40-m w-25-l") %>
      </div>
    <% end %>
```

**Comment by MollieCourtenay** [comment]
Thanks @katbow , the decision was to run with:
Logo
banner
nav.

👍 

It looks a bit small full screen - wen comparing to other sites?
I guess as long as it is 20px high as per guidelines? sorry not sure how to tell.

**Comment by katbow** [comment]
I can't measure it exactly because it's part of a larger image 🙁 . I increased the size now though!
