### ISSUE TITLE
Clinician: new item on navigation 'Tracking'

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#622]
+ [x] add 'Tracking':      Messages / Goals and strategies / Tracking / Details and contacts /

**Comment by RobStallion** [comment]
Morning @MollieCourtenay. Just added 'Tracking' to the navigation for clinicians and thought that I would send you a screen shot of mobile view as the text is starting to get a little squished. I don't know if this will be an issue as the clinician view will be on desktop but just wanted to make you aware.

![image](https://cloud.githubusercontent.com/assets/15571853/26149218/5d2bda64-3af1-11e7-85d4-266d203f9e7f.png)

**Comment by MollieCourtenay** [comment]
@RobStallion
As above, please edit to say: 'Goals and strategies' (remove coping)

Also the order of the menu items doesn't march the requirement above - is this because it is a bigger job?

Yikes this isn't great on smaller screens -  is there a way to fix it in a quick small way for now? reduced type size / stack the menu?

**Comment by MollieCourtenay** [comment]
will close this, I have made a new issue in backlog to look at clinician smaller screen nav - but it was not a requirement for this phase anyway.
