### ISSUE TITLE
Tracking: new item and icon: custom symptom tracker

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#623]
### acceptance criteria
+ [x] As a user in Tracking, I can click on a button called 'Symptom tracker'.

@indiamindwave24 we'll want a new icon here.

**Comment by indiamindwave24** [comment]
![problem_tracker-60](https://cloud.githubusercontent.com/assets/25007700/26209444/b930c81c-3be4-11e7-8548-9fa5626407d5.png)
