### ISSUE TITLE
Tracking:  add new item and icon for daily diary.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#624]
### acceptance criteria
+ [x] As a user in Tracking, I can click on a button called 'Diary'.

@indiamindwave24  can you bring this icon back to life for diary please.

<img width="93" alt="screen shot 2017-05-12 at 11 36 06" src="https://cloud.githubusercontent.com/assets/25012688/25994816/54e36964-3707-11e7-8ca1-6ce7d8ddae75.png">

**Comment by indiamindwave24** [comment]
![daily_diary](https://cloud.githubusercontent.com/assets/25007700/26005638/a8e84a6e-3731-11e7-8a8f-4b642f11042e.png)
