### ISSUE TITLE
Pulling together homepage, login, & content ui branches

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#63]
- Tests
    - [ ] Log in tests: Login controller & auth.ex need testing
    - [ ] homepage: failing test that needs fix by inserting info into test db
    - [ ] Move queries into model](https://blog.drewolson.org/composable-queries-ecto/) to be tested from there: can then test independently each query. 

- Log in/ Log out in Nav
    - [ ] #62 need to check if there is a current user and display log in or log out accordingly

- Styling (Not necessary for merging in other branches but needs doing)
   - [ ] carry on from styling branch

**Comment by katbow** [comment]
I'm going to start with the homepage & update content ui tests today.

I'll move on to tests for login & adding log in and log out to the nav after that's done.

**Comment by nelsonic** [comment]
@katbow sounds like a good _plan_ for today. please estimate required time. thanks! 👍
