### ISSUE TITLE
Azure Subdomain to demo Azure Deployment

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#631]
@iteles can you pair with me tomorrow morning to get a subdomain setup to demo the azure deployment? was thinking https://azure.healthlocker.uk until SLaM provision the necessary infrastructure for us then we can transition off Heroku and make the _main_ domain point to the SLaM-controlled Azure.

**Comment by iteles** [comment]
@nelsonic Any time before 09h45 or from 12h30 onwards (solid meetings between those two times)

**Comment by nelsonic** [comment]
@iteles 07:30 ? 🕢  😉

**Comment by nelsonic** [comment]
@iteles Azure IP address for DNS: `52.232.127.28`

**Comment by iteles** [comment]
@nelsonic Set up as `A` record pointing to that IP address, already propagated 👍 💃

**Comment by nelsonic** [comment]
@iteles thanks. 🎉
