### ISSUE TITLE
Accessing params in tests

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#65]
I am writing the tests for when there are query params for tags that it gets the correct result.

I originally tried putting this into `post_test.ex`, but then I was thinking that perhaps I would need to put it into`tip_controller_test.exs` so that I could have the connection and fetch the params from there using [fetch_query_params/2](https://hexdocs.pm/plug/Plug.Conn.html#fetch_query_params/2)

In `post.ex` I have tried:

```
  test "find_tags returns tips with the correct tag type" do
    post = fixture(:post)
    tip = Post |> Post.find_tags(%{"tag" => "connect"}) |> Repo.all
    assert String.contains? tip.content, "#connect"
  end
```

which gives the error:
** (ArgumentError) argument error
     stacktrace:
       :erlang.apply([%Healthlocker.Post{__meta__: #Ecto.Schema.Metadata<:loaded, "posts">, content: "Here's a tip #tip #connect", id: 625, inserted_at: ~N[2017-02-06 15:08:17.448356], updated_at: ~N[2017-02-06 15:08:17.448362]}], :content, [])
       test/models/post_test.exs:23: (test)

and in `tip_controller_test.exs` I have tried

```
  test "find_tags returns tips with the correct tag type", %{conn: conn} do
    post = fixture(:post)
    connection = get conn, "/tips?tags=connect"
    params = fetch_query_params(connection)
    tip = Post |> Post.find_tags(params) |> Repo.all
    assert String.contains? tip.content, "#connect"
  end
```

I can't seem to get it to work either way, and I am also uncertain which file would be better to test it in.

**Comment by nelsonic** [comment]
@katbow please share link to StackOverflow question once you've posted it. 😉

**Comment by katbow** [comment]
@RobStallion found the problem! I will post to stackoverflow still then link it here 😄  🎉

**Comment by katbow** [comment]
[Here it is](http://stackoverflow.com/questions/42073003/accessing-params-in-tests/42073098#42073098)

**Comment by nelsonic** [comment]
thanks @RobStallion! ❤️  ✅

**Comment by RobStallion** [comment]
No problem 👍
