### ISSUE TITLE
Edit carer title in clinician caseload view

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#650]
As requested by Nicola Byrne in our sprint 11 demo #644 today, rather than taking on https://github.com/healthlocker/healthlocker/issues/569, we will simply change the '(carer)' text to read '(friend/family/carer)'.

<img width="795" alt="screen shot 2017-05-16 at 21 36 30" src="https://cloud.githubusercontent.com/assets/4185328/26127034/c82079d2-3a7f-11e7-8b74-8498570feca6.png">

## Acceptance Criteria
+ [x] When a clinician looks at their caseload, all carers are denoted by the words '(friend/family/carer)' after their name

**Comment by katbow** [comment]
@Cleop Nicola & Mollie also confirmed they would like it with the name bold & the carer title regular text:

**Katherine Bowler** (friend/family/carer)

**Comment by MollieCourtenay** [comment]
@katbow @Cleop not sure if you have already covered this Kat in #625
