### ISSUE TITLE
Care team: contacts: add Clinician role/job title

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#659]
+ [x] As a SLaM service user or carer connected to a SLaM care team, I see the role of each clinician displayed underneath their name.(within care team > contacts.)
e.g. 
**Mary Watts**
Care coordinator

 #277

**Comment by markwilliamfirth** [comment]
Rob to update this issue

**Comment by Cleop** [comment]
- Need to add new column to table for clinician's role
