### ISSUE TITLE
Clinician: access HL caseload via ePJS

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#670]
+ [ ] As a clinician, when I click on the HL logo within ePJS, a new window opens in my browser 
+ [ ] I am already signed in to HL and authenticated 
+ [ ] my caseload is displayed

**Comment by markwilliamfirth** [comment]
Rob to update this issue

**Comment by MollieCourtenay** [comment]
Garry tested and signed off from his POV.
