### ISSUE TITLE
Clinician caseload: styling changes

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#678]
# Clinician caseload 
![clinician_caseload](https://cloud.githubusercontent.com/assets/25012688/26207901/b8d4cba6-3be0-11e7-8180-8c956dee479b.png)
+ [x] make arrows pink
+ [x] only have arrows on Healthlocker users (remove from not signed up users)
+ [x] make Healthlocker service user boxes blue (30% opacity) 
+ [x] give Healthlocker carer boxes yellow outline
+ [x] **Service user full name** = bold . 
+ [x] **Carer full name** = bold . (family, friend, carer) in italics (like the Ines example not Katherine)
+ [x] Edit 'Inactive users' to 'Users not signed up to Healthlocker'
+ [x] Remove 'Users not signed up to Healthlocker' text next to each user name
+ [x] Change inactive username to half opacity
+ [x] reduce size of 'Healthlocker users' and 'Users not signed up to Healthlocker'
+ [x] add grey separator line between HL users and 'Users not signed up to Healthlocker'
+ [x] reduce margin between name bubbles

**Comment by MollieCourtenay** [comment]
@Cleop the spacing between the User and their carers is quite a lot different to the visual reps from India. 

+ [ ] Can you tighten up a bit please?

**Comment by Cleop** [comment]
@MollieCourtenay, that's totally fine.

As the spacing amendment was not in the original acceptance criteria would you be able to open this as a new issue and close this one if you're happy that the acceptance criteria have been met? Then I can make the change there.

**Comment by MollieCourtenay** [comment]
@cleop the caseload got really muddled on an internet explorer 11 today. 
![hl](https://cloud.githubusercontent.com/assets/25012688/26455055/e5a4ab4e-4160-11e7-9dd2-740a921c6c4a.PNG)

**Comment by MollieCourtenay** [comment]
Assigning you both @katbow  @Cleop  as not sure who'll  fix this.

**Comment by MollieCourtenay** [comment]
![caseload](https://cloud.githubusercontent.com/assets/25012688/26500840/5ef08166-422f-11e7-8d71-d51023d9853c.PNG)
tested on a SLaM laptop :)
thanks
