### ISSUE TITLE
Clinician Messaging: styling changes

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#679]
# Clinician Messaging
![clinician_messages](https://cloud.githubusercontent.com/assets/25012688/26208830/fdff5f8c-3be2-11e7-88c8-0257cd701cce.png)
+ [x] change the boxes to 30% opacity
+ [x] align the timestamp to the top of the box (not bottom) 
+ [x] change the timestamp to italic 
+ [x] timestamp in dark blue not white
+ [x] light grey thinner grey conversation outline box

**Comment by MollieCourtenay** [comment]
@Cleop new styling looks fab for Clinicians messaging.
 
has it affected on a users view - there seems to be a big white gap at the top... see here - e.g. Evan, on Google Chrome, macbook.
<img width="1274" alt="screen shot 2017-05-22 at 17 41 06" src="https://cloud.githubusercontent.com/assets/25012688/26319189/e82463f2-3f15-11e7-88c6-d8990e614163.png">

**Comment by Cleop** [comment]
It will now look like this instead @MollieCourtenay, I hadn't got around to doing the styling for the carer menu too:
![image](https://cloud.githubusercontent.com/assets/16775804/26350928/2b813b74-3fad-11e7-8d59-f3065ba03653.png)
I'll be pushing it up shortly. I mentioned it here: https://github.com/healthlocker/healthlocker/issues/676#issuecomment-303069138 but it may not have made sense!
