### ISSUE TITLE
Clinician Goals and Strategies: styling changes

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#680]
# Clinician Goals and strategies
![clinician_goals_strategies](https://cloud.githubusercontent.com/assets/25012688/26208821/f6a3cd0e-3be2-11e7-92b4-7623fb556f15.png)

+ [x] add goals icon, centred in the column 
+ [x] add strategies icon, centred in the column 
+ [x] add dark blue separator line between goals and coping strategies
+ [x] add Goals centred title
+ [x] add Coping Strategies centred title
+ [x] add blue 30% opacity boxes for the goals
+ [x] add yellow 30% opacity boxes for the coping strategies
+ [x] right align the created stamp for coping strategies
+ [x] use regular not bold for coping strategies
+ [x] if possible, line break the coping strategies, if they have been input by the user with line breaks
+ [x] italicise 'Important' - same size as created text

**Comment by Cleop** [comment]
@MollieCourtenay due to the way the css is structured, the central blue line break doesn't look exactly as the design does. Are you happy with this version?

![image](https://cloud.githubusercontent.com/assets/16775804/26305655/1d550384-3ee8-11e7-8732-f7d621834e64.png)

**Comment by Cleop** [comment]
I have not done the line breaks for now as it said 'if possible', given the amount of time available this would not be a quick fix.

**Comment by MollieCourtenay** [comment]
@Cleop this is this causing a problem because it is a link?

<img width="359" alt="screen shot 2017-05-26 at 15 32 29" src="https://cloud.githubusercontent.com/assets/25012688/26498902/9562619e-4228-11e7-81d5-a6b8c6504806.png">

**Comment by Cleop** [comment]
@MollieCourtenay - it's because the link is all one word and so words are not broken up onto multiple lines. If I add to it then it does go on to a separate line but only when there are separate words. It also has less space in this particular example as well because of the bullet point.

I'll just take a look at potential solutions.

**Comment by MollieCourtenay** [comment]
@Cleop thanks :)

**Comment by Cleop** [comment]
Just needed to specify overflow-wrap : break-word. Now pushing this up and will pop the please test label on again when ready.
