### ISSUE TITLE
Clinician menu: Goals and Coping Strategies when there are none made yet

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#694]
Currently this section looks like this when it is empty:
![image](https://cloud.githubusercontent.com/assets/16775804/26358189/a9a995de-3fc9-11e7-98e0-077811a88b7d.png)
It looks a bit incomplete to me (now that the divide and image are there), would you like something underneath @MollieCourtenay like a line saying 'No goals yet created' or similar?

**Comment by MollieCourtenay** [comment]
@cleop that would be nice. Only if it is a quick thing. I'll prioritise within sprint 12 list.
