### ISSUE TITLE
View tips on staying well

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#7]
As a person using HL,
I can access approved wellness tips
so that I can have guidance to feel inspired and motivated

<img src="https://cloud.githubusercontent.com/assets/1287388/22246318/2c5f4830-e22c-11e6-90fb-7d29934aab85.jpg" width="200">

This can be on personalised to me on my profile, or as general tips for staying well if I am not logged in.

- [x] Create HTML skeleton
- [x] Responsive styling with Tachyons
- [x] Accumulate tips with tags
- [x] Store & display tips from the db
- [x] Filter & display tips based on tag type

## Acceptance Criteria

+ [x] tip of the day to be visible when user lands on HL

+ [x] user can click to see more tips

+ [x] A user can 'like' a tip

+ [x] each tip will be displayed along with its '5 ways to wellbeing tag' These are: 'Keep learning' / 'Connect' / 'Give to others' / 'Be active' / 'Take notice'

+ [x] The tag is a link which, if clicked, the user is shown more tips that have the same tag.

+ [x] The user can filter tips by tag.

**Comment by nelsonic** [comment]
@katbow thanks for creating this issue/story and for doing some _initial_ work on it. 👍 
@MollieCourtenay please update with a more _detailed_ **_acceptance_ criteria** so we are _clear_ on what is _expected_ to deliver this feature to end-users for UAT. thanks!

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria

+ [ ] tip of the day to be visible when user lands on HL

+ [ ] user can click to see more tips

+ [ ] each tip will be displayed along with its '5 ways to wellbeing tag' These are: 'Keep learning' / 'Connect' / 'Give to others' / 'Be active' / 'Take notice'

+ [ ] The tag is a link which, if clicked, the user is shown more tips that have the same tag.

+ [ ] The user can filter tips by tag.

**Comment by MollieCourtenay** [comment]
The tips are just statements, they do not contain links.

Find them here - a WIP google sheet.
https://docs.google.com/spreadsheets/d/197iLcKD6hJfx81KldY5GwBuU-4IEmFqPXvKAm9V9wLU/edit#gid=0

**Comment by katbow** [comment]
@MollieCourtenay if I understand correctly, the tips & events won't be populated by users, but the recovery stories will?

**Comment by LauraNevo** [comment]
> user can click to see more tips
In this case they would swipe. We could suggest 5 tips per day, for example, to not overwhelm the user.

![view tips](https://cloud.githubusercontent.com/assets/3858131/22462191/37dfa47a-e7a4-11e6-8315-1cb804b2e80b.png)

**Comment by MollieCourtenay** [comment]
@katbow the Recovery Stories will also be sourced from existing sites. I've popped some in the google sheet.

Allowing a user to add their own story will be something that comes quite a bit later... as they will need to be checked and approved in some way clinically before we pop them on our site.

**Comment by MollieCourtenay** [comment]
Looking at the wires above would it be possible to toggle between tags in the same screen as where the tips are displayed. I've sketched this:

![img_1855](https://cloud.githubusercontent.com/assets/25012688/22501617/82ddeba4-e861-11e6-8b78-88bbbdb8d28d.JPG)

If I click the green 'Connect' link on the first screen, I am taken to the Tips screen with 'Connect' already selected.

If I click the pink 'See more tips' I am taken to the Tips screen and I need to choose which topic to select. In this example both 'Be active' and 'Connect' are selected.

**Comment by LauraNevo** [comment]
I see where you're coming from with the multiple selection. You'd rather they can select more than one tag at the same time. It feels like a lot of filtering content for such a small screen though.

Could we do in the same way but in the tag selection screen? Then we can display "multiple tag selected" on the list page or even just "Connect, Keep learning, give..." with a cut and it would take less space.

**Comment by katbow** [comment]
It's possible to toggle between tips in the same page as where they are displayed - whether they are partially hidden or not.

As for the swipe, I think having a link for `See more tips` might be even easier for non tech-savvy users as it provides a written instruction for what to do.

**Comment by LauraNevo** [comment]
Sure, that makes sense. I might be too focus on how fancy swiping sounds. :D
