### ISSUE TITLE
Connect the fully paid version of Mixpanel

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#708]
SLaM are currently procuring a fully paid subscription to Mixpanel #550 which will provide much more granular control of the analytics.

When this is available, it needs to be hooked up to the healthlocker application.

**Comment by MollieCourtenay** [comment]
@katyedwards  will shared details with you @reddog

**Comment by katyedwards** [comment]
Done! @MollieCourtenay @reddog - on your email...

**Comment by katbow** [comment]
waiting for permissions from @tonydaly

**Comment by tonydaly** [comment]
Hey @katbow, sorry what do you need?

**Comment by katbow** [comment]
@tonydaly sorry I thought someone had messaged you! If you log in to your dwyl email, there should  be a message from someone at mix panel asking for permission to move what was previously done on healthlocker to the paid version.

**Comment by iteles** [comment]
@tonydaly Could you please log into  your mixpanel account and transfer ownership over to the email address I have just emailed over to you 😊 

Tony can log into his account and go to Project Settings -> Management to make the transfer.
![transferproject](https://user-images.githubusercontent.com/4185328/29274061-6526bfba-80fe-11e7-9df4-efb4482e0fcb.png)

**Comment by markwilliamfirth** [comment]
From Tony:

Heya,

I’ve already logged in and transferred the account to Cleo. The account is currently at the user limit, so probably best to delete my account and then add the new one.

Hope that helps!

**Comment by MollieCourtenay** [comment]
@Cleop can you let me know when you have managed to transfer the project to the SLaM account?
See email from me on Sunday for email to transfer to :)

**Comment by MollieCourtenay** [comment]
I've transferred the Healthlocker project to SLaMs paid for account.
