### ISSUE TITLE
Tips page: add tips intro and move explore more tips to top page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#710]
changes: 

+ [x] Add the intro:
**Tips: 5 Ways to Wellbeing**
Small improvements in our wellbeing can help to decrease some mental health problems and also help us to get more out of life.

These 5 actions are proven to improve personal wellbeing. 
[Read the full document](url)

+ [x] Filter the tips:  #Connect  #BeActive  #KeepLearning  #TakeNotice  #GiveToOthers

**Comment by katbow** [comment]
@MollieCourtenay I formatted this the same way as it is on the home page

![image](https://cloud.githubusercontent.com/assets/1287388/26585345/b939b4dc-4543-11e7-8083-0d2cfe416f32.png)

The category description comes underneath that when you are on a specific category.
Do you want the **Tips: 5 Ways to Wellbeing** centred on this page as well or left aligned? Should the category description remain underneath?

**Comment by MollieCourtenay** [comment]
@katbow edited your comment above
