### ISSUE TITLE
Small tweaks ahead of demo

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#74]
There are a couple of small tweaks I reckon we should make ahead of the demo today (small things that will make a difference):
+ [x] Add a 'See more stories' link to the homepage
+ [x] Remove the 'location' and 'photo' button from the new post page (temporarily, for now they don't do anything)
+ [x] Make the size of the font a little smaller in the `textarea` on the new post page

@katbow What do you reckon? I already have the code for this, so if you're happy to validate the requirement, I'll add the commits 👍

**Comment by katbow** [comment]
Agreed this needs doing! Great that it's there already 😄
