### ISSUE TITLE
About page content

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#75]
I was considering what content to put in the Healthlocker about section. I was thinking it should include:

* What is healthlocker?
* What are the aims of healthlocker?
* How are those aims being accomplished?

@MollieCourtenay Can you verify what content needs to be in the about page? Is there a copy available at this time? Thanks!

**Comment by iteles** [comment]
Linked to #23. I think the content is still up in the air!

**Comment by MollieCourtenay** [comment]
@katbow not yet, will work on it.

**Comment by katbow** [comment]
closing as now listed in #23
