### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#757]
- [x] Run through documentation & edit any necessary sections.

- [x] Ensure it has correct technical & feature documentation.

TODO: document other "core" features:
* Account flows including connecting to slam as a carer/SU
* Care team usage/availability
* Clinician caseload
* Goals & Coping strategies

Possibly?? Forgotten password from the user perspective?

**Comment by iteles** [comment]
Thanks @katbow !
