### ISSUE TITLE
Carer connect to SU care team, even if the SU doesn't have HL account

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#762]
+ [x] as a HL user, I can connect as a carer, even if the service user that I support does not have a HL account.
+ [x] As a clinician, I can see in my caseload view, an active Carer account underneath an inactive Service user account. -note this was agreed in #1012 to have the carer with the inactive service user underneath

QUESTION: WHERE / HOW best to list this?

## dwyl List of Steps
1. Break down requirements and break issue down into smaller steps
>This issue will be further broken down into separate steps/issues when it is tackled to ensure clear communication of requirements and tasks. The estimate is large because this issue involves complex architecture and changes across the repository.
2. * [ ] #1008
3. * [ ] #1009 
4. * [ ] #1010 
5. * [ ] #1011 
6. * [ ] #1012

**Comment by iteles** [comment]
@katyedwards This one is also still assigned to @MollieCourtenay so I assume that means it needs more thought, but in the meantime, do you have any more detail on this?

**Comment by katyedwards** [comment]
Some!
So a carer should be able to sign up using an SUs details and have exactly the same experience as a carer with a connected SU currently does - i.e. they get the care team and messaging, but can't view any of an SU's tracking etc.

The main 'change' would be for Clinicians, that there would need to be a visual different on the caseload to show that an SU isn't signed up, but their carer is.  I would suggest it would be clearest for Clinicians if the SU and carer moved to the top list of connected people, but the SU is maybe greyed out with a small Service User not connected message.

I'll ask India if she has ever mocked this up...

**Comment by katyedwards** [comment]
We don't have an official mock up for this, but essentially it should look like the existing UI, the non-signed up user will be grey like those in the bottom list and the Carer will be yellow lined the same as an active carer currently is, so something like this:
![screenshot 2017-06-08 10 21 03](https://user-images.githubusercontent.com/24604903/26921537-445b6e06-4c34-11e7-80fc-a133e2b43da5.png)
![screenshot 2017-06-08 10 21 18](https://user-images.githubusercontent.com/24604903/26921549-4cdc9ad2-4c34-11e7-8010-f754db031bd4.png)

**Comment by katyedwards** [comment]
Tested by SLaM and it works!
