### ISSUE TITLE
Error with earmark in tracking_data.html

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#766]
![image](https://cloud.githubusercontent.com/assets/1287388/26673507/0aab746e-46b5-11e7-8b86-cb302f40ecc0.png)

**Comment by MollieCourtenay** [comment]
@katbow what is this bug? Is it still causing problems?
Does it need to be in a milestone?

**Comment by katbow** [comment]
@MollieCourtenay this has been fixed. forgot to close, sorry.
