### ISSUE TITLE
Delete th /st Tracking Overview

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#767]
+ [x] As a user on tracking overview, I see dates presented correctly.

<img width="606" alt="screen shot 2017-06-01 at 10 16 21" src="https://cloud.githubusercontent.com/assets/25012688/26674015/c530d1c0-46b6-11e7-85c6-f1a0c7b5cf9f.png">

**Comment by MollieCourtenay** [comment]
@Cleop what did you do here, delete st/ th or fix the bug so they display correctly?

**Comment by katyedwards** [comment]
Yep - looking good!
