### ISSUE TITLE
Ensure: once SU connected: display first name / last name from ePJS record.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#776]

**Comment by markwilliamfirth** [comment]
@katyedwards to double check which phone number to display and whether to display address

**Comment by katyedwards** [comment]
Ref #513  This may have been implemented following the closure of 513?

@MollieCourtenay can you add any more detail to this issue...  Thanks!

**Comment by MollieCourtenay** [comment]
@katyedwards
 So as longs as for all user types , when a use connects the first and last name from the SUs ePJS record is displayed in stead of the option first and last name they entered on creating heir account then this issue can be closed.

**Comment by katyedwards** [comment]
@RobStallion @katbow can you update whether this was implemented - when an SU connects to care plan, to pull through and display first name/ last name from ePJS and replace the optional HL first name/ last name.

**Comment by katbow** [comment]
Yes, it updates to the name from ePJS & displays in account profile, but it's not editable.
