### ISSUE TITLE
Edit account created flash message: prompt them to connect to SLaM

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#777]
- [x] Edit the first ever flash message when a user first signs up to Healthlocker.

FROM: Account created successfully - Welcome to Healthlocker!

TO: 
**Welcome to Healthlocker!** 
Connect to your care team and record - find out more in [Account](https://www.healthlocker.uk/account).

**Comment by iteles** [comment]
@katyedwards Now sure we can do this one just yet 😉

**Comment by katyedwards** [comment]
No problem - bump it for quicker fixes!

**Comment by MollieCourtenay** [comment]
not showing
still this;
<img width="774" alt="screen shot 2017-08-25 at 09 36 06" src="https://user-images.githubusercontent.com/25012688/29706211-d90cf1c4-8978-11e7-85d3-5bd2d5f52eae.png">
