### ISSUE TITLE
Internal server error -  tracking overview - after adding problem/diary

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#778]
I had an internal server error with a user that I was testing with earlier when attempting to look at their tracking overview after putting in sleep it worked, but then after adding problem there was an error, and then with diary there was also an error. - I can't replicate though on other accounts. Not sure how to note this for investigation?

**Comment by RobStallion** [comment]
@MollieCourtenay. Would you be able to let us know which user you were testing with at the time? We want to see if it could have anything to do with the data that they have stored as we are also not able to replicate the problem at the moment.

**Comment by MollieCourtenay** [comment]
Hi @RobStallion I have direct messaged you on slack about this.

**Comment by MollieCourtenay** [comment]
<img width="740" alt="screen shot 2017-08-09 at 08 29 21" src="https://user-images.githubusercontent.com/25012688/29109978-f54ee520-7cdc-11e7-9a43-27e220fc4f44.png">
