### ISSUE TITLE
Edit welcome message: South London and Maudsley NHS Foundation Trust 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#779]

**Comment by iteles** [comment]
@katyedwards Can you confirm please that all we need is to change SLaM to South London and Maudsley NHS Foundation Trust ?

**Comment by katyedwards** [comment]
Sorry - didn't realise some of these weren't populated!  Will look now and update shortly...

**Comment by katyedwards** [comment]
Just on that brief welcome message on the homepage...
It should be the same as the first 2 paragraphs of the about page (without the link to the SLaM website):

Healthlocker is a secure platform powered by the South London and Maudsley NHS Foundation Trust (the trust) that promotes supported self-management and opportunities to improve communication between service users, carers and clinicians.

It is currently in development, more features and improvements will be added in the coming months.

**Comment by katyedwards** [comment]
Yep, great thanks
