### ISSUE TITLE
Remove 'SLaM care team' from Care Team: Contacts (SU and Carer)

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#780]

**Comment by katbow** [comment]
Before for carers:
![image](https://user-images.githubusercontent.com/1287388/26888888-4c1871ce-4ba4-11e7-83bb-ae17852d195f.png)
After for carers:
![image](https://user-images.githubusercontent.com/1287388/26888916-6845b258-4ba4-11e7-8c0c-c51296be79e5.png)
Before for service users:
![image](https://user-images.githubusercontent.com/1287388/26888964-845e1e6c-4ba4-11e7-81f0-93148dfe1ea0.png)
After for service users:
![image](https://user-images.githubusercontent.com/1287388/26888998-94b1fee6-4ba4-11e7-96ca-5351e964d246.png)

**Comment by katyedwards** [comment]
Yep - both look great, thanks!
