### ISSUE TITLE
Consent Screen in Account - add additional check box

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#783]
As a service user or carer with a healthlocker account connected to SLaM ePJS, I can consent  - or remove my consent to be contacted with newsletters or similar communications by SLaM or IOPPN.

Check box to be positioned below the existing 2, but equally spaced.

Text:

- [ ] I agree to be contacted with relevant newsletters and communications from the trust or their partner organisation the Institute of Psychiatry, Psychology & Neuroscience at King's College London (IoPPN), such as the C4C newsletter.  I understand that my details will not be passed onto anyone else.

**Comment by iteles** [comment]
@katyedwards We can definitely add this checkbox in, however, is there a plan for admins to be able to _see_ whether this box has been checked?
i.e. Is there an _immediate need_ to see whether this box has been checked or are we just making sure it's stored data for now and we'll deal with it later as with the rest of the sign up form?

**Comment by katyedwards** [comment]
Sorry - just stored data for now and we'll deal with it 'doing' something later.  Thanks!

**Comment by katyedwards** [comment]
Lovely, thanks!
