### ISSUE TITLE
User Test Feedback - Move Care Plan Summary

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#786]
For a connected SU (e.g. evan's demo account):

User Feedback that it felt odd that the Care Plan Summary button floated under goals and strategies, separating them from the similar size & shape icons for tracking and diary

**Comment by MollieCourtenay** [comment]
what 'type' of user said this? (SU / staff? what role?) @katyedwards

**Comment by katyedwards** [comment]
That is a very good point sorry.  Would have been staff because I don't think I have spoken to any SUs.  I can't remember now who said it though. 

I think take off here and just maybe note on your feedback sheet in case other people say the same thing.  Not sure now why I made it an actual issue.  Must have come from someone on Project Board or similar.

**Comment by katyedwards** [comment]
Moved from here to be tracked as feedback
