### ISSUE TITLE
IE - healthlocker has 2 scroll bars

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#788]
When IE11 is not in full screen mode, HL has 2 scroll bars (have not been able to reproduce on other websites)

![when_not_fullscr_has_two_scrollbars_wtf](https://user-images.githubusercontent.com/24604903/26871129-0b84027a-4b6a-11e7-91cc-18d71b395571.PNG)

**Comment by katbow** [comment]
@katyedwards the scroll comes from the hidden nav menu. I removed the extra margin that was on the bottom of the screen so there's not a lot of extra space length wise. There is still a limit where this may pop up (the length of the items in the nav menu). 

Let me know how it is. I can also remove some extra space from the top of the menu and/or make the X smaller & to the side.

**Comment by pm5k** [comment]
Fine now
