### ISSUE TITLE
Goals - Mark as achieved button, not clear it is a button

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#791]
When viewing a goal, the mark as achieved trophy 'button' gives no indication it is a button, either visually or when you hover over it.

Same on IE11 and chrome

![mark_as_achieved_super_not_obvious](https://user-images.githubusercontent.com/24604903/26871425-fc59d35a-4b6a-11e7-9850-0ef03863ef21.PNG)

**Comment by iteles** [comment]
@katyedwards Would changing the cursor to a pointer (the little hand) when hovering over both the trophy and the star suffice for this?

**Comment by katyedwards** [comment]
Yes I think for a quick fix that would work and we can test whether people still struggle with it or not.  Thanks!

**Comment by katyedwards** [comment]
@pm5k fine on chrome, can you check on IE11 too and if ok close the issue.  Thanks!

**Comment by pm5k** [comment]
Works fine. Although worth asking India about hover feedback for those icons.. just a thought
