### ISSUE TITLE
User Feedback - Diary entries don't 'submit'

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#793]
User Feedback - it isn't clear that the diary entry will appear on the tracking page so it looks like it hasn't submitted and will just be a neverending steam of consciousness with no date division.

It feels like it isn't working properly.  Was expecting it to make a proper entry on the same page when clicked.

**Comment by iteles** [comment]
@katyedwards At the moment when we press 'Save' in the diary entry, the screen moves to the toolkit page and gives the following success banner message:
<img width="798" alt="screen shot 2017-06-07 at 11 19 50" src="https://user-images.githubusercontent.com/4185328/26873896-59a1341a-4b73-11e7-992f-7817b47f26b4.png">

Is it when the users go _back_ to the diary entry page that they're not sure it has happened?

Two things that might be quick wins here:
+ A red message under the diary entry box saying something like 'Once you have saved your entry, you can view it in the Tracking Overview page' 
+ Adding to that success banner with ', view it in Tracking Overview' with a link to tracking overview.

What are your thoughts?

**Comment by katyedwards** [comment]
I think both of those sound like really good options.

If you can you do both quickly and easily then do both - if one or the other, I'd say a permanent message under the diary entry box as a preference.

**Comment by katbow** [comment]
@katyedwards I did both options. So you should see red text underneath the textbox when you enter/edit an entry, and the flash message is changed with a link for both adding and editing an entry.

**Comment by katyedwards** [comment]
Both working - thanks!
