### ISSUE TITLE
PlugConnWrapperError in login controller

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#795]
![image](https://user-images.githubusercontent.com/1287388/26874428-779d9a2e-4b75-11e7-892c-528ae36c9632.png)

Looks like the user was not set correctly when attempting to get data_access. Need to check how this is set & change.

**Comment by katbow** [comment]
@iteles I'm not sure how this one can be tested. I think it was Repo.get_by was failing sometimes so the user was nil. I couldn't replicate it, but I changed it to get the user from the current_user set after logging in, which will always be there if log in is successful.

**Comment by iteles** [comment]
@nelsonic Seems like we've done what we can here but assigning to you in case you have some insight here that I might not 😊 Please close if you're happy.

**Comment by nelsonic** [comment]
@katbow thanks for updating to use `current_user`. 👍 
@iteles nothing to add. 
Closing.
