### ISSUE TITLE
Spike research on implications of changing care team

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#796]
If a SU changes care team as per https://github.com/healthlocker/healthlocker/issues/59, what are the implications of this?

Particular concerns are:
+ Messaging 
+ Permissions (access to SU data being removed/added correctly)

**Comment by katbow** [comment]
I have the same concerns here. 

Potential problems with messaging (which also relates to permissions):
The permissions for messaging are set up when a carer or service user connects their account. 
How the current set up is, if the clinician were to change, then the user and clinician in the room used for messaging would remain the same. The rooms & who is in the room is currently only set up when a service user or carer connects. 

What we could do is have a check when the service user/carer goes to care team to see if it's the correct clinician. We can check if the clinician in the room is the same as the clinician for that user's slam_id from the `mhlTeamMembers` table in ePJS.
