### ISSUE TITLE
PlugConnWrapperError in Tip Controller

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#797]
![image](https://user-images.githubusercontent.com/1287388/26875042-06eeacfc-4b78-11e7-9e50-ba562b8c734f.png)

May be a case of casing - need to check if casing matters for `BeActive` versus `beactive`. The parameters in this case were `beactive`.

![image](https://user-images.githubusercontent.com/1287388/26875117-5072554a-4b78-11e7-8508-e08107363fa3.png)

**Comment by katbow** [comment]
@katyedwards you can test this by going to any of the tip categories and change the category in the url from upper to lowercase.

eg. https://www.healthlocker.uk/tips?tag=Connect and https://www.healthlocker.uk/tips?tag=connect should load the same.

**Comment by katyedwards** [comment]
Hi @katbow sorry - is this fixing the stretched tip icons?  If so, it seems to be fixed!

**Comment by katbow** [comment]
no, this is something that came up from AppSignal, which is what alerts us about errors. You may not have come across it yourself, (and possibly not Mollie either) but if someone were to type in the url with lower case tag E.g. /tips?tag=**c**onnect instead of /tips?tag=**C**onnect, then the page would get an internal server error. Now the page will load regardless of the casing in the category tag.

**Comment by katyedwards** [comment]
Ahh I'm with you, and yep both upper and lower case works!
