### ISSUE TITLE
Un-bookmark Stories

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#809]
Not sure if this was a requirement, if not ignore it, but if it was meant to work it's a bug!

I can bookmark stories, but I can't 'un-bookmark' them by clicking again.

(Logged in user)

**Comment by katbow** [comment]
There's this issue https://github.com/healthlocker/healthlocker/issues/41

We hadn't gotten around to un-bookmarking yet. We had just the bookmarking in (I think before that issue even maybe?) to possibly track interaction with content.

**Comment by katyedwards** [comment]
Ignore it in that case!  We'll leave it in the backlog - better to sort the other bits as time is short.  Thanks!  Will close this as the other issue is there.
