### ISSUE TITLE
#story tag doesn't link to main story page

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#810]
Not sure if it was meant to...

If this wasn't a requirement, ignore it, but when I was checking everything I did expect clicking on #story to return me to the page of all stories. 

If it is something I can edit in the markdown on individual stories, let me know.

**Comment by katbow** [comment]
Yep, in markdown you can do [#story](https://www.healthlocker.uk/posts).

That would, however, give a standard link. If you want one with the same colouring as the rest of the links, it should be 

```
<a href="https://www.healthlocker.uk/posts" class="link hl-aqua underline">#story</a>
```

I realised the `Link to source` are also default styled links, so may want to do the same with that one time.

**Comment by katyedwards** [comment]
Thanks @katbow I'll try to have a play with that when I have a minute!

**Comment by katyedwards** [comment]
Just tried it and that works great... I'll try to find time over the weekend to update them all.

Thanks!
