### ISSUE TITLE
Terms of service - Copy Changes

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#811]
Sorry - didn't notice the short-hand in the additional paragraph from IG.

Under Terminations, the 2nd Paragraph should use the full Healthlocker, not HL and the trust not SLaM.

Replace paragraph with:

You have the option to disconnect your Healthlocker account from your trust health record at any time. When your Healthlocker account is disconnected from your health record, all information you have previously shared with your care team will no longer be available to them. You will no longer be able to view information from your care team or send them messages. Your Healthlocker account will remain active for your personal use and you will be able to reconnect to your trust health record at a later time if you choose to.

While you are there, could you also edit 1 clunky bullet point under 'Setting up your account'

First bullet, remove *when setting up your account* so the bullets read:

- that you will not provide false information;
- that you will keep all your information updated;
- that you will not share your login details with anyone;
- that you will respect other users, including NHS staff, at all times.

**Comment by katbow** [comment]
@katyedwards I can't find this in privacy statement.

**Comment by katbow** [comment]
Oh wait, I see. It's in Terms of Service instead of privacy. Just going to update the title.

**Comment by katyedwards** [comment]
Balls - sorry @katbow !

**Comment by katyedwards** [comment]
Fab!
