### ISSUE TITLE
Load testing logged in routes 

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#813]
I'm having trouble with testing the logged in routes. I can't figure out how to log in with artillery.io, so unsure if I am taking the wrong approach or if there is another library/dependency to use for this.

Full details posted [here](https://stackoverflow.com/questions/44438769/load-testing-logged-in-routes-in-phoenix)

**Comment by katbow** [comment]
@tonydaly do you have experience with this?

**Comment by tonydaly** [comment]
@katbow doesn't look like there's anything specifically wrong with artillery for load testing the app, their docs state that cookies "are remembered and re-used by individual virtual users". So logging in should work fine. 

From the stackoverflow it looks like `window` isn't available, maybe there's another way to set the csrf token?
