### ISSUE TITLE
Get Support Page - Copy changes

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#814]
- [x] In the top grey box - Frank  The link for 'Chat online 2-6pm' is wrong.  Should be:
http://www.talktofrank.com/livechat

- [x] In the top grey box - Emergency Services - the find your A&E link opens in a new tab where the others don't.  Best to be consistent, esp if opening in the same tab is better practice.

- [x] Under More information and advice:
NHS Choices - remove the space between mental health conditions and the comma
most physical and mental health **conditions ,** treatments and services.

- [x] Under More information and advice:
Patient Advice and Liaison Service (PALS) at South London and Maudsley NHS Foundation Trust 
Un-bold "at South London and Maudsley NHS Foundation Trust"

- [x] Under More information and advice:
- Advice from a pharmacist
- Self referral drug and alcohol services 
Both should be black as those in the top box are when they aren't a link

**Comment by katbow** [comment]
> * [ ] Under More information and advice:
> * Advice from a pharmacist
> * Self referral drug and alcohol services

For this section, it was originally black but Mollie requested the change as she thought they looked out of place. I can change it back but wanted to confirm this point.

**Comment by katyedwards** [comment]
Can you make them black please - I've spoken to Sarah and apparently it's really bad for accessibility - there should be a certain degree of difference between links and non-links.

Thanks!

**Comment by katbow** [comment]
Makes sense to me 😉 . Will change.

**Comment by katyedwards** [comment]
Lovely!
