### ISSUE TITLE
Investigate caching data in phoenix

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#825]
In appsignal, the top slow events are ecto(database) events.

![image](https://user-images.githubusercontent.com/1287388/26972624-842bb9f6-4d0a-11e7-9ec5-17c0492c2af3.png)
![image](https://user-images.githubusercontent.com/1287388/26972655-9dd91eca-4d0a-11e7-9712-2b8f87a03c28.png)

The top 2 slow events are from /page and /posts. Posts in particular is loading the same set of posts most of the time, so we need to look into caching these with phoenix.

**Comment by katbow** [comment]
[caching libraries](https://github.com/h4cc/awesome-elixir#caching)

**Comment by katbow** [comment]
Spike found on [this branch](https://github.com/healthlocker/healthlocker/tree/cache)

**Comment by katbow** [comment]
this is done & will be used in particular for #858

**Comment by nelsonic** [comment]
@katbow `cache` branch is `404`
![image](https://user-images.githubusercontent.com/194400/27605982-446e75e0-5b76-11e7-8da9-6bd2771b4807.png)

if you have time, please add a few lines to https://github.com/dwyl/learn-phoenix-framework so the knowledge is transferred to others.
