### ISSUE TITLE
Account: Connect to SLaM. Don't allow under 12s to connect to SLaM

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#83]
As a user, I am unable to connect my HL and SLaM accounts if I am under 12 years of age, due to Gillick competencies.

## Acceptance Criteria
+ [x] As an under 12 user, once I have entered my first name, last name, DOB and NHS number, and click Connect (#118) I am not able to connect with my SLaM record.
+ [x] As an under 12 user, who is unable to connect with my SLaM record, I am presented with a message(content below).
+ [ ] As an under 12 user, who is presented with the message, I can click home and be redirected to the Healthlocker home screen.

## Content
We are unable to connect your account as you are under the age of 12. You can continue to use Healthlocker without this connection.

![under 16s](https://cloud.githubusercontent.com/assets/25012688/23307246/be554f34-fa9e-11e6-914b-56b90f01ab64.png)

**Comment by LauraNevo** [comment]
We could add a nice message about the fact we care about them though <3 and they can be notified when it'll be available if they give us their email address.

**Comment by katbow** [comment]
This needs a bit more detail to time estimate appropriately. But from my understanding there is a separate screen that will need to be shown if a user under 16 tries to connect with SLaM? Or would it be preferable to just have a notification somewhere on the page (under the birthdate field, by the submit button, etc) that you must be 16 or older?

**Comment by MollieCourtenay** [comment]
There are lots of options... can we discuss @katbow @nelsonic?

1.  No warning you must be +16, allow user to fill all fields, then bounce them if too young to a new page to say sorry. (poor UX, but interesting for us to see how users get on with the connecting bit).  We could within the sorry screen ask permission to email them when HL will let them connect. 

2. No warning you must be +16, allow user to fill all fields, then bounce them to a page to say sorry BUT approve the link between accounts somewhere in the back end, and make the connection live when Murat gives the nod. (notify user of this)

3. Warning you must be +16, within the connect screen near DOB. Users have to navigate back, if too young. 

4. Add a new question in profile, after [ ] I am a SLaM service user.... [ ] I am over 16 / [ ] I am under 16. So that the link to connect to SLaM is only displayed to those who have said they're old enough.

5. If the user ticks the box to say their under 16, we drop down a new option, permission to email them when HL will let them connect.

**Comment by katbow** [comment]
@MollieCourtenay since this is going to be temporary, I would suggest going with the quickest/simplest solution which would be the first option imo (without approving the link as in 2). 

There could be a message "Note: you must be over 16 to connect" on the connect to SLaM page that prevents under 16 users from attempting to connect in the first place, but we would still need the above in case they try it anyway.

**Comment by MollieCourtenay** [comment]
Yeah I agree, I re-wrote the ACs to align with option 1 a few days ago.

Lets leave the "Note: you must be over 16 to connect" as I'd want to add something about 'at the moment' or 'until May' - and then the message feels really long.

We've notified care teams about the 16+ so shouldn't be too common - and yes is temporary.

**Comment by MollieCourtenay** [comment]
UPDATE: now under 12. not under 16.

**Comment by katbow** [comment]
@MollieCourtenay can we just redirect to home with "We are unable to connect your account as you are under the age of 12. You can continue to use Healthlocker without this connection." as a flash message?

It's not very much text on it's own page. We can still go for a separate page, with a link to home at the bottom if that's preferable.

**Comment by RobStallion** [comment]
Hey @MollieCourtenay. Here's how it looks with the flash message on desktop...

![image](https://cloud.githubusercontent.com/assets/15571853/26056873/07167cf2-396f-11e7-9fd7-967691b22c8a.png)

and this is mobile...
![image](https://cloud.githubusercontent.com/assets/15571853/26056909/2cc2f066-396f-11e7-8aca-bda8c1ebe3ea.png)

**Comment by katbow** [comment]
@MollieCourtenay we have this done with the flash message only right now. You can test it out to see if it works with the following details:

Email: max@email.com
password: password

NHS details:
First Name: Max
Last Name: Power
Date of birth: 01/01/2007
NHS Number: 3351834797

**Comment by MollieCourtenay** [comment]
I like it, thanks.
