### ISSUE TITLE
Tracker overview display for 0 entry

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#830]
+ [x] as a user if I enter 0 hours sleep and 0 times waking up, then the 0 displays in the tracking summary under the graph. Sleep: 0 hours Woke up: 0 times

![screenshot 2017-06-09 16 44 15](https://user-images.githubusercontent.com/24604903/26983243-02ea7336-4d33-11e7-8bef-09dd681e7f70.png)

**Comment by Cleop** [comment]
Currently uses String.to_float which errors when a decimal is not given. Currently 0 is the only no. of hours slept without a '.0', changing this to 0.0 would work or creating an if statement to not `to_float` if dealing with 0.

**Comment by katyedwards** [comment]
@Cleop Not sure if that comment was meant for us?!  But preferably on the data below the tracking graph it would just display 0 not 0.0

**Comment by MollieCourtenay** [comment]
<img width="581" alt="screen shot 2017-08-25 at 09 39 40" src="https://user-images.githubusercontent.com/25012688/29706304-5647e004-8979-11e7-981a-e83b4f457dac.png">
Half way there...

**Comment by katyedwards** [comment]
Sorry @Cleop  - on current deployment we've lost the Woke up: 0 times
And have microseconds back!

![screenshot 2017-08-25 17 31 19](https://user-images.githubusercontent.com/24604903/29723088-3e172a7a-89bb-11e7-8674-938e4a48c9bb.png)

**Comment by katyedwards** [comment]
Today's View:

![screenshot 2017-08-29 10 44 25](https://user-images.githubusercontent.com/24604903/29814982-110f30f6-8ca7-11e7-98ac-0ede92fa2a27.png)

**Comment by MollieCourtenay** [comment]
blocked by #1048

**Comment by katyedwards** [comment]
Blocker solved.

Sleep 0 hours and Times work up 0 times works fine, but we still have microseconds on the average sleep.

![screenshot 2017-08-30 11 40 13](https://user-images.githubusercontent.com/24604903/29868723-01ca1ada-8d78-11e7-98ad-b72c1bd4ccfb.png)

**Comment by MollieCourtenay** [comment]
When no data entered it shows as 0 in average bar.
When data entered as 0, it says microseconds in average bar.

<img width="603" alt="screen shot 2017-09-01 at 12 15 54" src="https://user-images.githubusercontent.com/25012688/29967621-6a43703c-8f0f-11e7-9131-40d1222a714e.png">
<img width="587" alt="screen shot 2017-09-01 at 12 15 36" src="https://user-images.githubusercontent.com/25012688/29967620-69155b44-8f0f-11e7-96c0-906b157da7f5.png">

**Comment by katbow** [comment]
@MollieCourtenay what do you want it to say in each case?
no data entered -> Sleep: no entries ?
0 hours recorded -> 0 hours ?

**Comment by MollieCourtenay** [comment]
Average bar> Sleep: 0 hours / or blank with just Sleep:... don't mind - just not microseconds :)

In detail in grey boxes: 
Sleep: 0 hours
Woke up: 0 times

**Comment by MollieCourtenay** [comment]
<img width="512" alt="screen shot 2017-09-01 at 16 23 50" src="https://user-images.githubusercontent.com/25012688/29976447-fb8fffc0-8f31-11e7-9fae-e89960e0740c.png">
YESSSSSSS
