### ISSUE TITLE
Add NHS lozenge into the footer. Change colour of the footer.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#839]
+ [x] footer colour white
+ [x] top of footer to have thick dark blue line
+ [x] logo is added with exclusion area around it (as per file attached). 
+ [x] mobile as below
+ [x] desktop as below

![nhs logo-01](https://user-images.githubusercontent.com/25012688/27681784-339a7b54-5cb8-11e7-8d10-6748eb2fa772.png)

![screen shot 2017-06-29 at 10 59 21](https://user-images.githubusercontent.com/25012688/27682406-512fa606-5cba-11e7-90ff-7fbe6a814129.png)
![screen shot 2017-06-29 at 10 59 12](https://user-images.githubusercontent.com/25012688/27682407-513aa92a-5cba-11e7-92ad-2b7e4cecbc2a.png)

**Comment by RobStallion** [comment]
Hey @MollieCourtenay. Would it be possible to get the NHS logo without any whitespace around it. I can add it manually and it would make it a little easier when it comes to positioning it. Thanks

**Comment by katyedwards** [comment]
@indiamindwave24 can you help?

**Comment by indiamindwave24** [comment]
[NHS_Lozenge.zip](https://github.com/healthlocker/healthlocker/files/1114799/NHS_Lozenge.zip)

**Comment by katyedwards** [comment]
@RobStallion ^^

**Comment by indiamindwave24** [comment]
Apologies, please ignore the above @RobStallion 
.
.
this is the correct file
[NHS_Lozenge.zip](https://github.com/healthlocker/healthlocker/files/1114879/NHS_Lozenge.zip)
