### ISSUE TITLE
make the #tag links to see more tips

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#84]
e.g. '#beactive' instead of 'see more #beactive tips'

**Comment by Cleop** [comment]
Doing this would solve the current issue for tips that don't have any tags which currently display: "See more "no tag found" tips" in this instance.
<img src="https://cloud.githubusercontent.com/assets/16775804/23459395/08144a3a-fe78-11e6-8fef-e52853be28ff.png" width="250" />

I am aware that the screenshot shows a tip which has been given tags but these have not been recognised and displayed. This is to do with failure to recognise capitals, which has been raised as a separate issue: #162
