### ISSUE TITLE
Create a node script to communicate between elixir and ms sql 

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#843]
Create a Node script that will accept query strings from the Healthlocker app and query the MS SQL database on azure. Once it has queried the database it will return the data back to Healthlocker for use.

Steps to achieve:

- [x]  Create Node script that is capable of querying MS SQL

- [x]  Ensure query is in correct format in Node and query the database with it

- [x]  Implement functionality that will allow for a query string to be sent from HL to Node script
    * Need to be able to run a node script in Elixir. [Example here](https://github.com/karmaradio/karma/blob/7a599f986ff442b361bd365f904f692d7c4b8c85/lib/script_runner.ex)

- [x]  Format the response data from MS SQL and send it back to HL

- [x]  Decode data in elixir (look at poison decode) 
    * Need a function which will receive & handle the data. [Example here](https://github.com/karmaradio/karma/blob/7a599f986ff442b361bd365f904f692d7c4b8c85/lib/merger.ex#L34-L37)

- [ ] Reformat real data to be used in elixir (may be done differently for each query).
links to #837

**Comment by katbow** [comment]
Note: at this time it's being done with the test database and we were able to create the node script to query MSSQL. This has been made generic to take a querystring from the args (passed in from elixir), and use this to get rows, then JSON.stringify the rows and log in phoenix. This completes the first 4 tasks here 👍

**Comment by RobStallion** [comment]
Update:

We have currently completed the first 5 steps with dummy data. Cannot complete step 6 at the moment. Please see https://github.com/healthlocker/healthlocker/issues/844 for more info on why.

Steps 2 and 6 will need to be repeated for each query to the database but the other steps can be applied to all queries.

**Comment by RobStallion** [comment]
closing this issue as managed to connect HL to ePJS. see #848
