### ISSUE TITLE
Spike: Connecting mssql with elixir

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#846]
Try to connect elixir with mssql using mssqlex and mssql_ecto following the new information we have been given [here](https://github.com/findmypast-oss/mssql_ecto/issues/15)

**Comment by RobStallion** [comment]
Going to attempt the steps in the mac environment first. If that doesn't work I will move on to a linux environment on the vm

**Comment by RobStallion** [comment]
Currently getting the following error on both linux and mac environments..
![image](https://user-images.githubusercontent.com/15571853/27281239-f171bea4-54e2-11e7-8a61-8edea98b6222.png)

Looking into solutions for this at the moment. Will update [this issue](https://github.com/findmypast-oss/mssql_ecto/issues/15) with any findings

**Comment by RobStallion** [comment]
Have managed to connect elixir to the database now by using the database connection string provided on azure. Added the connection string to the hostname atom in the db config.

**Comment by RobStallion** [comment]
Have managed to grab data from the test ms sql db on azure and use it in a phoenix application. Going to stop work on [issue #847](https://github.com/healthlocker/healthlocker/issues/847) and try to implement the db queries using this method.

**Comment by katbow** [comment]
I had a little issue with this when I ran it on my computer. It looked like I had everything installed as I should (for the drivers, etc). However I was still getting the error:

```
[error] Mssqlex.Protocol (#PID<0.723.0>) failed to connect: ** (Mssqlex.Error) [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found Connection to database failed. | ODBC_CODE 01000 | SQL_SERVER_CODE 0
```

Which is what I was originally getting when I added `:mssqlex` to the applications list. I checked my set up against @RobStallion and for some reason, a file I had from installing `msodbcsql` called `odbcinst.ini`  was missing information. It should look like:

```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
UsageCount=1
```

All working now on both mac & ubuntu environments 👍

**Comment by katbow** [comment]
One last thing to check for this.

We should add another field to our test data, but *don't* reflect this in the model. E.g. Add `Description` field to table, but keep the model for `Product` exactly the same.

**Reason for doing this:** In HL, only the relevant/used fields were added to the models. This means there are some fields in the ePJS database that are not in the models. We need to check which errors, if any will happen with this, and update HL ePJS models accordingly.

**Comment by RobStallion** [comment]
Added extra fields to the test database but did not include them in the model and confirmed that the model will not need to be updated with all fields.
