### ISSUE TITLE
Connecting HL ePJS

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#848]
TODO:

* Likely need to change the primary keys for each of the epjs tables by having
`@primary_key {:PrimaryID, :integer, autogenerate: false}`

The primary id will likely be `StaffID`, `PatientID`, etc. All should be integers.

* Update the config to

```
config :healthlocker, Healthlocker.ReadOnlyRepo,
  adapter: MssqlEcto,
  hostname: "database_url_string"
```

Alternatively can have
```
config :healthlocker, Healthlocker.ReadOnlyRepo,
  adapter: MssqlEcto,
  username: "username + hostname"
  database: "db_name",
  password: "my_password"
```

* ~Add mssql_ecto & mssqlex to dependencies & mssqlex to applications~
* ~May need to add rest of fields to schemas - currently only has relevant fields. [See here for more information on why](https://github.com/healthlocker/healthlocker/issues/846#issuecomment-309486688)~
* ~May need to remove migrations for ReadOnlyRepo~

**Comment by katbow** [comment]
I am working on:

> change the primary keys for each of the epjs tables

and the primary key for some of the tables is unclear. 
Assumptions I have made regarding primary keys:
* None of the tables have a field `id`
* There needs to be a different primary key instead. It's not *necessary* for a table to have a primary key, but it is good practice.
* `mhlPatIndex` has `Patient_ID` which I am setting to primary key
* `mhlPatientAddressDetails` has `Address_ID` which I am setting to the primary key
* It is unclear what the primary key is for `mhlGPDetails` and `mhlTeamMembers`

### Questions:
* Are the assumptions about primary keys for `mhlPatIndex` and `mhlPatientAddressDetails` correct?
* What is the primary key for mhlGPDetails? Is it meant to have a Staff_ID which is referenced in `mhlTeamMembers`?
* If `mhlGPDetails` does not have a primary key `Staff_ID` (or an id field which isn't reflected), where does `Staff_ID come from for the `mhlTeamMembers` table?
* Does `mhlTeamMembers have a primary key? If so what is it? I wasn't sure if this one would since it's a join table.

**Comment by katbow** [comment]
I went through the calls to the epjs database before lunch. The only potential problem I am seeing is related to the `Staff_ID` and what that references in the `mhlGPDetails`. When we get a clinician's patient list, we are using the `id` from `mhlGPDetails`, which I think we will need to remove. We need to know instead which field in `mhlGPDetails` represents the `Staff_ID` in the `mhlTeamMembers` join table so that we can get the list of patients (and everything that follows).

**Comment by RobStallion** [comment]
Update

HL is now connected so closing this issue in favour of #852
