### ISSUE TITLE
Spike for multi page signup form

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#85]
Linked to #12 

Need to look into multi page signup forms

**Comment by tonydaly** [comment]
@katbow `Ecto.Multi` and embedded schemas might be helpful here, i hope...

https://medium.com/@abitdodgy/building-many-to-many-associations-with-embedded-schemas-in-ecto-and-phoenix-e420abc4c6ea#.2t1cki2cu

**Comment by katbow** [comment]
That does look like it will be helpful, thanks for that 👍

**Comment by katbow** [comment]
This is what I understand needs to happen for sign up.

![signup flow](https://cloud.githubusercontent.com/assets/1287388/22758608/4e91070a-ee47-11e6-997d-3e94ad382107.jpg)

I looked at [ecto.multi](https://hexdocs.pm/ecto/Ecto.Multi.html) and [ecto embedded schema](https://hexdocs.pm/ecto/Ecto.Schema.html#embedded_schema/1) and I am not certain I understand embedded schemas. However, there's no situation where it's all the information or nothing, and instead we build up parts of the user piece by piece, so it doesn't seem appropriate for db transaction (using Ecto.multi). What I understand from @iteles is that we want to keep the data at each stage. If the data only needs to be saved at the end of signup1 and after accepting T&Cs then I think it may be useful.

If this is correct some of the concerns I have would be how it affects user flow and seems to be an unnecessary complication. I think at least the T&Cs and Privacy statement can be in /signup2 as either a checkbox that says "I agree to the Terms & Conditions and the Privacy statement", or by having text that says "By clicking submit, you agree to the Terms & Conditions and the Privacy Statement" with both T&Cs and privacy as links to that content to be viewed in more detail. This prevents the user from seeing a wall of text upon signup. There also wouldn't be cases where the user fills in all other information with it persisted to the db then stops before agreeing to this - otherwise we would have to check each time a user logs in to see if they've agreed (which would also require another field in the db).

I'm also worried this will result in messy data for the users table. The number of users wouldn't necessarily equal the number of entries in the table (i.e. for any entries that are partially complete) and there would need to be extra checks for if someone actually is a registered user. 

I think the reasoning for this form layout was that it was originally quite complicated, but that isn't really the case anymore. There are not very many fields to fill in and it could be simplified further with a change to T&Cs/privacy, and possibly even removing name since it is optional and can be added in a user account page later. Having a single form in this case is less friction for users signing up, rather than steps that need completion where users could drop out at each stage.

**Comment by nelsonic** [comment]
Hi @katbow my approach to multi-stage signup would be to make _only_ **two fields _required_**:
+ `email` - String
+ `name` - String 

Then in the _same_ table ("Model") we can have **other _optional_ fields**:
+ `password` - String
+ `phone_number` - String (_counter-intuitively a string is appropriate

**Comment by tonydaly** [comment]
@nelsonic with changesets we can have different validations at each different stage. So each step has its own changeset, with its own unique validations. This is one of the really powerful features of Ecto as this is always a problem with other ORMs.

@katbow I'm not as worried about having users in the DB that haven't completed the full process. Having a record in the DB for a user that only partially signed up (e.g. didn't accept T&Cs) makes it easier to send the user to the right stage of their journey if they come back.

We can also make queries to filter out users at different states (or possibly use a state machine?)

However, all of this said, aren't we making an MVP? Shouldn't the first version of this be the simplest thing possible? Which as @katbow suggests, is a single form...

**Comment by nelsonic** [comment]
@tonydaly noted. (_thanks! any chance you can link to a good example/demo/doc for this?_) 👍

**Comment by tonydaly** [comment]
@nelsonic I was googling around earlier, but couldn't find any examples, just talk.
