### ISSUE TITLE
Queries to check

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#852]
We started going through queries here: https://github.com/healthlocker/healthlocker/issues/848#issuecomment-309803440

ReadOnlyRepo Queries we need to check are:

**Web**
- [x] AccountController(1)
    - [x] in localhost?
- [ ] CaseloadController(4)
    - [ ] in localhost?
    * Only one to change is on line 17 #851 
- [x] Caseload.RoomController (1)
    - [ ] in localhost?
- [x] Caseload.UserController (2)
    - [ ] in localhost?
    * Query work as expected, however need to account for nil address for people without a fixed address. Also need to consider which fields are present. Some people will have Address 1-3, while others will have all 5, while some will have none. When displaying this need to be considered.

**Lib**
- [x] Slam.CareTeam (2)
    - [ ] in localhost?
    * ~Need to delete lines 12-19~ This fixes the query, however we discovered that sometimes there is no care team for a user (see below & #853)
- [x] Slam.CarerConnection (1)
    - [x] in localhost?

**Comment by katbow** [comment]
So far the queries in Slam.CarerConnection & AccountController have been run & returned the correct data. The other have not yet been run, but the only changes we see from reading over the queries is one in CaseloadController and the Slam.CareTeam.

We will be running each of them this morning to ensure they work as expected 👍

**Comment by katbow** [comment]
Question:
Do SLaM SUs sometimes not have a care team? We were checking the queries to get the care team of an SU (for the Slam.CareTeam file), and it returned an empty list. If so, we will need to consider if there are any implications for this. Is it even useful for someone to connect to SLaM if they do not have a care team?

**Comment by RobStallion** [comment]
Currently getting the following error when trying to connect as a carer..

 ![image](https://user-images.githubusercontent.com/15571853/27384508-fe60d014-5686-11e7-9005-7a5ac055e581.png)

**Comment by RobStallion** [comment]
Removed type from date field in the carer connection query to resolve the issue above.

**Comment by RobStallion** [comment]
Next step: 

Going to change a user to a clinician in pg so that we can test the remaining queries. Will be updating in a separate issue.
