### ISSUE TITLE
Problem deploying when running scripts

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#856]
There was a problem deploying to healthlocker-pr-854. When we looked at the error, the app built fine, however the problem occurred in the next step which is "Run scripts & scale dynos". 
All of the Repo.migrations ran in this step, then stopped immediately after they were complete with the following error:

```
[0m/app/.platform_tools/erlang/lib/odbc-2.11.1/priv/bin/odbcserver: error while loading shared libraries: libodbc.so.1: cannot open shared object file: No such file or directory
/app/.platform_tools/erlang/lib/odbc-2.11.1/priv/bin/odbcserver: error while loading shared libraries: libodbc.so.1: cannot open shared object file: No such file or directory
[31m13:49:42.435 [error] GenServer #PID<0.428.0> terminating
** (stop) time out
Last message: {#PID<0.427.0>, {:connect, [1, 2, 2, 1, 2, 1, 1, 'DRIVER={ODBC Driver 13 for SQL Server};SERVER=localhost;DATABASE=;UID=;PWD=;'], :off, :on}, 15000}
State: {:state, #Port<0.13650>, {#PID<0.427.0>, #Reference<0.0.5.285>}, #PID<0.427.0>, :undefined, :off, :undefined, :undefined, :on, :connecting, :undefined, 0, [#Port<0.13641>, #Port<0.13642>], :undefined, :undefined}
[0m** (exit) exited in: :gen_server.call(#PID<0.426.0>, {:checkout, #Reference<0.0.5.283>, true, :infinity}, 5000)
    ** (EXIT) time out
    (db_connection) lib/db_connection/poolboy.ex:112: DBConnection.Poolboy.checkout/3
    (db_connection) lib/db_connection.ex:919: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:741: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    lib/mssql_ecto/connection.ex:58: MssqlEcto.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:193: Ecto.Adapters.SQL.query!/5
```

**Comment by nelsonic** [comment]
@katbow please try: https://healthlocker-pr-854.herokuapp.com/login

**Comment by nelsonic** [comment]
@katbow please _describe_ what steps you are taking to debug this as comments against this issue. thanks. I can sit next to you while debugging but the debugging is happening on your computer so please post comments for each thing you try.

e.g: "adding environment variables to heroku PR build 854 to check if that's the issue"

**Comment by RobStallion** [comment]
On staging server the env. variables are not configured for the ms sql db on azure. Trying to configure them now following the instructions found [here](https://github.com/dwyl/learn-phoenix-framework/blob/984c9ebea7869e9940ca69722160d887f750c355/production-deployment.md#162-edit-your-profile-file-on-azure-instance-to-set-tcp-port-for-phoenix)

**Comment by katbow** [comment]
Steps I have done:
* Set up branch which connects to a different Mssql database that doesn't have firewall restrictions
    * This is to check if the problem lies with connecting to an Mssql db at all, or if it is because of the restrictions with the ePJS database.
* There was an error on this, similar to the one above (`Last message: {#PID<0.427.0>, {:connect, [1, 2, 2,`), except instead of `:connect` it referred to `:checkout`, as well as errors on the ReadOnlyRepo database because the EPJS_DATABASE_URL was not available on the review app
* To add config vars for the EPJS_DATABASE_URL I edited the [`app.json`](https://github.com/healthlocker/healthlocker/blob/testing/app.json#L13-L14) file. This adds in the config var from the parent application. This removed the postgres error.
* When looking at the error for `/app/.platform_tools/erlang/lib/odbc-2.11.1/priv/bin/odbcserver: error while loading shared libraries: libodbc.so.1: cannot open shared object file: No such file or directory`, I found a suggestion that the [odbcini](http://knowledgebase.progress.com/articles/Article/error-while-loading-shared-libraries-libodbc-so-cannot-open-shared-object-file-No-such-file-or-directory-error-with-ODBC-driver) variable needs to be specified.
* There is a [buildpack on heroku](https://elements.heroku.com/buildpacks/ifix/heroku-buildpack-odbc) which was also added in [app.json](https://github.com/healthlocker/healthlocker/blob/testing/app.json#L29-L31)

Next steps:
* Ensure the the ODBCSYSINI variable is set globally in the config vars, from the instructions [here](https://elements.heroku.com/buildpacks/ifix/heroku-buildpack-odbc)
* If this doesn't work still, then ODBC drivers may not (and probably aren't) installed on heroku. Need to find a way to run a script to do this, possibly in [this section](https://github.com/healthlocker/healthlocker/blob/testing/app.json#L3-L5)

**Comment by katbow** [comment]
> Ensure the the ODBCSYSINI variable is set globally in the config vars, from the instructions here
That buildpack is crap & doesn't have any instructions for what this should be set to, AND I can't even open an issue on the repository for it because issues are disabled.

Moving on to the next one..

**Comment by RobStallion** [comment]
Have got the env. variables on set up now so that they can be used in the vm.

**Comment by nelsonic** [comment]
@RobStallion trying to run `master` on `localhost` get:
![image](https://user-images.githubusercontent.com/194400/27477678-c847de08-5804-11e7-8413-3e4e6bcb4dfb.png)

is the requirement for `odbc.app` documented somewhere?

**Comment by RobStallion** [comment]
@nelsonic. We haven't documented it anywhere as of yet. We were planning to update the readme for mssqlex over the weekend. I didn't think it was a priority as we were never connecting localhost to ePJS. Sorry if that was the wrong thing to assume. I can document them now if you like?

**Comment by nelsonic** [comment]
@RobStallion I'm trying to understand how to run the project on `localhost` to extend it, are you running it through Vagrant?

**Comment by RobStallion** [comment]
Sorry in advance if I'm misunderstanding what you mean but since we connected to ePJS we haven't been running the project on localhost as we cannot connect to the db. We can use localhost to check features that are separate from ePJS but anytime that we have connected to ePJS we have done so on the vm you set up. 

You can run the project using the Vagrantfile, if odbc is not installed locally, but you will still not be able to check anything related to ePJS.

**Comment by RobStallion** [comment]
Currently updating the vagrant file so that it can run the most recent version on HL and updating the README so that it is up to date with the most recent version of HL.

**Comment by nelsonic** [comment]
@RobStallion please assign PR with new `Vagrantfile` when ready. thanks! 👍

**Comment by katbow** [comment]
closing this in favour of #864 for updating vagrant file
