### ISSUE TITLE
Endpoint for generating epjs button

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#859]
Create endpoint which generates an image for the ePJS button

if able to send a binary back = ideal

if not, redirect the request (after authenticating) to another endpoint that returns a static button.

`<a href="healthlocker.uk/caseload"><img src="healthlocker.uk/epjsbutton" /></a>`

**Comment by RobStallion** [comment]
First step:

Going to try and save an image an image that I have locally as binary.

**Comment by RobStallion** [comment]
Base64 encoded binary image and displayed on the front end.

**Comment by nelsonic** [comment]
@katbow / @RobStallion this is what we need to make the Healthlocker menu button in ePJS. 👍 
Please assign PR when ready. thanks! 🎉

**Comment by nelsonic** [comment]
this technical task is now complete. 👍
