### ISSUE TITLE
Spike for schema changes for sign up with roles/permissions

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#86]
From #12 we will definitely need to add to the users schema `name`(string, not required), `selected_question`(string, required), `answer`(string, required), `data_access`(boolean, required).

In addition, there needs to be a way of setting permissions upon sign up - unless this would be better done at a different time and permissions are always the same when signing up? This might be a `role_id` field added to the users table which is associated with a roles table, or the roles can be places directly into the user schema.

**Comment by tonydaly** [comment]
@katbow check out some of these: https://github.com/h4cc/awesome-elixir#authorization

https://github.com/cpjk/canary looks decent, makes a lot of sense to have authorization as a plug.

**Comment by katbow** [comment]
Thoughts on this:

I was originally leaning towards the separate table, but I think it may be unnecessary and simpler to have the `role`(string) field in the `users` table. It seems like extra step to add in the separate table and I can't think of any particular benefits of doing it that way.

I thought that either the role could be set to a default role with no special permissions when signed up and then it is changed if verified from a clinician email, or admins verify roles. The former makes more sense in the long run, but the latter may be quicker to implement for first pass?

There seems to be [a few](https://github.com/cpjk/canary) authorisation [libraries](https://github.com/boydm/policy_wonk) which could be used once the roles are in place.

**Comment by katbow** [comment]
@tonydaly I liked the look of canary as well, I'll check out the other link as well.

**Comment by tonydaly** [comment]
@katbow yeah, I'd go with just an extra field (`role:string`) on the `users` table. TBH as it's quite important to get this right, I'd go straight for using one of the libraries. It'll be easier than trying to retrofit it later and then we're more likely to miss something. 

We'll definitely want good tests for this.

**Comment by katbow** [comment]
Out of the available options, canary with [canada](https://github.com/jarednorman/canada) does seem like the best option - it looks simple to use but provides what we will need.

**Comment by tonydaly** [comment]
@katbow agreed! My usual pattern for something like this is to write a number of failing tests first, that helps me to know when it's working and I haven't broken anything else :)
