### ISSUE TITLE
Update Vagrant file

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#864]
Update Vagrant file so that it can run the most recent version of the app.

**Comment by katbow** [comment]
updated rebar3, installed other fields here https://github.com/phoenixframework/phoenix/issues/1418#issuecomment-166140608 Server started, but postgres was not connected.

Attempted to run `psql -U postgres postgres` and had the error `Error: You must install at least one postgresql-client-<version> package.`

Resolved with `sudo apt-get install postgresql-client`, and had the error 
```
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
