### ISSUE TITLE
Move messages disclaimer to sit above messages.

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#865]
+ [x] as a user, I see the disclaimer message above the messaging.

+ [x] copy change SU
+ [x] copy change carer
+ [x] copy change clinician

## copy change 
**Please note, all service users and family, friends or carers will see the following statement:**
_**If you need urgent help or advice, go to  [Get support](url). Do not leave a note in an emergency.** 
Your note will be visible to your whole care team. Do not expect an immediate response._

<img width="597" alt="screen shot 2017-08-11 at 10 06 14" src="https://user-images.githubusercontent.com/25012688/29207541-77765086-7e7e-11e7-93f6-1d1b1bc102cf.png">

**Comment by MollieCourtenay** [comment]
@katbow I think you had fixed this - and this will be in your PR?

**Comment by katbow** [comment]
in #1045 now
