### ISSUE TITLE
Decrypt user data from ePJS

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#868]
If a user clicks the HL Button/Link in ePJS and they have a userdata parameter in the URL we decrypt it using a SQL Query. See [here](https://github.com/healthlocker/healthlocker/issues/838#issuecomment-310666304) for more info

**Comment by RobStallion** [comment]
have been able to use the query from the example that was linked above and get the following result...
![image](https://user-images.githubusercontent.com/15571853/27585009-5343677c-5b32-11e7-9c96-8888eec4e076.png)

The problem that I am having at the moment is that I currently cannot replicate the following part of the node code in elixir...
![image](https://user-images.githubusercontent.com/15571853/27585064-8a045bf4-5b32-11e7-9b79-9d5c42a2802d.png)

This is the part of the code that actually logs the string that we need to use in our app.

**Comment by RobStallion** [comment]
I'm not sure that the query is correct as I am unable to replicate the result that is returned in node. 

Currently the query that is being run in elixir looks like the following...
![image](https://user-images.githubusercontent.com/15571853/27592840-6a3fa47a-5b4d-11e7-98c4-0bf40fd4a5e1.png)

and returns the following...
![image](https://user-images.githubusercontent.com/15571853/27585009-5343677c-5b32-11e7-9c96-8888eec4e076.png)

Initially I thought that we needed to replicate the request.on function, as stated above, but I have noticed that even if the incorrect password is entered into the elixir query it still returns the same result.

**Comment by nelsonic** [comment]
@RobStallion please paste the query we wrote with @shouston3 👍

**Comment by RobStallion** [comment]
Thanks a lot @shouston3 & @nelsonic. 👍

Have managed to get the query working now so we can decode the string that is received from ePJS.

![image](https://user-images.githubusercontent.com/15571853/27606465-5097e584-5b78-11e7-8987-c4b1917a9bee.png)

**Comment by RobStallion** [comment]
@nelsonic. We can now decrypt the userdata from the url in caseload_controller. However, as we need to connect to the ePJS db to actually use this we cannot access it in the tests. We have run it in the vm to confirm it is working. 

Do you have any suggestions for the testing side of things?

**Comment by katbow** [comment]
we found a work around for this, which you can see in #871
