### ISSUE TITLE
Staging (prod.exs) MS SQL Environment Variable Configuration

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#874]
Hi @RobStallion / @katbow, the configuration files for development [`config/dev.exs`](https://github.com/healthlocker/healthlocker/blob/77f8d85956c1ac7ff24866f7c9021e2cd7311775/config/dev.exs) & production [`config/prod.exs`](https://github.com/healthlocker/healthlocker/blob/77f8d85956c1ac7ff24866f7c9021e2cd7311775/config/prod.exs) don't match for the ePJS Database:
![image](https://user-images.githubusercontent.com/194400/27632001-56ff5c02-5bf2-11e7-933d-87818021a018.png)

This means `staging` (_and `production`_) deployment will not work.
see error: https://github.com/healthlocker/healthlocker/issues/841#issuecomment-311613548

# Todo:
+ [x] ***replace*** the parts of `dev.exs` that refer to "Repo" with `import_config "prod.exs"` (_eliminate duplication and future updating_)

> @shouston3 / @SimonLab / @Danwhy which of these two approaches would you go with?

**Comment by shouston3** [comment]
If you are connecting to `epjs` as readonly, then I would make the dev config exactly the same as production

**Comment by nelsonic** [comment]
Given that we are using environment variables, we should not be "hard coding" _anything_ anymore.
we should _eliminate_ any duplication, between the files.
For example the `Repo` lines in: 
[`config/dev.exs#L36-L50`](https://github.com/healthlocker/healthlocker/blob/77f8d85956c1ac7ff24866f7c9021e2cd7311775/config/dev.exs#L36-L50) should be moved to `prod.exs` and then _imported_ back into `config.exs`

@RobStallion let's do this config file "refactor" `after` we get the "_manual_" deploy working on `staging`.

**Comment by nelsonic** [comment]
@RobStallion I think deployment using `edeliver` is _failing_ because of _these_ lines in `prod.exs`:
https://github.com/healthlocker/healthlocker/blob/b6c41b2cfedb3e5bb5ae8f58d2110efd0eedb2c5/config/prod.exs#L14-L16
![image](https://user-images.githubusercontent.com/194400/27636000-4df7aa38-5c01-11e7-9fbe-0cb37a410488.png)

we need to use _environment variables_ for this.

**Comment by RobStallion** [comment]
Will look into this now

**Comment by nelsonic** [comment]
@RobStallion see: https://github.com/healthlocker/healthlocker/pull/876

**Comment by MollieCourtenay** [comment]
@nelsonic @RobStallion is this done? Can this issue be closed?

**Comment by MollieCourtenay** [comment]
@RobStallion is this done? Can this issue be closed? Missed it earlier as it doesn't have a milestone?
