### ISSUE TITLE
Clinician: How are goals ordered in Clinician View?

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#878]
The goals in the clinician view, don't seem to be in order of last interacted with - which was what we thought was the case.

+ [x] As a clinician, I see goals displayed in a more logical order. (most recently interacted with at the top? OR most recently created at the top)
+ [x] adding achieved date
+ [x] separating important and achieved into 2 lines

<img width="528" alt="screen shot 2017-08-07 at 16 21 08" src="https://user-images.githubusercontent.com/25012688/29033297-7e841c4a-7b8c-11e7-8ae5-2572268808ed.png">
PS - listing steps to take in separate issue here: #900

**Comment by katbow** [comment]
@Cleop This is a possibility for something small to work on/finish up after the demo. For the last step of ordering the goals.

**Comment by katyedwards** [comment]
@Cleop 
Ordering Goals works great!

- [ ] Display on Important and Achieved is still off

- [ ] Achieved is spelt wrong with the date

- [ ] Any new step added (to an existing or new goal) is not aligning the text to the box

![screenshot 2017-08-25 17 56 56](https://user-images.githubusercontent.com/24604903/29724015-cb49efa6-89be-11e7-8a93-975f47f51b0f.png)

**Comment by katyedwards** [comment]
Check boxes need to be made smaller

**Comment by katbow** [comment]
@MollieCourtenay this seems to be open for the same reason #900 is open. Can this one be closed so we can take care of the resizing of tick boxes in just one issue?

**Comment by MollieCourtenay** [comment]
I'll trust here @katyedwards says the ordering works great.
