### ISSUE TITLE
Messaging - Long messages don't submit and disappear

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#880]
+ [x] as a user (SU, Carer, Clin) I have no character limit on my messages that I send (this was my understanding, as we did not choose to implement #588 character limit). So If I type a long message it will send. 

I noticed if you type a message which is too long, you don't get an error message, instead you try to send it and it just disappears and you have to re-type.

Not clear this is going to happen and annoying that you've lost all your text!

@MollieCourtenay not sure how you would want this to behave?

**Comment by MollieCourtenay** [comment]
277 characters with spaces (including words)

**Comment by MollieCourtenay** [comment]
PostgrexErrorconnection_id: 8521 message: nil postgres: code: :string_data_right_truncation file: "v (#151)
 
This is a bug - here is an example of the app signal message coming through.

**Comment by MollieCourtenay** [comment]
I just tried to send this message from Robert to Evan:

Hi Evan, I am well thanks, looking forward to the weekend. By the way, I am going to have a week off in August so I think I will try to introduce you to Trudy when I see you next week. She can be available to you during the week when I am away. What will you be doing this weekend? Going cycling?

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/28168079-ce113f2e-67d5-11e7-93fd-42c69c50a542.png)

Can now send very long messages as shown above

**Comment by katyedwards** [comment]
Amazing!

**Comment by katyedwards** [comment]
@RobStallion have you tested this?  I will have to pass to Garry to test as I don't have access to any connected users on the staging environment.

**Comment by katyedwards** [comment]
Blocked by #915

**Comment by reddog** [comment]
@RobStallion Out of interest, was your test above at https://github.com/healthlocker/healthlocker/issues/880#issuecomment-315074516 on your local machine, staging or the Heroku site?

**Comment by reddog** [comment]
@katyedwards Are you able to re-test this issue now that messaging is working?

**Comment by katyedwards** [comment]
@reddog Works great for me, but have asked Garry to double check too.
