### ISSUE TITLE
Error reading files on staging server

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#885]
When going through the sign up flow on the staging server we get the following error..

![image](https://user-images.githubusercontent.com/15571853/27831347-350fe16e-60c2-11e7-857d-d316745e9782.png)

The file still exists in master so it seems to be an issue with where the staging server is trying to read the file from. 

**Error**
could not read file "web/static/assets/hours_slept.txt": no such file or directory

**Comment by nelsonic** [comment]
when there is an error, please include the text (_not just the screenshot_) so that it can be copy-pasted when searching for a solution.

**Comment by RobStallion** [comment]
Ok that makes sense. Will do

**Comment by nelsonic** [comment]
https://github.com/phoenixframework/phoenix_guides/blob/master/docs/deployment/deployment.md#compiling-your-application-assets

**Comment by RobStallion** [comment]
have tried running the following command, which can be found (here)[https://github.com/phoenixframework/phoenix_guides/blob/master/docs/deployment/deployment.md#compiling-your-application-assets]...

`$ MIX_ENV=prod mix phoenix.digest`

When it is run it says `Check your digested files at "priv/static"`. The files appear to be created here but the issue is telling us that it it trying to read the files from `web/static/..`. The files are also stored there.

**Comment by RobStallion** [comment]
After reading [this](https://gist.github.com/chrismccord/b3975ba356dba902ec88#asset-digests-optional) it appears as thought the issue could be to do with the `cache_static_manifest` in `config/prod.exs` being commented out at the moment. 

The docs do say it is optional which suggests that you should be able to read the files without this option in the config, but as this appears to be a new error could be a good place to start.

@nelsonic what was the thinking behind commenting this out?

**Comment by RobStallion** [comment]
have tried running HL on localhost with `cache_static_manifest` in `config/prod.exs` being commented both in and out and have been able to make both work. 

When `cache_static_manifest` was **commented out** I had to use the following steps to get the app the start...
```
MIX_ENV=prod mix compile
MIX_ENV=prod mix phoenix.server
```

When it was **commented in** the commands were ...
```
MIX_ENV=prod mix compile
MIX_ENV=prod mix phoenix.digest
MIX_ENV=prod mix phoenix.server
```

**Comment by RobStallion** [comment]
⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠⁠Looked at where the images are sourced from as they are also in `web/static/assets/` but they load as expected. 

![image](https://user-images.githubusercontent.com/15571853/27842021-d4ca3e26-60fd-11e7-8c5a-3ef0c8de20a7.png)

In the image above it sources the file from images which is in the assets folder so will try replicating that with the `.txt` files

**Comment by RobStallion** [comment]
As I am unable to update the staging server at this time, I am going to try replicating the issue using vagrant.

**Comment by RobStallion** [comment]
Have set up Vagrant so that it is running on port 8000 in `prod` and am unable to replicate the issues that we are experiencing with the staging server. 

I think that I need to try making the changes directly on the staging server to see if the solutions that I have come across so far will work. 

@nelsonic Would it be possible to have a quick catch up at some point today to go over the deploying

**Comment by RobStallion** [comment]
See issue #841 for instructions on how to deploy the app to staging

**Comment by RobStallion** [comment]
closed in error

**Comment by RobStallion** [comment]
found solution [here](https://stackoverflow.com/questions/33931176/finding-a-file-in-a-phoenix-app-script-rails-root)
