### ISSUE TITLE
module not available 

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#894]
![image](https://user-images.githubusercontent.com/15571853/27904432-913d4b70-6234-11e7-9cab-819a41e1c08c.png)

Think that this will be the same issue that we had with earmark. See issue #887

**Comment by katyedwards** [comment]
@RobStallion The link worked ok, but I typed in some feedback, clicked submit and got an error page again:
![screenshot 2017-07-06 10 51 20](https://user-images.githubusercontent.com/24604903/27905834-270cdd24-6239-11e7-84d0-d9b322c654d5.png)

**Comment by RobStallion** [comment]
closing in favour of #905
