### ISSUE TITLE
Add healthlocker@slam email to About and Get support

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#895]
**About page.** 
+ [x] Within Who is Healthlocker for? Add a line to the end of the first sentence that ends in 'goals and coping strategies.' :
If you need help or support using Healthlocker, please email [healthlocker@slam.nhs.uk](mail to:)

+ [x] Within Who is Healthlocker for? Add a line to the end of the staff paragraph:
As staff, if you need help or support using Healthlocker, please contact the trust service desk. 

**Get support.** 
+ [x] between first and second grey box, add a line:
If you need help or support using Healthlocker, please email [healthlocker@slam.nhs.uk](mail to:)

**Comment by RobStallion** [comment]
Hey @MollieCourtenay @katyedwards 

I'm not going to deploy these changes just yet so thought I would post the screen shots so you could say if this is what you had in mind for these issues.

**HL email**

![image](https://user-images.githubusercontent.com/15571853/28218211-bdff9d8a-68af-11e7-832a-ffa28b9e9025.png)

**Trust service desk**

![image](https://user-images.githubusercontent.com/15571853/28218233-cdcbee4e-68af-11e7-848d-7edbac3178d9.png)

**HL email in get support**

![image](https://user-images.githubusercontent.com/15571853/28218189-b06488f2-68af-11e7-8646-cbec1ef0cc20.png)

**Comment by katyedwards** [comment]
Hi @RobStallion yep - that looks good, thanks

**Comment by katyedwards** [comment]
Lovely thanks!
