### ISSUE TITLE
Sleep and Problem tracker edit success flash message

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#899]
+ [x] As a user who has saved a sleep or problem entry, I see this yellow flash message 'Tracker saved successfully, view it in [Tracking Overview](http://healthlocker.uk/tracking-overview)'

**Comment by MollieCourtenay** [comment]
still old flash message.

**Comment by katbow** [comment]
@MollieCourtenay since we saw this in the demo, do you want to close? or wait until the deploy is fixed?

**Comment by MollieCourtenay** [comment]
@katbow there are loads of issues like this and I think I would rather close all these once I see them deployed. So will wait to hear from Rob.
