### ISSUE TITLE
Clinician view: steps to take for each goal

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#900]
+ [x] As a clinician, I see the steps a user has listed to achieve the goal, which ones they have ticked and which ones they have not.
+ [x]  Includes correct checkbox image

<img width="528" alt="screen shot 2017-08-07 at 16 21 08" src="https://user-images.githubusercontent.com/25012688/29033297-7e841c4a-7b8c-11e7-8ae5-2572268808ed.png">
PS - adding achieved date and separating important and achieved into 2 lines in separate issue here: #878 

tickboxes here: #450

**Comment by Cleop** [comment]
@MollieCourtenay the tickboxes issue #450 does not have all the assets I need. I need an image of the gold edged white box on its own and I need an image of the gold edge white box filled with the blue check. That issue has one image in the zip file of the blue tick on its own. For now, this issue will have the words 'tick' and 'unticked' to demonstrate where they will be.

**Comment by MollieCourtenay** [comment]
India please help as soon as you have the chance

**Comment by indiamindwave24** [comment]
![tickbox_complete](https://user-images.githubusercontent.com/25007700/29708971-90cab036-8982-11e7-947a-845345b2a3f7.png)
![tickbox](https://user-images.githubusercontent.com/25007700/29708972-90d01ba2-8982-11e7-8ee0-78416e43958f.png)

**Comment by MollieCourtenay** [comment]
@indiamindwave24 these are a different style to the ones here #450

**Comment by indiamindwave24** [comment]
![tickbox_complete](https://user-images.githubusercontent.com/25007700/29713700-c8dd5b6c-8997-11e7-897c-541b2ce3e2ae.png)
![tickbox](https://user-images.githubusercontent.com/25007700/29713701-c8ea0862-8997-11e7-847d-0524a6c68a28.png)

**Comment by MollieCourtenay** [comment]
<img width="363" alt="screen shot 2017-08-29 at 09 37 49" src="https://user-images.githubusercontent.com/25012688/29812198-baa23d16-8c9d-11e7-9462-4e03acd3abf5.png">

Styling wise, 
+ [ ] the goal tick boxes are still much bigger than the mock up above. Could they be made to the same height of the star icon?
+ [ ] the step to take text should be aligned to the centre of the tick box.

**Comment by katbow** [comment]
@MollieCourtenay These are the tick box icons the same size as the star icons which looks a bit big to me still (forgive my keyboard mashing goals and steps)

![image](https://user-images.githubusercontent.com/1287388/29966094-438170b8-8f08-11e7-91e8-b724c77da20a.png)


Here they are the next size down. Do you prefer like this or is it too small?
![image](https://user-images.githubusercontent.com/1287388/29966074-27051156-8f08-11e7-83f4-75da5990ffc8.png)

**Comment by MollieCourtenay** [comment]
@katbow I agree -  if prefer somewhere in the middle of those two sizes..
If not possible, then smaller option with a reduced gap between steps.

If the words for each step could align to the bottom of the tick box that would be great.

**Comment by katbow** [comment]
they've been resized to be in between the 2, although closer in size to the smaller. The padding has been halved between steps.

**Comment by MollieCourtenay** [comment]
<img width="428" alt="screen shot 2017-09-01 at 16 22 38" src="https://user-images.githubusercontent.com/25012688/29976404-d078f4cc-8f31-11e7-939e-dbaf25acfa15.png">

**Comment by MollieCourtenay** [comment]
nice!
