### ISSUE TITLE
Tips and home page - remove line break 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#901]
These 5 actions are proven to improve personal wellbeing. Read the full document.

+ [x] Read the full document should sit on the same line as the sentence before.
+ [x] add full stop after document.
____
+ [x] Home page (logged in and out)
+ [x]  [healthlocker.uk/tips?tag=BeActive] and for all 5 tip tags pages
+ [x] Tips page

**Comment by MollieCourtenay** [comment]
incorrect copy

**Comment by MollieCourtenay** [comment]
This works on the home page but not the Tips category pages or the Tips page.

**Comment by katyedwards** [comment]
@MollieCourtenay can you check this one - I'm not totally sure what I'm looking for to see if it can be closed!

**Comment by MollieCourtenay** [comment]
@katbow this is stuck here as i cant work it out.
Not a big deal but Ideally I wanted the line break an full stop to also show on https://staging.healthlocker.uk/tips and on all tag pages e.g. https://staging.healthlocker.uk/tips?tag=BeActive

**Comment by katbow** [comment]
Okay, yes this is done programmatically for each of the different tag pages, so it's not a matter of just editing the template.

**Comment by katbow** [comment]
@MollieCourtenay yes, that's because it's set programmatically for each of the tip tags.

**Comment by katbow** [comment]
![image](https://user-images.githubusercontent.com/1287388/29982528-f8156106-8f49-11e7-82a2-4dd01f6296d4.png)
Do mean the grey dividing line? Where would you like it on the main tips page? I'm not sure what you mean by the full stop. Do you mean the number that is done for each tag category on the home page? So connect will have **1.** in front of it and so on to match the home page?

Also where do you want the dividing line(s) for the tips category pages?

![image](https://user-images.githubusercontent.com/1287388/29982612-6194218a-8f4a-11e7-836c-477e8bc39355.png)

**Comment by MollieCourtenay** [comment]
@katbow not a grey divider but I would like to remove the line break so that Read the full document is on the same line. and add a full stop after document. It is been like this on the landing page but not the others.

https://staging.healthlocker.uk/


**Wellbeing Tips**
Small improvements in our wellbeing can help to decrease some mental health problems and also help us to get more out of life.

These 5 ways to wellbeing are proven to improve personal wellbeing. [Read the full document](url).

**Comment by katyedwards** [comment]
See Mollie's comment above from 2nd Sept
This is correct on the home page 
![screenshot 2018-01-02 16 38 38](https://user-images.githubusercontent.com/24604903/34491460-68c34656-efdb-11e7-94ef-2d41b2899b1b.png)

But the link is on a separate line on each of the individual tip pages:
![screenshot 2018-01-02 16 39 33](https://user-images.githubusercontent.com/24604903/34491489-8754810c-efdb-11e7-8e43-948cfd02fc82.png)

- [ ] https://staging.healthlocker.uk/tips?tag=Connect
- [ ] https://staging.healthlocker.uk/tips?tag=BeActive
- [ ] https://staging.healthlocker.uk/tips?tag=KeepLearning
- [ ] https://staging.healthlocker.uk/tips?tag=TakeNotice
- [ ] https://staging.healthlocker.uk/tips?tag=GiveToOthers

It seems like the actual text area on the home page is wider than it is on the individual tip category pages hence the text is wrapping.  
How easy is this to change and is it likely to cause any wider problems if we do?!

**Comment by RobStallion** [comment]
To fix this issues will only take a few minutes. The rest of the time is there as we would need to test to make sure that it does not effect any of the styling on other pages or mobile devices.
