### ISSUE TITLE
Server error when clinicians trying to log in using button in ePJS

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#906]
Currently the version of HL deployed to Azure (which is the most up to date version of the app and can be found at this URL http://staging.healthlocker.uk/) is sometimes getting the following error when a clinician is attempting to log in using the button in ePJS.

`cannot convert nil to param`
![image](https://user-images.githubusercontent.com/15571853/28016558-d09a57d2-656c-11e7-8a0a-42359a18de06.png)

The button should direct a clinician to the `http://staging.healthlocker.uk/caseload?userdata=*encrypted_string*`. We decode the `encrypted_string` and use the data to query the ePJS database and confirm that the clinician is able to be logged in. If the decryption fails or the user does not appear in the ePJS database the user should be direct to home page with a flash message saying `authentication failed`.

**Steps to replicate..** (as this is working sporadically you may need to try the links and multiple times)

- enter one of the following urls...
```
http://staging.healthlocker.uk/caseload?userdata=AQAAAMykN9181XUji18Iw4aTo8Rdi0ImVbM%2B9mzBTZXCp2CPQgryfNeNE4gNVxmMASO3CS2484wJ/v3QalyeQlcBYSfFmj%2B7TD1wcmKJg0IUOW/nTUdDA3Vl1ptsRPtSHIiLwVF0EJiD2N2n%2BYdytN%2B5B1fdHBLvALF6bGFRA1Mr991h
```
```
http://staging.healthlocker.uk/caseload?userdata=AQAAADyhSQUqcHkOWTRX80nd0Qfa7rO%2Bx63hsOMqs2UzJd60kzxrYZb8C9Klf4SYQjX1BOV1WFXuDd2xXd36niOxuo67K8iyrnGqqeZgkGE6AOMTeGyHkoY7QoGAagl17DsXS07FhlY8iAIdD4lb2eAYMXd6tXsV4%2BHSjlJ0ufKL7lCU
```

**Comment by RobStallion** [comment]
have turned off using edeliver for the staging server and will be running it manually by being `ssh-ed` into the VM. Am going to work this way in order to debug what is happening when the endpoint is hit.

**Comment by RobStallion** [comment]
Currently have a copy of the server logs both for when the site goes to the correct endpoint and when the server errors. Comparing the two in order to see exactly which step in the code is causing the error

**Comment by RobStallion** [comment]
Logging in using Gary's encrypted sting works consistently but when using James' we get the error consistently. It appears that a user for James in the database but it is throwing an error when trying to log in. 

Currently looking into the `Auth.login` function

**Comment by markwilliamfirth** [comment]
I can confirm testing on my side that Gary's encrypted string works and James' still throws the same error

![image](https://user-images.githubusercontent.com/5732209/28024075-99d5ecbe-6587-11e7-9f39-7579393e6e4e.png)

**Comment by RobStallion** [comment]
Have not been able to spot anything wrong with `Auth.login`. The flow seems to work as expected which leads me to believe that the issue is with the actual user in the db.

Next step is to `ssh` into the VM and check the `psql db` users

**Comment by RobStallion** [comment]
Going to delete James from the database as it appears that he may have been set up before all the migrations had been run.

**Comment by RobStallion** [comment]
James' url appears to be working correctly now.

Next step 

- Going to test with @markwilliamfirth 
- if @markwilliamfirth has the same results 
  - log in as James and create goals etc..
  - check for errors

**Comment by markwilliamfirth** [comment]
@RobStallion testing on my side I can see that James' link is now working (in addition to Gary's)

![image](https://user-images.githubusercontent.com/5732209/28027893-a8bcf5f0-6592-11e7-871f-15ee699b1b8d.png)

Over to you @RobStallion to log in as James and conduct further testing 👍

**Comment by RobStallion** [comment]
Have created test content under James user details and so far everything is working as expected. Have redeployed the staging.server. 

@katyedwards could you please test [this link](http://staging.healthlocker.uk/caseload?userdata=AQAAAMykN9181XUji18Iw4aTo8Rdi0ImVbM%2B9mzBTZXCp2CPQgryfNeNE4gNVxmMASO3CS2484wJ/v3QalyeQlcBYSfFmj%2B7TD1wcmKJg0IUOW/nTUdDA3Vl1ptsRPtSHIiLwVF0EJiD2N2n%2BYdytN%2B5B1fdHBLvALF6bGFRA1Mr991h) to log in as James and see if everything is working as expected. 

Could you also try to get us some more encoded URLs from Garry and co at SLaM? We currently have only been able to test with the 2 users.

**Comment by katyedwards** [comment]
Hi @RobStallion I emailed Garry on my way home yesterday and have asked for additional encoded URLs.  I'll let you know as soon as we have them.

I tried clicking the test link and it took me straight to a caseload view with some un-signed-up users.

So no error, but should I have been getting an authentication failed message?

![screenshot 2017-07-11 08 54 13](https://user-images.githubusercontent.com/24604903/28057030-b43ee3d2-6616-11e7-981a-e7c8bbf755fc.png)

**Comment by katyedwards** [comment]
**Update from Garry:**

Please find further below 5 URLs generated for the HL staging environment.  My colleagues and I have tested each of these and continue to get mixed results.  We have noted as pattern to this.

If the device being used has the following external IP of 80.0.251.1, the connection fails. 
![screenshot 2017-07-11 09 51 23](https://user-images.githubusercontent.com/24604903/28060243-84747d8a-661e-11e7-9097-74542b8bf38b.png)


And if the external IP address is 212.250.79.196, it is successful:
![image003](https://user-images.githubusercontent.com/24604903/28060210-72f090bc-661e-11e7-852b-e8a299650541.png)


Does the staging environment allow connectivity from 80.0.251.1?  Copied in Stuart who may be able to assist.
 
Kind regards,

Garry
 
 
Nicola Byrne (CCIO)
http://staging.healthlocker.uk/caseload?userdata=AQAAANcBJlhDKZ4pEKWnX2vfFzdJduLJkNkqTlVhq%2BNlPtp7bEy9%2B5OwHTbQRjKKHLJKSUgHu6Klzo9sXxeN/rc/L58rhGTxByPdCA/m4hCssfW8ik8j2o3y4jJvmIy8AOofvc3KJaEtcZTuFJFy/zA9NfSSufZzjkKGDw==
 
 
Jane Stewart (Clinical Systems)
http://staging.healthlocker.uk/caseload?userdata=AQAAAGs8A6B2JnkjLix0PqUZKi9gxGUv1AjPUXQi9PFP7bqthkeN6FaHAvFdbaWLBrUq%2B1HOSDBlQsmKgdXqYwzlGiyEZ55Cgwy1ZdCb%2BvcSX4q40jClo6THUu9GXcY0dDmmgwt7DELQ8VgyPySwzprhwW%2BScAmSBt%2Bt9xaeX0eGN/Y5
 
 
Ajoy Thachil (Consultant)
http://staging.healthlocker.uk/caseload?userdata=AQAAAPCH2XJZs/8OVi%2BtqNN/NCYKS%2BmIwzCZEKynI%2BMy6a5YK7%2BqTqxtnw%2BNMGk1s8YqRrRww3oYWLReaOn/tuyhT9J%2B5CZ4%2BaSaxZnvEyeS%2BLD3HAtPdXcAEUFKKZTuUb5K2I7%2BZU0hM3Ii2%2BsS5QIJ382V36sYDS%2BLctyNg5bB1Ufp
 
 
vtestward (test ePJS account)
http://staging.healthlocker.uk/caseload?userdata=AQAAAIMfPI8sytIq4WnEKWTnPjwH%2BeQ5gXY4WyAvbwkPHL34oZvEEV9Z3sKe10c7CTV5vCCVllPBCgRQkgQYtd85SebRrrClpjkjEHerBC9QUltu9xX7/GAgDjPzF4hBhQAz0BeXORMpLqI9APM5Lr78Jv6HOtpV8HoMeu599MtiJe6p
 
 
Grant Steele (Clinician - no patients on ePJS caseload)
http://staging.healthlocker.uk/caseload?userdata=AQAAAP14c7MWE5Z0TUhoWVUKny1bYPu1bCsgtPWBP8fN5wdLitPSGcmVyKUVYDLYbCwGvqsG70AZe%2BczZxXrJLFY4VncqOcHIpQcMm3XMio9oNgOnVsEiiabGBA45ilzYcUJejYZGf2NG/KHoQF9v1/brug6qp5Gp9wFRA4hXeuA%2BVJ7
 
 
David Baskerville (Clinician - with patients on ePJS caseload)
http://staging.healthlocker.uk/caseload?userdata=AQAAAI3cf5t8zvqGV3fR/YR%2BvYbXP/eDsxgMErAhSiMM1wIugKLEC5PQpzWqDKu63O5k8NPksp1vNhwiW6eY/XcIQIwVRxLkENCxpAKnUYcQFOVvz%2Bh4VQdj%2BcC05toq7PSfyjEAk7T1R65nyDBafplOjq1I6BQDUddDybbL4CNOpuPP

**Comment by RobStallion** [comment]
have emailed Garry and Stuart (and a few other) regarding this issue. Below is a copy of what was sent...

```
Good morning all,

Garry could you please send over some screen shots of the errors that you are receiving when the connection fails. 

If an IP address is being blocked that sounds like might be another firewall issue. Stuart could you please confirm if this may be the case.

Kinds regards

Rob 
```

**Comment by RobStallion** [comment]
response from Garry

** Issue uncovered during pre testing **
 
 
Descriptions:
Access through to ‘Health Locker’ errors from devices with using an external IP of 80.0.251.1.  The issue appears to be independent of user AD account and/or ePJS user account.
 
Steps:
To test for error condition, go to device using external IP of 80.0.251.1
http://staging.healthlocker.uk/caseload?userdata=**encrypted_string**
 
Error:
![image](https://user-images.githubusercontent.com/15571853/28066243-19f2f2f0-6634-11e7-9e72-262d4f50d1d1.png)

**Comment by RobStallion** [comment]
my reply to that...

```
Hi Garry,

Thanks for getting back to us so quickly.

Regarding the issue where the url is not being retrieved, could you please go to http://staging.healthlocker.uk/ on the IP address that is causing the error?

Just trying to determine if it is an issue with the endpoint or if it is an issue with the IP address. 
```

**Comment by katyedwards** [comment]
@RobStallion Response from Garry yesterday, not sure if this was picked up:

Hi Rob,

I can confirm we see the (110) Connection Timeout Error for http://staging.healthlocker.uk/ from a device assigned the external IP of 80.0.251.1.
 
Kind regards,

Garry

**Comment by markwilliamfirth** [comment]
Thanks for the update @katyedwards

**Comment by RobStallion** [comment]
@katyedwards this is still waiting on a fix from SLaM. The response from Garry was just to confirm that is wasn't a problem with the endpoint in HL but that it was an issue with some IP addresses being blocked on the staging server. 

I believe that Stuart was looking into getting this resolved as he stated it was being looked into in the email chain

![image](https://user-images.githubusercontent.com/15571853/28113442-6c910d38-66f4-11e7-9287-6635760d5b97.png)


![image](https://user-images.githubusercontent.com/15571853/28113405-54737cf4-66f4-11e7-825f-ebbcfbfade91.png)

**Comment by katyedwards** [comment]
Thanks @RobStallion I'll chase Stuart on that too and will try to get a time estimate from him.

**Comment by katyedwards** [comment]
Morning @RobStallion Stuart has emailed to say this one has been fixed.  Can you check/ test and let me know when it can go over to Garry to test.  Thanks!

**Comment by katyedwards** [comment]
Handed over to Garry to test.

**Comment by katyedwards** [comment]
Morning Katy,
 
I’ve had the team here testing through the morning.  No repetition of the error so far.
 
Kind regards,
 
Garry
