### ISSUE TITLE
Error when SU connecting to care team

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#909]
**From Garry:**

Description:
Connect with my care team and health record.  Error triggered (screenshot further below).
 
Steps: 
Ensure ePJS patient record is assigned an active Team Member and included in the mhl2 extraction tables
(Patient Record: 152 Tkest)
(Clinician Caseload: Garry Moriarty)
 
Ensure patient is signed up to Health Locker
(tkest152tkest@outlook.com; 1Clinical1)
 
Login => Account => Connect with my care team and health record

![image002](https://user-images.githubusercontent.com/24604903/28066055-442bfbb2-6633-11e7-9313-68de9fb20fd7.jpg)

![image010](https://user-images.githubusercontent.com/24604903/28066060-47a59c76-6633-11e7-9627-00c6809d2420.jpg)

**Comment by MollieCourtenay** [comment]
Could this be because Garry is signed  in as a clinician ?

**Comment by MollieCourtenay** [comment]
@robstallion

**Comment by MollieCourtenay** [comment]
@katyedwards

**Comment by RobStallion** [comment]
Looks like this is an issue to do with duplicate clinicians in the `mhlteammembers` table. Will use `Enum uniq/uniq_by` to filter clinicians list for duplicates (in `healthlocker.slam.connect_slam.ex`. Could also be an issue in `healthlocker.slam.connect_carer.ex`).

**Comment by katyedwards** [comment]
@RobStallion do you need anything from the SLaM side to fix this or are you able to get it sorted?

**Comment by reddog** [comment]
@RobStallion is the `mhlteammembers` table in MSSQL (SLaM ePJS extract) or PostgreSQL (HL) database?

Is it expected that there would be multiple entries for clinicians in this table?  Selecting with a `uniq` query may well fix this issue (and be an example of robust code), but it isn't covering for another issue (possibly not yet fully understood) elsewhere is it?

**Comment by RobStallion** [comment]
Below is a screen shot showing that SU can now connect to care team if that care team has the same member multiple times.

![image](https://user-images.githubusercontent.com/15571853/28156222-c2507a6e-67a9-11e7-9311-09f5a9424e3e.png)

**Comment by katyedwards** [comment]
Passed to Garry to test

**Comment by katyedwards** [comment]
Garry has confirmed all ok.  Thanks!

**Comment by reddog** [comment]
@RobStallion Were you able to consider my comment at https://github.com/healthlocker/healthlocker/issues/909#issuecomment-314704443 ?  Do we fully understand how/why there were multiple rows in the database and if that should / shouldn't be the case?  Just want to ensure we've fully understood the underlying issue to help ensure that we've fully addressed it and it doesn't recur in a different form somewhere else.

**Comment by RobStallion** [comment]
@reddog `mhlteammembers` is a MSSQL table and can/does have multiple entries for clinicians in the table. This happens because the clinician can have multiple roles in one care_team and each role gets entered as a new row in the db table. 

Hope this answers your question. Sorry I missed it first time round

**Comment by reddog** [comment]
@RobStallion Thanks for that.  So to confirm, your new code now anticipates that there may be/will be multiple entries per clinician per room?  Thanks.
