### ISSUE TITLE
Goals for all users

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#91]
As a user, I can set myself goals so that I have something to focus on.

## Acceptance Criteria  

+ [x]  As a user I can click to 'See more' goals (including completed goals)

+ [x]  As a user looking at my goals, the Add new button is available on the goals landing screen. (currently there when viewing a goal)

+ [x]  As a user I can create a new goal [free text boxes, allowing for bullet pointed text on each new line]

+ [x]  As a user I can click on a goal and edit or delete goals 

Epic #37

![image](https://cloud.githubusercontent.com/assets/25012688/22822233/78eac7cc-ef76-11e6-99c8-a3fe89151e07.png)

COPY

**To view a goal:**

Goal displayed in bold text.
Created <XX/XX/XX>

Steps to take:
[text box, displaying bullet pointed text on each new line]

Who could support you:
[text box, displaying bullet pointed text on each new line]

[ ] Mark as important / Important
[ ] Mark as complete / Complete xx/xx/xx

**To add a new goal:**

What do you want to achieve? Describe a personal goal.
(type in bold text)

List the steps you could take to achieve it.
[free text box, allowing for bullet pointed text on each new line]

Who could support you?
[free text box, allowing for bullet pointed text on each new line]

[ ] Mark as important

(Save)

**To edit a goal: (cannot edit goals from care plan)**

Describe a personal goal.
(bold text)

List the steps you could take to achieve it.
[free text box, allowing for bullet pointed text on each new line]

Who could support you?
[free text box, allowing for bullet pointed text on each new line]

[ ] Mark as important
[ ] Mark as complete

(When marked as complete reveal:) Reflection notes:
_What went well? What problems did you have, how did you overcome them? How do you feel now?_

(Save)

**Comment by LauraNevo** [comment]
Update on this, we decided to separate the Toolkit page (too much content to branch from there to keep in the same page):

![goals](https://cloud.githubusercontent.com/assets/3858131/23085253/8df550ea-f55e-11e6-8c70-7a53b94fda68.png)

**Comment by katbow** [comment]
Some questions to figure out before adding in the rest of goals functionality:

Since there is quite a bit more information compared to coping strategies, is it better to make a new schema/table for goals? This seems similar to working out events as it had quite different content needs compared to tips and stories. 

If this is to go in the same `posts` table, how to differentiate information for each field.

Finishing off goals would be ~4hrs to 1day depending on how to implement.

**Comment by MollieCourtenay** [comment]
@katbow there is a lot not done so i'm not closing and assigning to you. I've broken down the ACs/tasks a bit more, as per the wires and content requirements.

Ive got 7 goals and not seeing a see more message, is that AC now redundant as goals aren't displaying in the Toolkit screen? Will the page load all goals?

In what order are the goals loading in? I couldn't figure out the logic?
Ideally it would be important on top, then newest first. (when Mark as important is built)

New Post (story or tip) is really confusing, need to sort that.

**Comment by katbow** [comment]
@MollieCourtenay would you like to close this now since we have the other issues for each goal feature?
