### ISSUE TITLE
Token Expiry

### ISSUE THREAD

**Issue by markwilliamfirth** [healthlocker/healthlocker#911]
**Summary**
- [x]  Create functionality to expire clinician link tokens after 10 minutes

As a project lead for the healthlocker project, I want to ensure that the application has sufficient security. This involves ensuring that URL tokens expire after a certain time period from being generated. This reduces the chance of a clinician being able to access healthlocker outside of their workplace.

**Comment by reddog** [comment]
Can I just check that the server time is set correctly and being kept correct (NTP?), otherwise token expiry times won't match.

**Comment by RobStallion** [comment]
@reddog We need to check with the SLaM team on how the time in the string is generated. For example is it always `UTC +0` or does it change with the for BST and got to `UTC +1`

**Comment by reddog** [comment]
@RobStallion Would you like us to check - happy to do so?  Is this a block?

**Comment by RobStallion** [comment]
That would be great @reddog

**Comment by markwilliamfirth** [comment]
@reddog this isn't a block - Rob is currently writing the code to solve the issue, the timezone is a necessity to compare the times properly, but it doesn't change the functionality of the code

**Comment by RobStallion** [comment]
email @reddog sent to SLaM earlier today...

```
Hello Stuart and Garry,

Pleased to e-meet you both.  Thanks very much for all your help and support on this project.

We have a question about the "userdata" link that's sent over to Health Locker on initial login from ePJS, ie the encrypted string to allow access in to Health Locker.  Included in the userdata encrypted string is a "tokenexpiry" parameter, for example:


http://staging.healthlocker.uk/caseload?userdata=AQAAANsW4/PVnIhBkGy4oJ5l250DuThJ%2BKkFrs%2BxSYaowK2X3JTCm%2BK8APdeE8ZxJNMWwzRw0snaZ//yVqx9XDg%2Be5mvXr/aWVGMc%2BUj5keB25GgBU3m3o4ntJZlg4vZYqsNFuwZHGklKG1UgsoHHyEgdxsDrjKdkhlTqeF06MvrdmBk

->

(UserName=random_email&UserId=random_code&tokenexpiry=2019-05-30T23:16:12)
 

What is the date/time format of the tokenexpiry value?  In particular with regard to BST/GMT?

```

**Comment by RobStallion** [comment]
will test functionality of this on the branch ooh in order to keep disruptions to a minimum for anyone who may be using the site as it will need to be taken down temporarily.

**Comment by reddog** [comment]
@RobStallion Feedback from Garry at SLaM as follows:

> The `tokenexpiry` is formatted to `yyyy-mm-ddThh:mm:ss`.  The SQL server generating the datetime is set to BST.
> 
> `SELECT CONVERT(VARCHAR(19),DATEADD(mi,10,GETDATE()),126) AS UserData`

**Comment by RobStallion** [comment]
The tests are all passing now and everything appears to be working as expected but as stated above, would like to test with the real data before merging opening the pr to be merged into master. This will require the site being down for a short amount of time so will do ooh

**Comment by RobStallion** [comment]
The following encrypted string with a `tokenexpiry` that is 2 years from now goes to the correct HL endpoint...
```
http://staging.healthlocker.uk/caseload?userdata=AQAAANsW4/PVnIhBkGy4oJ5l250DuThJ%2BKkFrs%2BxSYaowK2X3JTCm%2BK8APdeE8ZxJNMWwzRw0snaZ//yVqx9XDg%2Be5mvXr/aWVGMc%2BUj5keB25GgBU3m3o4ntJZlg4vZYqsNFuwZHGklKG1UgsoHHyEgdxsDrjKdkhlTqeF06MvrdmBk
```

Screen shot of HL endpoint with encoded URL
![image](https://user-images.githubusercontent.com/15571853/28128723-94a5bfba-6728-11e7-9bd7-c3c4b7d93cb2.png)


When we pass in the following URL with a `tokenexpiry` that has already passed the site redirects to the HL home with a flash message explaining what went wrong...
```
http://staging.healthlocker.uk/caseload?userdata=AQAAADyhSQUqcHkOWTRX80nd0Qfa7rO%2Bx63hsOMqs2UzJd60kzxrYZb8C9Klf4SYQjX1BOV1WFXuDd2xXd36niOxuo67K8iyrnGqqeZgkGE6AOMTeGyHkoY7QoGAagl17DsXS07FhlY8iAIdD4lb2eAYMXd6tXsV4%2BHSjlJ0ufKL7lCU
```

Screen shot of redirect and flash message
![image](https://user-images.githubusercontent.com/15571853/28128883-2e5205e2-6729-11e7-94a5-ee9577e43b28.png)

**Comment by katyedwards** [comment]
Yes working thanks!
