### ISSUE TITLE
Changing Forgotten Password Flow for Clinicians

### ISSUE THREAD

**Issue by markwilliamfirth** [healthlocker/healthlocker#912]
If a clinician tries to change their password in the application instead of it sending the link to their email, it should instead follow the normal could not reset password flow.

**Comment by nelsonic** [comment]
@markwilliamfirth / @RobStallion  was this story requested/validated by the product owner?
(_not saying it's not a good idea to "enforce" Clinician Login via ePJS, just that we need confirmation of issues `before` working on them ..._)

**Comment by markwilliamfirth** [comment]
@nelsonic yes I can confirm this feature was requested by @reddog and @katyedwards for security reasons

**Comment by nelsonic** [comment]
@markwilliamfirth no, the Product Owner should reply in the issue, as far as I'm aware that's still @MollieCourtenay

**Comment by MollieCourtenay** [comment]
@katyedwards requested after we spoke about it the other day. 
Please continue 

But note it may be a requirement in the future to open HL up in some way to be accessed by clinicians not only via ePJS. So if there is anyway to do it which makes it easier to undo. That may be useful..

**Comment by katyedwards** [comment]
@MollieCourtenay as I understand it, it should be easily undo-able.  @RobStallion can confirm that.

**Comment by katyedwards** [comment]
@RobStallion 

Garry has tried testing and got an error page - looks like the same problem as #905 but I would assume this shouldn't be happening here because the system shouldn't be trying to send an email.  

Can you advise.

FYI - I asked him to try to use the forgot password link to access a clinician password.  He got the following error:

![image004](https://user-images.githubusercontent.com/24604903/28129930-27d4bf3a-672d-11e7-92b8-1576578255ae.jpg)

**Comment by reddog** [comment]
@RobStallion Do you have the email address of a clinician with which you can test against (there are examples in some of the unencrypted userdata strings we have - are any of these in the database, or could you pull a user out of the database who is a clinician for testing, or alternatively create a service user account and change the role to clinician in the database for testing - don't know if any of these would work)?

If you did, it would save the loop of having to go out to SLaM for first round of testing.

**Comment by RobStallion** [comment]
@reddog if you try to reset the password of any clinicians you should get the following flash message...

![image](https://user-images.githubusercontent.com/15571853/28169492-639e84ee-67da-11e7-965a-5b244579ef0d.png)

Test it out with Garry or James' emails.

**Comment by katyedwards** [comment]
Yep working!
