### ISSUE TITLE
ERROR: Messages not submitting

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#915]
Description:
Messages posted do not display.  Neither the signed up service user or linked member of the care team:
 
Steps:
Ensure ePJS patient record is assigned an active Team Member and included in the mhl2 extraction tables
(Patient Record: EDT 3 Tkest)
(Clinician Caseload: Garry Moriarty)
 
Ensure patient is signed up to Health Locker
(tkestedt3tkest@outlook.com; 1Clinical1)
 
Ensure ‘Connect with my care team and health record’ is place
 
Login => Care team  => Messages => ‘Type a message’
 
Error:  No messages displayed. Neither for the service user or care team
![image007](https://user-images.githubusercontent.com/24604903/28075452-73531da6-6653-11e7-8664-d10899e27346.png)

For this test I setup a service user with the account of:
EDT 3 Tkest
tkestedt3tkest@outlook.com
Password: 1Clinical1
 
They have had their account linked to SLaM successfully and assigned to my caseload (http://staging.healthlocker.uk/caseload?userdata=AQAAAAmmBaC4%2BzdsdG34YPc/EcW%2Blg1Ohttjip/LdsKKwyQETF2HVOdx0DhJ7qKbcwpdjzZXLOHw8Z2FsEGf0i6/V0ix3DtnUlCze3SgJMXVkI8nohrF43qtWStaX5ZtRwKGzCTVMT5Qqacxjaftyml%2B7lv1nbcQH4D1PxGFEQoPg2Ql).

**Comment by katyedwards** [comment]
Have checked with Garry and this was the case for messages from 1 character up to a paragraph - so **not** related to issue #880

**Comment by katyedwards** [comment]
@RobStallion any chance this will have been fixed by any of the other fixes you have been doing?

**Comment by RobStallion** [comment]
This appears to be an error with how `edeliver` deploys the site to the staging server. Will look into why this might be happening starting with the build.

**Comment by reddog** [comment]
@RobStallion When you get to working on this issue, it would be really interesting to understand a little more about why this feature was working and now isn't, and how it being broken relates to the depolyment method and if anything can be done to get to a (different?) solution faster.

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/28212091-bdfd3314-6897-11e7-8f1b-5d07fe3b5982.png)

```
VM97:35 WebSocket connection to 'wss://staging.healthlocker.uk/socket/websocket?token=SFMyNTY.g3QAAAACZAAEZG…c2lnbmVkbgYAMAwMQV0B.iqv9AgclbE6DfDvOazjpSix52j1lc7BwhrhLwqnoQIE&vsn=1.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403
```

Above is the error message that is coming up in the console when on a messaging page.

**Comment by reddog** [comment]
Blocked by #841

**Comment by markwilliamfirth** [comment]
@reddog it doesn't appear that this is a blocker - #841 has a lot of issues that link to it, (due to the fact it has a wide scope) but the completion of #915 does not appear to rely on #841 being finished. Would you be able to explain more about why it might be a blocker?

**Comment by reddog** [comment]
@markwilliamfirth See @RobStallion's comment here:  https://github.com/healthlocker/healthlocker/issues/841#issuecomment-315349219

**Comment by katyedwards** [comment]
Hi @nelsonic can you have a look at this issue for us. I appreciate HL should have been completed by now and you are on other projects, but if it is the problem it seems to be - I understand that is more within your remit than Rob's and we need to get over this final hurdle ASAP so we can handover to SLaM.

Can you confirm your availability to look at this today please.  Thanks!

**Comment by katyedwards** [comment]
HI @nelsonic Ines said you were going to look at this via #841 today - can you update us on how you got on - there doesn't seem to be anything new on either issue.  Thanks!

**Comment by nelsonic** [comment]
@katyedwards yes, looking at it now. 👍

**Comment by nelsonic** [comment]
@katyedwards please try again. I've updated the server configuration and am now able to send messages: 
![image](https://user-images.githubusercontent.com/194400/28428145-4dd43ce4-6d70-11e7-8a76-79102b32906b.png)

CC: @reddog 
PR: https://github.com/healthlocker/healthlocker/pull/936

**Comment by katyedwards** [comment]
Hooray!  Have tested it on both users and that 1 clinician account.  Will ask Garry to test from his end too before I close the comment.

**Comment by nelsonic** [comment]
@katyedwards: Garry is able to send messages:
![image](https://user-images.githubusercontent.com/194400/28430101-293e677c-6d77-11e7-8005-a8f12ef6a03c.png)

**Comment by nelsonic** [comment]
@katyedwards: Garry is able to send messages:
![image](https://user-images.githubusercontent.com/194400/28430145-5072185c-6d77-11e7-9827-96975c559f2e.png)

**Comment by katyedwards** [comment]
@nelsonic That was me logged in as him - Garry will have other users he can test with just to be sure.

**Comment by nelsonic** [comment]
@katyedwards ah, ok. 😄

**Comment by reddog** [comment]
@katyedwards Any update from Garry on testing?

**Comment by katyedwards** [comment]
@reddog not yet, but I emailed him after office hours yesterday so he's not had long.

**Comment by reddog** [comment]
@katyedwards Has testing of this been finished now by Garry?

**Comment by katyedwards** [comment]
Yes sorry!
