### ISSUE TITLE
ERROR - Care Team View for Service User

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#918]
Description:  Care Team view
 
Steps:
Service User email address: Tkestedt3tkest@outlook.com
Password: 1Clinical1
 
Login => Navigation Pane  => Care Team
 
Error:
 
Immediate error

![image003](https://user-images.githubusercontent.com/24604903/28130025-7e0500d6-672d-11e7-82f3-95c030680f78.png)

**Comment by markwilliamfirth** [comment]
This is still an issue following deployment

**Comment by RobStallion** [comment]
Currently this functionality only works for when a clinician has left the care team and another clinician joins the team. 

Will add clauses to allow of other possibilities

- A clinician being added to the care team
- A clinician leaving the care team
- One clinician being added and another being removed. 
- The care team remaining unchanged

**Comment by reddog** [comment]
@RobStallion Thanks for the details of the extra cases to be covered.  Is that all use cases for this action?

The initial issue report, https://github.com/healthlocker/healthlocker/issues/918#issue-242452513 shows an error on first view (ie without further action).  Will that be covered?

**Comment by RobStallion** [comment]
Getting a new error now that the code has been updated...

```
key :id not found in: %Healthlocker.EPJSTeamMember
```
![image](https://user-images.githubusercontent.com/15571853/28224133-df01ee3c-68c5-11e7-99ab-0e925f3c4f61.png)


Believe that the key should be `Staff_ID` not `id` as we currently have

**Comment by katyedwards** [comment]
Have passed to Garry to test

**Comment by katyedwards** [comment]
Garry has confirmed all good - thanks!
