### ISSUE TITLE
Ecto.NoPrimaryKeyValueError, but id is primary key

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#92]
When I go through the form and try to submit part 3 (with T&Cs, Privacy, and data access request) I get the error:

```
Ecto.NoPrimaryKeyValueError
struct `%Healthlocker.User{__meta__: #Ecto.Schema.Metadata<:built, "users">, data_access: nil, email: nil, id: nil, inserted_at: nil, name: nil, password: nil, password_hash: nil, role: nil, security_answer: nil, security_question: nil, updated_at: nil}` is missing primary key value
```

This didn't happen at any of the other steps (with very similar code), and the id is the primary key.

I looked at the changeset for this step and it is `valid`:

```
#Ecto.Changeset<action: nil, changes: %{data_access: false}, errors: [],
 data: #Healthlocker.User<>, valid?: true>
```

All I have found on this is repeating the obvious that it means I'm missing the primary key value. What I don't understand is how this can be the case since it seems the `id` field is defaulted to the primary key, unless there is something explicit put in the migrations such as 

` create table(:users, primary_key: false) do ... `

Edit: This is in [the signup branch](https://github.com/healthlocker/healthlocker/tree/signup) and the error says it's from [this line](https://github.com/healthlocker/healthlocker/blob/signup/web/controllers/user_controller.ex#L55).

**Comment by katbow** [comment]
Ahh I see the problem - silly mistake. It's because the changeset needed to have a specific user passed in

```
def create3(conn, %{"user" => user_params, "id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.data_access(user, user_params)
    
    case Repo.update(changeset) do
      {:ok, user} ->
     ...
end
```

whereas I was just passing in %User{} when making the changeset:

`changeset = User.data_access(%User{}, user_params)`

**Comment by tonydaly** [comment]
@katbow glad I could help 😛

**Comment by katbow** [comment]
Haha I think I was in need of some lunch at the time I posted this!  🍽  😋
