### ISSUE TITLE
updating variables when site is deployed with edeliver 

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#926]
Currently getting the following issue when trying to send a feedback email 

![image](https://user-images.githubusercontent.com/15571853/28169967-ceb0a4d2-67db-11e7-8956-ac5b63ba2d71.png)

I know that the error is on this line
```
{:permanent_failure, "email-smtp.eu-west-1.amazonaws.com", "554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: HealthLocker@slam.nhs.uk\r\n"}
```

and it is that the HL email should have no capital letters. 

To update the variables when the site is deployed do we just have to update them in the ssh?

**Comment by RobStallion** [comment]
Nelson gave update in slack 

each time the app is built/deployed using `edeliver` the `.profile` is reloaded https://github.com/healthlocker/healthlocker/blob/310e02ee57c59f7893fd9f104aaefbaff62a7a09/.deliver/config#L14

**Comment by nelsonic** [comment]
@RobStallion only place I can see with email in that case (`HealthLocker@slam.nhs.uk`) is: https://github.com/healthlocker/healthlocker/blob/b23bea1d055b370484ecfdad9698b23be9667c7f/web/templates/page/privacy.html.eex#L112

On the _staging_ server: ```cat /home/hladmin/.profile``` 
should show you: 
```
export FROM_EMAIL=healthlocker@slam.nhs.uk
```
in lowercase.

**Comment by nelsonic** [comment]
FYI: I prefer _not_ to reply in "Slack" (_or any other chat_) as it means other people are out-of-the-loop.

**Comment by RobStallion** [comment]
I had updated the variable on the staging server to make it all lowercase which is why it showed as above. I just wasn't sure how the deployed version would see that change which is what you helped me understand. 

Sorry for starting the convo in slack btw as I know that it excludes people. 

Thanks

**Comment by reddog** [comment]
@RobStallion @nelsonic What does this mean for the deployment plan (possibly particularly for when a different developer performs a deployment)?  Is there a requirement for the `.profile` of the deploying user to be correct with Health Locker staging / production environment settings?  Deployment is from a developer's local machine?

If this means that a deploying developer's local `.profile` has to be correctly configured with the settings to be used for the staging / production site, what measures are in place to ensure that this will always be the case, and that incorrect values are not used (eg staging vs full production settings, or settings with the same name from another project, etc)?
