### ISSUE TITLE
Change from staging.healthlocker to Reflect Correct URL (healthlocker.uk)

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#927]
When healthlocker.uk has been redirected to the staging site - the password reset link will need to be updated...

Current example:
https://staging.healthlocker.uk/password........

Will need to take them to 
https://healthlocker.uk/password/......

**Comment by MollieCourtenay** [comment]
This depends on deployment

**Comment by markwilliamfirth** [comment]
Heroku site URL needs changing so healthlocker.uk can be used

**Comment by Cleop** [comment]
I don't yet have access to heroku in order to be able to do this. So this may be done by @RobStallion  @katbow or me (if I am granted permissions).

**Comment by markwilliamfirth** [comment]
@katbow who are the people that currently have access?

**Comment by katbow** [comment]
me, Ines, Tony, Nelson. Max is 4.

**Comment by markwilliamfirth** [comment]
@katbow let's take off Tony (who probs shouldn't be on there anymore anyway) and add @Cleop so she has permission to do this issue!

**Comment by katyedwards** [comment]
SLaM have confirmed they do want to move into a production environment after they pen test so I think this issue is now redundant - no point updating to update again in a few weeks.

**Comment by katbow** [comment]
@reddog I am guessing that they will want to go to the respective URLS. As in, if someone clicks to reset password on staging, it should say staging.healthlocker.uk in the email, and if they do the same on live then it should direct to www.healthlocker.uk? Is that correct?

I will need to update [here](https://github.com/healthlocker/healthlocker/blob/master/lib/email.ex#L17) to grab the current base url.

**Comment by reddog** [comment]
@katbow Yes please, password reset emails from staging should direct users to staging, live to live.

Should the website domain name be a setting in the profile?  Then it could be just pulled in to `config/prod.exs` https://github.com/healthlocker/healthlocker/blob/master/config/prod.exs ?

**Comment by katbow** [comment]
I should be able to pull it through from phoenix's `Plug.Conn`. If not I will set it as an environment variable.

**Comment by katbow** [comment]
@katyedwards *full* testing of this issue cannot be done until live is also up to see if it gives the correct link in password reset for each site.

**Comment by katyedwards** [comment]
Thanks - staging works... waiting to test live when I can!

**Comment by katbow** [comment]
Ready to go on live now. Looking good to me!

![image](https://user-images.githubusercontent.com/1287388/30739015-d8f8aa9a-9f83-11e7-958b-004b964020ee.png)

**Comment by katbow** [comment]
@reddog since Katy is not on HL today, can you please test & close? Thanks!

**Comment by katyedwards** [comment]
Confirm it is working on live too, thanks!
