### ISSUE TITLE
Error when disconnecting from SLaM Account

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#928]
Logged in as 
tkest152tkest@outlook.com

Went to account - and disconnect SLaM account - 'yes disconnect'

Error:
![screenshot 2017-07-13 16 08 54](https://user-images.githubusercontent.com/24604903/28173259-cce2dba2-67e5-11e7-8fc4-3bc71ae5b7ba.png)

**Comment by RobStallion** [comment]
when this function was first made it was designed thinking a SU would only have one clinician assigned to their care team. 

Will update function to allow for multiple rooms to be deleted at one time.

**Comment by RobStallion** [comment]
Getting a new error now that the code has been updated...

```
key :id not found in: %Healthlocker.EPJSTeamMember
```
![image](https://user-images.githubusercontent.com/15571853/28224133-df01ee3c-68c5-11e7-99ab-0e925f3c4f61.png)


Believe that the key should be `Staff_ID` not `id` as we currently have

**Comment by katyedwards** [comment]
Yep, working great now!
