### ISSUE TITLE
Send banner feedback email to mollie's and healthlocker email addresses

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#939]
+ [x] also send feedback to healthlocker@slam.nhs.co.uk

**Comment by markwilliamfirth** [comment]
Blocked by #874

**Comment by RobStallion** [comment]
@MollieCourtenay should the email be healthlocker@slam.nhs.uk?

**Comment by MollieCourtenay** [comment]
Yes please.

**Comment by MollieCourtenay** [comment]
Ah sorry about the co.uk above !!

**Comment by MollieCourtenay** [comment]
Have send an email and hoping to hear back from Adele that is has been received?
