### ISSUE TITLE
For Beta release 13th March. Make it very obvious this is a Beta site

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#94]
As a user I am aware the website I am using is a Beta, so that I feel able to explore and give feedback without worrying the site is not perfect or beautiful.

## Acceptance Criteria
+ [x] add a banner to the user site like the Science Museum one. Include a link to feedback #95.
+ [x] add a banner to the clinician site like the Science Museum one. Include a link to feedback #95.

**Comment by MollieCourtenay** [comment]
Would appreciate your help on this @iteles as briefly discussed last week.

**Comment by katbow** [comment]
have you seen the "Beta banner" on http://collection.sciencemuseum.org.uk/ ?
is that what you have in mind?
