### ISSUE TITLE
For Beta release 13th March. Allow users to feedback within HL.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#95]
As a Beta user I am able to feedback on my experience of using HL so that I can feedback in real-time.

## Acceptance Criteria
+ [x] when a user clicks on the Beta banner to feedback, load a form for the user to type comments in and send. #94.
+ [x] when a clinician clicks on the Beta banner to feedback, load a form for the user to type comments in send. #94.

+ [x] Reassure the user that their feedback has been sent.

+ [x] send feedback emails to my email address (Mollie) / unless you can populate a google sheet like you mentioned in our workshop. (will we know the email of the person who has sent the message?)

**Comment by katbow** [comment]
see learn-phoenix repo https://github.com/dwyl/learn-phoenix-framework/pull/44

**Comment by katbow** [comment]
@iteles is there an [amazon account](https://github.com/dwyl/learn-phoenix-framework/blob/master/sending-emails.md) I should use for this already?

**Comment by katbow** [comment]
@MollieCourtenay once you've approved that email I can change it so feedback goes to you 🙂

**Comment by MollieCourtenay** [comment]
@katbow have approved it. please do change it.:)

**Comment by katbow** [comment]
Alright, did that and sent some feedback to ensure it got to you!

**Comment by MollieCourtenay** [comment]
great thanks!
