### ISSUE TITLE
SSL certificate ownership

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#961]
Who owns it now - should it be passed over to SLaM / Mindwave?

What tool is used?  Let's Encrypt?

Nelson wrote ages ago:

STUART_ Question: What is the bit key length for the ssl? Who will provide the cert?
NELSON_Answer: 2048 bits key length. Currently provided by https://letsencrypt.org but we can use any certificate provider as required by NHS. (please provide preferred supplier help us set up the certificate so you "own" it)

**Comment by katyedwards** [comment]
@RobStallion you mentioned the let's encrypt certs were probably associated to an email address -can you check which one and whether we can update them to a SLaM one?  Thanks!

**Comment by RobStallion** [comment]
Hey @katyedwards, it looks like you can change the email address linked to a certbot account with the following command...

`~/certbot/venv/bin/certbot register --update-registration --email yourname@example.com`

Just let us know if you would like us to update them to the SLaM one.

**Comment by katyedwards** [comment]
Yes please @RobStallion will slack you the email address to use.

**Comment by nelsonic** [comment]
Will the person monitoring the Slam email address be responsible for managing/updating/supporting the SSL certificate?

**Comment by katyedwards** [comment]
Yep, they want to take ownership of it from now on.

**Comment by RobStallion** [comment]
Updated both the staging and live servers. 

![image](https://user-images.githubusercontent.com/15571853/35327507-a468c376-00f1-11e8-8413-cef28146612f.png)

![image](https://user-images.githubusercontent.com/15571853/35327521-b4219298-00f1-11e8-9e62-d1f0f7f15a6c.png)

Closing this issue
