### ISSUE TITLE
Clinician: remove connect to SLaM in account

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#965]
- [x] Remove two links

If you are service user or family/friend or carer of someone with the South London and Maudsley NHS Foundation Trust, you can:

Connect with my care team and health record  
Connect with the care team of someone I care for  

<img width="1105" alt="screen shot 2017-08-14 at 13 14 11" src="https://user-images.githubusercontent.com/25012688/29271284-8e14ee1c-80f2-11e7-9882-f215f3b70394.png">

**Comment by katyedwards** [comment]
Yes done thanks!
