### ISSUE TITLE
Clinicians: details and contacts. ADD list of who is in that SU's care team

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#968]
+ [x] As a clinician, 
When i click on details and contacts,
underneath the yellow box, 
I can see a list of who is in the service users care team.

<img width="707" alt="screen shot 2017-08-07 at 17 21 29" src="https://user-images.githubusercontent.com/25012688/29035810-e2f2dfe2-7b94-11e7-8ec0-d8092a01da53.png">

**Comment by markwilliamfirth** [comment]
Linked to #659

**Comment by MollieCourtenay** [comment]
This works well. There is just a big gap between these two bits.
<img width="864" alt="screen shot 2017-08-25 at 18 02 38" src="https://user-images.githubusercontent.com/25012688/29724255-bd37f754-89bf-11e7-91da-79e9e54c4ef0.png">

<img width="810" alt="screen shot 2017-08-25 at 18 03 55" src="https://user-images.githubusercontent.com/25012688/29724261-ca397658-89bf-11e7-9b57-0bd754cfaab5.png">
