### ISSUE TITLE
copy change to consent point. in Sign up and Account.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#972]
I allow my anonymous **useage** data to be accessed by researchers to drive forward the future of mental health and care.

+ [x] sign up 3
+ [x] consent in account

**Comment by MollieCourtenay** [comment]
incorrect copy

**Comment by katbow** [comment]
@MollieCourtenay was this for the data data part?

**Comment by MollieCourtenay** [comment]
there was one round of changes.  adding the word 'useage', and making the consent point consistent across sign up and account.

the second round i did this morning was to take out data data.
