### ISSUE TITLE
Ensure all stories have hopeful titles

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#975]
please edit
- Nikki ten years of suffering
- Liz skin picking
- Depression is a very real illness
- A Carer’s Story, Jaya Kathrecha’s family

**Comment by MollieCourtenay** [comment]
@katyedwards 
Please can you edit so that this part of the carers story is not part of the title. (Life as a carer - seeing services steadily improving)

+ [ ] Make this body copy
Jaya Kathrecha’s family life was knocked off course when her two sons were diagnosed with depressive illnesses in quick succession some ten years ago.

**Comment by katyedwards** [comment]
Done!
