### ISSUE TITLE
Coping Strategies: confirmation of deletion when deleting coping strategies

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#977]
+ [x] As a user, if i click delete coping strategy, I am prompted with 'Are you sure you want to delete this coping strategy?' I can click Delete coping strategy or cancel.

**Comment by katyedwards** [comment]
Time estimate added - same as #213

**Comment by katyedwards** [comment]
@RobStallion do you need any kind of design for this, or can you base it on something else we already have in HL?

**Comment by RobStallion** [comment]
@katyedwards I think a basic design would be helpful if you could, just so I have a better idea. I can't think of anything in the site that I could base this off of.

**Comment by RobStallion** [comment]
Design for the button is [here](https://github.com/healthlocker/healthlocker/issues/213#issuecomment-361940619)
