### ISSUE TITLE
Adding coping strategies

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#98]
Since this is done with the same content UI, it would require the users to input some sort of hashtag/identifier to differentiate coping strategies from stories, tips, and goals (in particular). 

Ways to do this:

1. Have the users input #copingstrategy. 
    - Pros: easy to implement and follows same pattern as stories/tips. 
    - Cons: since coping strategies (and goals) will be done by general users, we can't rely on this being done consistently

2. Use query params like `/posts/new?type=copingstrategy`, then automatically insert a hashtag/other identifier into the content when the user submits before sending it to the db. 
    - Pros: done automatically so the user doesn't have to think about it. 
    - Cons: may need to remove the hashtag again before displaying so it looks how the user expected it to from how they input the strategy. 

3. Use query params, but instead of auto inserting a hashtag, have a hashtag that is prepopulated in the content text box. 
    - Pros: Still automatic and can indicate it's necessary. Users can expect that in the format for adding and viewing strategies.
    - Cons: May be deleted by user and then not viewable.

For 1 & 3 there could be a check on submit that it contains #copingstrategy and not allow submitting until that is added in. I think 2 would be the most friction-free way to do this but looking for other thoughts! The con that is listed for 2 is also probably a non-issue that I might be overthinking.

#88

**Comment by tonydaly** [comment]
I'm kinda leaning towards having self-descriptive URLs e.g. `copying_strategy/new`. 

1. This means our URLs and more descriptive to users
2. Controllers and models (`CopingStrategyController` rather than `PostController`) can contain its own business logic, but the underlying DB model is still the same.

**Comment by katbow** [comment]
Okay that makes sense - I was thinking the URL structure was starting to get a bit mad if it was pointing to the same URL for new content all the time. 

I am still wondering though, since it will still just be one field for the user to fill in how to differentiate when adding new coping strategies or goals? I feel like it's still the same question but with neater URLs

If it goes in to the DB just how the user types it in, when we try to get the coping strategies or goals from the db, there won't be a way to recognise which are which, unless there is a necessary keyword to be included in the text. 

If a user goes to `/coping_strategy/new`, would they need to type in #copingstrategy themselves, or should we add it to the content string before inserting into the db, or should it be prepopulated with #copingstrategy & give a warning if it is deleted? Or something else entirely?

**Comment by katbow** [comment]
After talking with @tonydaly this morning option to use would be to use `/copingstrategy/new` and `CopingStrategyController` to define the create action where the #copingstrategy is appended to the content body. This takes it away from the user completely and then we don't need to worry about things not being included or typos etc.

**Comment by tonydaly** [comment]
@katbow sounds good!

One small thing...shall we use camel case for the tags e.g. `#CopingStrategy` and dashes in URLs? e.g. `coping-strategy/new`? 🤔
