### ISSUE TITLE
 Clinician view of achieved goals

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#982]
+ [ ] Important and Achieved icons are on two separate lines (currently on one line).

+ [ ] As a clinician, I can see the date the goal was achieved.(date can sit underneath the goal created date.

Like this: 
<img width="528" alt="screen shot 2017-08-07 at 16 21 08" src="https://user-images.githubusercontent.com/25012688/29033297-7e841c4a-7b8c-11e7-8ae5-2572268808ed.png">

Order of goals issue - #878

PS - listing steps to take in separate issue here: #900

**Comment by markwilliamfirth** [comment]
Closed in favour of #878
